import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/api-keys.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "api-keys",
  title: "API Keys",
  category: "Segurança & Autenticação",
  tags: ["api-keys", "auth"],
  level: "intro",
  glossary: {},
  elements: [
    {
      id: "st_gen",
      tone: "accent",
      kind: "box",
      at: {
        x: 75,
        y: 100,
        w: 200,
        h: 63,
      },
      label: "① Gerar",
      variant: "outline",
    },
    {
      id: "st_store",
      tone: "accent2",
      kind: "box",
      at: {
        x: 350,
        y: 100,
        w: 200,
        h: 63,
      },
      label: "② Armazenar",
      variant: "outline",
    },
    {
      id: "st_use",
      tone: "good",
      kind: "box",
      at: {
        x: 625,
        y: 100,
        w: 200,
        h: 63,
      },
      label: "③ Usar",
      variant: "outline",
    },
    {
      id: "st_rl",
      tone: "warn",
      kind: "box",
      at: {
        x: 900,
        y: 100,
        w: 200,
        h: 63,
      },
      label: "④ Rate Limit",
      variant: "outline",
    },
    {
      id: "st_rot",
      tone: "hot",
      kind: "box",
      at: {
        x: 1175,
        y: 100,
        w: 200,
        h: 63,
      },
      label: "⑤ Rotacionar",
      variant: "outline",
    },
    {
      id: "pa1",
      kind: "connector",
      from: {
        x: 275,
        y: 131,
      },
      to: {
        x: 350,
        y: 131,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pa2",
      kind: "connector",
      from: {
        x: 550,
        y: 131,
      },
      to: {
        x: 625,
        y: 131,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pa3",
      kind: "connector",
      from: {
        x: 825,
        y: 131,
      },
      to: {
        x: 900,
        y: 131,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pa4",
      kind: "connector",
      from: {
        x: 1100,
        y: 131,
      },
      to: {
        x: 1175,
        y: 131,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "gen_bg",
      kind: "box",
      at: {
        x: 38,
        y: 213,
        w: 275,
        h: 288,
      },
      variant: "outline",
    },
    {
      id: "gen_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 117,
        y: 214,
        w: 116,
        h: 41,
      },
      text: "🔑 Geração",
      align: "center",
    },
    {
      id: "gen1",
      kind: "label",
      at: {
        x: -78,
        y: 249,
        w: 256,
        h: 41,
      },
      text: "crypto.randomBytes(32)",
      align: "center",
    },
    {
      id: "gen2",
      kind: "label",
      at: {
        x: -72,
        y: 277,
        w: 244,
        h: 41,
      },
      text: "→ 256 bits aleatórios",
      align: "center",
    },
    {
      id: "gen3",
      kind: "label",
      at: {
        x: -95,
        y: 304,
        w: 291,
        h: 41,
      },
      text: "→ encode base62/base64url",
      align: "center",
    },
    {
      id: "gen_ex",
      kind: "box",
      at: {
        x: 50,
        y: 348,
        w: 250,
        h: 43,
      },
      label: "sk_live_Xk9mB2qR4n...",
      variant: "outline",
    },
    {
      id: "gen4",
      kind: "label",
      at: {
        x: -43,
        y: 389,
        w: 186,
        h: 41,
      },
      text: "Prefixo legível:",
      align: "center",
    },
    {
      id: "gen5",
      tone: "good",
      kind: "label",
      at: {
        x: -124,
        y: 412,
        w: 349,
        h: 41,
      },
      text: "`sk_live_` → Secret Key (prod)",
      align: "center",
    },
    {
      id: "gen6",
      tone: "warn",
      kind: "label",
      at: {
        x: -119,
        y: 437,
        w: 337,
        h: 41,
      },
      text: "`sk_test_` → Test environment",
      align: "center",
    },
    {
      id: "gen7",
      kind: "label",
      at: {
        x: -130,
        y: 462,
        w: 360,
        h: 41,
      },
      text: "`ghp_`  → GitHub Personal Token",
      align: "center",
    },
    {
      id: "hash_bg",
      kind: "box",
      at: {
        x: 325,
        y: 213,
        w: 275,
        h: 288,
      },
      variant: "outline",
    },
    {
      id: "hash_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 370,
        y: 214,
        w: 186,
        h: 41,
      },
      text: "🔒 Armazenamento",
      align: "center",
    },
    {
      id: "hash1",
      tone: "hot",
      kind: "label",
      at: {
        x: 181,
        y: 247,
        w: 314,
        h: 41,
      },
      text: "NUNCA guardar em plain text",
      align: "center",
    },
    {
      id: "hash2",
      tone: "good",
      kind: "label",
      at: {
        x: 215,
        y: 272,
        w: 244,
        h: 41,
      },
      text: "→ guarde SHA-256(key)",
      align: "center",
    },
    {
      id: "hash_flow",
      kind: "box",
      at: {
        x: 338,
        y: 315,
        w: 250,
        h: 88,
      },
      variant: "outline",
    },
    {
      id: "hf1",
      kind: "label",
      at: {
        x: 187,
        y: 312,
        w: 326,
        h: 41,
      },
      text: "User recebe: sk_live_Xk9m...",
      align: "center",
    },
    {
      id: "hf2",
      tone: "accent2",
      kind: "label",
      at: {
        x: 211,
        y: 337,
        w: 279,
        h: 41,
      },
      text: "DB guarda: a3f8c2e1b7...",
      align: "center",
    },
    {
      id: "hf3",
      kind: "label",
      at: {
        x: 211,
        y: 362,
        w: 279,
        h: 41,
      },
      text: "          (hash SHA-256)",
      align: "center",
    },
    {
      id: "hash3",
      kind: "label",
      at: {
        x: 291,
        y: 397,
        w: 93,
        h: 41,
      },
      text: "Por quê?",
      align: "center",
    },
    {
      id: "hash4",
      kind: "label",
      at: {
        x: 181,
        y: 419,
        w: 314,
        h: 41,
      },
      text: "→ vazamento de DB não expõe",
      align: "center",
    },
    {
      id: "hash5",
      kind: "label",
      at: {
        x: 239,
        y: 442,
        w: 198,
        h: 41,
      },
      text: "  as chaves reais",
      align: "center",
    },
    {
      id: "hash6",
      kind: "label",
      at: {
        x: 157,
        y: 464,
        w: 360,
        h: 41,
      },
      text: "→ Hash é one-way (irreversível)",
      align: "center",
    },
    {
      id: "use_bg",
      kind: "box",
      at: {
        x: 613,
        y: 213,
        w: 350,
        h: 288,
      },
      variant: "outline",
    },
    {
      id: "use_title",
      tone: "good",
      kind: "label",
      at: {
        x: 671,
        y: 214,
        w: 233,
        h: 41,
      },
      text: "📡 Uso & Verificação",
      align: "center",
    },
    {
      id: "use1",
      kind: "label",
      at: {
        x: 515,
        y: 247,
        w: 221,
        h: 41,
      },
      text: "Envio pelo cliente:",
      align: "center",
    },
    {
      id: "use_hdr",
      kind: "box",
      at: {
        x: 625,
        y: 285,
        w: 325,
        h: 33,
      },
      label: "Authorization: Bearer sk_live_Xk9m...",
      variant: "outline",
    },
    {
      id: "use_hdr2",
      kind: "box",
      at: {
        x: 625,
        y: 323,
        w: 325,
        h: 33,
      },
      label: "X-API-Key: sk_live_Xk9m...",
      variant: "outline",
    },
    {
      id: "use2",
      kind: "label",
      at: {
        x: 486,
        y: 349,
        w: 279,
        h: 41,
      },
      text: "Verificação no servidor:",
      align: "center",
    },
    {
      id: "use3",
      kind: "label",
      at: {
        x: 375,
        y: 374,
        w: 500,
        h: 41,
      },
      text: "1. Extrair prefixo → achar candidatos no DB",
      align: "center",
    },
    {
      id: "use4",
      kind: "label",
      at: {
        x: 422,
        y: 399,
        w: 407,
        h: 41,
      },
      text: "2. SHA-256(recebida) == hash_no_DB?",
      align: "center",
    },
    {
      id: "use5",
      kind: "label",
      at: {
        x: 439,
        y: 424,
        w: 372,
        h: 41,
      },
      text: "3. Verificar expiração e escopos",
      align: "center",
    },
    {
      id: "use6",
      kind: "label",
      at: {
        x: 422,
        y: 449,
        w: 407,
        h: 41,
      },
      text: "4. Registrar uso (rate limit, logs)",
      align: "center",
    },
    {
      id: "rl_bg",
      kind: "box",
      at: {
        x: 38,
        y: 538,
        w: 550,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "rl_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 150,
        y: 539,
        w: 326,
        h: 41,
      },
      text: "⏱️ Rate Limiting por API Key",
      align: "center",
    },
    {
      id: "rl1",
      kind: "label",
      at: {
        x: -89,
        y: 572,
        w: 279,
        h: 41,
      },
      text: "Redis counter por chave:",
      align: "center",
    },
    {
      id: "rl_cmd",
      kind: "box",
      at: {
        x: 50,
        y: 610,
        w: 525,
        h: 33,
      },
      label: "INCR ratelimit:sk_live_Xk9m  → count",
      variant: "outline",
    },
    {
      id: "rl_ttl",
      kind: "box",
      at: {
        x: 50,
        y: 648,
        w: 525,
        h: 33,
      },
      label: "EXPIRE ratelimit:sk_live_Xk9m 60  ← janela",
      variant: "outline",
    },
    {
      id: "rl2",
      tone: "hot",
      kind: "label",
      at: {
        x: -165,
        y: 674,
        w: 430,
        h: 41,
      },
      text: "count > limit → 429 Too Many Requests",
      align: "center",
    },
    {
      id: "rl3",
      kind: "label",
      at: {
        x: -66,
        y: 702,
        w: 233,
        h: 41,
      },
      text: "Headers de resposta:",
      align: "center",
    },
    {
      id: "rl4",
      kind: "label",
      at: {
        x: -241,
        y: 724,
        w: 581,
        h: 41,
      },
      text: "X-RateLimit-Limit: 1000  X-RateLimit-Remaining: 42",
      align: "center",
    },
    {
      id: "rl5",
      kind: "label",
      at: {
        x: -165,
        y: 749,
        w: 430,
        h: 41,
      },
      text: "Retry-After: 34  (segundos até reset)",
      align: "center",
    },
    {
      id: "scope_bg",
      kind: "box",
      at: {
        x: 613,
        y: 538,
        w: 575,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "scope_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 766,
        y: 539,
        w: 267,
        h: 41,
      },
      text: "🎯 Escopos & Permissões",
      align: "center",
    },
    {
      id: "sc1",
      kind: "label",
      at: {
        x: 451,
        y: 572,
        w: 349,
        h: 41,
      },
      text: "Definidos na criação da chave:",
      align: "center",
    },
    {
      id: "sc2",
      kind: "label",
      at: {
        x: 387,
        y: 597,
        w: 477,
        h: 41,
      },
      text: "`read:repos`  `write:issues`  `admin:org`",
      align: "center",
    },
    {
      id: "sc3",
      tone: "good",
      kind: "label",
      at: {
        x: 369,
        y: 624,
        w: 512,
        h: 41,
      },
      text: "Granularidade → principle of least privilege",
      align: "center",
    },
    {
      id: "sc4",
      kind: "label",
      at: {
        x: 567,
        y: 652,
        w: 116,
        h: 41,
      },
      text: "Expiração:",
      align: "center",
    },
    {
      id: "sc5",
      kind: "label",
      at: {
        x: 352,
        y: 677,
        w: 546,
        h: 41,
      },
      text: "`expires_at: 2025-12-31`  +  notificação prévia",
      align: "center",
    },
    {
      id: "sc6",
      kind: "label",
      at: {
        x: 515,
        y: 704,
        w: 221,
        h: 41,
      },
      text: "Revogação imediata:",
      align: "center",
    },
    {
      id: "sc7",
      tone: "hot",
      kind: "label",
      at: {
        x: 346,
        y: 729,
        w: 558,
        h: 41,
      },
      text: "DELETE hash do banco → próxima req falha com 401",
      align: "center",
    },
    {
      id: "rev_bg",
      kind: "box",
      at: {
        x: 1000,
        y: 213,
        w: 525,
        h: 288,
      },
      variant: "outline",
    },
    {
      id: "rev_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 1146,
        y: 214,
        w: 233,
        h: 41,
      },
      text: "🔄 Rotação de Chaves",
      align: "center",
    },
    {
      id: "rv1",
      kind: "label",
      at: {
        x: 902,
        y: 247,
        w: 221,
        h: 41,
      },
      text: "Por que rotacionar?",
      align: "center",
    },
    {
      id: "rv2",
      kind: "label",
      at: {
        x: 803,
        y: 272,
        w: 419,
        h: 41,
      },
      text: "→ chave comprometida → dano limitado",
      align: "center",
    },
    {
      id: "rv3",
      kind: "label",
      at: {
        x: 832,
        y: 297,
        w: 360,
        h: 41,
      },
      text: "→ conformidade (SOC 2, PCI DSS)",
      align: "center",
    },
    {
      id: "rv4",
      kind: "label",
      at: {
        x: 885,
        y: 324,
        w: 256,
        h: 41,
      },
      text: "Processo sem downtime:",
      align: "center",
    },
    {
      id: "rv5",
      tone: "good",
      kind: "label",
      at: {
        x: 873,
        y: 349,
        w: 279,
        h: 41,
      },
      text: "1. Criar nova chave (v2)",
      align: "center",
    },
    {
      id: "rv6",
      tone: "good",
      kind: "label",
      at: {
        x: 838,
        y: 374,
        w: 349,
        h: 41,
      },
      text: "2. Aceitar v1 e v2 em paralelo",
      align: "center",
    },
    {
      id: "rv7",
      tone: "good",
      kind: "label",
      at: {
        x: 873,
        y: 399,
        w: 279,
        h: 41,
      },
      text: "3. Cliente migra para v2",
      align: "center",
    },
    {
      id: "rv8",
      tone: "warn",
      kind: "label",
      at: {
        x: 803,
        y: 424,
        w: 419,
        h: 41,
      },
      text: "4. Revogar v1 após período de gracia",
      align: "center",
    },
    {
      id: "rv9",
      kind: "label",
      at: {
        x: 821,
        y: 449,
        w: 384,
        h: 41,
      },
      text: "→ zero downtime para o integrador",
      align: "center",
    },
    {
      id: "cmp_bg",
      kind: "box",
      at: {
        x: 1000,
        y: 525,
        w: 525,
        h: 138,
      },
      variant: "outline",
    },
    {
      id: "cmp_title",
      kind: "label",
      at: {
        x: 1140,
        y: 527,
        w: 244,
        h: 41,
      },
      text: "🔐 API Keys vs Outros",
      align: "center",
    },
    {
      id: "cm1",
      kind: "label",
      at: {
        x: 815,
        y: 554,
        w: 395,
        h: 41,
      },
      text: "vs Session: sem estado server-side",
      align: "center",
    },
    {
      id: "cm2",
      kind: "label",
      at: {
        x: 768,
        y: 579,
        w: 488,
        h: 41,
      },
      text: "vs JWT: mais simples, sem claims embutidas",
      align: "center",
    },
    {
      id: "cm3",
      kind: "label",
      at: {
        x: 809,
        y: 604,
        w: 407,
        h: 41,
      },
      text: "vs OAuth: ideal M2M, sem user agent",
      align: "center",
    },
    {
      id: "cm4",
      kind: "label",
      at: {
        x: 739,
        y: 629,
        w: 546,
        h: 41,
      },
      text: "Uso típico: CLI tools, webhooks, integração B2B",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que são API Keys e quando usar",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "cmp_bg",
        "cmp_title",
        "cm1",
        "cm2",
        "cm3",
        "cm4",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "cmp_bg",
        placement: "left",
        text: "API Keys são tokens opacos que identificam/autenticam um **cliente programático** (M2M). Ideais para CLIs, webhooks e integração B2B onde não há usuário interativo.",
      },
    },
    {
      id: "s2",
      title: "① Geração: token criptograficamente aleatório",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "gen_bg",
        "gen_title",
        "gen1",
        "gen2",
        "gen3",
        "gen_ex",
        "gen4",
        "gen5",
        "gen6",
        "gen7",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_gen",
          do: "highlight",
        },
        {
          at: 0,
          target: "gen_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "gen_bg",
        placement: "right",
        text: "`crypto.randomBytes(32)` gera 256 bits de entropia. O **prefixo legível** (`sk_live_`, `ghp_`) facilita identificar o tipo e ambiente da chave — essencial para buscar em logs sem expor o valor real.",
        why: "Nunca use UUIDs sequenciais ou hashes de dados previsíveis como API Keys.",
      },
    },
    {
      id: "s3",
      title: "② Armazenamento: guardar o hash, nunca a chave",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "hash_bg",
        "hash_title",
        "hash1",
        "hash2",
        "hash_flow",
        "hf1",
        "hf2",
        "hf3",
        "hash3",
        "hash4",
        "hash5",
        "hash6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_store",
          do: "highlight",
        },
        {
          at: 0,
          target: "hash_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hash_bg",
        placement: "right",
        text: "O banco guarda apenas `SHA-256(key)`. Um vazamento de banco não expõe as chaves reais. Na verificação, o servidor recalcula `SHA-256(recebida)` e compara com o hash armazenado.",
        why: "SHA-256 é one-way — mesmo com o hash, não dá para reconstruir a chave original.",
      },
    },
    {
      id: "s4",
      title: "③ Uso e verificação no servidor",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "use_bg",
        "use_title",
        "use1",
        "use_hdr",
        "use_hdr2",
        "use2",
        "use3",
        "use4",
        "use5",
        "use6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_use",
          do: "highlight",
        },
        {
          at: 0,
          target: "use_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "use_bg",
        placement: "left",
        text: "Cliente envia via `Authorization: Bearer` ou `X-API-Key`. Servidor usa o prefixo para filtrar candidatos no DB (evitar full-table-scan), depois compara `SHA-256(recebida) == hash_armazenado`.",
      },
    },
    {
      id: "s5",
      title: "④ Rate Limiting por API Key no Redis",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "rl_bg",
        "rl_title",
        "rl1",
        "rl_cmd",
        "rl_ttl",
        "rl2",
        "rl3",
        "rl4",
        "rl5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_rl",
          do: "highlight",
        },
        {
          at: 0,
          target: "rl_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "rl_bg",
        placement: "right",
        text: "Contador Redis por chave: `INCR ratelimit:sk_live_Xk9m` — se `count > limit`, retorna **429**. `EXPIRE` define a janela de tempo (60s, 1h...). Headers informam o cliente quanto falta.",
        why: "Rate limit por chave evita que um abusador impacte outros clientes da API.",
      },
    },
    {
      id: "s6",
      title: "Escopos, Permissões e Expiração",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "scope_bg",
        "scope_title",
        "sc1",
        "sc2",
        "sc3",
        "sc4",
        "sc5",
        "sc6",
        "sc7",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "scope_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "scope_bg",
        placement: "left",
        text: "Escopos definem o que a chave pode fazer (`read:repos`, `write:issues`). Principle of least privilege — chaves com menos permissões limitam o dano de uma chave comprometida. Expiração + revogação imediata completam o ciclo.",
      },
    },
    {
      id: "s7",
      title: "⑤ Rotação de chaves sem downtime",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "rev_bg",
        "rev_title",
        "rv1",
        "rv2",
        "rv3",
        "rv4",
        "rv5",
        "rv6",
        "rv7",
        "rv8",
        "rv9",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_rot",
          do: "highlight",
        },
        {
          at: 0,
          target: "rev_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "rev_bg",
        placement: "left",
        text: "Crie a nova chave → aceite v1 e v2 em paralelo → cliente migra → revogue v1. Esse overlap evita downtime durante a troca. Para revogação de emergência: deletar do DB imediatamente.",
      },
    },
    {
      id: "s8",
      title: "API Keys vs JWT vs Sessions vs OAuth",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "cmp_bg",
        "cmp_title",
        "cm1",
        "cm2",
        "cm3",
        "cm4",
        "rev_bg",
        "rev_title",
        "rv1",
        "rv2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "cmp_bg",
        placement: "top",
        text: "**API Keys**: simples, M2M, sem claims. **JWT**: stateless com claims embutidas. **Sessions**: estado server-side, revogação fácil. **OAuth**: delegação de acesso com user flow. Use API Keys quando o cliente é confiável e controlado.",
      },
    },
    {
      id: "s9",
      title: "Quiz",
      duration: 6500,
      add: ["st_gen", "st_store", "st_use", "st_rl", "st_rot", "pa1", "pa2", "pa3", "pa4"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: "Por que o servidor deve guardar apenas o SHA-256 da API Key, e não a chave em plain text?",
        options: [
          "Para economizar espaço no banco — hashes são menores que a chave original",
          "Para dificultar que um atacante que vaze o banco possa usar as chaves roubadas",
          "Porque a API Key é derivada matematicamente do hash armazenado",
          "Para que o servidor possa regenerar a chave original a partir do hash quando necessário",
        ],
        answer: 1,
        explain:
          "SHA-256 é one-way: não é possível reconstruir a chave original a partir do hash. Se o banco vazar, o atacante tem apenas hashes inúteis — para usá-los, precisaria fazer brute-force de 256 bits de entropia, o que é computacionalmente inviável.",
      },
    },
    {
      id: "s10",
      title: "Resumo: API Keys",
      duration: 6500,
      add: [
        "st_gen",
        "st_store",
        "st_use",
        "st_rl",
        "st_rot",
        "pa1",
        "pa2",
        "pa3",
        "pa4",
        "gen_bg",
        "gen_title",
        "gen1",
        "gen3",
        "gen_ex",
        "hash_bg",
        "hash_title",
        "hash1",
        "hash2",
        "hash_flow",
        "hf1",
        "hf2",
        "hf3",
        "use_bg",
        "use_title",
        "use_hdr",
        "rl_bg",
        "rl_title",
        "rl_cmd",
        "scope_bg",
        "scope_title",
        "sc2",
        "sc6",
        "sc7",
        "rev_bg",
        "rev_title",
        "rv5",
        "rv6",
        "rv7",
        "rv8",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "hash_bg",
        placement: "right",
        text: "API Keys: 256 bits aleatórios com prefixo legível. Guardar apenas SHA-256. Rate limit por key no Redis. Escopos mínimos. Rotação com overlap. Revogação imediata deletando o hash.",
      },
    },
  ],
};

export const apiKeys = validateExplainer(data);
