import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/blockchain.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "blockchain",
  title: "Blockchain",
  category: "Sistemas Distribuídos",
  tags: ["blockchain", "distribuído"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "chain_title",
      kind: "label",
      at: {
        x: 104,
        y: 4,
        w: 616,
        h: 41,
      },
      text: "⛓️  Blockchain — cadeia de blocos encadeados por hash",
      align: "center",
    },
    {
      id: "blk0",
      kind: "box",
      at: {
        x: 25,
        y: 63,
        w: 175,
        h: 175,
      },
      label: "Bloco 0\n(Genesis)",
      variant: "outline",
    },
    {
      id: "blk1",
      tone: "accent",
      kind: "box",
      at: {
        x: 225,
        y: 63,
        w: 175,
        h: 175,
      },
      label: "Bloco 1",
      variant: "outline",
    },
    {
      id: "blk2",
      tone: "accent2",
      kind: "box",
      at: {
        x: 425,
        y: 63,
        w: 175,
        h: 175,
      },
      label: "Bloco 2",
      variant: "outline",
    },
    {
      id: "blk3",
      tone: "good",
      kind: "box",
      at: {
        x: 625,
        y: 63,
        w: 175,
        h: 175,
      },
      label: "Bloco 3",
      variant: "outline",
    },
    {
      id: "ch0",
      tone: "accent",
      kind: "connector",
      from: {
        x: 200,
        y: 150,
      },
      to: {
        x: 225,
        y: 150,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ch1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 400,
        y: 150,
      },
      to: {
        x: 425,
        y: 150,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ch2",
      tone: "accent",
      kind: "connector",
      from: {
        x: 600,
        y: 150,
      },
      to: {
        x: 625,
        y: 150,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "chl0",
      tone: "accent",
      kind: "label",
      at: {
        x: 160,
        y: 112,
        w: 105,
        h: 41,
      },
      text: "prev_hash",
      align: "center",
    },
    {
      id: "chl1",
      tone: "accent",
      kind: "label",
      at: {
        x: 360,
        y: 112,
        w: 105,
        h: 41,
      },
      text: "prev_hash",
      align: "center",
    },
    {
      id: "chl2",
      tone: "accent",
      kind: "label",
      at: {
        x: 560,
        y: 112,
        w: 105,
        h: 41,
      },
      text: "prev_hash",
      align: "center",
    },
    {
      id: "b0_idx",
      kind: "label",
      at: {
        x: -9,
        y: 77,
        w: 93,
        h: 41,
      },
      text: "index: 0",
      align: "center",
    },
    {
      id: "b0_prv",
      kind: "label",
      at: {
        x: -38,
        y: 102,
        w: 151,
        h: 41,
      },
      text: "prev: 0000...",
      align: "center",
    },
    {
      id: "b0_hsh",
      tone: "accent",
      kind: "label",
      at: {
        x: -50,
        y: 127,
        w: 174,
        h: 41,
      },
      text: "hash: a1b2c3...",
      align: "center",
    },
    {
      id: "b1_idx",
      kind: "label",
      at: {
        x: 191,
        y: 77,
        w: 93,
        h: 41,
      },
      text: "index: 1",
      align: "center",
    },
    {
      id: "b1_prv",
      tone: "accent",
      kind: "label",
      at: {
        x: 150,
        y: 102,
        w: 174,
        h: 41,
      },
      text: "prev: a1b2c3...",
      align: "center",
    },
    {
      id: "b1_hsh",
      tone: "accent2",
      kind: "label",
      at: {
        x: 150,
        y: 127,
        w: 174,
        h: 41,
      },
      text: "hash: d4e5f6...",
      align: "center",
    },
    {
      id: "b2_idx",
      kind: "label",
      at: {
        x: 391,
        y: 77,
        w: 93,
        h: 41,
      },
      text: "index: 2",
      align: "center",
    },
    {
      id: "b2_prv",
      tone: "accent2",
      kind: "label",
      at: {
        x: 350,
        y: 102,
        w: 174,
        h: 41,
      },
      text: "prev: d4e5f6...",
      align: "center",
    },
    {
      id: "b2_hsh",
      tone: "good",
      kind: "label",
      at: {
        x: 350,
        y: 127,
        w: 174,
        h: 41,
      },
      text: "hash: 00007a...",
      align: "center",
    },
    {
      id: "b3_idx",
      kind: "label",
      at: {
        x: 591,
        y: 77,
        w: 93,
        h: 41,
      },
      text: "index: 3",
      align: "center",
    },
    {
      id: "b3_prv",
      tone: "good",
      kind: "label",
      at: {
        x: 550,
        y: 102,
        w: 174,
        h: 41,
      },
      text: "prev: 00007a...",
      align: "center",
    },
    {
      id: "b3_hsh",
      tone: "good",
      kind: "label",
      at: {
        x: 550,
        y: 127,
        w: 174,
        h: 41,
      },
      text: "hash: 0000b2...",
      align: "center",
    },
    {
      id: "b1_nc",
      tone: "warn",
      kind: "label",
      at: {
        x: 168,
        y: 152,
        w: 140,
        h: 41,
      },
      text: "nonce: 83721",
      align: "center",
    },
    {
      id: "b2_nc",
      tone: "warn",
      kind: "label",
      at: {
        x: 362,
        y: 152,
        w: 151,
        h: 41,
      },
      text: "nonce: 192847",
      align: "center",
    },
    {
      id: "b3_nc",
      tone: "warn",
      kind: "label",
      at: {
        x: 556,
        y: 152,
        w: 163,
        h: 41,
      },
      text: "nonce: 4710293",
      align: "center",
    },
    {
      id: "b1_tx",
      kind: "label",
      at: {
        x: 127,
        y: 179,
        w: 221,
        h: 41,
      },
      text: "txs: [A→B 1BTC,...]",
      align: "center",
    },
    {
      id: "b2_tx",
      kind: "label",
      at: {
        x: 327,
        y: 179,
        w: 221,
        h: 41,
      },
      text: "txs: [C→D 0.5,...] ",
      align: "center",
    },
    {
      id: "b3_tx",
      kind: "label",
      at: {
        x: 521,
        y: 179,
        w: 233,
        h: 41,
      },
      text: "txs: [E→F 2BTC,...] ",
      align: "center",
    },
    {
      id: "immut_bg",
      kind: "box",
      at: {
        x: 25,
        y: 250,
        w: 775,
        h: 30,
      },
      variant: "outline",
    },
    {
      id: "immut_lbl",
      tone: "hot",
      kind: "label",
      at: {
        x: -29,
        y: 249,
        w: 884,
        h: 41,
      },
      text: "⚠️ Alterar bloco 2 → hash 2 muda → prev_hash 3 invalida → e assim por diante",
      align: "center",
    },
    {
      id: "zoom_bg",
      kind: "box",
      at: {
        x: 825,
        y: 38,
        w: 725,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "zoom_title",
      kind: "label",
      at: {
        x: 1054,
        y: 39,
        w: 267,
        h: 41,
      },
      text: "🔍 Anatomia de um Bloco",
      align: "center",
    },
    {
      id: "z1",
      kind: "label",
      at: {
        x: 553,
        y: 69,
        w: 570,
        h: 41,
      },
      text: "index      → número sequencial do bloco na cadeia",
      align: "center",
    },
    {
      id: "z2",
      kind: "label",
      at: {
        x: 559,
        y: 94,
        w: 558,
        h: 41,
      },
      text: "timestamp  → momento em que o bloco foi minerado",
      align: "center",
    },
    {
      id: "z3",
      kind: "label",
      at: {
        x: 541,
        y: 119,
        w: 593,
        h: 41,
      },
      text: "txs[]      → lista de transações incluídas no bloco",
      align: "center",
    },
    {
      id: "z4",
      tone: "warn",
      kind: "label",
      at: {
        x: 553,
        y: 144,
        w: 570,
        h: 41,
      },
      text: "nonce      → número ajustável para satisfazer PoW",
      align: "center",
    },
    {
      id: "z5",
      tone: "accent",
      kind: "label",
      at: {
        x: 547,
        y: 169,
        w: 581,
        h: 41,
      },
      text: "prev_hash  → hash do bloco anterior (cria o chain)",
      align: "center",
    },
    {
      id: "z6",
      tone: "good",
      kind: "label",
      at: {
        x: 535,
        y: 197,
        w: 605,
        h: 41,
      },
      text: "hash       → SHA256(index + txs + nonce + prev_hash)",
      align: "center",
    },
    {
      id: "z7",
      kind: "label",
      at: {
        x: 599,
        y: 227,
        w: 477,
        h: 41,
      },
      text: "Merkle root→ hash da árvore de transações",
      align: "center",
    },
    {
      id: "hash_formula",
      kind: "box",
      at: {
        x: 838,
        y: 270,
        w: 700,
        h: 35,
      },
      label: "hash = SHA256(index ‖ timestamp ‖ txs ‖ nonce ‖ prev_hash)",
      variant: "outline",
    },
    {
      id: "z8",
      tone: "hot",
      kind: "label",
      at: {
        x: 535,
        y: 302,
        w: 605,
        h: 41,
      },
      text: "Para alterar 1 tx no bloco 2: hash 2 muda → invalida",
      align: "center",
    },
    {
      id: "z9",
      tone: "hot",
      kind: "label",
      at: {
        x: 582,
        y: 327,
        w: 512,
        h: 41,
      },
      text: "→ prev_hash 3 e todos os blocos subsequentes",
      align: "center",
    },
    {
      id: "z10",
      tone: "hot",
      kind: "label",
      at: {
        x: 559,
        y: 352,
        w: 558,
        h: 41,
      },
      text: "→ Teria que re-minerar TODOS os blocos seguintes",
      align: "center",
    },
    {
      id: "mine_bg",
      kind: "box",
      at: {
        x: 825,
        y: 413,
        w: 725,
        h: 225,
      },
      variant: "outline",
    },
    {
      id: "mine_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 1060,
        y: 414,
        w: 256,
        h: 41,
      },
      text: "⛏️ Proof of Work (PoW)",
      align: "center",
    },
    {
      id: "m1",
      kind: "label",
      at: {
        x: 506,
        y: 447,
        w: 663,
        h: 41,
      },
      text: "Objetivo: encontrar nonce tal que hash comece com N zeros",
      align: "center",
    },
    {
      id: "mine_ex",
      kind: "box",
      at: {
        x: 838,
        y: 488,
        w: 700,
        h: 33,
      },
      label: 'while SHA256(bloco+nonce) não começa com "0000":  nonce++',
      variant: "outline",
    },
    {
      id: "m2",
      kind: "label",
      at: {
        x: 617,
        y: 517,
        w: 442,
        h: 41,
      },
      text: "N=4 zeros: ~65.000 tentativas em média",
      align: "center",
    },
    {
      id: "m3",
      tone: "hot",
      kind: "label",
      at: {
        x: 628,
        y: 542,
        w: 419,
        h: 41,
      },
      text: "N=20 zeros: ~1 trilhão de tentativas",
      align: "center",
    },
    {
      id: "m4",
      kind: "label",
      at: {
        x: 500,
        y: 567,
        w: 674,
        h: 41,
      },
      text: "Bitcoin ~N=74 bits: ~10 min/bloco (4B nonces + extraNonce)",
      align: "center",
    },
    {
      id: "m5",
      kind: "label",
      at: {
        x: 547,
        y: 592,
        w: 581,
        h: 41,
      },
      text: "Dificuldade ajusta a cada 2016 blocos (~2 semanas)",
      align: "center",
    },
    {
      id: "con_bg",
      kind: "box",
      at: {
        x: 825,
        y: 675,
        w: 725,
        h: 200,
      },
      variant: "outline",
    },
    {
      id: "con_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 996,
        y: 677,
        w: 384,
        h: 41,
      },
      text: "🗳️ Consensus: Longest Chain Wins",
      align: "center",
    },
    {
      id: "con1",
      kind: "label",
      at: {
        x: 559,
        y: 709,
        w: 558,
        h: 41,
      },
      text: "Regra: a cadeia mais longa (mais trabalho) vence",
      align: "center",
    },
    {
      id: "con2",
      tone: "hot",
      kind: "label",
      at: {
        x: 570,
        y: 734,
        w: 535,
        h: 41,
      },
      text: "Ataque 51%: controlar >50% do hashrate da rede",
      align: "center",
    },
    {
      id: "con3",
      tone: "hot",
      kind: "label",
      at: {
        x: 547,
        y: 759,
        w: 581,
        h: 41,
      },
      text: "→ Pode re-organizar blocos recentes (double-spend)",
      align: "center",
    },
    {
      id: "con4",
      kind: "label",
      at: {
        x: 733,
        y: 784,
        w: 209,
        h: 41,
      },
      text: "PoW vs PoS vs BFT:",
      align: "center",
    },
    {
      id: "con5",
      tone: "warn",
      kind: "label",
      at: {
        x: 564,
        y: 809,
        w: 546,
        h: 41,
      },
      text: "PoW (Bitcoin): energia, seguro, descentralizado",
      align: "center",
    },
    {
      id: "con6",
      tone: "good",
      kind: "label",
      at: {
        x: 541,
        y: 834,
        w: 593,
        h: 41,
      },
      text: "PoS (Ethereum 2.0): eficiente, finality mais rápida",
      align: "center",
    },
    {
      id: "con7",
      tone: "accent",
      kind: "label",
      at: {
        x: 529,
        y: 859,
        w: 616,
        h: 41,
      },
      text: "BFT (Hyperledger): permissioned, finality instantânea",
      align: "center",
    },
    {
      id: "mem_bg",
      kind: "box",
      at: {
        x: 38,
        y: 300,
        w: 763,
        h: 338,
      },
      variant: "outline",
    },
    {
      id: "mem_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 227,
        y: 302,
        w: 384,
        h: 41,
      },
      text: "💳 Ciclo de Vida de uma Transação",
      align: "center",
    },
    {
      id: "mem1",
      kind: "label",
      at: {
        x: -171,
        y: 334,
        w: 442,
        h: 41,
      },
      text: "1. Usuário assina tx com chave privada",
      align: "center",
    },
    {
      id: "mem2",
      kind: "label",
      at: {
        x: -113,
        y: 359,
        w: 326,
        h: 41,
      },
      text: "2. Broadcast para a rede P2P",
      align: "center",
    },
    {
      id: "mem3",
      tone: "accent2",
      kind: "label",
      at: {
        x: -194,
        y: 384,
        w: 488,
        h: 41,
      },
      text: "3. Tx entra no Mempool (fila de pendentes)",
      align: "center",
    },
    {
      id: "mem4",
      tone: "warn",
      kind: "label",
      at: {
        x: -212,
        y: 409,
        w: 523,
        h: 41,
      },
      text: "4. Minerador escolhe txs (geralmente por fee)",
      align: "center",
    },
    {
      id: "mem5",
      tone: "warn",
      kind: "label",
      at: {
        x: -177,
        y: 434,
        w: 453,
        h: 41,
      },
      text: "5. Mina o bloco (encontra nonce válido)",
      align: "center",
    },
    {
      id: "mem6",
      kind: "label",
      at: {
        x: -153,
        y: 459,
        w: 407,
        h: 41,
      },
      text: "6. Bloco propagado para toda a rede",
      align: "center",
    },
    {
      id: "mem7",
      tone: "good",
      kind: "label",
      at: {
        x: -194,
        y: 484,
        w: 488,
        h: 41,
      },
      text: "7. Outros nós validam e adicionam ao chain",
      align: "center",
    },
    {
      id: "mem8",
      tone: "warn",
      kind: "label",
      at: {
        x: -194,
        y: 512,
        w: 488,
        h: 41,
      },
      text: "⚠️  1 confirmação = bloco incluso na chain",
      align: "center",
    },
    {
      id: "mem9",
      tone: "good",
      kind: "label",
      at: {
        x: -264,
        y: 537,
        w: 628,
        h: 41,
      },
      text: "✅  6 confirmações = considerado irreversível (Bitcoin)",
      align: "center",
    },
    {
      id: "mem10",
      kind: "label",
      at: {
        x: -281,
        y: 562,
        w: 663,
        h: 41,
      },
      text: "→ 6 blocos após = atacante precisaria re-minerar 7 blocos",
      align: "center",
    },
    {
      id: "mem11",
      kind: "label",
      at: {
        x: -177,
        y: 589,
        w: 453,
        h: 41,
      },
      text: "   com >50% hashrate — custo proibitivo",
      align: "center",
    },
    {
      id: "mem12",
      kind: "label",
      at: {
        x: -177,
        y: 614,
        w: 453,
        h: 41,
      },
      text: "→ Tempo médio: ~60 minutos (6 × 10 min)",
      align: "center",
    },
    {
      id: "sc_bg",
      kind: "box",
      at: {
        x: 38,
        y: 663,
        w: 763,
        h: 188,
      },
      variant: "outline",
    },
    {
      id: "sc_title",
      tone: "good",
      kind: "label",
      at: {
        x: 320,
        y: 664,
        w: 198,
        h: 41,
      },
      text: "⚡ Smart Contracts",
      align: "center",
    },
    {
      id: "sc1",
      kind: "label",
      at: {
        x: -217,
        y: 697,
        w: 535,
        h: 41,
      },
      text: "Código determinístico armazenado no blockchain",
      align: "center",
    },
    {
      id: "sc2",
      kind: "label",
      at: {
        x: -241,
        y: 722,
        w: 581,
        h: 41,
      },
      text: "Executado por todos os nós durante validação (EVM)",
      align: "center",
    },
    {
      id: "sc3",
      kind: "label",
      at: {
        x: -270,
        y: 747,
        w: 639,
        h: 41,
      },
      text: "Autoexecutável: condição cumprida → execução automática",
      align: "center",
    },
    {
      id: "sc4",
      kind: "label",
      at: {
        x: -275,
        y: 772,
        w: 651,
        h: 41,
      },
      text: "Ex: escrow — liberar pagamento quando entrega confirmada",
      align: "center",
    },
    {
      id: "sc5",
      tone: "warn",
      kind: "label",
      at: {
        x: -258,
        y: 797,
        w: 616,
        h: 41,
      },
      text: "Gas fee: custo computacional em ETH pago ao minerador",
      align: "center",
    },
    {
      id: "sc6",
      kind: "label",
      at: {
        x: -229,
        y: 822,
        w: 558,
        h: 41,
      },
      text: "Solidity (Ethereum), Rust (Solana), Move (Aptos)",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: confiança sem intermediário",
      duration: 6500,
      add: ["chain_title", "blk0", "blk1", "blk2", "blk3", "ch0", "ch1", "ch2", "chl0", "chl1", "chl2"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "blk1",
        placement: "bottom",
        text: "Como garantir que uma transação é válida sem confiar em um banco central? Blockchain resolve o double-spend com um ledger distribuído e imutável.",
      },
    },
    {
      id: "s2",
      title: "Ledger distribuído: todos os nós verificam",
      duration: 6500,
      add: ["chain_title", "blk0", "blk1", "blk2", "blk3", "ch0", "ch1", "ch2", "chl0", "chl1", "chl2"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "blk2",
        placement: "bottom",
        text: "Milhares de nós ao redor do mundo têm **cópia idêntica** da cadeia. Cada um valida independentemente toda nova transação e bloco. Para fraudar, precisaria enganar a maioria dos nós.",
      },
    },
    {
      id: "s3",
      title: "Anatomia de um bloco",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "chl0",
        "chl1",
        "chl2",
        "b1_idx",
        "b1_prv",
        "b1_hsh",
        "b1_nc",
        "b1_tx",
        "b2_idx",
        "b2_prv",
        "b2_hsh",
        "b2_nc",
        "b2_tx",
        "b3_idx",
        "b3_prv",
        "b3_hsh",
        "b3_nc",
        "b3_tx",
        "b0_idx",
        "b0_prv",
        "b0_hsh",
        "zoom_bg",
        "zoom_title",
        "z1",
        "z2",
        "z3",
        "z4",
        "z5",
        "z6",
        "hash_formula",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "blk2",
          do: "highlight",
        },
        {
          at: 0,
          target: "zoom_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "zoom_bg",
        placement: "left",
        text: 'Cada bloco contém: `index`, `timestamp`, `txs[]`, `nonce`, `prev_hash` e o próprio `hash = SHA256(todos os campos)`. O `prev_hash` é o elo que cria a "cadeia".',
      },
    },
    {
      id: "s4",
      title: "Encadeamento: prev_hash cria imutabilidade",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "chl0",
        "chl1",
        "chl2",
        "b0_hsh",
        "b1_prv",
        "b1_hsh",
        "b2_prv",
        "b2_hsh",
        "b3_prv",
        "b3_hsh",
        "immut_bg",
        "immut_lbl",
        "zoom_bg",
        "zoom_title",
        "z5",
        "z6",
        "z7",
        "z8",
        "z9",
        "z10",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "blk2",
          do: "highlight",
        },
        {
          at: 0,
          target: "blk3",
          do: "highlight",
        },
        {
          at: 0,
          target: "immut_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "immut_lbl",
        placement: "top",
        text: "O `hash` do bloco 1 vira o `prev_hash` do bloco 2. Se qualquer campo do bloco 2 mudar, seu hash muda — e o `prev_hash` do bloco 3 fica inconsistente. A cadeia é **imutável retroativamente**.",
        why: "Para reescrever o bloco 2, precisaria re-minerar 2, 3, 4... e superar o poder computacional de toda a rede.",
      },
    },
    {
      id: "s5",
      title: "Proof of Work: encontrar o nonce certo",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "b2_hsh",
        "b2_nc",
        "mine_bg",
        "mine_title",
        "m1",
        "mine_ex",
        "m2",
        "m3",
        "m4",
        "m5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "blk2",
          do: "highlight",
        },
        {
          at: 0,
          target: "mine_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "mine_bg",
        placement: "left",
        text: "O hash precisa começar com N zeros: `0000ab2c3d...`. Para isso, o minerador testa bilhões de valores de `nonce` até encontrar um que satisfaça essa condição — puro brute-force intencional.",
        why: 'O custo computacional é a "prova de trabalho" — torna inviável reescrever a história.',
      },
    },
    {
      id: "s6",
      title: "Mining: brute-force e dificuldade ajustável",
      duration: 6500,
      add: ["mine_bg", "mine_title", "m1", "mine_ex", "m2", "m3", "m4", "m5"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "mine_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "mine_bg",
        placement: "right",
        text: "A rede Bitcoin ajusta a dificuldade a cada 2016 blocos (~2 semanas) para manter ~10 min/bloco, independente de quantos mineradores entrarem na rede. Mais hashrate = dificuldade maior.",
      },
    },
    {
      id: "s7",
      title: "Consensus: longest chain wins",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "con_bg",
        "con_title",
        "con1",
        "con2",
        "con3",
        "con4",
        "con5",
        "con6",
        "con7",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "con_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "con_bg",
        placement: "left",
        text: "Quando dois nós mineram simultaneamente, há um fork temporário. A rede adota a cadeia com **mais trabalho acumulado** (geralmente a mais longa). Forks curtos se resolvem em 1-2 blocos.",
        why: "Ataque 51%: se um grupo controla >50% do hashrate, pode criar uma cadeia alternativa mais rápida e revisar transações recentes — extremamente caro em Bitcoin.",
      },
    },
    {
      id: "s8",
      title: "Ciclo de vida de uma transação",
      duration: 6500,
      add: [
        "mem_bg",
        "mem_title",
        "mem1",
        "mem2",
        "mem3",
        "mem4",
        "mem5",
        "mem6",
        "mem7",
        "mem8",
        "mem9",
        "mem10",
        "mem11",
        "mem12",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "mem_bg",
        placement: "right",
        text: "Tx assinada → broadcast P2P → Mempool → minerador seleciona (por fee) → bloco minerado → propagado → validado. 6 confirmações = ~60 min = irreversível na prática.",
      },
    },
    {
      id: "s9",
      title: "PoW vs PoS vs BFT",
      duration: 6500,
      add: ["con_bg", "con_title", "con4", "con5", "con6", "con7"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "con_bg",
        placement: "right",
        text: "**PoW** (Bitcoin): computacionalmente intenso, muito seguro, sem finality imediata. **PoS** (Ethereum 2.0): validators apostam ETH como garantia — 99% menos energia, finality em 2 épocas. **BFT** (Hyperledger): permissioned, finality instantânea, ideal para consortium.",
      },
    },
    {
      id: "s10",
      title: "Smart Contracts: código autoexecutável no bloco",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "sc_bg",
        "sc_title",
        "sc1",
        "sc2",
        "sc3",
        "sc4",
        "sc5",
        "sc6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sc_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sc_bg",
        placement: "right",
        text: "Smart contracts são programas armazenados no blockchain, executados deterministicamente por todos os nós. Quando condições são cumpridas, executam automaticamente — sem intermediário. EVM (Ethereum), Solana, etc.",
      },
    },
    {
      id: "s11",
      title: "Quiz",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "b0_hsh",
        "b1_prv",
        "b1_hsh",
        "b2_prv",
        "b2_hsh",
        "b3_prv",
        "b3_hsh",
      ],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: "Por que alterar uma transação no bloco 2 invalida também os blocos 3, 4, 5...?",
        options: [
          "Porque todos os blocos usam o mesmo nonce, que precisa ser recalculado",
          "Porque o hash do bloco 2 muda, e o bloco 3 armazena esse hash como prev_hash",
          "Porque os mineradores re-validam todas as transações da cadeia inteira",
          "Porque a rede P2P retransmite a mudança para todos os nós simultaneamente",
        ],
        answer: 1,
        explain:
          'O campo `prev_hash` do bloco 3 contém o hash do bloco 2. Se qualquer dado do bloco 2 mudar, seu `hash` muda — e agora o `prev_hash` do bloco 3 aponta para um hash que não existe mais. O bloco 3 fica inválido, e o mesmo efeito cascateia para todos os blocos seguintes. Para "corrigir" isso, o atacante precisaria re-minerar todos os blocos afetados, gastando mais poder computacional que toda a rede honesta.',
      },
    },
    {
      id: "s12",
      title: "Resumo: Blockchain",
      duration: 6500,
      add: [
        "chain_title",
        "blk0",
        "blk1",
        "blk2",
        "blk3",
        "ch0",
        "ch1",
        "ch2",
        "chl0",
        "chl1",
        "chl2",
        "b0_hsh",
        "b1_prv",
        "b1_hsh",
        "b2_nc",
        "b2_hsh",
        "b3_prv",
        "b3_hsh",
        "immut_bg",
        "immut_lbl",
        "zoom_bg",
        "zoom_title",
        "z5",
        "z6",
        "hash_formula",
        "mine_bg",
        "mine_title",
        "m1",
        "m4",
        "mem_bg",
        "mem_title",
        "mem3",
        "mem9",
        "con_bg",
        "con_title",
        "con1",
        "con5",
        "con6",
        "sc_bg",
        "sc_title",
        "sc1",
        "sc3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "blk2",
        placement: "bottom",
        text: "Blocos encadeados por prev_hash → imutabilidade. PoW: brute-force de nonce para hash com N zeros. Longest chain wins. 6 confirmações = irreversível. PoS é mais eficiente. Smart contracts: código autoexecutável no chain.",
      },
    },
  ],
};

export const blockchain = validateExplainer(data);
