import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/circuit-breaker.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "circuit-breaker",
  title: "Circuit Breaker — Resiliência de serviços",
  subtitle: "CLOSED → OPEN → HALF-OPEN: evitar falhas em cascata",
  category: "Infraestrutura & Cloud",
  tags: ["resiliência", "microsserviços"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "st_closed",
      kind: "box",
      at: {
        x: 50,
        y: 88,
        w: 225,
        h: 225,
      },
      label: "✓ CLOSED",
      sub: "(fechado) · requisições · passam",
      variant: "outline",
    },
    {
      id: "st_open",
      kind: "box",
      at: {
        x: 50,
        y: 388,
        w: 225,
        h: 225,
      },
      label: "✗ OPEN",
      sub: "(aberto) · requisições · BLOQUEADAS",
      variant: "outline",
    },
    {
      id: "st_halfopen",
      kind: "box",
      at: {
        x: 75,
        y: 675,
        w: 175,
        h: 175,
      },
      label: "? HALF",
      sub: "OPEN",
      variant: "outline",
    },
    {
      id: "st_lbl",
      kind: "label",
      at: {
        x: 17,
        y: 12,
        w: 291,
        h: 41,
      },
      text: "Estado do Circuit Breaker",
      align: "center",
    },
    {
      id: "a_co",
      tone: "hot",
      kind: "connector",
      from: {
        x: 163,
        y: 313,
      },
      to: {
        x: 163,
        y: 388,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lbl_co",
      kind: "label",
      at: {
        x: 120,
        y: 329,
        w: 209,
        h: 41,
      },
      text: "threshold atingido",
      align: "center",
      muted: true,
    },
    {
      id: "a_oh",
      tone: "warn",
      kind: "connector",
      from: {
        x: 163,
        y: 613,
      },
      to: {
        x: 163,
        y: 675,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lbl_oh",
      kind: "label",
      at: {
        x: 155,
        y: 611,
        w: 140,
        h: 41,
      },
      text: "timer expira",
      align: "center",
      muted: true,
    },
    {
      id: "a_hc",
      tone: "good",
      kind: "connector",
      from: {
        x: 75,
        y: 763,
      },
      to: {
        x: 50,
        y: 200,
      },
      route: "curve",
      arrow: true,
    },
    {
      id: "lbl_hc",
      kind: "label",
      at: {
        x: -84,
        y: 461,
        w: 93,
        h: 41,
      },
      text: "probe ok",
      align: "center",
      muted: true,
    },
    {
      id: "a_ho",
      tone: "hot",
      kind: "connector",
      from: {
        x: 250,
        y: 763,
      },
      to: {
        x: 275,
        y: 500,
      },
      route: "curve",
      arrow: true,
    },
    {
      id: "lbl_ho",
      kind: "label",
      at: {
        x: 368,
        y: 611,
        w: 140,
        h: 41,
      },
      text: "probe falhou",
      align: "center",
      muted: true,
    },
    {
      id: "cl_box",
      kind: "box",
      at: {
        x: 625,
        y: 275,
        w: 250,
        h: 100,
      },
      label: "📱 Serviço A",
      sub: "(cliente)",
      variant: "outline",
    },
    {
      id: "sv_box",
      kind: "box",
      at: {
        x: 1125,
        y: 275,
        w: 250,
        h: 100,
      },
      label: "⚙️ Serviço B",
      sub: "(dependência)",
      variant: "outline",
    },
    {
      id: "req_ok",
      tone: "good",
      kind: "connector",
      from: {
        x: 875,
        y: 325,
      },
      to: {
        x: 1125,
        y: 325,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "req_ok_l",
      kind: "label",
      at: {
        x: 895,
        y: 283,
        w: 209,
        h: 41,
      },
      text: "request → OK (200)",
      align: "center",
      muted: true,
    },
    {
      id: "resp_ok2",
      tone: "good",
      kind: "connector",
      from: {
        x: 1125,
        y: 363,
      },
      to: {
        x: 875,
        y: 363,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "resp_ok2_l",
      kind: "label",
      at: {
        x: 901,
        y: 364,
        w: 198,
        h: 41,
      },
      text: "response ← 200 ms",
      align: "center",
      muted: true,
    },
    {
      id: "fail_ctr",
      kind: "box",
      at: {
        x: 925,
        y: 425,
        w: 300,
        h: 100,
      },
      label: "Contador de falhas",
      sub: "████░░░░ 4/5",
      variant: "outline",
    },
    {
      id: "fail_bar",
      tone: "warn",
      kind: "bars",
      at: {
        x: 938,
        y: 438,
        w: 35,
        h: 75,
      },
      values: [0.8],
    },
    {
      id: "fail_lbl",
      kind: "label",
      at: {
        x: 899,
        y: 519,
        w: 302,
        h: 41,
      },
      text: "threshold: 5 falhas em 10s",
      align: "center",
      muted: true,
    },
    {
      id: "req_blk",
      tone: "hot",
      kind: "connector",
      from: {
        x: 875,
        y: 600,
      },
      to: {
        x: 1000,
        y: 600,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "req_blk_l",
      kind: "label",
      at: {
        x: 897,
        y: 558,
        w: 81,
        h: 41,
      },
      text: "request",
      align: "center",
      muted: true,
    },
    {
      id: "blk_box",
      kind: "box",
      at: {
        x: 1013,
        y: 575,
        w: 200,
        h: 55,
      },
      label: "⛔ OPEN: bloqueado",
      variant: "outline",
    },
    {
      id: "fast_fail",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1013,
        y: 625,
      },
      to: {
        x: 875,
        y: 625,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "fast_lbl",
      kind: "label",
      at: {
        x: 862,
        y: 627,
        w: 163,
        h: 41,
      },
      text: "← 503 imediato",
      align: "center",
      muted: true,
    },
    {
      id: "timer_box",
      kind: "box",
      at: {
        x: 1125,
        y: 550,
        w: 250,
        h: 100,
      },
      label: "⏱️ Timer OPEN",
      sub: "aguardando 30s...",
      variant: "outline",
    },
    {
      id: "probe_req",
      tone: "warn",
      kind: "connector",
      from: {
        x: 875,
        y: 775,
      },
      to: {
        x: 1125,
        y: 775,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "probe_req_l",
      kind: "label",
      at: {
        x: 924,
        y: 733,
        w: 151,
        h: 41,
      },
      text: "probe request",
      align: "center",
      muted: true,
    },
    {
      id: "probe_ok",
      kind: "token",
      at: {
        x: 1138,
        y: 795,
        w: 225,
        h: 45,
      },
      text: "✓ 200 OK → CLOSED",
    },
    {
      id: "probe_fail",
      kind: "token",
      at: {
        x: 1138,
        y: 850,
        w: 225,
        h: 45,
      },
      text: "✗ falhou → OPEN",
    },
    {
      id: "cascade_box",
      kind: "box",
      at: {
        x: 575,
        y: 70,
        w: 975,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "cascade_lbl",
      kind: "label",
      at: {
        x: 847,
        y: 74,
        w: 430,
        h: 41,
      },
      text: "Sem Circuit Breaker: Falha em cascata",
      align: "center",
    },
    {
      id: "casc1",
      kind: "token",
      at: {
        x: 600,
        y: 120,
        w: 213,
        h: 45,
      },
      text: "DB lento",
    },
    {
      id: "casc2",
      kind: "token",
      at: {
        x: 850,
        y: 120,
        w: 213,
        h: 45,
      },
      text: "Auth timeout",
    },
    {
      id: "casc3",
      kind: "token",
      at: {
        x: 1100,
        y: 120,
        w: 213,
        h: 45,
      },
      text: "API esgotada",
    },
    {
      id: "casc4",
      kind: "token",
      at: {
        x: 1350,
        y: 120,
        w: 213,
        h: 45,
      },
      text: "Site fora!",
    },
    {
      id: "a_c12",
      tone: "hot",
      kind: "connector",
      from: {
        x: 815,
        y: 143,
      },
      to: {
        x: 848,
        y: 143,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_c23",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1065,
        y: 143,
      },
      to: {
        x: 1098,
        y: 143,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_c34",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1315,
        y: 143,
      },
      to: {
        x: 1348,
        y: 143,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "cascade_desc",
      kind: "label",
      at: {
        x: 638,
        y: 174,
        w: 849,
        h: 41,
      },
      text: "Uma falha derruba todo o sistema por filas bloqueadas e threads esgotadas",
      align: "center",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O problema: falhas em cascata",
      duration: 9000,
      add: [
        "cascade_box",
        "cascade_lbl",
        "casc1",
        "casc2",
        "casc3",
        "casc4",
        "a_c12",
        "a_c23",
        "a_c34",
        "cascade_desc",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 600,
          target: "a_c12",
          do: "draw",
        },
        {
          at: 700,
          target: "a_c23",
          do: "draw",
        },
        {
          at: 800,
          target: "a_c34",
          do: "draw",
        },
        {
          at: 0,
          target: "casc4",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cascade_box",
        placement: "bottom",
        text: "Em sistemas distribuídos, uma falha num serviço lento faz com que outros serviços fiquem bloqueados esperando resposta. As threads se esgotam, as filas enchem e a falha se propaga em **cascata** — derrubando tudo.",
        why: "O Circuit Breaker foi criado especificamente para cortar essa cascata: ao detectar que um serviço está falhando, ele para de chamar o serviço imediatamente, evitando que o problema se alastre.",
      },
    },
    {
      id: "s2",
      title: "O padrão Circuit Breaker",
      duration: 9000,
      add: ["st_lbl", "st_closed", "st_open", "st_halfopen"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_closed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_closed",
        placement: "right",
        text: "O Circuit Breaker é uma **máquina de estados** com três estados: **CLOSED** (circuito fechado, tráfego normal), **OPEN** (circuito aberto, tráfego bloqueado) e **HALF-OPEN** (testando se o serviço recuperou).",
        why: "O nome vem dos disjuntores elétricos: quando detecta sobrecarga, abre o circuito para proteger o sistema. Quando a tensão normaliza, pode ser testado novamente.",
      },
    },
    {
      id: "s3",
      title: "Estado CLOSED: operação normal",
      duration: 9000,
      add: ["cl_box", "sv_box", "req_ok", "req_ok_l", "resp_ok2", "resp_ok2_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "req_ok",
          do: "draw",
        },
        {
          at: 500,
          target: "resp_ok2",
          do: "draw",
        },
        {
          at: 0,
          target: "st_closed",
          do: "highlight",
        },
        {
          at: 0,
          target: "req_ok",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_closed",
        placement: "right",
        text: "No estado **CLOSED**, todas as requisições passam normalmente para o serviço dependente. O Circuit Breaker monitora cada chamada: tempo de resposta, códigos de erro e timeouts.",
        why: "Em CLOSED, o CB é quase transparente — apenas um interceptador que observa. O overhead é mínimo (uma comparação de contador por chamada).",
      },
    },
    {
      id: "s4",
      title: "Falhas acumulam no contador",
      duration: 9000,
      add: ["fail_ctr", "fail_bar", "fail_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "fail_bar",
          do: "setBars",
          values: [0.4],
        },
        {
          at: 300,
          target: "fail_bar",
          do: "setBars",
          values: [0.6],
        },
        {
          at: 600,
          target: "fail_bar",
          do: "setBars",
          values: [0.8],
        },
        {
          at: 0,
          target: "fail_ctr",
          do: "highlight",
        },
        {
          at: 0,
          target: "st_closed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "fail_ctr",
        placement: "top",
        text: "A cada falha (timeout, 5xx, exception), o **contador de falhas** incrementa. Quando atinge o **threshold** (ex.: 5 falhas em 10 segundos), o CB transita para OPEN.",
        why: "O threshold evita que uma falha isolada abra o circuito. Configurar threshold muito baixo causa falsos positivos; muito alto demora a proteger. Ajuste baseado no SLA do serviço.",
      },
    },
    {
      id: "s5",
      title: "Threshold atingido → OPEN",
      duration: 9000,
      add: ["a_co", "lbl_co"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_co",
          do: "draw",
        },
        {
          at: 0,
          target: "st_open",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_co",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_open",
        placement: "right",
        text: "Com o threshold atingido, o CB transita para **OPEN**. A partir daqui, ele rejeita *todas* as chamadas imediatamente, sem tentar contactar o serviço dependente.",
        why: "Fail fast em OPEN é intencional: melhor retornar um erro instantâneo do que bloquear threads por segundos esperando um serviço que sabemos estar falhando.",
      },
    },
    {
      id: "s6",
      title: "Estado OPEN: fast-fail sem chamar o serviço",
      duration: 9000,
      add: ["req_blk", "req_blk_l", "blk_box", "fast_fail", "fast_lbl", "timer_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "req_blk",
          do: "draw",
        },
        {
          at: 400,
          target: "fast_fail",
          do: "draw",
        },
        {
          at: 0,
          target: "st_open",
          do: "highlight",
        },
        {
          at: 0,
          target: "blk_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "blk_box",
        placement: "top",
        text: "Em **OPEN**, o CB intercepta a chamada e responde com **503 imediato** — sem nem tentar contactar o Serviço B. Um timer conta o tempo de espera (ex.: 30 segundos).",
        why: "O cliente recebe um erro rápido e pode tomar uma ação alternativa: retornar dados do cache, mostrar mensagem de manutenção ou redirecionar para backup.",
      },
    },
    {
      id: "s7",
      title: "Timer expira → HALF-OPEN",
      duration: 9000,
      add: ["a_oh", "lbl_oh"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_oh",
          do: "draw",
        },
        {
          at: 0,
          target: "st_halfopen",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_oh",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_halfopen",
        placement: "right",
        text: "Após o timer de espera expirar, o CB transita para **HALF-OPEN**: ele permite que *uma única* requisição de teste (probe) passe para o serviço dependente.",
        why: "HALF-OPEN é o mecanismo de auto-recuperação: o CB verifica periodicamente se o serviço voltou a funcionar, sem precisar de intervenção humana para reativar.",
      },
    },
    {
      id: "s8",
      title: "Probe: testando se o serviço recuperou",
      duration: 9000,
      add: ["probe_req", "probe_req_l", "probe_ok", "probe_fail"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "probe_req",
          do: "draw",
        },
        {
          at: 0,
          target: "st_halfopen",
          do: "highlight",
        },
        {
          at: 0,
          target: "probe_req",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "probe_req",
        placement: "top",
        text: "O **probe request** vai ao Serviço B. Se retornar sucesso (2xx dentro do timeout), o CB transita para CLOSED — tráfego normal é retomado. Se falhar, volta para OPEN e o timer recomeça.",
        why: "Uma probe é suficiente — não é necessário aquecer com múltiplas chamadas. Isso minimiza a carga no serviço que está se recuperando.",
      },
    },
    {
      id: "s9",
      title: "Sucesso → volta a CLOSED",
      duration: 9000,
      add: ["a_hc", "lbl_hc"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_hc",
          do: "draw",
        },
        {
          at: 0,
          target: "st_closed",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_hc",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_closed",
        placement: "right",
        text: "Probe bem-sucedido → CB transita de HALF-OPEN para **CLOSED**. O tráfego normal é retomado gradualmente. O contador de falhas é zerado.",
        why: "A recuperação é automática: o sistema se auto-cura sem intervenção humana. Isso é fundamental para alta disponibilidade em microservices.",
      },
    },
    {
      id: "s10",
      title: "Falha na probe → volta a OPEN",
      duration: 9000,
      add: ["a_ho", "lbl_ho"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_ho",
          do: "draw",
        },
        {
          at: 0,
          target: "st_open",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_ho",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_open",
        placement: "left",
        text: "Se a probe falhar, o CB volta para **OPEN** e o timer recomeça. O serviço ainda não recuperou — o sistema aguarda mais um ciclo antes de tentar novamente.",
        why: "Back-off exponencial pode ser implementado: primeiro espera 30s, depois 60s, depois 120s. Isso evita sobrecarregar um serviço que está tentando se recuperar.",
      },
    },
    {
      id: "s11",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "right",
        text: "Confirme o que você aprendeu sobre Circuit Breaker 👇",
      },
      quiz: {
        question: "Por que o estado HALF-OPEN envia apenas UMA requisição de probe (e não várias)?",
        options: [
          "Para economizar bandwidth — múltiplas probes consumiriam muitos recursos de rede",
          "Para minimizar a carga em um serviço que está se recuperando; uma probe é suficiente para verificar",
          "Porque o protocolo HTTP não suporta requisições paralelas em HALF-OPEN",
          "Para garantir que o serviço cliente não espere mais de uma resposta simultânea",
        ],
        answer: 1,
        explain:
          "Um serviço em recuperação pode estar frágil — sobrecarregá-lo com múltiplas probes pode derrubá-lo novamente. Uma única probe é suficiente: se passar, o serviço está estável; se falhar, volta a OPEN.",
      },
    },
    {
      id: "s12",
      title: "Resumo: Circuit Breaker",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st_closed",
          do: "pulse",
          times: 2,
        },
        {
          at: 120,
          target: "st_open",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "st_halfopen",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "st_closed",
          do: "highlight",
        },
        {
          at: 0,
          target: "st_open",
          do: "highlight",
        },
        {
          at: 0,
          target: "st_halfopen",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 130,
          y: 400,
        },
        placement: "right",
        text: "**CLOSED**: tráfego normal, monitora falhas. **OPEN**: bloqueia tudo, fast-fail, aguarda timer. **HALF-OPEN**: probe única — sucesso → CLOSED, falha → OPEN. Evita cascata e permite auto-recuperação.",
        why: "Circuit Breaker é essencial em microservices: cada serviço depende de outros, e sem CB, uma falha isolada derruba o sistema inteiro. Com CB, cada serviço falha de forma controlada e se recupera automaticamente.",
      },
    },
  ],
};

export const circuitBreaker = validateExplainer(data);
