import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/consistent-hashing.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "consistent-hashing",
  title: "Consistent Hashing",
  category: "Sistemas Distribuídos",
  tags: ["hashing", "distribuído"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "ring",
      kind: "box",
      at: {
        x: 163,
        y: 188,
        w: 525,
        h: 525,
      },
      variant: "outline",
    },
    {
      id: "n_a",
      tone: "accent",
      kind: "box",
      at: {
        x: 500,
        y: 198,
        w: 113,
        h: 50,
      },
      label: "Node A",
      variant: "outline",
    },
    {
      id: "n_b",
      tone: "good",
      kind: "box",
      at: {
        x: 500,
        y: 652,
        w: 113,
        h: 50,
      },
      label: "Node B",
      variant: "outline",
    },
    {
      id: "n_c",
      tone: "accent2",
      kind: "box",
      at: {
        x: 106,
        y: 425,
        w: 113,
        h: 50,
      },
      label: "Node C",
      variant: "outline",
    },
    {
      id: "k1",
      tone: "warn",
      kind: "box",
      at: {
        x: 563,
        y: 326,
        w: 93,
        h: 35,
      },
      label: "user:42",
      variant: "outline",
    },
    {
      id: "k2",
      tone: "warn",
      kind: "box",
      at: {
        x: 578,
        y: 505,
        w: 93,
        h: 35,
      },
      label: "sess:99",
      variant: "outline",
    },
    {
      id: "k3",
      tone: "hot",
      kind: "box",
      at: {
        x: 306,
        y: 632,
        w: 93,
        h: 35,
      },
      label: "img:7",
      variant: "outline",
    },
    {
      id: "k4",
      tone: "hot",
      kind: "box",
      at: {
        x: 242,
        y: 270,
        w: 93,
        h: 35,
      },
      label: "cart:12",
      variant: "outline",
    },
    {
      id: "ring_lbl",
      kind: "label",
      at: {
        x: 373,
        y: 417,
        w: 105,
        h: 41,
      },
      text: "Hash Ring",
      align: "center",
    },
    {
      id: "ring_sub",
      kind: "label",
      at: {
        x: 332,
        y: 447,
        w: 186,
        h: 41,
      },
      text: "espaço: 0 .. 2³²",
      align: "center",
    },
    {
      id: "ring_arrow_cw",
      kind: "label",
      at: {
        x: 599,
        y: 132,
        w: 128,
        h: 41,
      },
      text: "↻ clockwise",
      align: "center",
    },
    {
      id: "own1",
      tone: "accent",
      kind: "label",
      at: {
        x: 541,
        y: 429,
        w: 93,
        h: 41,
      },
      text: "→ Node B",
      align: "center",
    },
    {
      id: "own2",
      tone: "accent",
      kind: "label",
      at: {
        x: 512,
        y: 523,
        w: 93,
        h: 41,
      },
      text: "→ Node B",
      align: "center",
    },
    {
      id: "own3",
      tone: "accent2",
      kind: "label",
      at: {
        x: 264,
        y: 544,
        w: 93,
        h: 41,
      },
      text: "→ Node C",
      align: "center",
    },
    {
      id: "own4",
      tone: "accent",
      kind: "label",
      at: {
        x: 336,
        y: 272,
        w: 93,
        h: 41,
      },
      text: "→ Node A",
      align: "center",
    },
    {
      id: "naive_bg",
      kind: "box",
      at: {
        x: 900,
        y: 38,
        w: 663,
        h: 188,
      },
      variant: "outline",
    },
    {
      id: "naive_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 1103,
        y: 39,
        w: 256,
        h: 41,
      },
      text: "❌ Naive: hash(key) % N",
      align: "center",
    },
    {
      id: "naive1",
      kind: "label",
      at: {
        x: 674,
        y: 72,
        w: 477,
        h: 41,
      },
      text: 'Com 3 nós: hash("user:42") % 3 = 1 → Nó 1',
      align: "center",
    },
    {
      id: "naive2",
      tone: "warn",
      kind: "label",
      at: {
        x: 686,
        y: 97,
        w: 453,
        h: 41,
      },
      text: "Adicionamos 4º nó → divisor muda para 4",
      align: "center",
    },
    {
      id: "naive3",
      tone: "hot",
      kind: "label",
      at: {
        x: 686,
        y: 122,
        w: 453,
        h: 41,
      },
      text: "Resultado: ~75% das chaves mudam de nó!",
      align: "center",
    },
    {
      id: "naive4",
      tone: "hot",
      kind: "label",
      at: {
        x: 674,
        y: 147,
        w: 477,
        h: 41,
      },
      text: "Ex: 1.000.000 chaves → 750.000 remapeadas",
      align: "center",
    },
    {
      id: "naive5",
      tone: "hot",
      kind: "label",
      at: {
        x: 668,
        y: 172,
        w: 488,
        h: 41,
      },
      text: "Cache thrash, sobrecarga nos nós, downtime",
      align: "center",
    },
    {
      id: "naive6",
      kind: "label",
      at: {
        x: 622,
        y: 197,
        w: 581,
        h: 41,
      },
      text: "→ Inviável para sistemas que escalam dinamicamente",
      align: "center",
    },
    {
      id: "con_bg",
      kind: "box",
      at: {
        x: 900,
        y: 250,
        w: 663,
        h: 225,
      },
      variant: "outline",
    },
    {
      id: "con_title",
      tone: "good",
      kind: "label",
      at: {
        x: 1115,
        y: 252,
        w: 233,
        h: 41,
      },
      text: "✅ Consistent Hashing",
      align: "center",
    },
    {
      id: "c1",
      kind: "label",
      at: {
        x: 645,
        y: 284,
        w: 535,
        h: 41,
      },
      text: "1. Mapear nós no ring: hash(node_id) → posição",
      align: "center",
    },
    {
      id: "c2",
      kind: "label",
      at: {
        x: 657,
        y: 309,
        w: 512,
        h: 41,
      },
      text: "2. Mapear chave: hash(key) → posição no ring",
      align: "center",
    },
    {
      id: "c3",
      kind: "label",
      at: {
        x: 697,
        y: 334,
        w: 430,
        h: 41,
      },
      text: "3. Lookup: avançar ↻ até o próximo nó",
      align: "center",
    },
    {
      id: "c4",
      tone: "good",
      kind: "label",
      at: {
        x: 622,
        y: 359,
        w: 581,
        h: 41,
      },
      text: "→ Adicionar nó: só rouba chaves do vizinho direito",
      align: "center",
    },
    {
      id: "c5",
      tone: "good",
      kind: "label",
      at: {
        x: 610,
        y: 384,
        w: 605,
        h: 41,
      },
      text: "→ Remover nó: chaves migram apenas para o próximo nó",
      align: "center",
    },
    {
      id: "c6",
      tone: "good",
      kind: "label",
      at: {
        x: 610,
        y: 409,
        w: 605,
        h: 41,
      },
      text: "→ ~1/N das chaves são remapeadas (vs ~(N-1)/N naive)",
      align: "center",
    },
    {
      id: "c7",
      tone: "accent",
      kind: "label",
      at: {
        x: 715,
        y: 434,
        w: 395,
        h: 41,
      },
      text: "Lookup com binary search: O(log N)",
      align: "center",
    },
    {
      id: "c8",
      kind: "label",
      at: {
        x: 622,
        y: 452,
        w: 581,
        h: 41,
      },
      text: "Usado em: Cassandra, DynamoDB, Redis Cluster, CDNs",
      align: "center",
    },
    {
      id: "vn_bg",
      kind: "box",
      at: {
        x: 900,
        y: 500,
        w: 663,
        h: 188,
      },
      variant: "outline",
    },
    {
      id: "vn_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1086,
        y: 502,
        w: 291,
        h: 41,
      },
      text: "⚖️ Virtual Nodes (vnodes)",
      align: "center",
    },
    {
      id: "vn1",
      tone: "warn",
      kind: "label",
      at: {
        x: 663,
        y: 534,
        w: 500,
        h: 41,
      },
      text: "Problema com 3 nós: distribuição irregular!",
      align: "center",
    },
    {
      id: "vn2",
      tone: "good",
      kind: "label",
      at: {
        x: 645,
        y: 559,
        w: 535,
        h: 41,
      },
      text: "Solução: cada nó físico tem K posições no ring",
      align: "center",
    },
    {
      id: "vn3",
      kind: "label",
      at: {
        x: 674,
        y: 584,
        w: 477,
        h: 41,
      },
      text: "Ex: Node A → A_1, A_2, ..., A_150 no ring",
      align: "center",
    },
    {
      id: "vn4",
      tone: "good",
      kind: "label",
      at: {
        x: 680,
        y: 609,
        w: 465,
        h: 41,
      },
      text: "→ distribuição estatisticamente uniforme",
      align: "center",
    },
    {
      id: "vn5",
      kind: "label",
      at: {
        x: 703,
        y: 634,
        w: 419,
        h: 41,
      },
      text: "Cassandra usa 256 vnodes por default",
      align: "center",
    },
    {
      id: "vn6",
      kind: "label",
      at: {
        x: 558,
        y: 659,
        w: 709,
        h: 41,
      },
      text: "K ajustável por nó → nós com mais RAM/CPU recebem mais vnodes",
      align: "center",
    },
    {
      id: "rep_bg",
      kind: "box",
      at: {
        x: 900,
        y: 713,
        w: 663,
        h: 138,
      },
      variant: "outline",
    },
    {
      id: "rep_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 1074,
        y: 714,
        w: 314,
        h: 41,
      },
      text: "🔁 Replicação com Hash Ring",
      align: "center",
    },
    {
      id: "r1",
      kind: "label",
      at: {
        x: 657,
        y: 747,
        w: 512,
        h: 41,
      },
      text: "Para replicação fator 3: avançar ↻ por 3 nós",
      align: "center",
    },
    {
      id: "r2",
      kind: "label",
      at: {
        x: 587,
        y: 772,
        w: 651,
        h: 41,
      },
      text: "key → Nó A (primary), Nó B (replica 1), Nó C (replica 2)",
      align: "center",
    },
    {
      id: "r3",
      tone: "good",
      kind: "label",
      at: {
        x: 657,
        y: 797,
        w: 512,
        h: 41,
      },
      text: "Nó falha → replicas continuam servindo a key",
      align: "center",
    },
    {
      id: "r4",
      kind: "label",
      at: {
        x: 703,
        y: 822,
        w: 419,
        h: 41,
      },
      text: "Quorum read/write: evita split-brain",
      align: "center",
    },
    {
      id: "nd_bg",
      kind: "box",
      at: {
        x: 38,
        y: 738,
        w: 250,
        h: 113,
      },
      variant: "outline",
    },
    {
      id: "nd_title",
      tone: "good",
      kind: "label",
      at: {
        x: 40,
        y: 739,
        w: 244,
        h: 41,
      },
      text: "➕ Novo Nó (D) no ring",
      align: "center",
    },
    {
      id: "nd1",
      kind: "label",
      at: {
        x: -78,
        y: 767,
        w: 256,
        h: 41,
      },
      text: "D inserido entre C e A",
      align: "center",
    },
    {
      id: "nd2",
      kind: "label",
      at: {
        x: -107,
        y: 792,
        w: 314,
        h: 41,
      },
      text: "Apenas chaves de C→D migram",
      align: "center",
    },
    {
      id: "nd3",
      tone: "good",
      kind: "label",
      at: {
        x: -78,
        y: 817,
        w: 256,
        h: 41,
      },
      text: "A, B, C: sem alteração",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: hash(key) % N",
      duration: 6500,
      add: [
        "naive_bg",
        "naive_title",
        "naive1",
        "naive2",
        "naive3",
        "naive4",
        "naive5",
        "naive6",
        "ring",
        "ring_lbl",
        "ring_sub",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "naive_bg",
        placement: "left",
        text: "Com `hash(key) % N`, adicionar ou remover um servidor muda o denominador N — quase todas as chaves precisam ser remapeadas. Para um cache distribuído, isso é catastrófico.",
      },
    },
    {
      id: "s2",
      title: "Exemplo concreto: 3 → 4 nós, 75% remapeado",
      duration: 6500,
      add: ["naive_bg", "naive_title", "naive1", "naive2", "naive3", "naive4", "naive5", "naive6"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "naive_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "naive_bg",
        placement: "left",
        text: "Com 3 nós: chave `user:42` → hash mod 3 = 1 → Nó 1. Adicionamos Nó 4: agora hash mod 4 = 2 → Nó 2. A chave mudou de nó! 75% das chaves mudam de destino — cache miss em massa.",
      },
    },
    {
      id: "s3",
      title: "Hash Ring: espaço circular 0..2³²",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "con_bg",
        "con_title",
        "c1",
        "c2",
        "c3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ring",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ring",
        placement: "right",
        text: "O espaço de hash (0 a 2³²) é disposto em um anel circular. Nós são posicionados no anel com `hash(node_id)`. As chaves também são mapeadas no anel com `hash(key)`.",
      },
    },
    {
      id: "s4",
      title: "Lookup: avançar clockwise até o próximo nó",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "k1",
        "k2",
        "k3",
        "k4",
        "own1",
        "own2",
        "own3",
        "own4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ring",
          do: "highlight",
        },
        {
          at: 0,
          target: "k1",
          do: "highlight",
        },
        {
          at: 0,
          target: "k2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ring",
        placement: "right",
        text: "Para encontrar o nó dono de uma chave: avança-se no sentido horário até o primeiro nó encontrado. `user:42` (60°) → avança até Node B (150°). Lookup em O(log N) com busca binária.",
        why: "Cada nó é responsável pelo arco de ring entre o nó anterior e ele mesmo.",
      },
    },
    {
      id: "s5",
      title: "Adicionar nó: só rouba do vizinho",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "k1",
        "k2",
        "k3",
        "k4",
        "nd_bg",
        "nd_title",
        "nd1",
        "nd2",
        "nd3",
        "con_bg",
        "con_title",
        "c4",
        "c5",
        "c6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_a",
          do: "highlight",
        },
        {
          at: 0,
          target: "nd_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "nd_bg",
        placement: "top",
        text: "Ao inserir Node D entre C e A: apenas as chaves que estavam no arco C→D migram para D. Todos os outros arcos (A→B, B→C) ficam inalterados. Isso é ~1/N chaves remapeadas.",
      },
    },
    {
      id: "s6",
      title: "Remover nó: migração localizada",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "k1",
        "k2",
        "k3",
        "k4",
        "con_bg",
        "con_title",
        "c4",
        "c5",
        "c6",
        "c7",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_b",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ring",
        placement: "right",
        text: "Se Node B é removido (falha ou scale-down): suas chaves (`user:42`, `sess:99`) migram apenas para o próximo nó clockwise (Node C). Nodes A e C não são afetados entre si.",
      },
    },
    {
      id: "s7",
      title: "Problema sem vnodes: distribuição irregular",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "vn_bg",
        "vn_title",
        "vn1",
        "vn2",
        "vn3",
        "vn4",
        "vn5",
        "vn6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "vn_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "vn_bg",
        placement: "left",
        text: "Com apenas 3 nós no ring, o espaço pode ficar desbalanceado — um nó pode ter o dobro de chaves dos outros. Virtual nodes resolvem isso.",
      },
    },
    {
      id: "s8",
      title: "Virtual Nodes: K posições por nó físico",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "n_a",
        "n_b",
        "n_c",
        "vn_bg",
        "vn_title",
        "vn1",
        "vn2",
        "vn3",
        "vn4",
        "vn5",
        "vn6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_a",
          do: "highlight",
        },
        {
          at: 0,
          target: "n_b",
          do: "highlight",
        },
        {
          at: 0,
          target: "n_c",
          do: "highlight",
        },
        {
          at: 0,
          target: "vn_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "vn_bg",
        placement: "left",
        text: 'Cada nó físico é mapeado K vezes no ring: `hash("A_1")`, `hash("A_2")`, ..., `hash("A_150")`. Com muitas posições, a distribuição se torna estatisticamente uniforme. Cassandra usa 256 vnodes por padrão.',
        why: "Nós mais poderosos podem receber mais vnodes — balanceamento heterogêneo.",
      },
    },
    {
      id: "s9",
      title: "Replicação com o Hash Ring",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "k1",
        "k2",
        "k3",
        "k4",
        "rep_bg",
        "rep_title",
        "r1",
        "r2",
        "r3",
        "r4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "rep_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "rep_bg",
        placement: "left",
        text: "Para replicação com fator 3: a chave é copiada para os **próximos 3 nós** no ring. Se o nó primário falhar, as réplicas assumem sem reconfiguração. Quorum R+W > N garante consistência.",
      },
    },
    {
      id: "s10",
      title: "Onde é usado na prática",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "con_bg",
        "con_title",
        "c1",
        "c2",
        "c3",
        "c4",
        "c5",
        "c6",
        "c7",
        "c8",
        "vn_bg",
        "vn_title",
        "vn4",
        "vn5",
        "rep_bg",
        "rep_title",
        "r1",
        "r3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "con_bg",
        placement: "left",
        text: "**Cassandra & DynamoDB**: particionamento + replicação. **Redis Cluster**: 16384 hash slots distribuídos. **CDNs (Akamai, Fastly)**: roteamento de requisições para edge servers. **Memcached**: balanceamento de cache.",
      },
    },
    {
      id: "s11",
      title: "Quiz",
      duration: 6500,
      add: ["ring", "ring_lbl", "ring_sub", "n_a", "n_b", "n_c", "k1", "k2"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question:
          "Ao adicionar um novo nó no hash ring, quantas chaves aproximadamente precisam ser remapeadas (com N nós existentes)?",
        options: [
          "Todas as chaves — equivalente ao hash(key) % N",
          "Aproximadamente metade das chaves do vizinho mais próximo",
          "Apenas ~1/N das chaves — somente do arco do vizinho direto",
          "Nenhuma — consistent hashing não remapeia chaves ao adicionar nós",
        ],
        answer: 2,
        explain:
          "No consistent hashing, ao adicionar o nó D entre C e A, apenas as chaves do arco que pertencia a A (especificamente o sub-arco C→D) precisam migrar para D. Isso representa ~1/N das chaves totais. Com 100 nós, adicionar 1 nó remapeia ~1% das chaves — muito melhor que o ~99% do método naive.",
      },
    },
    {
      id: "s12",
      title: "Resumo: Consistent Hashing",
      duration: 6500,
      add: [
        "ring",
        "ring_lbl",
        "ring_sub",
        "ring_arrow_cw",
        "n_a",
        "n_b",
        "n_c",
        "k1",
        "k2",
        "k3",
        "k4",
        "own1",
        "own2",
        "own3",
        "own4",
        "con_bg",
        "con_title",
        "c1",
        "c2",
        "c3",
        "c4",
        "c5",
        "c6",
        "c7",
        "c8",
        "vn_bg",
        "vn_title",
        "vn2",
        "vn4",
        "vn5",
        "rep_bg",
        "rep_title",
        "r1",
        "r2",
        "r3",
        "nd_bg",
        "nd_title",
        "nd2",
        "nd3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "ring",
        placement: "right",
        text: "Ring 0..2³². Nós + chaves mapeados por hash. Lookup: avançar clockwise → O(log N). Add/remove nó: ~1/N remapeado. Vnodes: distribuição uniforme. Replicação: K próximos nós. Base de Cassandra, DynamoDB, Redis Cluster.",
      },
    },
  ],
};

export const consistentHashing = validateExplainer(data);
