import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/context-eng.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "context-eng",
  title: "Engenharia de Contexto",
  subtitle: "Gerenciar o que o LLM vê: tokens, hierarquia e estratégias",
  category: "IA & Agentes",
  tags: ["contexto", "llm", "prompt"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "cw_border",
      kind: "box",
      at: {
        x: 70,
        y: 170,
        w: 1460,
        h: 285,
      },
      variant: "outline",
    },
    {
      id: "cw_lbl",
      kind: "label",
      at: {
        x: 544,
        y: 124,
        w: 512,
        h: 41,
      },
      text: "Janela de Contexto do LLM (ex.: 200k tokens)",
      align: "center",
    },
    {
      id: "cw_tok",
      kind: "label",
      at: {
        x: 585,
        y: 459,
        w: 430,
        h: 41,
      },
      text: "← cada pixel representa ≈ 10 tokens →",
      align: "center",
      muted: true,
    },
    {
      id: "s_sys",
      kind: "box",
      at: {
        x: 75,
        y: 175,
        w: 275,
        h: 275,
      },
      label: "System Prompt",
      variant: "outline",
    },
    {
      id: "s_hist",
      kind: "box",
      at: {
        x: 350,
        y: 175,
        w: 438,
        h: 275,
      },
      label: "Histórico",
      variant: "outline",
    },
    {
      id: "s_tool",
      kind: "box",
      at: {
        x: 788,
        y: 175,
        w: 250,
        h: 275,
      },
      label: "Tool Results",
      variant: "outline",
    },
    {
      id: "s_rag",
      kind: "box",
      at: {
        x: 1038,
        y: 175,
        w: 250,
        h: 275,
      },
      label: "Docs (RAG)",
      variant: "outline",
    },
    {
      id: "s_usr",
      kind: "box",
      at: {
        x: 1288,
        y: 175,
        w: 225,
        h: 275,
      },
      label: "User",
      variant: "outline",
    },
    {
      id: "s_free",
      kind: "box",
      at: {
        x: 1513,
        y: 175,
        w: 88,
        h: 275,
      },
      label: "livre",
      variant: "outline",
    },
    {
      id: "lbl_sys",
      kind: "label",
      at: {
        x: 175,
        y: 282,
        w: 75,
        h: 41,
      },
      text: "System",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_hist",
      kind: "label",
      at: {
        x: 516,
        y: 282,
        w: 105,
        h: 41,
      },
      text: "Histórico",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_tool",
      kind: "label",
      at: {
        x: 875,
        y: 282,
        w: 75,
        h: 41,
      },
      text: "Tools",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_rag",
      kind: "label",
      at: {
        x: 1125,
        y: 282,
        w: 75,
        h: 41,
      },
      text: "RAG",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_usr",
      kind: "label",
      at: {
        x: 1363,
        y: 282,
        w: 75,
        h: 41,
      },
      text: "User",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_free",
      kind: "label",
      at: {
        x: 1519,
        y: 282,
        w: 75,
        h: 41,
      },
      text: "livre",
      align: "center",
      muted: true,
    },
    {
      id: "tok_sys",
      kind: "label",
      at: {
        x: 175,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~4k",
      align: "center",
      muted: true,
    },
    {
      id: "tok_hist",
      kind: "label",
      at: {
        x: 531,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~40k",
      align: "center",
      muted: true,
    },
    {
      id: "tok_tool",
      kind: "label",
      at: {
        x: 875,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~8k",
      align: "center",
      muted: true,
    },
    {
      id: "tok_rag",
      kind: "label",
      at: {
        x: 1125,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~10k",
      align: "center",
      muted: true,
    },
    {
      id: "tok_usr",
      kind: "label",
      at: {
        x: 1363,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~1.5k",
      align: "center",
      muted: true,
    },
    {
      id: "tok_free",
      kind: "label",
      at: {
        x: 1519,
        y: 492,
        w: 75,
        h: 41,
      },
      text: "~6k",
      align: "center",
      muted: true,
    },
    {
      id: "hier_box",
      kind: "box",
      at: {
        x: 75,
        y: 538,
        w: 425,
        h: 225,
      },
      variant: "outline",
    },
    {
      id: "hier_lbl",
      kind: "label",
      at: {
        x: 154,
        y: 544,
        w: 267,
        h: 41,
      },
      text: "Hierarquia de mensagens",
      align: "center",
    },
    {
      id: "hier_sys2",
      kind: "token",
      at: {
        x: 100,
        y: 585,
        w: 375,
        h: 48,
      },
      text: "system (maior autoridade)",
    },
    {
      id: "hier_ast",
      kind: "token",
      at: {
        x: 100,
        y: 645,
        w: 375,
        h: 48,
      },
      text: "assistant",
    },
    {
      id: "hier_usr2",
      kind: "token",
      at: {
        x: 100,
        y: 705,
        w: 375,
        h: 48,
      },
      text: "user",
    },
    {
      id: "a_hier1",
      kind: "connector",
      from: {
        x: 288,
        y: 635,
      },
      to: {
        x: 288,
        y: 643,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_hier2",
      kind: "connector",
      from: {
        x: 288,
        y: 695,
      },
      to: {
        x: 288,
        y: 703,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "strat_lbl",
      kind: "label",
      at: {
        x: 597,
        y: 519,
        w: 407,
        h: 41,
      },
      text: "Estratégias quando o contexto enche",
      align: "center",
    },
    {
      id: "st1",
      kind: "token",
      at: {
        x: 550,
        y: 565,
        w: 475,
        h: 60,
      },
      text: "Compressão: resumir histórico antigo",
    },
    {
      id: "st2",
      kind: "token",
      at: {
        x: 550,
        y: 640,
        w: 475,
        h: 60,
      },
      text: "Sliding window: manter só as N últimas trocas",
    },
    {
      id: "st3",
      kind: "token",
      at: {
        x: 550,
        y: 715,
        w: 475,
        h: 60,
      },
      text: "Memória externa: salvar e recuperar por RAG",
    },
    {
      id: "st4",
      kind: "token",
      at: {
        x: 550,
        y: 790,
        w: 475,
        h: 60,
      },
      text: "Arquivamento: descartar tool results antigos",
    },
    {
      id: "cache_box",
      kind: "box",
      at: {
        x: 1075,
        y: 540,
        w: 475,
        h: 300,
      },
      variant: "outline",
    },
    {
      id: "cache_lbl",
      kind: "label",
      at: {
        x: 1121,
        y: 544,
        w: 384,
        h: 41,
      },
      text: "Prompt Cache (caching de prefixo)",
      align: "center",
    },
    {
      id: "cache_1",
      kind: "token",
      at: {
        x: 1100,
        y: 585,
        w: 425,
        h: 55,
      },
      text: "System Prompt → cacheado ✓",
    },
    {
      id: "cache_2",
      kind: "token",
      at: {
        x: 1100,
        y: 653,
        w: 425,
        h: 55,
      },
      text: "Docs/RAG longos → cacheados ✓",
    },
    {
      id: "cache_3",
      kind: "token",
      at: {
        x: 1100,
        y: 720,
        w: 425,
        h: 55,
      },
      text: "User/Assistant → não cacheados",
    },
    {
      id: "cache_cost",
      kind: "label",
      at: {
        x: 1051,
        y: 772,
        w: 523,
        h: 41,
      },
      text: "Cache = 90% menos custo em prefixos repetidos",
      align: "center",
      muted: true,
    },
    {
      id: "limit_box",
      kind: "token",
      at: {
        x: 70,
        y: 288,
        w: 1460,
        h: 50,
      },
      text: "⚠️ Limite atingido — contexto precisará ser truncado ou comprimido",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que é a janela de contexto",
      duration: 9000,
      add: ["cw_border", "cw_lbl", "cw_tok"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cw_border",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cw_lbl",
        placement: "bottom",
        text: "Todo LLM tem uma **janela de contexto**: o máximo de tokens que ele pode processar de uma vez. Tokens são fragmentos de texto (palavras, sílabas, pontuação). Modelos modernos têm de 8k a 1M tokens.",
        why: "O que cabe na janela determina o que o LLM 'sabe' naquele momento. Tudo fora dela é invisível — por isso gerenciar o contexto é tão crítico.",
      },
    },
    {
      id: "s2",
      title: "System Prompt: a base fixa",
      duration: 9000,
      add: ["s_sys", "lbl_sys", "tok_sys"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_sys",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_sys",
        placement: "bottom",
        text: "O **System Prompt** é a primeira e mais importante seção: define a identidade, restrições e capacidades do agente. Ele está presente em todas as requisições e tem a maior autoridade.",
        why: "Coloque no system: persona, regras de negócio, formato de resposta e capacidades disponíveis. Instruções no system têm peso maior que no user para a maioria dos modelos.",
      },
    },
    {
      id: "s3",
      title: "Histórico de conversa cresce",
      duration: 9000,
      add: ["s_hist", "lbl_hist", "tok_hist"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_hist",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_hist",
        placement: "bottom",
        text: "O **histórico** de mensagens (alternando user/assistant) ocupa a maior parte da janela em conversas longas. Cada resposta do modelo adiciona tokens que ficam para sempre — o contexto só cresce.",
        why: "É o maior consumidor de tokens em aplicações de chat. Gerenciar o histórico (comprimir, truncar, resumir) é fundamental para conversas longas serem viáveis.",
      },
    },
    {
      id: "s4",
      title: "Tool Results: resultados de ferramentas",
      duration: 9000,
      add: ["s_tool", "lbl_tool", "tok_tool"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_tool",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_tool",
        placement: "bottom",
        text: "Quando o LLM usa uma ferramenta (MCP, function calling), o **resultado** é injetado no contexto como uma mensagem `tool_result`. Outputs de ferramentas podem ser enormes: logs, JSONs, conteúdo de arquivos.",
        why: "Comprima ou filtre resultados de tools antes de injetá-los. Passar um JSON de 50k tokens quando só 500 são relevantes desperdiça espaço e aumenta custo.",
      },
    },
    {
      id: "s5",
      title: "Documentos RAG no contexto",
      duration: 9000,
      add: ["s_rag", "lbl_rag", "tok_rag"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_rag",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_rag",
        placement: "bottom",
        text: "Chunks recuperados pelo RAG são inseridos no contexto como referência. Mesmo sendo úteis, **ocupam espaço valioso** e competem com o histórico e as respostas do modelo.",
        why: "Seja seletivo: recupere apenas os K chunks mais relevantes e considere comprimi-los. Um bom retriever recupera menos e melhor; um mau retriever inunda o contexto com ruído.",
      },
    },
    {
      id: "s6",
      title: "A mensagem do usuário: a menor parte",
      duration: 9000,
      add: ["s_usr", "lbl_usr", "tok_usr", "s_free", "lbl_free", "tok_free"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_usr",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_free",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_usr",
        placement: "bottom",
        text: "A pergunta do usuário geralmente tem **poucos tokens**, mas ocupa a posição mais recente e por isso mais influente para o modelo. O espaço 'livre' é o que sobra para a resposta do LLM.",
        why: "Se o contexto encher antes da resposta começar, o modelo pode ser forçado a truncar sua própria resposta ou o sistema pode jogar fora contexto antigo de forma abrupta.",
      },
    },
    {
      id: "s7",
      title: "⚠️ Quando o limite é atingido",
      duration: 9000,
      add: ["limit_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "limit_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "limit_box",
        placement: "top",
        text: "Ao atingir o limite da janela, o sistema precisa **descartar, comprimir ou resumir** parte do contexto. Se não gerenciado, o modelo começa a 'esquecer' partes cruciais da conversa.",
        why: "Truncar pela metade do histórico (estratégia ingênua) pode fazer o agente perder instruções críticas ou o início de uma tarefa. A estratégia de compressão importa muito.",
      },
    },
    {
      id: "s8",
      title: "Hierarquia de mensagens",
      duration: 9000,
      add: ["hier_box", "hier_lbl", "hier_sys2", "a_hier1", "hier_ast", "a_hier2", "hier_usr2"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hier_sys2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hier_sys2",
        placement: "right",
        text: "As mensagens têm uma **hierarquia de autoridade**: `system` define regras invioláveis; `assistant` são as próprias respostas do modelo; `user` são as instruções do usuário final.",
        why: "Um system prompt bem escrito impede que o usuário subverta o comportamento do agente. Guardrails e instruções de segurança devem sempre estar no system, não no user.",
      },
    },
    {
      id: "s9",
      title: "Estratégias de compressão",
      duration: 9000,
      add: ["strat_lbl", "st1", "st2", "st3", "st4"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "st1",
          do: "highlight",
        },
        {
          at: 0,
          target: "st2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "strat_lbl",
        placement: "bottom",
        text: "Quando o contexto enche, há várias estratégias: **Compressão** (resumir histórico com outro LLM), **Sliding window** (manter só as N últimas trocas), **Memória externa** (RAG do histórico) ou **Arquivamento** (descartar tool results já processados).",
        why: "Nenhuma estratégia é universalmente ótima. Sliding window é simples mas perde contexto inicial. Compressão preserva mais mas adiciona latência e custo.",
      },
    },
    {
      id: "s10",
      title: "Prompt Cache: economizar com prefixos",
      duration: 9000,
      add: ["cache_box", "cache_lbl", "cache_1", "cache_2", "cache_3", "cache_cost"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cache_1",
          do: "highlight",
        },
        {
          at: 0,
          target: "cache_2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cache_box",
        placement: "left",
        text: "**Prompt Caching** armazena prefixos do contexto (system prompt, docs longos) e os reutiliza sem reprocessar. Uma requisição com cache pode custar **90% menos** para a parte cacheada.",
        why: "Use caching para system prompts estáticos e documentos grandes que se repetem entre requisições. O cache tem TTL (ex.: 5 min na Anthropic) — refaça a requisição antes de expirar.",
      },
    },
    {
      id: "s11",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 400,
        },
        placement: "bottom",
        text: "Teste seus conhecimentos de Context Engineering 👇",
      },
      quiz: {
        question: "Por que o System Prompt tem mais autoridade que o User na janela de contexto?",
        options: [
          "Porque vem primeiro na janela e o modelo dá mais peso ao início",
          "É uma convenção de papel: system define as regras do jogo que user não pode sobrescrever",
          "O modelo ignora automaticamente instruções do user que contradizem o system",
          "Ambas as opções A e B são igualmente verdadeiras",
        ],
        answer: 3,
        explain:
          "System tem maior autoridade por dois motivos complementares: a posição (início da janela tem peso maior para atenção) e o papel semântico (a arquitetura treina o modelo a tratar system como regras prioritárias).",
      },
    },
    {
      id: "s12",
      title: "Resumo: Context Engineering",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_sys",
          do: "pulse",
          times: 2,
        },
        {
          at: 80,
          target: "s_hist",
          do: "pulse",
          times: 2,
        },
        {
          at: 160,
          target: "s_tool",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "s_rag",
          do: "pulse",
          times: 2,
        },
        {
          at: 320,
          target: "s_usr",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "s_free",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "s_sys",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_hist",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_tool",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_rag",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_usr",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "**Engenharia de Contexto**: gerenciar o que cabe e onde na janela. System define regras, histórico cresce e precisa ser comprimido, tool results devem ser filtrados, RAG deve ser seletivo, e prompt cache economiza custo em prefixos repetidos.",
        why: "Um sistema de IA bom é 50% arquitetura de modelo e 50% engenharia de contexto. Saber o que colocar, onde e quanto é o que separa demos de produção.",
      },
    },
  ],
};

export const contextEng = validateExplainer(data);
