import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/crypto.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "crypto",
  title: "Criptografia — Simétrica, Assimétrica e Hashes",
  category: "Segurança & Autenticação",
  tags: ["criptografia"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "sym_bg",
      kind: "box",
      at: {
        x: 25,
        y: 25,
        w: 725,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "sym_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 242,
        y: 27,
        w: 291,
        h: 41,
      },
      text: "🔑 Criptografia Simétrica",
      align: "center",
    },
    {
      id: "sym_def",
      kind: "label",
      at: {
        x: -236,
        y: 54,
        w: 546,
        h: 41,
      },
      text: "1 chave secreta compartilhada → cifra E decifra",
      align: "center",
    },
    {
      id: "sym_pro",
      tone: "good",
      kind: "label",
      at: {
        x: -166,
        y: 79,
        w: 407,
        h: 41,
      },
      text: "✓ Muito rápida (AES-NI em hardware)",
      align: "center",
    },
    {
      id: "sym_con",
      tone: "hot",
      kind: "label",
      at: {
        x: -218,
        y: 102,
        w: 512,
        h: 41,
      },
      text: "✗ Problema: como distribuir a chave secreta?",
      align: "center",
    },
    {
      id: "aes_bg",
      kind: "box",
      at: {
        x: 38,
        y: 145,
        w: 700,
        h: 125,
      },
      variant: "outline",
    },
    {
      id: "aes_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 190,
        y: 147,
        w: 395,
        h: 41,
      },
      text: "AES — Advanced Encryption Standard",
      align: "center",
    },
    {
      id: "aes1",
      kind: "label",
      at: {
        x: -299,
        y: 169,
        w: 698,
        h: 41,
      },
      text: "Block cipher: blocos de 128 bits, chaves de 128/192/256 bits",
      align: "center",
    },
    {
      id: "aes2",
      tone: "hot",
      kind: "label",
      at: {
        x: -339,
        y: 192,
        w: 779,
        h: 41,
      },
      text: "ECB: cada bloco cifrado independente → padrões visíveis (inseguro!)",
      align: "center",
    },
    {
      id: "aes3",
      tone: "warn",
      kind: "label",
      at: {
        x: -305,
        y: 214,
        w: 709,
        h: 41,
      },
      text: "CBC: XOR com bloco anterior → esconde padrões (IV necessário)",
      align: "center",
    },
    {
      id: "aes4",
      tone: "good",
      kind: "label",
      at: {
        x: -322,
        y: 237,
        w: 744,
        h: 41,
      },
      text: "GCM: stream + GHASH → confidencialidade + autenticidade (AEAD) ✓",
      align: "center",
    },
    {
      id: "cha_bg",
      kind: "box",
      at: {
        x: 38,
        y: 285,
        w: 700,
        h: 88,
      },
      variant: "outline",
    },
    {
      id: "cha_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 289,
        y: 287,
        w: 198,
        h: 41,
      },
      text: "ChaCha20-Poly1305",
      align: "center",
    },
    {
      id: "cha1",
      kind: "label",
      at: {
        x: -241,
        y: 309,
        w: 581,
        h: 41,
      },
      text: "Stream cipher: keystream XOR plaintext (sem bloco)",
      align: "center",
    },
    {
      id: "cha2",
      kind: "label",
      at: {
        x: -223,
        y: 332,
        w: 546,
        h: 41,
      },
      text: "Sem hardware AES-NI → mais rápido em mobile/IoT",
      align: "center",
    },
    {
      id: "cha3",
      kind: "label",
      at: {
        x: -299,
        y: 352,
        w: 698,
        h: 41,
      },
      text: "Poly1305 MAC integrado (AEAD) · usado no TLS 1.3 e WireGuard",
      align: "center",
    },
    {
      id: "sym_key_prob",
      tone: "hot",
      kind: "label",
      at: {
        x: -317,
        y: 374,
        w: 709,
        h: 41,
      },
      text: "⚠️ Key Distribution Problem: Eve intercepta a troca de chave?",
      align: "center",
    },
    {
      id: "sym_sol",
      tone: "good",
      kind: "label",
      at: {
        x: -311,
        y: 399,
        w: 698,
        h: 41,
      },
      text: "→ Solução: usar criptografia assimétrica para trocar a chave",
      align: "center",
    },
    {
      id: "sym_ex",
      kind: "label",
      at: {
        x: -317,
        y: 422,
        w: 709,
        h: 41,
      },
      text: "Usada em: AES-GCM (TLS), ChaCha20 (WireGuard), AES-CBC (disk)",
      align: "center",
    },
    {
      id: "asym_bg",
      kind: "box",
      at: {
        x: 813,
        y: 25,
        w: 725,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "asym_title",
      tone: "good",
      kind: "label",
      at: {
        x: 1018,
        y: 27,
        w: 314,
        h: 41,
      },
      text: "🔐 Criptografia Assimétrica",
      align: "center",
    },
    {
      id: "asym_def",
      kind: "label",
      at: {
        x: 534,
        y: 54,
        w: 581,
        h: 41,
      },
      text: "Par de chaves: pública (cifra) + privada (decifra)",
      align: "center",
    },
    {
      id: "asym_pro",
      tone: "good",
      kind: "label",
      at: {
        x: 587,
        y: 79,
        w: 477,
        h: 41,
      },
      text: "✓ Troca de chaves sem canal seguro prévio",
      align: "center",
    },
    {
      id: "asym_con",
      tone: "hot",
      kind: "label",
      at: {
        x: 616,
        y: 102,
        w: 419,
        h: 41,
      },
      text: "✗ 100-1000× mais lenta que simétrica",
      align: "center",
    },
    {
      id: "rsa_bg",
      kind: "box",
      at: {
        x: 825,
        y: 145,
        w: 700,
        h: 125,
      },
      variant: "outline",
    },
    {
      id: "rsa_title",
      tone: "good",
      kind: "label",
      at: {
        x: 1018,
        y: 147,
        w: 314,
        h: 41,
      },
      text: "RSA — Rivest-Shamir-Adleman",
      align: "center",
    },
    {
      id: "rsa1",
      kind: "label",
      at: {
        x: 512,
        y: 169,
        w: 651,
        h: 41,
      },
      text: "Segurança baseada em fatoração de números primos grandes",
      align: "center",
    },
    {
      id: "rsa2",
      kind: "label",
      at: {
        x: 559,
        y: 192,
        w: 558,
        h: 41,
      },
      text: "Gerar: escolher p,q primos → n=p×q, calcular e,d",
      align: "center",
    },
    {
      id: "rsa3",
      kind: "label",
      at: {
        x: 541,
        y: 214,
        w: 593,
        h: 41,
      },
      text: "Cifragem: c = m^e mod n   Decifragem: m = c^d mod n",
      align: "center",
    },
    {
      id: "rsa4",
      kind: "label",
      at: {
        x: 529,
        y: 237,
        w: 616,
        h: 41,
      },
      text: "Tamanhos: 2048 bits (mínimo), 4096 bits (recomendado)",
      align: "center",
    },
    {
      id: "ecc_bg",
      kind: "box",
      at: {
        x: 825,
        y: 285,
        w: 700,
        h: 100,
      },
      variant: "outline",
    },
    {
      id: "ecc_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 983,
        y: 287,
        w: 384,
        h: 41,
      },
      text: "ECC — Elliptic Curve Cryptography",
      align: "center",
    },
    {
      id: "ecc1",
      kind: "label",
      at: {
        x: 483,
        y: 309,
        w: 709,
        h: 41,
      },
      text: "Segurança baseada no problema do logaritmo discreto em curvas",
      align: "center",
    },
    {
      id: "ecc2",
      tone: "good",
      kind: "label",
      at: {
        x: 442,
        y: 332,
        w: 791,
        h: 41,
      },
      text: "Chave ECC 256 bits ≈ segurança de RSA 3072 bits (chaves 10× menores)",
      align: "center",
    },
    {
      id: "ecc3",
      kind: "label",
      at: {
        x: 448,
        y: 354,
        w: 779,
        h: 41,
      },
      text: "ECDH: troca de chave · ECDSA: assinatura digital · Ed25519: assinar",
      align: "center",
    },
    {
      id: "asym_use",
      kind: "label",
      at: {
        x: 482,
        y: 374,
        w: 686,
        h: 41,
      },
      text: "Curvas: secp256r1 (NIST P-256), Curve25519 (X25519/Ed25519)",
      align: "center",
    },
    {
      id: "asym_ex",
      kind: "label",
      at: {
        x: 441,
        y: 399,
        w: 767,
        h: 41,
      },
      text: "Usada em: TLS (ECDHE), SSH, JWT (RS256/ES256), Bitcoin (secp256k1)",
      align: "center",
    },
    {
      id: "asym_note",
      tone: "warn",
      kind: "label",
      at: {
        x: 436,
        y: 422,
        w: 779,
        h: 41,
      },
      text: "⚠️ Post-quantum: RSA/ECC vulneráveis ao algoritmo de Shor (quantum)",
      align: "center",
    },
    {
      id: "hyb_bg",
      kind: "box",
      at: {
        x: 25,
        y: 475,
        w: 725,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "hyb_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 271,
        y: 477,
        w: 233,
        h: 41,
      },
      text: "🔀 Hybrid Encryption",
      align: "center",
    },
    {
      id: "hyb1",
      kind: "label",
      at: {
        x: -276,
        y: 507,
        w: 628,
        h: 41,
      },
      text: "1. Gerar AES key aleatória (DEK — Data Encryption Key)",
      align: "center",
    },
    {
      id: "hyb2",
      kind: "label",
      at: {
        x: -340,
        y: 532,
        w: 756,
        h: 41,
      },
      text: "2. RSA/ECDH cifra o DEK com public key (KEK — Key Encryption Key)",
      align: "center",
    },
    {
      id: "hyb3",
      kind: "label",
      at: {
        x: -172,
        y: 557,
        w: 419,
        h: 41,
      },
      text: "3. AES-GCM cifra o payload com o DEK",
      align: "center",
    },
    {
      id: "hyb4",
      kind: "label",
      at: {
        x: -317,
        y: 582,
        w: 709,
        h: 41,
      },
      text: "→ Receptor decifra KEK(DEK) com private key → decifra payload",
      align: "center",
    },
    {
      id: "hyb5",
      kind: "label",
      at: {
        x: -294,
        y: 607,
        w: 663,
        h: 41,
      },
      text: "Usado em: TLS, PGP/GPG, Signal Protocol, AWS KMS, JWT JWE",
      align: "center",
    },
    {
      id: "hyb_arr",
      tone: "accent",
      kind: "connector",
      from: {
        x: 375,
        y: 581,
      },
      to: {
        x: 825,
        y: 581,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "sig_bg",
      kind: "box",
      at: {
        x: 813,
        y: 475,
        w: 725,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "sig_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1041,
        y: 477,
        w: 267,
        h: 41,
      },
      text: "✍️ Assinaturas Digitais",
      align: "center",
    },
    {
      id: "sig1",
      kind: "label",
      at: {
        x: 494,
        y: 507,
        w: 663,
        h: 41,
      },
      text: "Alice assina: signature = Sign(hash(msg), priv_key_Alice)",
      align: "center",
    },
    {
      id: "sig2",
      kind: "label",
      at: {
        x: 418,
        y: 532,
        w: 814,
        h: 41,
      },
      text: "Bob verifica: Verify(signature, hash(msg), pub_key_Alice) → true/false",
      align: "center",
    },
    {
      id: "sig3",
      tone: "good",
      kind: "label",
      at: {
        x: 575,
        y: 557,
        w: 500,
        h: 41,
      },
      text: "→ Autenticidade: só Alice tem a private key",
      align: "center",
    },
    {
      id: "sig4",
      tone: "good",
      kind: "label",
      at: {
        x: 523,
        y: 579,
        w: 605,
        h: 41,
      },
      text: "→ Integridade: hash garante que msg não foi alterada",
      align: "center",
    },
    {
      id: "sig5",
      kind: "label",
      at: {
        x: 505,
        y: 602,
        w: 639,
        h: 41,
      },
      text: "Algoritmos: RSA-PSS, ECDSA (secp256r1), EdDSA (Ed25519)",
      align: "center",
    },
    {
      id: "sig6",
      kind: "label",
      at: {
        x: 476,
        y: 624,
        w: 698,
        h: 41,
      },
      text: "Usado em: certificados X.509, JWT (RS256/ES256), Git commits",
      align: "center",
    },
    {
      id: "hash_bg",
      kind: "box",
      at: {
        x: 25,
        y: 673,
        w: 725,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "hash_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 225,
        y: 674,
        w: 326,
        h: 41,
      },
      text: "#️⃣ Hash Functions (one-way)",
      align: "center",
    },
    {
      id: "h1",
      kind: "label",
      at: {
        x: -236,
        y: 704,
        w: 546,
        h: 41,
      },
      text: "Determinístico: mesmo input → mesmo hash sempre",
      align: "center",
    },
    {
      id: "h2",
      kind: "label",
      at: {
        x: -276,
        y: 729,
        w: 628,
        h: 41,
      },
      text: "One-way: impossível reconstruir input a partir do hash",
      align: "center",
    },
    {
      id: "h3",
      kind: "label",
      at: {
        x: -323,
        y: 754,
        w: 721,
        h: 41,
      },
      text: "Collision-resistant: difícil encontrar 2 inputs com mesmo hash",
      align: "center",
    },
    {
      id: "h4",
      tone: "good",
      kind: "label",
      at: {
        x: -265,
        y: 779,
        w: 605,
        h: 41,
      },
      text: "SHA-256: 256 bits · SHA-3 (Keccak) · BLAKE3 (rápido)",
      align: "center",
    },
    {
      id: "h5",
      tone: "hot",
      kind: "label",
      at: {
        x: -369,
        y: 804,
        w: 814,
        h: 41,
      },
      text: "MD5 e SHA-1: QUEBRADOS — colisões encontradas, não usar para segurança",
      align: "center",
    },
    {
      id: "h6",
      kind: "label",
      at: {
        x: -276,
        y: 829,
        w: 628,
        h: 41,
      },
      text: "HMAC: hash com chave secreta → integridade autenticada",
      align: "center",
    },
    {
      id: "kdf_bg",
      kind: "box",
      at: {
        x: 813,
        y: 673,
        w: 725,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "kdf_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 983,
        y: 674,
        w: 384,
        h: 41,
      },
      text: "🔑 Key Derivation Functions (KDF)",
      align: "center",
    },
    {
      id: "kdf1",
      kind: "label",
      at: {
        x: 470,
        y: 704,
        w: 709,
        h: 41,
      },
      text: "Propósito: converter senha fraca em chave criptográfica forte",
      align: "center",
    },
    {
      id: "kdf2",
      tone: "good",
      kind: "label",
      at: {
        x: 505,
        y: 729,
        w: 639,
        h: 41,
      },
      text: "Salt: valor aleatório por usuário → evita rainbow table",
      align: "center",
    },
    {
      id: "kdf3",
      tone: "good",
      kind: "label",
      at: {
        x: 459,
        y: 754,
        w: 732,
        h: 41,
      },
      text: "Iterations: custo computacional intencional → slows brute-force",
      align: "center",
    },
    {
      id: "kdf4",
      kind: "label",
      at: {
        x: 569,
        y: 779,
        w: 512,
        h: 41,
      },
      text: "PBKDF2: HMAC-SHA256 × N iterations — simples",
      align: "center",
    },
    {
      id: "kdf5",
      tone: "accent",
      kind: "label",
      at: {
        x: 488,
        y: 804,
        w: 674,
        h: 41,
      },
      text: "bcrypt: memory-hard, fator de custo ajustável — padrão web",
      align: "center",
    },
    {
      id: "kdf6",
      tone: "good",
      kind: "label",
      at: {
        x: 482,
        y: 829,
        w: 686,
        h: 41,
      },
      text: "Argon2id: winner PHC, memory+CPU hard → melhor contra ASICs",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: comunicação secreta sem se encontrar",
      duration: 6500,
      add: ["sym_bg", "sym_title", "sym_def", "sym_pro", "sym_con", "asym_bg", "asym_title", "asym_def"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "sym_bg",
        placement: "right",
        text: "Alice quer mandar mensagem secreta para Bob pela internet. O problema: como combinam a chave secreta sem que Eve (no meio) intercepte? Criptografia simétrica é rápida mas exige chave pré-compartilhada.",
      },
    },
    {
      id: "s2",
      title: "Criptografia Simétrica: 1 chave, 2 operações",
      duration: 6500,
      add: [
        "sym_bg",
        "sym_title",
        "sym_def",
        "sym_pro",
        "sym_con",
        "aes_bg",
        "aes_title",
        "aes1",
        "aes2",
        "aes3",
        "aes4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sym_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sym_bg",
        placement: "right",
        text: "A mesma chave cifra e decifra. AES é o padrão atual: 128-256 bits, acelerado por hardware (AES-NI). O modo importa muito: **GCM** é o correto para dados (AEAD = cifra + autentica em 1 passo).",
        why: 'ECB é inseguro porque blocos idênticos produzem ciphertext idêntico — padrões ficam visíveis (a "imagem do pinguim" do Linux).',
      },
    },
    {
      id: "s3",
      title: "AES-GCM: o modo correto para dados",
      duration: 6500,
      add: ["sym_bg", "sym_title", "aes_bg", "aes_title", "aes1", "aes2", "aes3", "aes4"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "aes4",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "aes_bg",
        placement: "right",
        text: '**GCM (Galois/Counter Mode)**: combina Counter Mode (stream cipher) com GHASH (MAC). AEAD = "Authenticated Encryption with Associated Data". Resultado: ciphertext autenticado — adulteração detectada imediatamente.',
      },
    },
    {
      id: "s4",
      title: "ChaCha20-Poly1305: quando não há AES-NI",
      duration: 6500,
      add: [
        "sym_bg",
        "sym_title",
        "sym_con",
        "sym_key_prob",
        "sym_sol",
        "cha_bg",
        "cha_title",
        "cha1",
        "cha2",
        "cha3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cha_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cha_bg",
        placement: "right",
        text: "Em dispositivos sem aceleração de hardware AES (ARM antigos, IoT), **ChaCha20** é mais rápido e igualmente seguro. Poly1305 é o MAC integrado. É o cipher suite padrão no **TLS 1.3 mobile** e no **WireGuard VPN**.",
      },
    },
    {
      id: "s5",
      title: "O Key Distribution Problem",
      duration: 6500,
      add: [
        "sym_bg",
        "sym_title",
        "sym_def",
        "sym_pro",
        "sym_con",
        "sym_key_prob",
        "sym_sol",
        "asym_bg",
        "asym_title",
        "asym_def",
        "asym_pro",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sym_con",
          do: "highlight",
        },
        {
          at: 0,
          target: "sym_key_prob",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sym_con",
        placement: "right",
        text: "Alice e Bob precisam combinar a chave secreta **antecipadamente** por um canal já seguro. Mas se já têm um canal seguro, para que precisam de criptografia? A solução é usar **criptografia assimétrica** apenas para trocar a chave simétrica.",
      },
    },
    {
      id: "s6",
      title: "RSA: chaves públicas e privadas",
      duration: 6500,
      add: [
        "asym_bg",
        "asym_title",
        "asym_def",
        "asym_pro",
        "asym_con",
        "rsa_bg",
        "rsa_title",
        "rsa1",
        "rsa2",
        "rsa3",
        "rsa4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "asym_bg",
          do: "highlight",
        },
        {
          at: 0,
          target: "rsa_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "asym_bg",
        placement: "left",
        text: "Bob publica sua **chave pública**. Alice cifra com ela. Só Bob (com a **chave privada**) consegue decifrar. A segurança do RSA depende da dificuldade de fatorar `n = p × q` sendo `p` e `q` primos muito grandes.",
        why: "2048 bits é o mínimo seguro; 4096 bits recomendado para chaves de longa duração.",
      },
    },
    {
      id: "s7",
      title: "ECC: mesma segurança, chaves muito menores",
      duration: 6500,
      add: [
        "asym_bg",
        "asym_title",
        "asym_def",
        "asym_pro",
        "ecc_bg",
        "ecc_title",
        "ecc1",
        "ecc2",
        "ecc3",
        "asym_use",
        "asym_ex",
        "asym_note",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ecc_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ecc_bg",
        placement: "left",
        text: "**Curva elíptica**: equação `y² = x³ + ax + b`. A chave é um ponto na curva. ECDH permite troca de chave segura. ECDSA assina. **Chave ECC de 256 bits = RSA de 3072 bits** — muito menor para mesma segurança. Padrão no TLS 1.3.",
        why: "Post-quantum: RSA e ECC são vulneráveis ao algoritmo de Shor em computadores quânticos. NIST padronizou algoritmos PQC (Kyber, Dilithium) em 2024.",
      },
    },
    {
      id: "s8",
      title: "Hybrid Encryption: o melhor dos dois mundos",
      duration: 6500,
      add: [
        "sym_bg",
        "sym_title",
        "sym_pro",
        "asym_bg",
        "asym_title",
        "asym_pro",
        "hyb_bg",
        "hyb_title",
        "hyb1",
        "hyb2",
        "hyb3",
        "hyb4",
        "hyb5",
        "hyb_arr",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hyb_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hyb_bg",
        placement: "top",
        text: "Ninguém cifra dados grandes com RSA — é lento demais. A solução padrão: **gerar uma AES key aleatória (DEK)**, cifrar o payload com AES-GCM, e cifrar a DEK com a chave pública do destinatário. Isso é o que TLS, PGP e AWS KMS fazem.",
      },
    },
    {
      id: "s9",
      title: "Assinaturas Digitais: autenticidade + integridade",
      duration: 6500,
      add: ["asym_bg", "asym_title", "sig_bg", "sig_title", "sig1", "sig2", "sig3", "sig4", "sig5", "sig6"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sig_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sig_bg",
        placement: "left",
        text: "Alice assina com **chave privada** — qualquer um pode verificar com sua **chave pública**. O `hash(msg)` garante que a mensagem não foi alterada. Usado em X.509 (TLS certs), JWT (RS256), Git commits assinados.",
        why: "Ao contrário da cifração, na assinatura a privada ASSINA e a pública VERIFICA — o inverso do padrão de cifração.",
      },
    },
    {
      id: "s10",
      title: "Hash Functions: impressão digital one-way",
      duration: 6500,
      add: ["hash_bg", "hash_title", "h1", "h2", "h3", "h4", "h5", "h6"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hash_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hash_bg",
        placement: "right",
        text: "**SHA-256**: 256 bits, base do Bitcoin, X.509, TLS. **BLAKE3**: mais rápido, ideal para checksums. **HMAC**: hash com chave secreta (ex: JWT HS256). **MD5 e SHA-1 estão quebrados** — não usar para segurança, apenas para checksums não-críticos.",
      },
    },
    {
      id: "s11",
      title: "Key Derivation Functions: senhas → chaves fortes",
      duration: 6500,
      add: ["kdf_bg", "kdf_title", "kdf1", "kdf2", "kdf3", "kdf4", "kdf5", "kdf6"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "kdf_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "kdf_bg",
        placement: "left",
        text: "Senhas são fracas e previsíveis. KDFs as transformam em chaves criptograficamente fortes: **salt** (único por usuário, evita rainbow tables) + **iterations** (custo alto dificulta brute-force). **Argon2id** é o padrão moderno (OWASP recomendado).",
        why: "bcrypt e Argon2 são memory-hard: mesmo com GPUs/ASICs, o ataque de força bruta fica caro porque requer muita RAM.",
      },
    },
    {
      id: "s12",
      title: "Quiz",
      duration: 6500,
      add: ["sym_bg", "sym_title", "asym_bg", "asym_title", "hyb_bg", "hyb_title"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question:
          'Por que sistemas como TLS usam "hybrid encryption" (AES + RSA/ECDH) em vez de cifrar tudo com RSA diretamente?',
        options: [
          "Porque RSA não suporta chaves maiores que 4096 bits, limitando o tamanho dos dados",
          "Porque AES é 100-1000× mais rápido que RSA — RSA cifra apenas a AES key (pequena), AES cifra os dados",
          "Porque o algoritmo RSA não é considerado seguro para dados maiores que 256 bytes",
          "Porque TLS 1.3 removeu suporte a RSA por razões de compliance",
        ],
        answer: 1,
        explain:
          'RSA é seguro mas **muito lento** para grandes volumes de dados: cifrar 1 MB com RSA-2048 leva centenas de vezes mais tempo que com AES-256-GCM. O padrão é usar RSA/ECDH apenas para o "key wrapping" — cifrar a chave AES (32 bytes). Então AES cifra o payload inteiro em velocidade de hardware. Esse padrão se chama hybrid encryption e é a base de TLS, PGP, JOSE/JWE e AWS KMS.',
      },
    },
    {
      id: "s13",
      title: "Resumo: Criptografia",
      duration: 6500,
      add: [
        "sym_bg",
        "sym_title",
        "sym_def",
        "sym_pro",
        "sym_con",
        "aes_bg",
        "aes_title",
        "aes4",
        "cha_bg",
        "cha_title",
        "cha3",
        "asym_bg",
        "asym_title",
        "asym_def",
        "asym_pro",
        "rsa_bg",
        "rsa_title",
        "rsa1",
        "ecc_bg",
        "ecc_title",
        "ecc2",
        "hyb_bg",
        "hyb_title",
        "hyb1",
        "hyb3",
        "hyb4",
        "sig_bg",
        "sig_title",
        "sig3",
        "sig4",
        "hash_bg",
        "hash_title",
        "h4",
        "h5",
        "kdf_bg",
        "kdf_title",
        "kdf5",
        "kdf6",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "hyb_bg",
        placement: "top",
        text: "Simétrica (AES-GCM, ChaCha20): rápida, AEAD. Assimétrica (RSA, ECC): troca de chave sem canal seguro. Hybrid: assimétrica troca a AES key, simétrica cifra os dados (TLS, PGP). Assinatura: privada assina, pública verifica. Hashes: SHA-256 (MD5 quebrado). KDFs: Argon2id para senhas.",
      },
    },
  ],
};

export const crypto = validateExplainer(data);
