import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/grpc.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "grpc",
  title: "gRPC",
  subtitle: "Protocol Buffers · HTTP/2 · 4 RPC Types · Code Generation",
  category: "Web & Protocolos",
  tags: ["grpc", "rpc"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "rest_box",
      kind: "box",
      at: {
        x: 25,
        y: 13,
        w: 725,
        h: 100,
      },
      label: "REST / JSON",
      sub: "HTTP 1.1 · Text · No schema",
      variant: "outline",
    },
    {
      id: "grpc_box",
      kind: "box",
      at: {
        x: 825,
        y: 13,
        w: 750,
        h: 100,
      },
      label: "gRPC / Protobuf",
      sub: "HTTP/2 · Binary · Schema-first",
      variant: "outline",
    },
    {
      id: "vs_lbl",
      kind: "label",
      at: {
        x: 763,
        y: 42,
        w: 75,
        h: 41,
      },
      text: "vs",
      align: "center",
    },
    {
      id: "cmp_k0",
      kind: "label",
      at: {
        x: 88,
        y: 114,
        w: 105,
        h: 41,
      },
      text: "Transport",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a0",
      kind: "label",
      at: {
        x: 354,
        y: 114,
        w: 93,
        h: 41,
      },
      text: "HTTP/1.1",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b0",
      kind: "label",
      at: {
        x: 1013,
        y: 114,
        w: 75,
        h: 41,
      },
      text: "HTTP/2",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_k1",
      kind: "label",
      at: {
        x: 88,
        y: 159,
        w: 75,
        h: 41,
      },
      text: "Format",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a1",
      kind: "label",
      at: {
        x: 336,
        y: 159,
        w: 128,
        h: 41,
      },
      text: "JSON (text)",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b1",
      kind: "label",
      at: {
        x: 951,
        y: 159,
        w: 198,
        h: 41,
      },
      text: "Protobuf (binary)",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_k2",
      kind: "label",
      at: {
        x: 88,
        y: 204,
        w: 75,
        h: 41,
      },
      text: "Schema",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a2",
      kind: "label",
      at: {
        x: 295,
        y: 204,
        w: 209,
        h: 41,
      },
      text: "Optional (OpenAPI)",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b2",
      kind: "label",
      at: {
        x: 951,
        y: 204,
        w: 198,
        h: 41,
      },
      text: "Required (.proto)",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_k3",
      kind: "label",
      at: {
        x: 88,
        y: 249,
        w: 105,
        h: 41,
      },
      text: "Streaming",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a3",
      kind: "label",
      at: {
        x: 336,
        y: 249,
        w: 128,
        h: 41,
      },
      text: "Workarounds",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b3",
      kind: "label",
      at: {
        x: 969,
        y: 249,
        w: 163,
        h: 41,
      },
      text: "Native 4 types",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_k4",
      kind: "label",
      at: {
        x: 88,
        y: 294,
        w: 93,
        h: 41,
      },
      text: "Code gen",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a4",
      kind: "label",
      at: {
        x: 319,
        y: 294,
        w: 163,
        h: 41,
      },
      text: "Manual clients",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b4",
      kind: "label",
      at: {
        x: 922,
        y: 294,
        w: 256,
        h: 41,
      },
      text: "protoc generates stubs",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_k5",
      kind: "label",
      at: {
        x: 88,
        y: 339,
        w: 75,
        h: 41,
      },
      text: "Perf",
      align: "start",
      muted: true,
    },
    {
      id: "cmp_a5",
      kind: "label",
      at: {
        x: 313,
        y: 339,
        w: 174,
        h: 41,
      },
      text: "Higher overhead",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_b5",
      kind: "label",
      at: {
        x: 934,
        y: 339,
        w: 233,
        h: 41,
      },
      text: "~10x smaller payload",
      align: "center",
      muted: true,
    },
    {
      id: "proto_bg",
      kind: "box",
      at: {
        x: 575,
        y: 138,
        w: 450,
        h: 450,
      },
      variant: "outline",
    },
    {
      id: "proto_ttl",
      kind: "label",
      at: {
        x: 742,
        y: 147,
        w: 116,
        h: 41,
      },
      text: "user.proto",
      align: "center",
    },
    {
      id: "proto_l0",
      kind: "label",
      at: {
        x: 594,
        y: 177,
        w: 209,
        h: 41,
      },
      text: 'syntax = "proto3";',
      align: "start",
      muted: true,
    },
    {
      id: "proto_l1",
      kind: "label",
      at: {
        x: 594,
        y: 201,
        w: 75,
        h: 41,
      },
      text: "",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l2",
      kind: "label",
      at: {
        x: 594,
        y: 224,
        w: 163,
        h: 41,
      },
      text: "message User {",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l3",
      kind: "label",
      at: {
        x: 594,
        y: 248,
        w: 221,
        h: 41,
      },
      text: "  uint64 id    = 1;",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l4",
      kind: "label",
      at: {
        x: 594,
        y: 272,
        w: 221,
        h: 41,
      },
      text: "  string name  = 2;",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l5",
      kind: "label",
      at: {
        x: 594,
        y: 296,
        w: 221,
        h: 41,
      },
      text: "  string email = 3;",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l6",
      kind: "label",
      at: {
        x: 594,
        y: 319,
        w: 75,
        h: 41,
      },
      text: "}",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l7",
      kind: "label",
      at: {
        x: 594,
        y: 343,
        w: 75,
        h: 41,
      },
      text: "",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l8",
      kind: "label",
      at: {
        x: 594,
        y: 367,
        w: 244,
        h: 41,
      },
      text: "service UserService {",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l9",
      kind: "label",
      at: {
        x: 594,
        y: 391,
        w: 256,
        h: 41,
      },
      text: "  rpc GetUser(UserReq)",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l10",
      kind: "label",
      at: {
        x: 594,
        y: 414,
        w: 221,
        h: 41,
      },
      text: "    returns (User);",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l11",
      kind: "label",
      at: {
        x: 594,
        y: 438,
        w: 279,
        h: 41,
      },
      text: "  rpc ListUsers(ListReq)",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l12",
      kind: "label",
      at: {
        x: 594,
        y: 462,
        w: 302,
        h: 41,
      },
      text: "    returns (stream User);",
      align: "start",
      muted: true,
    },
    {
      id: "proto_l13",
      kind: "label",
      at: {
        x: 594,
        y: 486,
        w: 75,
        h: 41,
      },
      text: "}",
      align: "start",
      muted: true,
    },
    {
      id: "gen_cl",
      tone: "accent",
      kind: "connector",
      from: {
        x: 575,
        y: 375,
      },
      to: {
        x: 400,
        y: 375,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "gen_cl_l",
      kind: "label",
      at: {
        x: 424,
        y: 338,
        w: 128,
        h: 41,
      },
      text: "client stub",
      align: "center",
      muted: true,
    },
    {
      id: "gen_sv",
      tone: "good",
      kind: "connector",
      from: {
        x: 1025,
        y: 375,
      },
      to: {
        x: 1163,
        y: 375,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "gen_sv_l",
      kind: "label",
      at: {
        x: 1001,
        y: 338,
        w: 186,
        h: 41,
      },
      text: "server interface",
      align: "center",
      muted: true,
    },
    {
      id: "protoc_btn",
      kind: "box",
      at: {
        x: 738,
        y: 338,
        w: 125,
        h: 45,
      },
      label: "protoc",
      variant: "outline",
    },
    {
      id: "client_bg",
      kind: "box",
      at: {
        x: 25,
        y: 413,
        w: 350,
        h: 325,
      },
      variant: "outline",
    },
    {
      id: "client_ttl",
      kind: "label",
      at: {
        x: 142,
        y: 419,
        w: 116,
        h: 41,
      },
      text: "Client App",
      align: "center",
    },
    {
      id: "stub_box",
      kind: "box",
      at: {
        x: 50,
        y: 463,
        w: 300,
        h: 55,
      },
      label: "Generated Stub",
      variant: "outline",
    },
    {
      id: "stub_detail",
      kind: "label",
      at: {
        x: 101,
        y: 527,
        w: 198,
        h: 41,
      },
      text: "stub.GetUser(req)",
      align: "center",
      muted: true,
    },
    {
      id: "stub_detail2",
      kind: "label",
      at: {
        x: 72,
        y: 552,
        w: 256,
        h: 41,
      },
      text: "→ marshals to protobuf",
      align: "center",
      muted: true,
    },
    {
      id: "stub_detail3",
      kind: "label",
      at: {
        x: 95,
        y: 577,
        w: 209,
        h: 41,
      },
      text: "→ sends via HTTP/2",
      align: "center",
      muted: true,
    },
    {
      id: "server_bg",
      kind: "box",
      at: {
        x: 1175,
        y: 413,
        w: 350,
        h: 325,
      },
      variant: "outline",
    },
    {
      id: "server_ttl",
      kind: "label",
      at: {
        x: 1338,
        y: 419,
        w: 75,
        h: 41,
      },
      text: "Server",
      align: "center",
    },
    {
      id: "skel_box",
      kind: "box",
      at: {
        x: 1200,
        y: 463,
        w: 300,
        h: 55,
      },
      label: "Generated Interface",
      variant: "outline",
    },
    {
      id: "skel_detail",
      kind: "label",
      at: {
        x: 1247,
        y: 527,
        w: 256,
        h: 41,
      },
      text: "impl GetUser(ctx, req)",
      align: "center",
      muted: true,
    },
    {
      id: "skel_detail2",
      kind: "label",
      at: {
        x: 1282,
        y: 552,
        w: 186,
        h: 41,
      },
      text: "→ business logic",
      align: "center",
      muted: true,
    },
    {
      id: "skel_detail3",
      kind: "label",
      at: {
        x: 1253,
        y: 577,
        w: 244,
        h: 41,
      },
      text: "→ returns User object",
      align: "center",
      muted: true,
    },
    {
      id: "h2_bg",
      kind: "box",
      at: {
        x: 650,
        y: 413,
        w: 300,
        h: 113,
      },
      label: "HTTP/2 Transport",
      sub: "Binary · Multiplexed · Streams",
      variant: "outline",
    },
    {
      id: "h2_sub1",
      kind: "label",
      at: {
        x: 661,
        y: 536,
        w: 279,
        h: 41,
      },
      text: "HPACK header compression",
      align: "center",
      muted: true,
    },
    {
      id: "h2_sub2",
      kind: "label",
      at: {
        x: 620,
        y: 558,
        w: 360,
        h: 41,
      },
      text: "Multiple streams per connection",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_req",
      tone: "accent",
      kind: "connector",
      from: {
        x: 420,
        y: 475,
      },
      to: {
        x: 630,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_req_l",
      kind: "label",
      at: {
        x: 403,
        y: 438,
        w: 244,
        h: 41,
      },
      text: "Unary Request (bytes)",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_res",
      tone: "good",
      kind: "connector",
      from: {
        x: 970,
        y: 475,
      },
      to: {
        x: 1155,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_res_l",
      kind: "label",
      at: {
        x: 970,
        y: 438,
        w: 186,
        h: 41,
      },
      text: "Response (bytes)",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_ss1",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 970,
        y: 613,
      },
      to: {
        x: 1155,
        y: 613,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_ss1_l",
      kind: "label",
      at: {
        x: 993,
        y: 576,
        w: 140,
        h: 41,
      },
      text: "stream req →",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_ss2",
      tone: "good",
      kind: "connector",
      from: {
        x: 1195,
        y: 669,
      },
      to: {
        x: 630,
        y: 669,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_ss2_l",
      kind: "label",
      at: {
        x: 866,
        y: 632,
        w: 93,
        h: 41,
      },
      text: "← User 1",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_ss3",
      tone: "good",
      kind: "connector",
      from: {
        x: 1195,
        y: 706,
      },
      to: {
        x: 630,
        y: 706,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_ss3_l",
      kind: "label",
      at: {
        x: 866,
        y: 669,
        w: 93,
        h: 41,
      },
      text: "← User 2",
      align: "center",
      muted: true,
    },
    {
      id: "rpc_ss4",
      tone: "good",
      kind: "connector",
      from: {
        x: 1195,
        y: 744,
      },
      to: {
        x: 630,
        y: 744,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rpc_ss4_l",
      kind: "label",
      at: {
        x: 796,
        y: 707,
        w: 233,
        h: 41,
      },
      text: "← User 3  END_STREAM",
      align: "center",
      muted: true,
    },
    {
      id: "types_bg",
      kind: "box",
      at: {
        x: 38,
        y: 613,
        w: 738,
        h: 263,
      },
      variant: "outline",
    },
    {
      id: "types_ttl",
      kind: "label",
      at: {
        x: 342,
        y: 617,
        w: 128,
        h: 41,
      },
      text: "4 RPC Types",
      align: "center",
    },
    {
      id: "type_n0",
      kind: "label",
      at: {
        x: 75,
        y: 654,
        w: 75,
        h: 41,
      },
      text: "Unary",
      align: "start",
      muted: false,
    },
    {
      id: "type_f0",
      kind: "label",
      at: {
        x: 360,
        y: 654,
        w: 105,
        h: 41,
      },
      text: "req → res",
      align: "center",
      muted: true,
    },
    {
      id: "type_n1",
      kind: "label",
      at: {
        x: 75,
        y: 704,
        w: 151,
        h: 41,
      },
      text: "Server Stream",
      align: "start",
      muted: false,
    },
    {
      id: "type_f1",
      kind: "label",
      at: {
        x: 308,
        y: 704,
        w: 209,
        h: 41,
      },
      text: "req → res res res…",
      align: "center",
      muted: true,
    },
    {
      id: "type_n2",
      kind: "label",
      at: {
        x: 75,
        y: 754,
        w: 151,
        h: 41,
      },
      text: "Client Stream",
      align: "start",
      muted: false,
    },
    {
      id: "type_f2",
      kind: "label",
      at: {
        x: 308,
        y: 754,
        w: 209,
        h: 41,
      },
      text: "req req req… → res",
      align: "center",
      muted: true,
    },
    {
      id: "type_n3",
      kind: "label",
      at: {
        x: 75,
        y: 804,
        w: 151,
        h: 41,
      },
      text: "Bidirectional",
      align: "start",
      muted: false,
    },
    {
      id: "type_f3",
      kind: "label",
      at: {
        x: 325,
        y: 804,
        w: 174,
        h: 41,
      },
      text: "req↔res (async)",
      align: "center",
      muted: true,
    },
    {
      id: "icp_bg",
      kind: "box",
      at: {
        x: 600,
        y: 613,
        w: 400,
        h: 163,
      },
      variant: "outline",
    },
    {
      id: "icp_ttl",
      kind: "label",
      at: {
        x: 655,
        y: 617,
        w: 291,
        h: 41,
      },
      text: "Interceptors (Middleware)",
      align: "center",
    },
    {
      id: "icp_1",
      kind: "label",
      at: {
        x: 678,
        y: 654,
        w: 244,
        h: 41,
      },
      text: "• Auth (verify token)",
      align: "center",
      muted: true,
    },
    {
      id: "icp_2",
      kind: "label",
      at: {
        x: 690,
        y: 682,
        w: 221,
        h: 41,
      },
      text: "• Logging + Tracing",
      align: "center",
      muted: true,
    },
    {
      id: "icp_3",
      kind: "label",
      at: {
        x: 695,
        y: 709,
        w: 209,
        h: 41,
      },
      text: "• Retry + Deadline",
      align: "center",
      muted: true,
    },
    {
      id: "icp_4",
      kind: "label",
      at: {
        x: 643,
        y: 737,
        w: 314,
        h: 41,
      },
      text: "• Metrics (latency, errors)",
      align: "center",
      muted: true,
    },
    {
      id: "use_bg",
      kind: "box",
      at: {
        x: 25,
        y: 663,
        w: 738,
        h: 213,
      },
      variant: "outline",
    },
    {
      id: "use_ttl",
      kind: "label",
      at: {
        x: 248,
        y: 669,
        w: 267,
        h: 41,
      },
      text: "gRPC vs REST vs GraphQL",
      align: "center",
    },
    {
      id: "use_n0",
      kind: "label",
      at: {
        x: 50,
        y: 707,
        w: 75,
        h: 41,
      },
      text: "gRPC",
      align: "start",
    },
    {
      id: "use_d0",
      kind: "label",
      at: {
        x: 163,
        y: 707,
        w: 639,
        h: 41,
      },
      text: "Internal microservices, streaming, performance-critical",
      align: "start",
      muted: true,
    },
    {
      id: "use_n1",
      kind: "label",
      at: {
        x: 50,
        y: 752,
        w: 75,
        h: 41,
      },
      text: "REST",
      align: "start",
    },
    {
      id: "use_d1",
      kind: "label",
      at: {
        x: 163,
        y: 752,
        w: 581,
        h: 41,
      },
      text: "Public APIs, browser clients, CRUD, simple tooling",
      align: "start",
      muted: true,
    },
    {
      id: "use_n2",
      kind: "label",
      at: {
        x: 50,
        y: 797,
        w: 81,
        h: 41,
      },
      text: "GraphQL",
      align: "start",
    },
    {
      id: "use_d2",
      kind: "label",
      at: {
        x: 163,
        y: 797,
        w: 593,
        h: 41,
      },
      text: "Client-driven queries, aggregating multiple sources",
      align: "start",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "REST: O Status Quo",
      duration: 9000,
      add: [
        "rest_box",
        "grpc_box",
        "vs_lbl",
        "cmp_k0",
        "cmp_a0",
        "cmp_k1",
        "cmp_a1",
        "cmp_k2",
        "cmp_a2",
        "cmp_k3",
        "cmp_a3",
        "cmp_k4",
        "cmp_a4",
        "cmp_k5",
        "cmp_a5",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "rest_box",
        placement: "bottom",
        text: "REST sobre HTTP/1.1 com JSON é a escolha default para APIs. Flexível e ubíquo — mas **verboso** (headers repetidos, JSON text parsing) e sem tipagem forte em runtime.",
        why: "Um payload JSON típico de 1KB pode se tornar 100 bytes em Protobuf. Em alta frequência (telemetria, IoT, microserviços internos) isso importa.",
      },
    },
    {
      id: "s2",
      title: "gRPC: Schema-first com Protocol Buffers",
      duration: 9000,
      add: [
        "rest_box",
        "grpc_box",
        "vs_lbl",
        "cmp_k0",
        "cmp_a0",
        "cmp_b0",
        "cmp_k1",
        "cmp_a1",
        "cmp_b1",
        "cmp_k2",
        "cmp_a2",
        "cmp_b2",
        "cmp_k3",
        "cmp_a3",
        "cmp_b3",
        "cmp_k4",
        "cmp_a4",
        "cmp_b4",
        "cmp_k5",
        "cmp_a5",
        "cmp_b5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "grpc_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "grpc_box",
        placement: "bottom",
        text: "gRPC usa **Protocol Buffers** (.proto) como IDL (Interface Definition Language). Dados são serializados em binário — menor payload e mais rápido que JSON text parsing.",
        why: "Protobuf numera cada campo — isso permite evoluir a API sem quebrar compatibilidade. Adicionar campo novo com número novo é backward-compatible.",
      },
    },
    {
      id: "s3",
      title: "O arquivo .proto: Contrato da API",
      duration: 9000,
      add: [
        "proto_bg",
        "proto_ttl",
        "proto_l0",
        "proto_l1",
        "proto_l2",
        "proto_l3",
        "proto_l4",
        "proto_l5",
        "proto_l6",
        "proto_l7",
        "proto_l8",
        "proto_l9",
        "proto_l10",
        "proto_l11",
        "proto_l12",
        "proto_l13",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 480,
        },
        placement: "bottom",
        text: "O `.proto` define **Messages** (estruturas de dados) e **Services** (RPCs). Cada campo tem um *número* único (não o nome) — isso garante compatibilidade binária entre versões.",
        why: "O contrato fica no repositório e é a fonte de verdade. Qualquer alteração incompatível quebra o build — não surpresas em runtime.",
      },
    },
    {
      id: "s4",
      title: "protoc: Gerando Código Automaticamente",
      duration: 9000,
      add: [
        "proto_bg",
        "proto_ttl",
        "proto_l0",
        "proto_l1",
        "proto_l2",
        "proto_l3",
        "proto_l4",
        "proto_l5",
        "proto_l6",
        "proto_l7",
        "proto_l8",
        "proto_l9",
        "proto_l10",
        "proto_l11",
        "proto_l12",
        "proto_l13",
        "protoc_btn",
        "gen_cl",
        "gen_cl_l",
        "gen_sv",
        "gen_sv_l",
        "client_bg",
        "client_ttl",
        "stub_box",
        "skel_box",
        "server_bg",
        "server_ttl",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "gen_cl",
          do: "draw",
        },
        {
          at: 300,
          target: "gen_sv",
          do: "draw",
        },
      ],
      caption: {
        anchor: "protoc_btn",
        placement: "bottom",
        text: "`protoc --go_out=. user.proto` gera: **client stub** (faz chamada como função local) e **server interface** (que o dev implementa). Suporta 10+ linguagens.",
        why: "Zero código de serialização manual. A camada de transporte é gerada — o dev foca 100% na lógica de negócio.",
      },
    },
    {
      id: "s5",
      title: "HTTP/2: O Transporte",
      duration: 9000,
      add: [
        "client_bg",
        "client_ttl",
        "stub_box",
        "stub_detail",
        "stub_detail2",
        "stub_detail3",
        "h2_bg",
        "h2_sub1",
        "h2_sub2",
        "server_bg",
        "server_ttl",
        "skel_box",
        "skel_detail",
        "skel_detail2",
        "skel_detail3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "h2_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "h2_bg",
        placement: "bottom",
        text: "**HTTP/2** sob o gRPC: <br>• *Multiplexing*: múltiplas RPCs na mesma conexão TCP <br>• *HPACK*: compressão de headers (economiza ~80% em headers repetidos) <br>• *Binary frames*: mais eficiente que HTTP/1.1 text",
        why: "HTTP/1.1 exige uma conexão TCP por request simultânea (ou pipelining limitado). HTTP/2 resolve isso com streams numerados numa única conexão.",
      },
    },
    {
      id: "s6",
      title: "Unary RPC: Request → Response",
      duration: 9000,
      add: [
        "client_bg",
        "client_ttl",
        "stub_box",
        "h2_bg",
        "server_bg",
        "server_ttl",
        "skel_box",
        "rpc_req",
        "rpc_req_l",
        "rpc_res",
        "rpc_res_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "rpc_req",
          do: "draw",
        },
        {
          at: 400,
          target: "rpc_res",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 395,
        },
        placement: "bottom",
        text: '**Unary RPC**: 1 request, 1 response — o equivalente de uma chamada REST. Ex: `GetUser(id: 42)` → `User{id:42, name:"Alice"}`.',
        why: "Mesmo sendo 'igual ao REST' funcionalmente, a Unary RPC já ganha em payload (protobuf binário) e headers (HTTP/2 HPACK).",
      },
    },
    {
      id: "s7",
      title: "Server Streaming: 1 Request → N Responses",
      duration: 9000,
      add: [
        "client_bg",
        "client_ttl",
        "stub_box",
        "h2_bg",
        "server_bg",
        "server_ttl",
        "skel_box",
        "rpc_ss1",
        "rpc_ss1_l",
        "rpc_ss2",
        "rpc_ss2_l",
        "rpc_ss3",
        "rpc_ss3_l",
        "rpc_ss4",
        "rpc_ss4_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "rpc_ss1",
          do: "draw",
        },
        {
          at: 300,
          target: "rpc_ss2",
          do: "draw",
        },
        {
          at: 600,
          target: "rpc_ss3",
          do: "draw",
        },
        {
          at: 900,
          target: "rpc_ss4",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 560,
        },
        placement: "top",
        text: "**Server Streaming**: cliente envia 1 request, servidor responde com *N mensagens* no mesmo stream HTTP/2. Útil para: paginação de resultados grandes, feed de eventos, progresso de processamento.",
        why: "Sem server streaming, o cliente precisaria fazer múltiplas requisições ou receber tudo de uma vez (payload gigante). Com streaming, começa a processar na primeira mensagem.",
      },
    },
    {
      id: "s8",
      title: "Client Streaming e Bidirectional",
      duration: 9000,
      add: [
        "types_bg",
        "types_ttl",
        "type_n0",
        "type_f0",
        "type_n1",
        "type_f1",
        "type_n2",
        "type_f2",
        "type_n3",
        "type_f3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 325,
          y: 510,
        },
        placement: "bottom",
        text: "**Client Streaming**: cliente envia múltiplas mensagens, servidor responde ao final (ex: upload, aggregation). **Bidirectional**: ambos enviam quando quiserem — full-duplex como WebSocket, mas com RPC semantics.",
        why: "Bidirectional streaming é raro mas poderoso: telemetria em tempo real, chat de microserviços, jogos multiplayer.",
      },
    },
    {
      id: "s9",
      title: "Status Codes, Metadata e Deadlines",
      duration: 9000,
      add: [
        "h2_bg",
        "h2_sub1",
        "h2_sub2",
        "client_bg",
        "client_ttl",
        "stub_box",
        "server_bg",
        "server_ttl",
        "skel_box",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "h2_bg",
        placement: "bottom",
        text: "**Status**: 16 códigos padrão (OK, NOT_FOUND, UNAVAILABLE, DEADLINE_EXCEEDED…). **Metadata**: key-value headers (auth token, trace-id). **Deadlines**: timeout propagado para toda a cadeia de chamadas.",
        why: "Deadlines são melhores que timeouts locais: se o cliente desiste, o servidor downstream também sabe desistir, economizando recursos no sistema inteiro.",
      },
    },
    {
      id: "s10",
      title: "Interceptors: Middleware no gRPC",
      duration: 9000,
      add: [
        "icp_bg",
        "icp_ttl",
        "icp_1",
        "icp_2",
        "icp_3",
        "icp_4",
        "client_bg",
        "client_ttl",
        "server_bg",
        "server_ttl",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "icp_bg",
        placement: "top",
        text: "**Interceptors** são executados antes/depois de cada RPC: autenticação (verificar Bearer token), logging estruturado, distributed tracing, retry com backoff exponencial.",
        why: "Separa concerns de infraestrutura da lógica de negócio. Um interceptor de auth centralizado elimina verificações duplicadas em cada método.",
      },
    },
    {
      id: "s11",
      title: "Quando usar gRPC vs REST vs GraphQL",
      duration: 9000,
      add: ["use_bg", "use_ttl", "use_n0", "use_d0", "use_n1", "use_d1", "use_n2", "use_d2"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 305,
          y: 640,
        },
        placement: "top",
        text: "**gRPC**: microserviços internos, alta performance, streaming. **REST**: APIs públicas, browser direto, simplicidade. **GraphQL**: clientes com necessidades diferentes de dados.",
        why: "gRPC exige que o cliente entenda Protobuf e HTTP/2 — browsers não suportam nativamente. grpc-web é uma proxy workaround. Para APIs públicas, REST ainda vence em adoção.",
      },
    },
    {
      id: "s12",
      title: "Quiz",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Teste seu conhecimento sobre gRPC:",
      },
      quiz: {
        question: "Por que gRPC usa HTTP/2 como transporte e qual o benefício principal?",
        options: [
          "HTTP/2 é obrigatório pela especificação Protobuf para garantir a ordem dos bytes",
          "HTTP/2 permite multiplexing — múltiplas RPCs simultâneas numa única conexão TCP",
          "HTTP/2 criptografa automaticamente o payload Protobuf com TLS",
          "HTTP/2 converte binário Protobuf para JSON para compatibilidade com browsers",
        ],
        answer: 1,
        explain:
          "HTTP/2 streams permitem que várias RPCs rodem em paralelo na mesma conexão TCP sem head-of-line blocking. Isso reduz latência e overhead de handshake. gRPC sobre HTTP/1.1 não suporta streaming bidirectional.",
      },
    },
    {
      id: "s13",
      title: "Resumo",
      duration: 9000,
      add: [
        "rest_box",
        "grpc_box",
        "vs_lbl",
        "proto_bg",
        "proto_ttl",
        "proto_l0",
        "proto_l1",
        "client_bg",
        "client_ttl",
        "stub_box",
        "h2_bg",
        "server_bg",
        "server_ttl",
        "skel_box",
        "types_bg",
        "types_ttl",
        "type_n0",
        "type_f0",
        "type_n1",
        "type_f1",
        "type_n2",
        "type_f2",
        "type_n3",
        "type_f3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 400,
        },
        placement: "right",
        text: "**gRPC** = Protobuf (.proto schema) + HTTP/2 (streaming, multiplexing) + code generation (stubs). 4 tipos de RPC: Unary, Server Stream, Client Stream, Bidirectional. Interceptors para cross-cutting concerns.",
        why: "Use gRPC em microsserviços internos onde performance e contratos fortes importam. Expose REST ou GraphQL para clientes externos.",
      },
    },
  ],
};

export const grpc = validateExplainer(data);
