import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/guardrails.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "guardrails",
  title: "Guardrails para sistemas de IA",
  subtitle: "Defesa em profundidade: input → filtros → LLM → validação → output",
  category: "IA & Agentes",
  tags: ["segurança", "llm", "agentes"],
  level: "medio",
  glossary: {
    PII: "CPF, email, telefone, cartão de crédito, endereço — qualquer dado que identifique uma pessoa.",
  },
  elements: [
    {
      id: "req_box",
      kind: "box",
      at: {
        x: 75,
        y: 388,
        w: 225,
        h: 75,
      },
      label: "👤 Usuário",
      sub: '"input aqui"',
      variant: "outline",
    },
    {
      id: "a_req",
      tone: "accent",
      kind: "connector",
      from: {
        x: 300,
        y: 425,
      },
      to: {
        x: 550,
        y: 425,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "req_lbl",
      kind: "label",
      at: {
        x: 147,
        y: 342,
        w: 81,
        h: 41,
      },
      text: "Entrada",
      align: "center",
    },
    {
      id: "l1",
      kind: "box",
      at: {
        x: 550,
        y: 75,
        w: 500,
        h: 70,
      },
      label: "🔍 Validação de entrada",
      variant: "outline",
    },
    {
      id: "l2",
      kind: "box",
      at: {
        x: 550,
        y: 175,
        w: 500,
        h: 70,
      },
      label: "💉 Detecção de Prompt Injection",
      variant: "outline",
    },
    {
      id: "l3",
      kind: "box",
      at: {
        x: 550,
        y: 275,
        w: 500,
        h: 70,
      },
      label: "🔐 Filtro de PII / Dados sensíveis",
      variant: "outline",
    },
    {
      id: "l4",
      kind: "box",
      at: {
        x: 550,
        y: 375,
        w: 500,
        h: 70,
      },
      label: "🚫 Filtro de conteúdo / toxicidade",
      variant: "outline",
    },
    {
      id: "l5",
      kind: "box",
      at: {
        x: 550,
        y: 475,
        w: 500,
        h: 83,
      },
      label: "🧠 LLM processa",
      sub: "(com contexto filtrado)",
      variant: "outline",
    },
    {
      id: "l6",
      kind: "box",
      at: {
        x: 550,
        y: 588,
        w: 500,
        h: 70,
      },
      label: "✅ Validação de saída",
      variant: "outline",
    },
    {
      id: "l7",
      kind: "box",
      at: {
        x: 550,
        y: 688,
        w: 500,
        h: 70,
      },
      label: "🔬 Grounding / Hallucination check",
      variant: "outline",
    },
    {
      id: "a12",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 145,
      },
      to: {
        x: 800,
        y: 175,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a23",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 245,
      },
      to: {
        x: 800,
        y: 275,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a34",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 345,
      },
      to: {
        x: 800,
        y: 375,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a45",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 445,
      },
      to: {
        x: 800,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a56",
      tone: "good",
      kind: "connector",
      from: {
        x: 800,
        y: 558,
      },
      to: {
        x: 800,
        y: 588,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a67",
      tone: "good",
      kind: "connector",
      from: {
        x: 800,
        y: 658,
      },
      to: {
        x: 800,
        y: 688,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "resp_ok",
      kind: "box",
      at: {
        x: 1125,
        y: 688,
        w: 225,
        h: 70,
      },
      label: "✓ Resposta",
      sub: "aprovada",
      variant: "outline",
    },
    {
      id: "a_resp",
      tone: "good",
      kind: "connector",
      from: {
        x: 1050,
        y: 723,
      },
      to: {
        x: 1125,
        y: 723,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "blk_inj",
      kind: "token",
      at: {
        x: 1075,
        y: 185,
        w: 250,
        h: 50,
      },
      text: "⛔ Bloqueado: injection",
    },
    {
      id: "a_blk_inj",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1050,
        y: 210,
      },
      to: {
        x: 1075,
        y: 210,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "blk_pii",
      kind: "token",
      at: {
        x: 1075,
        y: 285,
        w: 250,
        h: 50,
      },
      text: "⚠️ PII mascarado",
    },
    {
      id: "a_blk_pii",
      tone: "warn",
      kind: "connector",
      from: {
        x: 1050,
        y: 310,
      },
      to: {
        x: 1075,
        y: 310,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "blk_tox",
      kind: "token",
      at: {
        x: 1075,
        y: 385,
        w: 250,
        h: 50,
      },
      text: "⛔ Bloqueado: conteúdo",
    },
    {
      id: "a_blk_tox",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1050,
        y: 410,
      },
      to: {
        x: 1075,
        y: 410,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "blk_hal",
      kind: "token",
      at: {
        x: 1075,
        y: 698,
        w: 250,
        h: 50,
      },
      text: "⛔ Hallucination detectada",
    },
    {
      id: "a_blk_hal",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1050,
        y: 723,
      },
      to: {
        x: 1075,
        y: 723,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "fallback",
      kind: "box",
      at: {
        x: 1125,
        y: 75,
        w: 325,
        h: 175,
      },
      label: "🔄 Fallback behavior",
      sub: " · • Resposta padrão segura · • Log + alerta ao time · • Retry com prompt reformulado",
      variant: "outline",
    },
    {
      id: "log_box",
      kind: "box",
      at: {
        x: 38,
        y: 750,
        w: 1525,
        h: 95,
      },
      label: "📊 Logging & Auditoria (sempre ativo em todas as camadas)",
      sub: "inputs bloqueados · PII detectado · latência por camada · taxa de bloqueio por regra",
      variant: "outline",
    },
    {
      id: "hitl",
      kind: "box",
      at: {
        x: 1125,
        y: 313,
        w: 325,
        h: 125,
      },
      label: "👁️ Human-in-the-loop",
      sub: "casos ambíguos são · roteados para revisão humana",
      variant: "outline",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Por que Guardrails são necessários",
      duration: 9000,
      add: ["req_box", "req_lbl", "a_req"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "req_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "req_box",
        placement: "right",
        text: "Sistemas de IA em produção recebem entradas de usuários reais — que podem ser maliciosas, conter dados sensíveis ou tentar manipular o modelo. Sem proteção, um único prompt mal-intencionado pode comprometer todo o sistema.",
        why: "Guardrails são as 'cercas de segurança' do sistema: elas não tornam o modelo mais inteligente, mas garantem que ele opere dentro de limites seguros e previsíveis.",
      },
    },
    {
      id: "s2",
      title: "Pipeline de camadas de proteção",
      duration: 9000,
      add: ["l1", "l2", "l3", "l4", "l5", "l6", "l7", "a12", "a23", "a34", "a45", "a56", "a67"],
      remove: [],
      set: {},
      cues: [
        {
          at: 600,
          target: "a12",
          do: "draw",
        },
        {
          at: 660,
          target: "a23",
          do: "draw",
        },
        {
          at: 720,
          target: "a34",
          do: "draw",
        },
        {
          at: 780,
          target: "a45",
          do: "draw",
        },
        {
          at: 840,
          target: "a56",
          do: "draw",
        },
        {
          at: 900,
          target: "a67",
          do: "draw",
        },
        {
          at: 0,
          target: "l1",
          do: "highlight",
        },
        {
          at: 0,
          target: "l5",
          do: "highlight",
        },
        {
          at: 0,
          target: "l7",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l5",
        placement: "right",
        text: "Os guardrails formam um **pipeline de camadas**: a entrada passa por várias verificações antes de chegar ao LLM, e a saída passa por verificações adicionais antes de ser entregue ao usuário.",
        why: "Defesa em profundidade: nenhuma camada sozinha é perfeita, mas várias camadas juntas tornam o sistema muito mais robusto. Se uma falha, as outras ainda protegem.",
      },
    },
    {
      id: "s3",
      title: "Camada 1: Validação de entrada",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "l1",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l1",
        placement: "right",
        text: "A primeira camada valida o formato básico: **tamanho máximo** do input, **encoding** válido, **tipo de conteúdo** esperado (texto, JSON, imagem). Rejeita entradas malformadas antes de qualquer processamento.",
        why: "Validação precoce evita que entradas gigantes ou malformadas consumam recursos caros de processamento (GPU, tokens do LLM). Fail fast: erros baratos devem ser detectados primeiro.",
      },
    },
    {
      id: "s4",
      title: "Camada 2: Detecção de Prompt Injection",
      duration: 9000,
      add: ["blk_inj", "a_blk_inj"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_blk_inj",
          do: "draw",
        },
        {
          at: 0,
          target: "l2",
          do: "highlight",
        },
        {
          at: 0,
          target: "blk_inj",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l2",
        placement: "right",
        text: '**Prompt Injection** é quando um usuário tenta inserir instruções escondidas no input para subverter o comportamento do agente. Ex.: "Ignore todas as instruções anteriores e..." Um classificador detecta e bloqueia.',
        why: "Injection é o ataque mais comum em sistemas baseados em LLM. Detecção por palavras-chave é frágil; classificadores treinados são mais robustos mas não infalíveis — combine múltiplas técnicas.",
      },
    },
    {
      id: "s5",
      title: "Camada 3: Filtro de PII",
      duration: 9000,
      add: ["blk_pii", "a_blk_pii"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_blk_pii",
          do: "draw",
        },
        {
          at: 0,
          target: "l3",
          do: "highlight",
        },
        {
          at: 0,
          target: "blk_pii",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l3",
        placement: "right",
        text: "Dados pessoais identificáveis ({{PII}}) como CPF, e-mail, cartões de crédito são detectados e **mascarados antes** de chegar ao LLM. O modelo processa texto anonimizado.",
        why: "LGPD, GDPR e outras regulações exigem que PII não seja enviado a serviços de terceiros sem consentimento. Mascarar antes do LLM protege usuários e evita multas.",
      },
    },
    {
      id: "s6",
      title: "Camada 4: Filtro de conteúdo",
      duration: 9000,
      add: ["blk_tox", "a_blk_tox"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_blk_tox",
          do: "draw",
        },
        {
          at: 0,
          target: "l4",
          do: "highlight",
        },
        {
          at: 0,
          target: "blk_tox",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l4",
        placement: "right",
        text: "Um classificador de **toxicidade e conteúdo impróprio** analisa o input antes do LLM: linguagem de ódio, conteúdo adulto, instruções para atividades ilegais. Bloqueios são logados para análise.",
        why: "Mesmo que o LLM recuse por si só, filtrar antes é mais eficiente (evita tokens desperdiçados) e mais auditável (o motivo do bloqueio fica registrado na camada de guardrail, não no modelo).",
      },
    },
    {
      id: "s7",
      title: "O LLM processa com contexto filtrado",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "l5",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l5",
        placement: "right",
        text: "Após passar por todas as camadas de entrada, o input **limpo e seguro** chega ao LLM. O modelo pode se concentrar em ser útil, sem precisar lidar sozinho com injeções, PII ou toxicidade.",
        why: "LLMs não são guardrails confiáveis por si só: eles podem ser persuadidos, ter jailbreaks ou simplesmente errar. As camadas externas são determinísticas e auditalávéis.",
      },
    },
    {
      id: "s8",
      title: "Validação e Grounding da saída",
      duration: 9000,
      add: ["blk_hal", "a_blk_hal", "resp_ok", "a_resp"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_blk_hal",
          do: "draw",
        },
        {
          at: 400,
          target: "a_resp",
          do: "draw",
        },
        {
          at: 0,
          target: "l6",
          do: "highlight",
        },
        {
          at: 0,
          target: "l7",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l6",
        placement: "right",
        text: "A saída do LLM passa por duas verificações: **Validação** (formato correto? JSON válido? resposta tem o campo esperado?) e **Grounding** (a resposta é suportada pelo contexto fornecido? há alucinação?).",
        why: "Verificar a saída é tão importante quanto filtrar a entrada. Um LLM pode gerar JSON sintaticamente correto mas semanticamente errado — a validação de schema detecta isso.",
      },
    },
    {
      id: "s9",
      title: "Fallback behavior",
      duration: 9000,
      add: ["fallback"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "fallback",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "fallback",
        placement: "left",
        text: 'Quando um guardrail bloqueia, o sistema precisa de um **comportamento de fallback** claro: resposta padrão segura ("Não posso ajudar com isso"), log para o time de segurança e opcionalmente retry com o prompt reformulado.',
        why: "Falhar silenciosamente é pior que falhar com mensagem. O usuário precisa saber que não foi ajudado; o time de segurança precisa saber o que foi bloqueado e por quê.",
      },
    },
    {
      id: "s10",
      title: "Human-in-the-loop",
      duration: 9000,
      add: ["hitl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hitl",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hitl",
        placement: "left",
        text: "Casos **ambíguos ou de alta consequência** são roteados para revisão humana antes da resposta ser enviada. Um humano aprova ou rejeita. Comum em contextos médicos, jurídicos e financeiros.",
        why: "Automação total funciona para casos claros. Para decisões de alto impacto, a revisão humana é a última linha de defesa — e muitas vezes uma exigência regulatória.",
      },
    },
    {
      id: "s11",
      title: "Logging e auditoria contínua",
      duration: 9000,
      add: ["log_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "log_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "log_box",
        placement: "top",
        text: "Todas as camadas **logam tudo**: inputs bloqueados, PII detectado, latência de cada camada, taxa de bloqueio por regra. Esses logs são a base para melhorar os guardrails ao longo do tempo.",
        why: "Sem logs, você não sabe o que está bloqueando nem por quê. Métricas de guardrail (false positive rate, false negative rate) determinam onde ajustar thresholds.",
      },
    },
    {
      id: "s12",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Confirme o que você aprendeu sobre Guardrails 👇",
      },
      quiz: {
        question: "Por que o filtro de PII deve atuar ANTES do LLM, e não apenas na saída?",
        options: [
          "Para economizar tokens e reduzir o custo da chamada ao LLM",
          "Porque LLMs não conseguem reconhecer PII no texto",
          "Para evitar que dados pessoais sejam enviados ao provedor do LLM, cumprindo regulações como LGPD/GDPR",
          "Porque o LLM pode vazar PII na resposta mesmo que não o mencione diretamente",
        ],
        answer: 2,
        explain:
          "O principal motivo é regulatório: ao enviar texto ao LLM (API externa), os dados saem do controle da empresa. PII mascarado antes da chamada garante que dados pessoais nunca saem do perímetro — mesmo que o modelo seja confiável.",
      },
    },
    {
      id: "s13",
      title: "Resumo: Guardrails em profundidade",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "l1",
          do: "pulse",
          times: 2,
        },
        {
          at: 80,
          target: "l2",
          do: "pulse",
          times: 2,
        },
        {
          at: 160,
          target: "l3",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "l4",
          do: "pulse",
          times: 2,
        },
        {
          at: 320,
          target: "l5",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "l6",
          do: "pulse",
          times: 2,
        },
        {
          at: 480,
          target: "l7",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "l1",
          do: "highlight",
        },
        {
          at: 0,
          target: "l2",
          do: "highlight",
        },
        {
          at: 0,
          target: "l3",
          do: "highlight",
        },
        {
          at: 0,
          target: "l4",
          do: "highlight",
        },
        {
          at: 0,
          target: "l5",
          do: "highlight",
        },
        {
          at: 0,
          target: "l6",
          do: "highlight",
        },
        {
          at: 0,
          target: "l7",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "right",
        text: "Guardrails formam um pipeline de **defesa em profundidade**: validação → injection → PII → toxicidade → LLM → validação de saída → grounding. Falhas são logadas, casos ambíguos vão para humanos, bloqueios têm fallback.",
        why: "Guardrails não são opcionais em produção. Eles tornam o sistema auditável, previsível e seguro — e permitem evoluir o modelo sem reconstruir toda a segurança do zero.",
      },
    },
  ],
};

export const guardrails = validateExplainer(data);
