import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/hashmap.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "hashmap",
  title: "Hash Map por dentro",
  subtitle: "Como uma chave vira um endereço — colisões, encadeamento e resize",
  category: "Algoritmos & Estruturas de Dados",
  tags: ["hash map", "estrutura de dados"],
  level: "intro",
  glossary: {
    "fator de carga": "Razão itens ÷ buckets. Acima de ~0,75 as colisões aumentam e o desempenho cai.",
  },
  elements: [
    {
      id: "key",
      kind: "token",
      at: {
        x: 138,
        y: 385,
        w: 213,
        h: 60,
      },
      text: "“Ana” 🔑",
    },
    {
      id: "hash",
      kind: "box",
      at: {
        x: 450,
        y: 375,
        w: 275,
        h: 80,
      },
      label: "função hash",
      sub: "h(key) % 8",
      variant: "outline",
    },
    {
      id: "a_kh",
      kind: "connector",
      from: {
        x: 356,
        y: 415,
      },
      to: {
        x: 444,
        y: 415,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "calc",
      kind: "label",
      at: {
        x: 402,
        y: 486,
        w: 372,
        h: 41,
      },
      text: "h('Ana') = 1899  →  1899 % 8 = 3",
      align: "center",
      muted: true,
    },
    {
      id: "a_hb",
      tone: "good",
      kind: "connector",
      from: {
        x: 731,
        y: 415,
      },
      to: {
        x: 1048,
        y: 408,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "b0",
      kind: "box",
      at: {
        x: 1063,
        y: 98,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b1",
      kind: "box",
      at: {
        x: 1063,
        y: 190,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b2",
      kind: "box",
      at: {
        x: 1063,
        y: 283,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b3",
      kind: "box",
      at: {
        x: 1063,
        y: 375,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b4",
      kind: "box",
      at: {
        x: 1063,
        y: 468,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b5",
      kind: "box",
      at: {
        x: 1063,
        y: 560,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b6",
      kind: "box",
      at: {
        x: 1063,
        y: 653,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "b7",
      kind: "box",
      at: {
        x: 1063,
        y: 745,
        w: 263,
        h: 65,
      },
      variant: "outline",
    },
    {
      id: "bi0",
      kind: "label",
      at: {
        x: 993,
        y: 109,
        w: 75,
        h: 41,
      },
      text: "0",
      align: "center",
      muted: true,
    },
    {
      id: "bi1",
      kind: "label",
      at: {
        x: 993,
        y: 202,
        w: 75,
        h: 41,
      },
      text: "1",
      align: "center",
      muted: true,
    },
    {
      id: "bi2",
      kind: "label",
      at: {
        x: 993,
        y: 294,
        w: 75,
        h: 41,
      },
      text: "2",
      align: "center",
      muted: true,
    },
    {
      id: "bi3",
      kind: "label",
      at: {
        x: 993,
        y: 387,
        w: 75,
        h: 41,
      },
      text: "3",
      align: "center",
      muted: true,
    },
    {
      id: "bi4",
      kind: "label",
      at: {
        x: 993,
        y: 479,
        w: 75,
        h: 41,
      },
      text: "4",
      align: "center",
      muted: true,
    },
    {
      id: "bi5",
      kind: "label",
      at: {
        x: 993,
        y: 572,
        w: 75,
        h: 41,
      },
      text: "5",
      align: "center",
      muted: true,
    },
    {
      id: "bi6",
      kind: "label",
      at: {
        x: 993,
        y: 664,
        w: 75,
        h: 41,
      },
      text: "6",
      align: "center",
      muted: true,
    },
    {
      id: "bi7",
      kind: "label",
      at: {
        x: 993,
        y: 757,
        w: 75,
        h: 41,
      },
      text: "7",
      align: "center",
      muted: true,
    },
    {
      id: "arr_cap",
      kind: "label",
      at: {
        x: 1014,
        y: 39,
        w: 360,
        h: 41,
      },
      text: "array de buckets (capacidade 8)",
      align: "center",
    },
    {
      id: "e_ana",
      kind: "token",
      at: {
        x: 1080,
        y: 384,
        w: 163,
        h: 48,
      },
      text: "Ana → 30",
    },
    {
      id: "e_beto",
      kind: "token",
      at: {
        x: 1080,
        y: 661,
        w: 163,
        h: 48,
      },
      text: "Beto → 25",
    },
    {
      id: "e_carla",
      kind: "token",
      at: {
        x: 1363,
        y: 384,
        w: 188,
        h: 48,
      },
      text: "Carla → 41",
    },
    {
      id: "e_link",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1245,
        y: 408,
      },
      to: {
        x: 1360,
        y: 408,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "calc2",
      kind: "label",
      at: {
        x: 407,
        y: 529,
        w: 360,
        h: 41,
      },
      text: "h('Carla') % 8 = 3  →  colisão!",
      align: "center",
      muted: true,
    },
    {
      id: "scan",
      kind: "label",
      at: {
        x: 938,
        y: 339,
        w: 512,
        h: 41,
      },
      text: "percorre a lista do bucket até achar a chave",
      align: "center",
      muted: true,
    },
    {
      id: "resize",
      kind: "token",
      at: {
        x: 1088,
        y: 825,
        w: 400,
        h: 55,
      },
      text: "fator de carga alto → dobra p/ 16 e rehash",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que é um Hash Map",
      duration: 8000,
      add: [
        "arr_cap",
        "b0",
        "b1",
        "b2",
        "b3",
        "b4",
        "b5",
        "b6",
        "b7",
        "bi0",
        "bi1",
        "bi2",
        "bi3",
        "bi4",
        "bi5",
        "bi6",
        "bi7",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "b0",
        placement: "left",
        text: "Um **hash map** (dicionário) guarda pares **chave → valor** e promete busca, inserção e remoção em tempo **O(1) médio**.",
        why: "O segredo é não procurar item por item: a própria chave nos diz *onde* o valor está, num array de “gavetas” (buckets).",
      },
    },
    {
      id: "s2",
      title: "O array de buckets",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "arr_cap",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "b4",
        placement: "left",
        text: "Por baixo existe um **array** de tamanho fixo (aqui 8 posições, índices 0–7). Cada posição é um **bucket**, capaz de guardar entradas.",
        why: "Acessar um índice de array é instantâneo. Falta só transformar uma chave qualquer num índice válido — é o papel da função hash.",
      },
    },
    {
      id: "s3",
      title: "A função hash",
      duration: 8000,
      add: ["key", "hash", "a_kh", "calc"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_kh",
          do: "draw",
        },
        {
          at: 0,
          target: "hash",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hash",
        placement: "bottom",
        text: "A **função hash** transforma a chave (“Ana”) num número grande e, com **% 8**, reduz ao intervalo dos índices. Aqui dá **3**.",
        why: "Uma boa hash espalha as chaves de forma uniforme pelos buckets — menos colisões, desempenho mais previsível.",
      },
    },
    {
      id: "s4",
      title: "Inserir no bucket",
      duration: 8000,
      add: ["a_hb", "e_ana"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_hb",
          do: "draw",
        },
        {
          at: 0,
          target: "b3",
          do: "highlight",
        },
        {
          at: 0,
          target: "e_ana",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "e_ana",
        placement: "right",
        text: "O par **“Ana” → 30** é guardado no **bucket 3**. Pronto: inserção em O(1).",
        why: "Para recuperar depois, basta refazer o hash de “Ana”, chegar ao índice 3 e ler o valor. Nada de varrer o array todo.",
      },
    },
    {
      id: "s5",
      title: "Mais uma chave",
      duration: 8000,
      add: ["e_beto"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "b6",
          do: "highlight",
        },
        {
          at: 0,
          target: "e_beto",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "e_beto",
        placement: "right",
        text: "Outra chave, outro índice: **“Beto” → 25** cai no **bucket 6**. Chaves diferentes costumam ir para buckets diferentes.",
        why: "Enquanto cada chave cai num bucket próprio, tudo é O(1) — leitura e escrita diretas.",
      },
    },
    {
      id: "s6",
      title: "Colisão!",
      duration: 8000,
      add: ["calc2", "e_carla", "e_link"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "e_link",
          do: "draw",
        },
        {
          at: 0,
          target: "b3",
          do: "highlight",
        },
        {
          at: 0,
          target: "e_carla",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "e_carla",
        placement: "bottom",
        text: "Duas chaves podem gerar o **mesmo índice**: “Carla” também dá 3. Isso é uma **colisão**. A solução clássica é **encadear**: o bucket vira uma lista.",
        why: "Colisões são inevitáveis (há infinitas chaves para 8 buckets). O importante é resolvê-las sem perder dados — aqui, ligando as entradas numa lista.",
      },
    },
    {
      id: "s7",
      title: "Buscar uma chave",
      duration: 8000,
      add: ["scan"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "b3",
          do: "highlight",
        },
        {
          at: 0,
          target: "e_ana",
          do: "highlight",
        },
        {
          at: 0,
          target: "e_carla",
          do: "highlight",
        },
        {
          at: 0,
          target: "scan",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "scan",
        placement: "left",
        text: 'Para `get("Carla")`: refaz o hash → índice 3 → **percorre a lista** daquele bucket comparando as chaves até achar.',
        why: "Com poucas colisões, a lista é curtíssima (1–2 itens), então a busca continua praticamente O(1). Com muitas, degrada para O(n).",
      },
    },
    {
      id: "s8",
      title: "Resize & rehash",
      duration: 8000,
      add: ["resize"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "resize",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "resize",
        placement: "top",
        text: "Quando o {{fator de carga}} (itens ÷ buckets) passa de um limite (~0,75), o map **dobra o array** e **recalcula o índice** de tudo (rehash).",
        why: "Mais buckets = menos colisões = listas curtas. É isso que mantém o O(1) médio mesmo com o mapa crescendo.",
      },
    },
    {
      id: "s9",
      title: "Teste rápido",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "hash",
        placement: "bottom",
        text: "Fixe o conceito de colisão 👇",
      },
      quiz: {
        question: "O que é uma “colisão” num hash map?",
        options: [
          "Quando duas chaves diferentes geram o mesmo índice",
          "Quando o array de buckets fica completamente cheio",
          "Quando uma chave procurada não existe",
          "Quando o valor armazenado é nulo",
        ],
        answer: 0,
        explain:
          "Há infinitas chaves para um número finito de buckets, então colisões são inevitáveis. Resolvem-se, por exemplo, encadeando as entradas numa lista.",
      },
    },
    {
      id: "s10",
      title: "Resumo",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hash",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "b3",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "key",
          do: "highlight",
        },
        {
          at: 0,
          target: "hash",
          do: "highlight",
        },
        {
          at: 0,
          target: "b3",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "hash",
        placement: "bottom",
        text: "Receita do hash map: **chave → hash → índice → bucket**. Colisões viram listas; quando enche, ele cresce e refaz o hash.",
        why: "É por isso que dicionários/objetos são tão rápidos: a chave “calcula” o endereço do valor, em vez de procurá-lo.",
      },
    },
  ],
};

export const hashmap = validateExplainer(data);
