import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/http.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "http",
  title: "O ciclo de uma requisição HTTP",
  subtitle: "Da URL digitada até a página renderizada",
  category: "Web & Protocolos",
  tags: ["http", "web"],
  level: "intro",
  glossary: {
    TTL: "Time To Live: por quantos segundos a resposta do DNS pode ser reutilizada antes de perguntar de novo.",
  },
  elements: [
    {
      id: "cli",
      kind: "box",
      at: {
        x: 194,
        y: 45,
        w: 238,
        h: 58,
      },
      label: "🖥️ Navegador (cliente)",
      variant: "outline",
    },
    {
      id: "dnss",
      kind: "box",
      at: {
        x: 688,
        y: 45,
        w: 238,
        h: 58,
      },
      label: "🌐 Servidor DNS",
      variant: "outline",
    },
    {
      id: "srv",
      kind: "box",
      at: {
        x: 1169,
        y: 45,
        w: 238,
        h: 58,
      },
      label: "🗄️ Servidor web",
      variant: "outline",
    },
    {
      id: "ll_c",
      kind: "connector",
      from: {
        x: 313,
        y: 105,
      },
      to: {
        x: 313,
        y: 863,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_d",
      kind: "connector",
      from: {
        x: 806,
        y: 105,
      },
      to: {
        x: 806,
        y: 863,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_s",
      kind: "connector",
      from: {
        x: 1288,
        y: 105,
      },
      to: {
        x: 1288,
        y: 863,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "url",
      kind: "box",
      at: {
        x: 125,
        y: 138,
        w: 375,
        h: 50,
      },
      label: "https://www.exemplo.com/index.html",
      variant: "outline",
    },
    {
      id: "m_dnsq",
      tone: "warn",
      kind: "connector",
      from: {
        x: 313,
        y: 263,
      },
      to: {
        x: 806,
        y: 263,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_dnsq_l",
      kind: "label",
      at: {
        x: 432,
        y: 227,
        w: 256,
        h: 41,
      },
      text: "1 · A? www.exemplo.com",
      align: "center",
      muted: true,
    },
    {
      id: "m_dnsr",
      tone: "warn",
      kind: "connector",
      from: {
        x: 806,
        y: 338,
      },
      to: {
        x: 313,
        y: 338,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_dnsr_l",
      kind: "label",
      at: {
        x: 461,
        y: 302,
        w: 198,
        h: 41,
      },
      text: "2 · 93.184.216.34",
      align: "center",
      muted: true,
    },
    {
      id: "m_tcp",
      tone: "accent",
      kind: "connector",
      from: {
        x: 313,
        y: 438,
      },
      to: {
        x: 1288,
        y: 438,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_tcp_l",
      kind: "label",
      at: {
        x: 608,
        y: 402,
        w: 384,
        h: 41,
      },
      text: "3 · TCP connect (SYN/SYN-ACK/ACK)",
      align: "center",
      muted: true,
    },
    {
      id: "m_tls",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 313,
        y: 525,
      },
      to: {
        x: 1288,
        y: 525,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_tls_l",
      kind: "label",
      at: {
        x: 631,
        y: 489,
        w: 337,
        h: 41,
      },
      text: "4 · TLS handshake 🔒 (chaves)",
      align: "center",
      muted: true,
    },
    {
      id: "m_get",
      tone: "good",
      kind: "connector",
      from: {
        x: 313,
        y: 625,
      },
      to: {
        x: 1288,
        y: 625,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_get_l",
      kind: "label",
      at: {
        x: 585,
        y: 589,
        w: 430,
        h: 41,
      },
      text: "5 · GET /index.html  ·  Host, Accept…",
      align: "center",
      muted: true,
    },
    {
      id: "proc",
      kind: "box",
      at: {
        x: 1175,
        y: 675,
        w: 225,
        h: 48,
      },
      label: "monta a resposta",
      variant: "outline",
    },
    {
      id: "m_resp",
      tone: "hot",
      kind: "connector",
      from: {
        x: 1288,
        y: 788,
      },
      to: {
        x: 313,
        y: 788,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_resp_l",
      kind: "label",
      at: {
        x: 643,
        y: 752,
        w: 314,
        h: 41,
      },
      text: "6 · 200 OK + headers + HTML",
      align: "center",
      muted: true,
    },
    {
      id: "status",
      kind: "token",
      at: {
        x: 225,
        y: 825,
        w: 175,
        h: 48,
      },
      text: "200 OK ✓",
    },
    {
      id: "d_dnsq",
      tone: "warn",
      kind: "box",
      at: {
        x: 301,
        y: 251,
        w: 23,
        h: 23,
      },
      variant: "outline",
    },
    {
      id: "d_get",
      tone: "good",
      kind: "box",
      at: {
        x: 301,
        y: 614,
        w: 23,
        h: 23,
      },
      variant: "outline",
    },
    {
      id: "d_resp",
      tone: "hot",
      kind: "box",
      at: {
        x: 1276,
        y: 776,
        w: 23,
        h: 23,
      },
      variant: "outline",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Você digita a URL",
      duration: 8000,
      add: ["cli", "ll_c", "url"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "url",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "url",
        placement: "bottom",
        text: "Tudo começa quando você pede **https://www.exemplo.com/index.html**. A URL tem esquema (https), host (www.exemplo.com) e caminho (/index.html).",
        why: "O navegador precisa descobrir *onde* está esse host e *como* falar com ele antes de pedir a página.",
      },
    },
    {
      id: "s2",
      title: "DNS: nome → IP",
      duration: 8000,
      add: ["dnss", "ll_d", "m_dnsq", "m_dnsq_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_dnsq",
          do: "move",
          by: {
            x: 0,
            y: 0,
          },
        },
        {
          at: 0,
          target: "m_dnsq",
          do: "draw",
        },
        {
          at: 60,
          target: "d_dnsq",
          do: "move",
          by: {
            x: 494,
            y: 0,
          },
        },
        {
          at: 0,
          target: "d_dnsq",
          do: "show",
        },
        {
          at: 0,
          target: "dnss",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_dnsq_l",
        placement: "bottom",
        text: "O nome **www.exemplo.com** não serve para rotear pacotes. O navegador pergunta ao **DNS** qual é o endereço IP correspondente.",
        why: "A internet entrega pacotes por **endereço IP**, não por nome. O DNS é a “lista telefônica”.",
      },
    },
    {
      id: "s3",
      title: "DNS responde o IP",
      duration: 8000,
      add: ["m_dnsr", "m_dnsr_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_dnsr",
          do: "draw",
        },
      ],
      caption: {
        anchor: "m_dnsr_l",
        placement: "bottom",
        text: "O DNS devolve o **IP** (ex.: 93.184.216.34). O resultado fica em **cache** por um tempo ({{TTL}}).",
        why: "Com o IP em mãos, o navegador já pode abrir uma conexão até o servidor.",
      },
    },
    {
      id: "s4",
      title: "Conexão TCP",
      duration: 8000,
      add: ["srv", "ll_s", "m_tcp", "m_tcp_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_tcp",
          do: "draw",
        },
        {
          at: 0,
          target: "srv",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_tcp_l",
        placement: "bottom",
        text: "O navegador abre uma conexão **TCP** com o servidor por meio do **three-way handshake** (SYN → SYN-ACK → ACK).",
        why: "TCP garante entrega confiável e em ordem. (Veja o explicador de TCP/IP para o detalhe do handshake.)",
      },
    },
    {
      id: "s5",
      title: "TLS (o cadeado 🔒)",
      duration: 8000,
      add: ["m_tls", "m_tls_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_tls",
          do: "draw",
        },
      ],
      caption: {
        anchor: "m_tls_l",
        placement: "bottom",
        text: "Como é **https**, cliente e servidor negociam o **TLS**: validam o certificado e combinam uma chave de sessão para criptografar tudo.",
        why: "Sem TLS, qualquer um no caminho leria/alteraria os dados. O cadeado do navegador = TLS ativo.",
      },
    },
    {
      id: "s6",
      title: "Requisição HTTP",
      duration: 8000,
      add: ["m_get", "m_get_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_get",
          do: "move",
          by: {
            x: 0,
            y: 0,
          },
        },
        {
          at: 0,
          target: "m_get",
          do: "draw",
        },
        {
          at: 60,
          target: "d_get",
          do: "move",
          by: {
            x: 975,
            y: 0,
          },
        },
        {
          at: 0,
          target: "d_get",
          do: "show",
        },
        {
          at: 0,
          target: "m_get_l",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_get_l",
        placement: "top",
        text: "Agora sim o pedido HTTP: **método** (GET), **caminho** (/index.html) e **headers** (Host, Accept, Cookie, User-Agent…).",
        why: "Os headers descrevem o que o cliente quer e quem ele é; o método diz a ação (GET lê, POST envia, etc.).",
      },
    },
    {
      id: "s7",
      title: "Servidor processa",
      duration: 8000,
      add: ["proc"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "proc",
          do: "highlight",
        },
        {
          at: 0,
          target: "srv",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "proc",
        placement: "top",
        text: "O servidor recebe a requisição, executa a lógica (roteamento, banco de dados, template…) e **monta a resposta**.",
        why: "É aqui que back-end, frameworks e bancos entram. Para o cliente, isso é uma caixa-preta: ele só espera a resposta.",
      },
    },
    {
      id: "s8",
      title: "Resposta HTTP",
      duration: 8000,
      add: ["m_resp", "m_resp_l", "status"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_resp",
          do: "move",
          by: {
            x: 0,
            y: 0,
          },
        },
        {
          at: 0,
          target: "m_resp",
          do: "draw",
        },
        {
          at: 60,
          target: "d_resp",
          do: "move",
          by: {
            x: -975,
            y: 0,
          },
        },
        {
          at: 0,
          target: "d_resp",
          do: "show",
        },
        {
          at: 0,
          target: "status",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_resp_l",
        placement: "top",
        text: "Volta a resposta: uma **linha de status** (200 OK, 404, 500…), **headers** (Content-Type, Cache-Control…) e o **corpo** (o HTML).",
        why: "O código de status resume o resultado; os headers dizem como tratar o corpo (tipo, tamanho, cache).",
      },
    },
    {
      id: "s9",
      title: "Teste rápido",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "dnss",
        placement: "bottom",
        text: "Antes de fechar, confira um ponto-chave 👇",
      },
      quiz: {
        question: "Para que serve a etapa de DNS numa requisição?",
        options: [
          "Criptografar a conexão com o servidor",
          "Traduzir o nome (www.exemplo.com) para um endereço IP",
          "Comprimir o HTML antes de enviar",
          "Guardar os cookies do usuário",
        ],
        answer: 1,
        explain:
          "A internet roteia por IP, não por nome. O DNS resolve o nome para o IP antes de qualquer conexão acontecer.",
      },
    },
    {
      id: "s10",
      title: "Renderiza e (talvez) cacheia",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_dnsq",
          do: "pulse",
          times: 2,
        },
        {
          at: 90,
          target: "m_dnsr",
          do: "pulse",
          times: 2,
        },
        {
          at: 180,
          target: "m_tcp",
          do: "pulse",
          times: 2,
        },
        {
          at: 270,
          target: "m_tls",
          do: "pulse",
          times: 2,
        },
        {
          at: 360,
          target: "m_get",
          do: "pulse",
          times: 2,
        },
        {
          at: 450,
          target: "m_resp",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "cli",
          do: "highlight",
        },
        {
          at: 0,
          target: "url",
          do: "highlight",
        },
        {
          at: 0,
          target: "status",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 250,
          y: 360,
        },
        placement: "right",
        text: "O navegador **interpreta o HTML**, descobre CSS/JS/imagens e repete o ciclo para cada um. Recursos podem vir do **cache**, sem nova ida ao servidor.",
        why: "Resumo do fluxo: **URL → DNS → TCP → TLS → request → resposta → render**. Esse mesmo ciclo se repete o tempo todo na web.",
      },
    },
  ],
};

export const http = validateExplainer(data);
