import type { Explainer } from "@/schema/explainer";

export interface ContentMeta {
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  level: "intro" | "medio" | "avancado";
  loader: () => Promise<Explainer>;
}

/**
 * Registro central: metadados leves (para a home, sem puxar o conteúdo todo)
 * + carregador dynamic import (code-split — só baixa o explainer que o usuário abrir).
 */
export const REGISTRY: ContentMeta[] = [
  {
    slug: "como-um-llm-funciona",
    title: "Como um LLM funciona",
    subtitle: "Do texto ao próximo token, passo a passo",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./como-um-llm-funciona")).comoUmLlmFunciona,
  },
  {
    slug: "tls-1-3-na-pratica",
    title: "TLS 1.3 na prática",
    subtitle: "O aperto de mão que protege toda conexão HTTPS",
    category: "Segurança & Autenticação",
    level: "avancado",
    loader: async () => (await import("./tls-1-3-na-pratica")).tls13NaPratica,
  },
  {
    slug: "recursao",
    title: "Recursão e a pilha de chamadas",
    subtitle: "fact(4): empilhar as chamadas e desempilhar os retornos",
    category: "Algoritmos & Estruturas de Dados",
    level: "intro",
    loader: async () => (await import("./recursao")).recursao,
  },
  {
    slug: "api-keys",
    title: "API Keys",
    subtitle: "",
    category: "Segurança & Autenticação",
    level: "intro",
    loader: async () => (await import("./api-keys")).apiKeys,
  },
  {
    slug: "blockchain",
    title: "Blockchain",
    subtitle: "",
    category: "Sistemas Distribuídos",
    level: "avancado",
    loader: async () => (await import("./blockchain")).blockchain,
  },
  {
    slug: "consistent-hashing",
    title: "Consistent Hashing",
    subtitle: "",
    category: "Sistemas Distribuídos",
    level: "avancado",
    loader: async () => (await import("./consistent-hashing")).consistentHashing,
  },
  {
    slug: "crypto",
    title: "Criptografia — Simétrica, Assimétrica e Hashes",
    subtitle: "",
    category: "Segurança & Autenticação",
    level: "avancado",
    loader: async () => (await import("./crypto")).crypto,
  },
  {
    slug: "kafka-schema",
    title: "Kafka Serialization + Schema Registry",
    subtitle: "",
    category: "Mensageria & Processamento Async",
    level: "avancado",
    loader: async () => (await import("./kafka-schema")).kafkaSchema,
  },
  {
    slug: "load-balancer",
    title: "Load Balancer — L4, L7 e Algoritmos",
    subtitle: "",
    category: "Infraestrutura & Cloud",
    level: "intro",
    loader: async () => (await import("./load-balancer")).loadBalancer,
  },
  {
    slug: "mfa",
    title: "MFA / 2FA — Autenticação Multifator",
    subtitle: "",
    category: "Segurança & Autenticação",
    level: "medio",
    loader: async () => (await import("./mfa")).mfa,
  },
  {
    slug: "sessions",
    title: "Sessions & Cookies",
    subtitle: "",
    category: "Segurança & Autenticação",
    level: "intro",
    loader: async () => (await import("./sessions")).sessions,
  },
  {
    slug: "sso",
    title: "SSO — Single Sign-On",
    subtitle: "",
    category: "Segurança & Autenticação",
    level: "avancado",
    loader: async () => (await import("./sso")).sso,
  },
  {
    slug: "tls",
    title: "TLS / mTLS — Handshake e Autenticação Mútua",
    subtitle: "",
    category: "Web & Protocolos",
    level: "avancado",
    loader: async () => (await import("./tls")).tls,
  },
  {
    slug: "async-redis-kafka",
    title: "Async com Redis / Kafka",
    subtitle: "Fire-and-Forget · 202 Accepted · Dead Letter Queue · Idempotência",
    category: "Mensageria & Processamento Async",
    level: "medio",
    loader: async () => (await import("./async-redis-kafka")).asyncRedisKafka,
  },
  {
    slug: "eks",
    title: "Amazon EKS",
    subtitle: "K8s Gerenciado · Fargate · IRSA · Node Groups · Add-ons",
    category: "Infraestrutura & Cloud",
    level: "avancado",
    loader: async () => (await import("./eks")).eks,
  },
  {
    slug: "ingress",
    title: "Kubernetes Ingress",
    subtitle: "Host-based · Path-based · TLS · Ingress Controller",
    category: "Infraestrutura & Cloud",
    level: "medio",
    loader: async () => (await import("./ingress")).ingress,
  },
  {
    slug: "iso8583",
    title: "ISO 8583",
    subtitle: "MTI · Bitmap · Data Elements · Auth Flow · Settlement",
    category: "Web & Protocolos",
    level: "avancado",
    loader: async () => (await import("./iso8583")).iso8583,
  },
  {
    slug: "kubernetes",
    title: "Kubernetes",
    subtitle: "Control Plane · Worker Nodes · Pods · Services · Deployments",
    category: "Infraestrutura & Cloud",
    level: "avancado",
    loader: async () => (await import("./kubernetes")).kubernetes,
  },
  {
    slug: "rds",
    title: "Amazon RDS",
    subtitle: "Multi-AZ · Read Replicas · PITR · Managed Database",
    category: "Infraestrutura & Cloud",
    level: "medio",
    loader: async () => (await import("./rds")).rds,
  },
  {
    slug: "virtual-threads",
    title: "Virtual Threads Java",
    subtitle: "Project Loom · Carrier Threads · Structured Concurrency · Java 21",
    category: "Runtime & Linguagens",
    level: "avancado",
    loader: async () => (await import("./virtual-threads")).virtualThreads,
  },
  {
    slug: "rate-limit",
    title: "Rate Limiting",
    subtitle: "Token Bucket · Leaky Bucket · Sliding Window",
    category: "Infraestrutura & Cloud",
    level: "medio",
    loader: async () => (await import("./rate-limit")).rateLimit,
  },
  {
    slug: "grpc",
    title: "gRPC",
    subtitle: "Protocol Buffers · HTTP/2 · 4 RPC Types · Code Generation",
    category: "Web & Protocolos",
    level: "medio",
    loader: async () => (await import("./grpc")).grpc,
  },
  {
    slug: "jwt",
    title: "JWT — JSON Web Tokens",
    subtitle: "Header · Payload · Signature · RS256 · Stateless Verification · Refresh Pattern",
    category: "Segurança & Autenticação",
    level: "medio",
    loader: async () => (await import("./jwt")).jwt,
  },
  {
    slug: "oauth",
    title: "OAuth 2.0 / OIDC",
    subtitle: "Authorization Code Flow · PKCE · Access Token · Refresh Token · OpenID Connect",
    category: "Segurança & Autenticação",
    level: "avancado",
    loader: async () => (await import("./oauth")).oauth,
  },
  {
    slug: "websocket",
    title: "WebSockets",
    subtitle: "Full-duplex · Frames · Opcodes · Heartbeat · RFC 6455",
    category: "Web & Protocolos",
    level: "medio",
    loader: async () => (await import("./websocket")).websocket,
  },
  {
    slug: "context-eng",
    title: "Engenharia de Contexto",
    subtitle: "Gerenciar o que o LLM vê: tokens, hierarquia e estratégias",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./context-eng")).contextEng,
  },
  {
    slug: "guardrails",
    title: "Guardrails para sistemas de IA",
    subtitle: "Defesa em profundidade: input → filtros → LLM → validação → output",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./guardrails")).guardrails,
  },
  {
    slug: "hashmap",
    title: "Hash Map por dentro",
    subtitle: "Como uma chave vira um endereço — colisões, encadeamento e resize",
    category: "Algoritmos & Estruturas de Dados",
    level: "intro",
    loader: async () => (await import("./hashmap")).hashmap,
  },
  {
    slug: "mcp",
    title: "Model Context Protocol (MCP)",
    subtitle: "Como LLMs se conectam a ferramentas e dados externos",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./mcp")).mcp,
  },
  {
    slug: "prompt-eng",
    title: "Engenharia de Prompt",
    subtitle: "Zero-shot, Few-shot, CoT, ReAct e boas práticas",
    category: "IA & Agentes",
    level: "intro",
    loader: async () => (await import("./prompt-eng")).promptEng,
  },
  {
    slug: "sdd",
    title: "Spec-Driven Development (SDD)",
    subtitle: "Spec → IA gera → Testes validam → Feedback → Spec evolui",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./sdd")).sdd,
  },
  {
    slug: "skills",
    title: "Skills — Capacidades de Agentes de IA",
    subtitle: "Registry, anatomia, trigger, execução e composição",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./skills")).skills,
  },
  {
    slug: "specs",
    title: "Specs para Agentes de IA",
    subtitle: "O documento que define comportamento, tools, contratos e exemplos",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./specs")).specs,
  },
  {
    slug: "subagents",
    title: "SubAgentes — Arquitetura multi-agente",
    subtitle: "Orquestrador, especialização, paralelismo e agregação de resultados",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./subagents")).subagents,
  },
  {
    slug: "git",
    title: "Git: do `add` ao `push`",
    subtitle: "As quatro áreas e o caminho de uma mudança",
    category: "Ferramentas",
    level: "intro",
    loader: async () => (await import("./git")).git,
  },
  {
    slug: "busca-binaria",
    title: "Busca Binária",
    subtitle: "Dividir para conquistar: achar um valor em O(log n)",
    category: "Algoritmos & Estruturas de Dados",
    level: "intro",
    loader: async () => (await import("./busca-binaria")).buscaBinaria,
  },
  {
    slug: "http",
    title: "O ciclo de uma requisição HTTP",
    subtitle: "Da URL digitada até a página renderizada",
    category: "Web & Protocolos",
    level: "intro",
    loader: async () => (await import("./http")).http,
  },
  {
    slug: "tcp",
    title: "TCP/IP: handshake e transporte confiável",
    subtitle: "Como bytes chegam inteiros e em ordem sobre uma rede que perde pacotes",
    category: "Web & Protocolos",
    level: "intro",
    loader: async () => (await import("./tcp")).tcp,
  },
  {
    slug: "circuit-breaker",
    title: "Circuit Breaker — Resiliência de serviços",
    subtitle: "CLOSED → OPEN → HALF-OPEN: evitar falhas em cascata",
    category: "Infraestrutura & Cloud",
    level: "medio",
    loader: async () => (await import("./circuit-breaker")).circuitBreaker,
  },
  {
    slug: "rag",
    title: "RAG — Retrieval-Augmented Generation",
    subtitle: "Como fundamentar respostas de LLMs em dados reais",
    category: "IA & Agentes",
    level: "medio",
    loader: async () => (await import("./rag")).rag,
  },
  {
    slug: "transformer",
    title: "Como funciona uma rede Transformer",
    subtitle: "Do texto cru à próxima palavra — passo a passo",
    category: "IA & Agentes",
    level: "avancado",
    loader: async () => (await import("./transformer")).transformer,
  },
];

export const SLUGS = REGISTRY.map((e) => e.slug);

export function loaderFor(slug: string): (() => Promise<Explainer>) | undefined {
  return REGISTRY.find((e) => e.slug === slug)?.loader;
}
