import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/jwt.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "jwt",
  title: "JWT — JSON Web Tokens",
  subtitle: "Header · Payload · Signature · RS256 · Stateless Verification · Refresh Pattern",
  category: "Segurança & Autenticação",
  tags: ["jwt", "auth", "token"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "band_h",
      kind: "box",
      at: {
        x: 25,
        y: 63,
        w: 638,
        h: 80,
      },
      variant: "outline",
    },
    {
      id: "band_h_t",
      kind: "label",
      at: {
        x: 43,
        y: 59,
        w: 75,
        h: 41,
      },
      text: "HEADER",
      align: "start",
    },
    {
      id: "band_h_v",
      kind: "label",
      at: {
        x: 43,
        y: 89,
        w: 419,
        h: 41,
      },
      text: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9",
      align: "start",
      muted: true,
    },
    {
      id: "band_p",
      kind: "box",
      at: {
        x: 25,
        y: 150,
        w: 638,
        h: 80,
      },
      variant: "outline",
    },
    {
      id: "band_p_t",
      kind: "label",
      at: {
        x: 43,
        y: 147,
        w: 81,
        h: 41,
      },
      text: "PAYLOAD",
      align: "start",
    },
    {
      id: "band_p_v",
      kind: "label",
      at: {
        x: 43,
        y: 177,
        w: 430,
        h: 41,
      },
      text: "eyJzdWIiOiJ1c2VyXzQyIiwiZXhwIjoxNzIw…",
      align: "start",
      muted: true,
    },
    {
      id: "band_s",
      kind: "box",
      at: {
        x: 25,
        y: 238,
        w: 638,
        h: 80,
      },
      variant: "outline",
    },
    {
      id: "band_s_t",
      kind: "label",
      at: {
        x: 43,
        y: 234,
        w: 105,
        h: 41,
      },
      text: "SIGNATURE",
      align: "start",
    },
    {
      id: "band_s_v",
      kind: "label",
      at: {
        x: 43,
        y: 264,
        w: 419,
        h: 41,
      },
      text: "SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_…",
      align: "start",
      muted: true,
    },
    {
      id: "sep1",
      kind: "label",
      at: {
        x: 200,
        y: 127,
        w: 75,
        h: 41,
      },
      text: ".",
      align: "center",
    },
    {
      id: "sep2",
      kind: "label",
      at: {
        x: 413,
        y: 127,
        w: 75,
        h: 41,
      },
      text: ".",
      align: "center",
    },
    {
      id: "hdr_bg",
      kind: "box",
      at: {
        x: 25,
        y: 340,
        w: 638,
        h: 120,
      },
      variant: "outline",
    },
    {
      id: "hdr_ttl",
      kind: "label",
      at: {
        x: 251,
        y: 342,
        w: 186,
        h: 41,
      },
      text: "Header (decoded)",
      align: "center",
    },
    {
      id: "hdr_1",
      kind: "label",
      at: {
        x: 43,
        y: 372,
        w: 75,
        h: 41,
      },
      text: "{",
      align: "start",
      muted: true,
    },
    {
      id: "hdr_2",
      kind: "label",
      at: {
        x: 43,
        y: 394,
        w: 465,
        h: 41,
      },
      text: '  "alg": "RS256",   // signing algorithm',
      align: "start",
      muted: true,
    },
    {
      id: "hdr_3",
      kind: "label",
      at: {
        x: 43,
        y: 417,
        w: 163,
        h: 41,
      },
      text: '  "typ": "JWT"',
      align: "start",
      muted: true,
    },
    {
      id: "hdr_4",
      kind: "label",
      at: {
        x: 43,
        y: 439,
        w: 75,
        h: 41,
      },
      text: "}",
      align: "start",
      muted: true,
    },
    {
      id: "pay_bg",
      kind: "box",
      at: {
        x: 25,
        y: 470,
        w: 638,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "pay_ttl",
      kind: "label",
      at: {
        x: 198,
        y: 474,
        w: 291,
        h: 41,
      },
      text: "Payload — Standard Claims",
      align: "center",
    },
    {
      id: "pay_1",
      kind: "label",
      at: {
        x: 43,
        y: 504,
        w: 326,
        h: 41,
      },
      text: '{ "iss": "auth.example.com",',
      align: "start",
      muted: true,
    },
    {
      id: "pay_2",
      kind: "label",
      at: {
        x: 43,
        y: 529,
        w: 221,
        h: 41,
      },
      text: '  "sub": "user_42",',
      align: "start",
      muted: true,
    },
    {
      id: "pay_3",
      kind: "label",
      at: {
        x: 43,
        y: 554,
        w: 314,
        h: 41,
      },
      text: '  "aud": "api.example.com",',
      align: "start",
      muted: true,
    },
    {
      id: "pay_4",
      kind: "label",
      at: {
        x: 43,
        y: 579,
        w: 453,
        h: 41,
      },
      text: '  "exp": 1720000900,  // expires (Unix)',
      align: "start",
      muted: true,
    },
    {
      id: "pay_5",
      kind: "label",
      at: {
        x: 43,
        y: 604,
        w: 395,
        h: 41,
      },
      text: '  "iat": 1720000000,  // issued at',
      align: "start",
      muted: true,
    },
    {
      id: "pay_6",
      kind: "label",
      at: {
        x: 43,
        y: 629,
        w: 465,
        h: 41,
      },
      text: '  "jti": "abc-123",   // unique token ID',
      align: "start",
      muted: true,
    },
    {
      id: "pay_7",
      kind: "label",
      at: {
        x: 43,
        y: 654,
        w: 419,
        h: 41,
      },
      text: '  "role": "admin" }  // custom claim',
      align: "start",
      muted: true,
    },
    {
      id: "pay_warn",
      kind: "label",
      at: {
        x: -28,
        y: 687,
        w: 744,
        h: 41,
      },
      text: "⚠️  Payload is base64 encoded, not encrypted — visible to anyone",
      align: "center",
      muted: true,
    },
    {
      id: "sig_bg",
      kind: "box",
      at: {
        x: 25,
        y: 730,
        w: 638,
        h: 125,
      },
      variant: "outline",
    },
    {
      id: "sig_ttl",
      kind: "label",
      at: {
        x: 245,
        y: 732,
        w: 198,
        h: 41,
      },
      text: "Signature (RS256)",
      align: "center",
    },
    {
      id: "sig_1",
      kind: "label",
      at: {
        x: 43,
        y: 762,
        w: 75,
        h: 41,
      },
      text: "Sign(",
      align: "start",
      muted: true,
    },
    {
      id: "sig_2",
      kind: "label",
      at: {
        x: 43,
        y: 787,
        w: 546,
        h: 41,
      },
      text: '  base64url(header) + "." + base64url(payload),',
      align: "start",
      muted: true,
    },
    {
      id: "sig_3",
      kind: "label",
      at: {
        x: 43,
        y: 812,
        w: 477,
        h: 41,
      },
      text: "  privateKey  // RS256 = RSA with SHA-256",
      align: "start",
      muted: true,
    },
    {
      id: "sig_4",
      kind: "label",
      at: {
        x: 43,
        y: 837,
        w: 75,
        h: 41,
      },
      text: ")",
      align: "start",
      muted: true,
    },
    {
      id: "ver_bg",
      kind: "box",
      at: {
        x: 700,
        y: 50,
        w: 875,
        h: 400,
      },
      variant: "outline",
    },
    {
      id: "ver_ttl",
      kind: "label",
      at: {
        x: 992,
        y: 57,
        w: 291,
        h: 41,
      },
      text: "Verification Flow (RS256)",
      align: "center",
    },
    {
      id: "ver_cli",
      kind: "box",
      at: {
        x: 725,
        y: 100,
        w: 163,
        h: 58,
      },
      label: "Client",
      variant: "outline",
    },
    {
      id: "ver_srv",
      kind: "box",
      at: {
        x: 725,
        y: 350,
        w: 163,
        h: 58,
      },
      label: "Server",
      variant: "outline",
    },
    {
      id: "ver_pk",
      kind: "box",
      at: {
        x: 1250,
        y: 175,
        w: 300,
        h: 200,
      },
      label: "🔑 Public Key",
      sub: "(JWKS endpoint) · RS256 verify only",
      variant: "outline",
    },
    {
      id: "ver_a1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 888,
        y: 129,
      },
      to: {
        x: 1225,
        y: 129,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ver_a1l",
      kind: "label",
      at: {
        x: 987,
        y: 92,
        w: 140,
        h: 41,
      },
      text: "Bearer <JWT>",
      align: "center",
      muted: true,
    },
    {
      id: "ver_a2",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 888,
        y: 366,
      },
      to: {
        x: 1225,
        y: 366,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ver_a2l",
      kind: "label",
      at: {
        x: 905,
        y: 329,
        w: 302,
        h: 41,
      },
      text: "hash(hdr+pay) compare sig?",
      align: "center",
      muted: true,
    },
    {
      id: "ver_a3",
      tone: "good",
      kind: "connector",
      from: {
        x: 1225,
        y: 275,
      },
      to: {
        x: 888,
        y: 379,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ver_a3l",
      kind: "label",
      at: {
        x: 946,
        y: 287,
        w: 221,
        h: 41,
      },
      text: "✓ valid / ✗ invalid",
      align: "center",
      muted: true,
    },
    {
      id: "ver_note1",
      kind: "label",
      at: {
        x: 925,
        y: 192,
        w: 291,
        h: 41,
      },
      text: "1. Split JWT into 3 parts",
      align: "start",
      muted: true,
    },
    {
      id: "ver_note2",
      kind: "label",
      at: {
        x: 925,
        y: 217,
        w: 407,
        h: 41,
      },
      text: "2. Fetch public key (JWKS / cached)",
      align: "start",
      muted: true,
    },
    {
      id: "ver_note3",
      kind: "label",
      at: {
        x: 925,
        y: 242,
        w: 407,
        h: 41,
      },
      text: "3. Verify signature with public key",
      align: "start",
      muted: true,
    },
    {
      id: "ver_note4",
      kind: "label",
      at: {
        x: 925,
        y: 267,
        w: 337,
        h: 41,
      },
      text: "4. Check exp, iss, aud claims",
      align: "start",
      muted: true,
    },
    {
      id: "ver_note5",
      kind: "label",
      at: {
        x: 925,
        y: 292,
        w: 384,
        h: 41,
      },
      text: "5. No DB query needed — stateless",
      align: "start",
      muted: true,
    },
    {
      id: "alg_bg",
      kind: "box",
      at: {
        x: 700,
        y: 463,
        w: 875,
        h: 200,
      },
      variant: "outline",
    },
    {
      id: "alg_ttl",
      kind: "label",
      at: {
        x: 1056,
        y: 469,
        w: 163,
        h: 41,
      },
      text: "HS256 vs RS256",
      align: "center",
    },
    {
      id: "alg_h1",
      kind: "label",
      at: {
        x: 713,
        y: 504,
        w: 221,
        h: 41,
      },
      text: "HS256 (HMAC-SHA256)",
      align: "start",
    },
    {
      id: "alg_h2",
      kind: "label",
      at: {
        x: 713,
        y: 534,
        w: 523,
        h: 41,
      },
      text: "Shared secret — any party can verify AND sign",
      align: "start",
      muted: true,
    },
    {
      id: "alg_h3",
      kind: "label",
      at: {
        x: 713,
        y: 559,
        w: 581,
        h: 41,
      },
      text: "Simple, fast. Risk: secret leak = full compromise.",
      align: "start",
      muted: true,
    },
    {
      id: "alg_r1",
      kind: "label",
      at: {
        x: 713,
        y: 599,
        w: 209,
        h: 41,
      },
      text: "RS256 (RSA-SHA256)",
      align: "start",
    },
    {
      id: "alg_r2",
      kind: "label",
      at: {
        x: 713,
        y: 629,
        w: 419,
        h: 41,
      },
      text: "Private key signs (Auth Server only)",
      align: "start",
      muted: true,
    },
    {
      id: "alg_r3",
      kind: "label",
      at: {
        x: 713,
        y: 654,
        w: 512,
        h: 41,
      },
      text: "Public key verifies (anyone — JWKS endpoint)",
      align: "start",
      muted: true,
    },
    {
      id: "rev_bg",
      kind: "box",
      at: {
        x: 700,
        y: 675,
        w: 875,
        h: 205,
      },
      variant: "outline",
    },
    {
      id: "rev_ttl",
      kind: "label",
      at: {
        x: 975,
        y: 682,
        w: 326,
        h: 41,
      },
      text: "Revocation Problem + Pattern",
      align: "center",
    },
    {
      id: "rev_1",
      kind: "label",
      at: {
        x: 713,
        y: 717,
        w: 686,
        h: 41,
      },
      text: "Problem: JWT is valid until exp — can't invalidate mid-life",
      align: "start",
      muted: true,
    },
    {
      id: "rev_2",
      kind: "label",
      at: {
        x: 713,
        y: 742,
        w: 500,
        h: 41,
      },
      text: "Solution: short-lived access tokens (15min)",
      align: "start",
      muted: true,
    },
    {
      id: "rev_3",
      kind: "label",
      at: {
        x: 713,
        y: 767,
        w: 570,
        h: 41,
      },
      text: "  + long-lived refresh token (stored server-side)",
      align: "start",
      muted: true,
    },
    {
      id: "rev_4",
      kind: "label",
      at: {
        x: 713,
        y: 792,
        w: 453,
        h: 41,
      },
      text: "  + revocation = delete refresh from DB",
      align: "start",
      muted: true,
    },
    {
      id: "rev_5",
      kind: "label",
      at: {
        x: 713,
        y: 817,
        w: 453,
        h: 41,
      },
      text: "  + optional: blocklist of revoked JTIs",
      align: "start",
      muted: true,
    },
    {
      id: "rev_note",
      kind: "label",
      at: {
        x: 800,
        y: 844,
        w: 674,
        h: 41,
      },
      text: "access = stateless (fast). refresh = stateful (revocable).",
      align: "center",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: Autenticação Stateless",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 275,
          y: 195,
        },
        placement: "right",
        text: "HTTP é stateless. Sem state, como o servidor sabe quem fez a request? Opção 1: session cookie (banco consulta a cada request). Opção 2: **JWT** — o token carrega as informações e prova que são autênticas.",
        why: "JWT transfere o estado para o cliente de forma segura. O servidor verifica a assinatura criptográfica — sem consultar banco para cada request.",
      },
    },
    {
      id: "s2",
      title: "JWT = 3 Partes Separadas por Ponto",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
        "sep1",
        "sep2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 275,
          y: 195,
        },
        placement: "right",
        text: "Um JWT é: **base64url(header)** + **.** + **base64url(payload)** + **.** + **signature**. Tudo numa única string compacta — pode ir em headers, cookies, URL.",
        why: "Base64url (sem +, / e =) é safe para URL e headers HTTP. O ponto como separador é simples de parsear — nenhuma biblioteca especial necessária.",
      },
    },
    {
      id: "s3",
      title: "Header: Algoritmo e Tipo",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
        "hdr_bg",
        "hdr_ttl",
        "hdr_1",
        "hdr_2",
        "hdr_3",
        "hdr_4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "band_h",
          do: "highlight",
        },
        {
          at: 0,
          target: "hdr_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 275,
          y: 300,
        },
        placement: "right",
        text: "`alg`: o algoritmo de assinatura (`HS256`, `RS256`, `ES256`). `typ`: sempre `JWT`. Verifique o `alg` ao validar — nunca aceite `alg:none`.",
        why: "Ataques 'alg:none' tentam forjar tokens sem assinatura. Implmentações devem exigir explicitamente o algoritmo esperado, nunca aceitar o que o token declara às cegas.",
      },
    },
    {
      id: "s4",
      title: "Payload: Claims do Token",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
        "hdr_bg",
        "hdr_ttl",
        "hdr_2",
        "pay_bg",
        "pay_ttl",
        "pay_1",
        "pay_2",
        "pay_3",
        "pay_4",
        "pay_5",
        "pay_6",
        "pay_7",
        "pay_warn",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "band_p",
          do: "highlight",
        },
        {
          at: 0,
          target: "pay_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 275,
          y: 490,
        },
        placement: "right",
        text: "**iss**: quem emitiu. **sub**: sujeito (user_id). **aud**: audiência (para qual API). **exp**: expiração Unix timestamp. **iat**: issued at. **jti**: ID único do token.",
        why: "⚠️ O payload é apenas base64 — não criptografado. Qualquer um pode decodificar e ler. Nunca coloque dados sensíveis (senha, CPF) no payload. Use JWE se precisar criptografar.",
      },
    },
    {
      id: "s5",
      title: "Signature: Garantindo Integridade",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
        "pay_bg",
        "pay_ttl",
        "pay_4",
        "sig_bg",
        "sig_ttl",
        "sig_1",
        "sig_2",
        "sig_3",
        "sig_4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "band_s",
          do: "highlight",
        },
        {
          at: 0,
          target: "sig_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 275,
          y: 650,
        },
        placement: "right",
        text: 'A signature é `Sign(header + "." + payload, privateKey)`. Qualquer alteração no header ou payload invalida a signature — proteção contra tampering.',
        why: "A signature NÃO criptografa o conteúdo — apenas prova que o token não foi alterado desde que foi emitido pelo Auth Server que tem a privateKey.",
      },
    },
    {
      id: "s6",
      title: "Verificação: Sem Consultar o Banco",
      duration: 9000,
      add: [
        "ver_bg",
        "ver_ttl",
        "ver_cli",
        "ver_srv",
        "ver_pk",
        "ver_a1",
        "ver_a1l",
        "ver_a2",
        "ver_a2l",
        "ver_a3",
        "ver_a3l",
        "ver_note1",
        "ver_note2",
        "ver_note3",
        "ver_note4",
        "ver_note5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ver_a1",
          do: "draw",
        },
        {
          at: 400,
          target: "ver_a2",
          do: "draw",
        },
        {
          at: 800,
          target: "ver_a3",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 910,
          y: 220,
        },
        placement: "bottom",
        text: "O servidor verifica o JWT **sem consultar banco**: 1) Split nas 3 partes, 2) busca public key no JWKS endpoint (cached), 3) verifica signature, 4) checa `exp`, `iss`, `aud`.",
        why: "Stateless verification = horizontal scaling fácil. Cada instância verifica independentemente sem coordenação. Desvantagem: não dá para revogar um token antes do exp.",
      },
    },
    {
      id: "s7",
      title: "HS256: Chave Simétrica",
      duration: 9000,
      add: [
        "ver_bg",
        "ver_ttl",
        "ver_cli",
        "ver_srv",
        "ver_pk",
        "ver_a1",
        "ver_a1l",
        "ver_a2",
        "ver_a2l",
        "ver_a3",
        "ver_a3l",
        "alg_bg",
        "alg_ttl",
        "alg_h1",
        "alg_h2",
        "alg_h3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "alg_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "alg_bg",
        placement: "right",
        text: "**HS256**: usa uma *chave simétrica compartilhada*. Todos que podem verificar também podem criar novos tokens. Simples e rápido.",
        why: "Use HS256 quando só um sistema (ex: o próprio backend) precisa verificar — nunca compartilhe a secret entre múltiplos serviços. Vazamento da secret = comprometimento total.",
      },
    },
    {
      id: "s8",
      title: "RS256: Par de Chaves Assimétricas",
      duration: 9000,
      add: [
        "ver_bg",
        "ver_ttl",
        "ver_cli",
        "ver_srv",
        "ver_pk",
        "ver_a1",
        "ver_a1l",
        "ver_a2",
        "ver_a2l",
        "ver_a3",
        "ver_a3l",
        "alg_bg",
        "alg_ttl",
        "alg_r1",
        "alg_r2",
        "alg_r3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ver_pk",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ver_pk",
        placement: "left",
        text: "**RS256**: Auth Server assina com *private key*. Qualquer serviço verifica com a *public key* (disponível no JWKS endpoint). Assimétrico: verificador não pode forjar tokens.",
        why: "RS256 é o padrão para sistemas distribuídos. Auth Server centraliza assinatura. Cada microserviço verifica independentemente com public key — sem compartilhar secrets.",
      },
    },
    {
      id: "s9",
      title: "JWT Stateless: Vantagens e Limitações",
      duration: 9000,
      add: [
        "ver_bg",
        "ver_ttl",
        "ver_cli",
        "ver_srv",
        "ver_note1",
        "ver_note2",
        "ver_note3",
        "ver_note4",
        "ver_note5",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 740,
          y: 210,
        },
        placement: "right",
        text: "**✓ Vantagens**: sem session store, horizontal scaling, microserviços verificam independentemente, informações no token. **✗ Limitações**: não pode revogar antes do `exp`.",
        why: "Para logout ou revogação de emergência (conta comprometida), o token continuaria válido até expirar. Tokens curtos (15min) minimizam a janela.",
      },
    },
    {
      id: "s10",
      title: "Problema de Revogação + Padrão Recomendado",
      duration: 9000,
      add: ["rev_bg", "rev_ttl", "rev_1", "rev_2", "rev_3", "rev_4", "rev_5", "rev_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "rev_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "rev_bg",
        placement: "left",
        text: "Padrão: **access_token curto** (15min, stateless JWT) + **refresh_token longo** (7d, stateful no banco). Revogação = deletar refresh token. Blocklist de JTI para casos urgentes.",
        why: "Refresh token rotation: cada uso gera novo refresh e invalida o anterior. Se um refresh vazar, o sistema detecta uso duplicado e revoga a sessão inteira.",
      },
    },
    {
      id: "s11",
      title: "JWT vs Session Cookie",
      duration: 9000,
      add: [
        "rev_bg",
        "rev_ttl",
        "rev_1",
        "rev_2",
        "rev_3",
        "rev_4",
        "rev_5",
        "alg_bg",
        "alg_ttl",
        "alg_h1",
        "alg_h2",
        "alg_r1",
        "alg_r2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 910,
          y: 460,
        },
        placement: "top",
        text: "**JWT**: stateless, maior payload, revogação difícil, ideal para microserviços e APIs. **Session cookie**: stateful (DB lookup), menor payload, revogação imediata, ideal para monolitos.",
        why: "Para aplicações tradicionais com um banco centralizado, session cookies são mais simples e revocáveis. JWT brilha em sistemas distribuídos com múltiplos services.",
      },
    },
    {
      id: "s12",
      title: "Quiz",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Teste seu conhecimento sobre JWT:",
      },
      quiz: {
        question: "Por que o payload de um JWT NÃO deve conter dados sensíveis como senhas ou CPF?",
        options: [
          "Porque o payload excede o limite de 256 bytes do header HTTP",
          "Porque o payload é apenas base64-encoded — qualquer um pode decodificar e ler o conteúdo",
          "Porque o algoritmo RS256 não consegue assinar payloads com caracteres especiais",
          "Porque o servidor não processa o payload durante a verificação da assinatura",
        ],
        answer: 1,
        explain:
          "Base64url não é criptografia — é apenas codificação. Qualquer pessoa com o token pode decodificar e ler o payload. Use JWE (JSON Web Encryption) se precisar de confidencialidade, ou não coloque dados sensíveis no token.",
      },
    },
    {
      id: "s13",
      title: "Resumo",
      duration: 9000,
      add: [
        "band_h",
        "band_h_t",
        "band_h_v",
        "band_p",
        "band_p_t",
        "band_p_v",
        "band_s",
        "band_s_t",
        "band_s_v",
        "sep1",
        "sep2",
        "pay_bg",
        "pay_ttl",
        "pay_1",
        "pay_2",
        "pay_3",
        "pay_4",
        "ver_bg",
        "ver_ttl",
        "ver_cli",
        "ver_srv",
        "ver_a1",
        "ver_a1l",
        "ver_a3",
        "ver_a3l",
        "rev_bg",
        "rev_ttl",
        "rev_2",
        "rev_3",
        "rev_4",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 275,
          y: 400,
        },
        placement: "right",
        text: "**JWT** = header.payload.signature. Payload: claims (sub, exp, iss). Signature: RS256 assimetrico (private/public key). Stateless verify. Padrão: access token curto (15min) + refresh longo (7d).",
        why: "Nunca exponha dado sensível no payload. Use RS256 em sistemas distribuídos. Access token curto = janela de exposição pequena. Refresh token = revogável no banco.",
      },
    },
  ],
};

export const jwt = validateExplainer(data);
