import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/kafka-schema.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "kafka-schema",
  title: "Kafka Serialization + Schema Registry",
  category: "Mensageria & Processamento Async",
  tags: ["kafka", "schema registry"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "json_bg",
      kind: "box",
      at: {
        x: 25,
        y: 25,
        w: 450,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "json_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 209,
        y: 27,
        w: 81,
        h: 41,
      },
      text: "📄 JSON",
      align: "center",
    },
    {
      id: "j1",
      kind: "label",
      at: {
        x: -114,
        y: 57,
        w: 302,
        h: 41,
      },
      text: "Human-readable, sem schema",
      align: "center",
    },
    {
      id: "j2",
      kind: "label",
      at: {
        x: -224,
        y: 79,
        w: 523,
        h: 41,
      },
      text: "Flexível: adicionar/remover campos livremente",
      align: "center",
    },
    {
      id: "j3",
      tone: "hot",
      kind: "label",
      at: {
        x: -218,
        y: 104,
        w: 512,
        h: 41,
      },
      text: "Grande: nomes de campo repetidos em cada msg",
      align: "center",
    },
    {
      id: "json_ex",
      kind: "box",
      at: {
        x: 38,
        y: 145,
        w: 425,
        h: 100,
      },
      variant: "outline",
    },
    {
      id: "je1",
      kind: "label",
      at: {
        x: -40,
        y: 144,
        w: 174,
        h: 41,
      },
      text: '{ "userId": 42,',
      align: "center",
    },
    {
      id: "je2",
      kind: "label",
      at: {
        x: -80,
        y: 164,
        w: 256,
        h: 41,
      },
      text: '  "event": "checkout",',
      align: "center",
    },
    {
      id: "je3",
      kind: "label",
      at: {
        x: -57,
        y: 184,
        w: 209,
        h: 41,
      },
      text: '  "amount": 99.90,',
      align: "center",
    },
    {
      id: "je4",
      kind: "label",
      at: {
        x: -75,
        y: 202,
        w: 244,
        h: 41,
      },
      text: '  "currency": "BRL" }',
      align: "center",
    },
    {
      id: "j4",
      tone: "hot",
      kind: "label",
      at: {
        x: -73,
        y: 242,
        w: 221,
        h: 41,
      },
      text: "Payload: ~120 bytes",
      align: "center",
    },
    {
      id: "j5",
      tone: "hot",
      kind: "label",
      at: {
        x: -178,
        y: 267,
        w: 430,
        h: 41,
      },
      text: "Sem schema enforcement: producer pode",
      align: "center",
    },
    {
      id: "j6",
      tone: "hot",
      kind: "label",
      at: {
        x: -160,
        y: 289,
        w: 395,
        h: 41,
      },
      text: 'remover "amount" → consumer crasha',
      align: "center",
    },
    {
      id: "j7",
      tone: "warn",
      kind: "label",
      at: {
        x: -143,
        y: 314,
        w: 360,
        h: 41,
      },
      text: "Sem compressão nativa de schema",
      align: "center",
    },
    {
      id: "j8",
      tone: "warn",
      kind: "label",
      at: {
        x: -148,
        y: 334,
        w: 372,
        h: 41,
      },
      text: "Serialização lenta (parse texto)",
      align: "center",
    },
    {
      id: "avro_bg",
      kind: "box",
      at: {
        x: 500,
        y: 25,
        w: 450,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "avro_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 644,
        y: 27,
        w: 163,
        h: 41,
      },
      text: "🔷 Apache Avro",
      align: "center",
    },
    {
      id: "av1",
      kind: "label",
      at: {
        x: 327,
        y: 57,
        w: 372,
        h: 41,
      },
      text: "Schema em JSON, encoding binário",
      align: "center",
    },
    {
      id: "av2",
      tone: "good",
      kind: "label",
      at: {
        x: 303,
        y: 79,
        w: 419,
        h: 41,
      },
      text: "Schema resolvido via Schema Registry",
      align: "center",
    },
    {
      id: "av3",
      kind: "label",
      at: {
        x: 303,
        y: 104,
        w: 419,
        h: 41,
      },
      text: "Campos sem nome no wire (só posição)",
      align: "center",
    },
    {
      id: "avro_schema",
      kind: "box",
      at: {
        x: 513,
        y: 145,
        w: 425,
        h: 100,
      },
      variant: "outline",
    },
    {
      id: "avs1",
      tone: "accent2",
      kind: "label",
      at: {
        x: 412,
        y: 144,
        w: 221,
        h: 41,
      },
      text: '{ "type": "record",',
      align: "center",
    },
    {
      id: "avs2",
      tone: "accent2",
      kind: "label",
      at: {
        x: 389,
        y: 164,
        w: 267,
        h: 41,
      },
      text: '  "name": "OrderEvent",',
      align: "center",
    },
    {
      id: "avs3",
      tone: "accent2",
      kind: "label",
      at: {
        x: 447,
        y: 184,
        w: 151,
        h: 41,
      },
      text: '  "fields": [',
      align: "center",
    },
    {
      id: "avs4",
      tone: "accent2",
      kind: "label",
      at: {
        x: 307,
        y: 204,
        w: 430,
        h: 41,
      },
      text: '    {"name":"userId","type":"int"} ]}',
      align: "center",
    },
    {
      id: "av4",
      tone: "good",
      kind: "label",
      at: {
        x: 303,
        y: 242,
        w: 419,
        h: 41,
      },
      text: "Payload: ~25 bytes (schema separado)",
      align: "center",
    },
    {
      id: "av5",
      tone: "good",
      kind: "label",
      at: {
        x: 286,
        y: 267,
        w: 453,
        h: 41,
      },
      text: "Schema evolution nativa: default values",
      align: "center",
    },
    {
      id: "av6",
      kind: "label",
      at: {
        x: 268,
        y: 289,
        w: 488,
        h: 41,
      },
      text: "Schema enviado com a mensagem (standalone)",
      align: "center",
    },
    {
      id: "av7",
      tone: "good",
      kind: "label",
      at: {
        x: 280,
        y: 314,
        w: 465,
        h: 41,
      },
      text: "Ou resolvido via Registry (ID no header)",
      align: "center",
    },
    {
      id: "av8",
      kind: "label",
      at: {
        x: 292,
        y: 334,
        w: 442,
        h: 41,
      },
      text: "Popular no ecossistema Confluent Kafka",
      align: "center",
    },
    {
      id: "proto_bg",
      kind: "box",
      at: {
        x: 975,
        y: 25,
        w: 600,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "proto_title",
      tone: "good",
      kind: "label",
      at: {
        x: 1106,
        y: 27,
        w: 337,
        h: 41,
      },
      text: "⚡ Protocol Buffers (Protobuf)",
      align: "center",
    },
    {
      id: "p1",
      kind: "label",
      at: {
        x: 784,
        y: 57,
        w: 407,
        h: 41,
      },
      text: "Schema em arquivo .proto, compilado",
      align: "center",
    },
    {
      id: "p2",
      tone: "good",
      kind: "label",
      at: {
        x: 749,
        y: 79,
        w: 477,
        h: 41,
      },
      text: "Binary com field numbers — muito compacto",
      align: "center",
    },
    {
      id: "p3",
      tone: "good",
      kind: "label",
      at: {
        x: 778,
        y: 104,
        w: 419,
        h: 41,
      },
      text: "Type-safe: protoc gera código tipado",
      align: "center",
    },
    {
      id: "proto_schema",
      kind: "box",
      at: {
        x: 988,
        y: 145,
        w: 575,
        h: 100,
      },
      variant: "outline",
    },
    {
      id: "ps1",
      tone: "good",
      kind: "label",
      at: {
        x: 893,
        y: 144,
        w: 209,
        h: 41,
      },
      text: 'syntax = "proto3";',
      align: "center",
    },
    {
      id: "ps2",
      tone: "good",
      kind: "label",
      at: {
        x: 881,
        y: 164,
        w: 233,
        h: 41,
      },
      text: "message OrderEvent {",
      align: "center",
    },
    {
      id: "ps3",
      tone: "good",
      kind: "label",
      at: {
        x: 881,
        y: 184,
        w: 233,
        h: 41,
      },
      text: "  int32 user_id = 1;",
      align: "center",
    },
    {
      id: "ps4",
      tone: "good",
      kind: "label",
      at: {
        x: 858,
        y: 204,
        w: 279,
        h: 41,
      },
      text: "  string currency = 3; }",
      align: "center",
    },
    {
      id: "p4",
      tone: "good",
      kind: "label",
      at: {
        x: 784,
        y: 242,
        w: 407,
        h: 41,
      },
      text: "Payload: ~10 bytes (menor que Avro)",
      align: "center",
    },
    {
      id: "p5",
      kind: "label",
      at: {
        x: 749,
        y: 267,
        w: 477,
        h: 41,
      },
      text: "Campo removido: adicionar `reserved` para",
      align: "center",
    },
    {
      id: "p6",
      kind: "label",
      at: {
        x: 761,
        y: 289,
        w: 453,
        h: 41,
      },
      text: "evitar reuso de field number → breaking",
      align: "center",
    },
    {
      id: "p7",
      tone: "warn",
      kind: "label",
      at: {
        x: 767,
        y: 314,
        w: 442,
        h: 41,
      },
      text: "Backward compat: manter field numbers!",
      align: "center",
    },
    {
      id: "p8",
      kind: "label",
      at: {
        x: 755,
        y: 334,
        w: 465,
        h: 41,
      },
      text: "Schema Registry: Confluent suporta proto",
      align: "center",
    },
    {
      id: "pr_box",
      tone: "accent",
      kind: "box",
      at: {
        x: 31,
        y: 463,
        w: 138,
        h: 63,
      },
      label: "📤 Producer",
      variant: "outline",
    },
    {
      id: "sr_box",
      tone: "accent2",
      kind: "box",
      at: {
        x: 356,
        y: 463,
        w: 163,
        h: 63,
      },
      label: "📋 Schema\nRegistry",
      variant: "outline",
    },
    {
      id: "ka_box",
      tone: "warn",
      kind: "box",
      at: {
        x: 706,
        y: 463,
        w: 138,
        h: 63,
      },
      label: "📨 Kafka\nBroker",
      variant: "outline",
    },
    {
      id: "co_box",
      tone: "good",
      kind: "box",
      at: {
        x: 981,
        y: 463,
        w: 138,
        h: 63,
      },
      label: "📥 Consumer",
      variant: "outline",
    },
    {
      id: "ll_pr",
      kind: "connector",
      from: {
        x: 100,
        y: 525,
      },
      to: {
        x: 100,
        y: 875,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_sr",
      kind: "connector",
      from: {
        x: 438,
        y: 525,
      },
      to: {
        x: 438,
        y: 875,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_ka",
      kind: "connector",
      from: {
        x: 775,
        y: 525,
      },
      to: {
        x: 775,
        y: 875,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_co",
      kind: "connector",
      from: {
        x: 1050,
        y: 525,
      },
      to: {
        x: 1050,
        y: 875,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "s_reg",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 100,
        y: 563,
      },
      to: {
        x: 438,
        y: 563,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_reg_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 7,
        y: 527,
        w: 523,
        h: 41,
      },
      text: "POST /subjects/orders-value/versions {schema}",
      align: "center",
    },
    {
      id: "s_reg_r",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 438,
        y: 600,
      },
      to: {
        x: 100,
        y: 600,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_reg_r_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 83,
        y: 564,
        w: 372,
        h: 41,
      },
      text: '{"id": 7}  ← schema_id atribuído',
      align: "center",
    },
    {
      id: "s_prod",
      tone: "accent",
      kind: "connector",
      from: {
        x: 100,
        y: 638,
      },
      to: {
        x: 775,
        y: 638,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_prod_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 170,
        y: 602,
        w: 535,
        h: 41,
      },
      text: "Produce: [0x00][schema_id=7][avro/proto bytes]",
      align: "center",
    },
    {
      id: "s_pub",
      tone: "warn",
      kind: "connector",
      from: {
        x: 775,
        y: 675,
      },
      to: {
        x: 1050,
        y: 675,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_pub_l",
      tone: "warn",
      kind: "label",
      at: {
        x: 674,
        y: 639,
        w: 477,
        h: 41,
      },
      text: "Poll: mensagem com magic byte + schema_id",
      align: "center",
    },
    {
      id: "s_read",
      tone: "good",
      kind: "connector",
      from: {
        x: 1050,
        y: 713,
      },
      to: {
        x: 438,
        y: 713,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_read_l",
      tone: "good",
      kind: "label",
      at: {
        x: 558,
        y: 677,
        w: 372,
        h: 41,
      },
      text: "GET /schemas/ids/7  (cache miss)",
      align: "center",
    },
    {
      id: "s_read_r",
      tone: "good",
      kind: "connector",
      from: {
        x: 438,
        y: 788,
      },
      to: {
        x: 1050,
        y: 788,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_read_r_l",
      tone: "good",
      kind: "label",
      at: {
        x: 535,
        y: 752,
        w: 419,
        h: 41,
      },
      text: '{schema: "OrderEvent" ...}  ← cached',
      align: "center",
    },
    {
      id: "s_proc",
      tone: "good",
      kind: "connector",
      from: {
        x: 1050,
        y: 825,
      },
      to: {
        x: 1100,
        y: 825,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s_proc_l",
      tone: "good",
      kind: "label",
      at: {
        x: 953,
        y: 789,
        w: 244,
        h: 41,
      },
      text: "deserialize → process",
      align: "center",
    },
    {
      id: "wire_bg",
      kind: "box",
      at: {
        x: 213,
        y: 619,
        w: 200,
        h: 35,
      },
      variant: "outline",
    },
    {
      id: "wire_lbl",
      tone: "accent",
      kind: "label",
      at: {
        x: 121,
        y: 621,
        w: 384,
        h: 41,
      },
      text: "[0x00][4-byte schema_id][payload]",
      align: "center",
    },
    {
      id: "wire_sub",
      kind: "label",
      at: {
        x: 185,
        y: 639,
        w: 256,
        h: 41,
      },
      text: "magic byte sempre 0x00",
      align: "center",
    },
    {
      id: "compat_bg",
      kind: "box",
      at: {
        x: 1313,
        y: 463,
        w: 263,
        h: 388,
      },
      variant: "outline",
    },
    {
      id: "compat_title",
      kind: "label",
      at: {
        x: 1351,
        y: 464,
        w: 186,
        h: 41,
      },
      text: "⚙️ Compatibility",
      align: "center",
    },
    {
      id: "cm_bk_h",
      tone: "good",
      kind: "label",
      at: {
        x: 1279,
        y: 497,
        w: 93,
        h: 41,
      },
      text: "BACKWARD",
      align: "center",
    },
    {
      id: "cm_bk1",
      kind: "label",
      at: {
        x: 1209,
        y: 519,
        w: 233,
        h: 41,
      },
      text: "Novos consumers leem",
      align: "center",
    },
    {
      id: "cm_bk2",
      kind: "label",
      at: {
        x: 1226,
        y: 539,
        w: 198,
        h: 41,
      },
      text: "mensagens antigas",
      align: "center",
    },
    {
      id: "cm_bk3",
      tone: "good",
      kind: "label",
      at: {
        x: 1186,
        y: 559,
        w: 279,
        h: 41,
      },
      text: "→ add campo c/ default ✓",
      align: "center",
    },
    {
      id: "cm_bk4",
      tone: "good",
      kind: "label",
      at: {
        x: 1226,
        y: 579,
        w: 198,
        h: 41,
      },
      text: "→ remover campo ✓",
      align: "center",
    },
    {
      id: "cm_fw_h",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1284,
        y: 614,
        w: 81,
        h: 41,
      },
      text: "FORWARD",
      align: "center",
    },
    {
      id: "cm_fw1",
      kind: "label",
      at: {
        x: 1197,
        y: 637,
        w: 256,
        h: 41,
      },
      text: "Antigos consumers leem",
      align: "center",
    },
    {
      id: "cm_fw2",
      kind: "label",
      at: {
        x: 1238,
        y: 657,
        w: 174,
        h: 41,
      },
      text: "mensagens novas",
      align: "center",
    },
    {
      id: "cm_fw3",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1197,
        y: 677,
        w: 256,
        h: 41,
      },
      text: "→ remover c/ default ✓",
      align: "center",
    },
    {
      id: "cm_fw4",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1249,
        y: 697,
        w: 151,
        h: 41,
      },
      text: "→ add campo ✓",
      align: "center",
    },
    {
      id: "cm_fl_h",
      tone: "warn",
      kind: "label",
      at: {
        x: 1288,
        y: 729,
        w: 75,
        h: 41,
      },
      text: "FULL",
      align: "center",
    },
    {
      id: "cm_fl1",
      kind: "label",
      at: {
        x: 1203,
        y: 752,
        w: 244,
        h: 41,
      },
      text: "Ambas: back + forward",
      align: "center",
    },
    {
      id: "cm_fl2",
      kind: "label",
      at: {
        x: 1238,
        y: 772,
        w: 174,
        h: 41,
      },
      text: "Mais restritivo",
      align: "center",
    },
    {
      id: "cm_no_h",
      tone: "hot",
      kind: "label",
      at: {
        x: 1288,
        y: 799,
        w: 75,
        h: 41,
      },
      text: "NONE",
      align: "center",
    },
    {
      id: "cm_no1",
      tone: "hot",
      kind: "label",
      at: {
        x: 1174,
        y: 819,
        w: 302,
        h: 41,
      },
      text: "Sem verificação (perigoso)",
      align: "center",
    },
    {
      id: "evol_bg",
      kind: "box",
      at: {
        x: 1313,
        y: 860,
        w: 263,
        h: 75,
      },
      variant: "outline",
    },
    {
      id: "evol_t",
      tone: "warn",
      kind: "label",
      at: {
        x: 1351,
        y: 859,
        w: 186,
        h: 41,
      },
      text: "Schema Evolution",
      align: "center",
    },
    {
      id: "ev1",
      tone: "good",
      kind: "label",
      at: {
        x: 1116,
        y: 882,
        w: 419,
        h: 41,
      },
      text: "add campo c/ default → OK (BACKWARD)",
      align: "center",
    },
    {
      id: "ev2",
      tone: "hot",
      kind: "label",
      at: {
        x: 1145,
        y: 902,
        w: 360,
        h: 41,
      },
      text: "mudar tipo (int→str) → BREAKING",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: Schema Drift",
      duration: 6500,
      add: ["json_bg", "json_title", "j1", "j2", "j3", "json_ex", "je1", "je2", "je3", "je4", "j5", "j6"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "json_bg",
        placement: "right",
        text: "Producer A publica mensagens JSON com campo `amount`. Um dia remove o campo para refatorar. Consumer B crasha com `KeyError: amount`. Sem schema enforcement, o contrato entre producer e consumer é invisível.",
        why: "Schema drift é a principal causa de falhas silenciosas em pipelines de dados — difícil de detectar até a produção.",
      },
    },
    {
      id: "s2",
      title: "JSON: flexível mas sem garantias",
      duration: 6500,
      add: [
        "json_bg",
        "json_title",
        "j1",
        "j2",
        "j3",
        "json_ex",
        "je1",
        "je2",
        "je3",
        "je4",
        "j4",
        "j5",
        "j6",
        "j7",
        "j8",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "json_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "json_bg",
        placement: "right",
        text: "JSON: human-readable, zero setup. Problemas: **payloads grandes** (nomes de campo repetidos em cada mensagem), **sem schema enforcement** e **parse lento** (texto → objeto). Bom para desenvolvimento; problemático em alta escala.",
      },
    },
    {
      id: "s3",
      title: "Protocol Buffers: schema compilado, binário compacto",
      duration: 6500,
      add: [
        "proto_bg",
        "proto_title",
        "p1",
        "p2",
        "p3",
        "proto_schema",
        "ps1",
        "ps2",
        "ps3",
        "ps4",
        "p4",
        "p5",
        "p6",
        "p7",
        "p8",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "proto_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "proto_bg",
        placement: "left",
        text: "Protobuf usa **field numbers** em vez de nomes — o wire format é muito menor (~10 bytes vs ~120 JSON). O `.proto` file é a fonte de verdade. `protoc` gera código tipado. Campo removido: usar `reserved` para não reutilizar o number.",
        why: "Field numbers são a chave da backward compatibility: adicionar campo com number novo → safe. Reutilizar number de campo removido → BREAKING.",
      },
    },
    {
      id: "s4",
      title: "Apache Avro: schema JSON, encoding binário",
      duration: 6500,
      add: [
        "avro_bg",
        "avro_title",
        "av1",
        "av2",
        "av3",
        "avro_schema",
        "avs1",
        "avs2",
        "avs3",
        "avs4",
        "av4",
        "av5",
        "av6",
        "av7",
        "av8",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "avro_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "avro_bg",
        placement: "right",
        text: "Avro define o schema em JSON mas serializa em binário. Campos são identificados por **posição** no schema (não por nome no wire). Schema evolution via `default` values. Muito integrado ao ecossistema Confluent Kafka.",
      },
    },
    {
      id: "s5",
      title: "Comparativo: JSON vs Avro vs Protobuf",
      duration: 6500,
      add: [
        "json_bg",
        "json_title",
        "j3",
        "j4",
        "j5",
        "avro_bg",
        "avro_title",
        "av4",
        "av5",
        "av7",
        "proto_bg",
        "proto_title",
        "p2",
        "p3",
        "p4",
        "p7",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "avro_bg",
        placement: "bottom",
        text: "| | JSON | Avro | Protobuf |\n|Payload|~120B|~25B|~10B|\n|Schema|nenhum|JSON def|.proto file|\n|Tipagem|none|runtime|compilada|\n|Evolution|manual|default values|field numbers|\n\nProtobuf é menor; Avro integra melhor ao Kafka ecosystem com Registry.",
      },
    },
    {
      id: "s6",
      title: "Schema Registry: o contrato centralizado",
      duration: 6500,
      add: ["pr_box", "sr_box", "ka_box", "co_box", "ll_pr", "ll_sr", "ll_ka", "ll_co"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sr_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sr_box",
        placement: "right",
        text: "O Schema Registry é um serviço HTTP que armazena e versiona schemas. Cada schema recebe um **schema_id** único. Producer registra antes de publicar. Consumer busca o schema pelo ID para deserializar.",
        why: "O Registry garante que producer e consumer sempre usam schemas compatíveis — sem coordenação manual entre times.",
      },
    },
    {
      id: "s7",
      title: "Producer: registrar schema e serializar",
      duration: 6500,
      add: [
        "pr_box",
        "sr_box",
        "ka_box",
        "ll_pr",
        "ll_sr",
        "ll_ka",
        "s_reg",
        "s_reg_l",
        "s_reg_r",
        "s_reg_r_l",
        "s_prod",
        "s_prod_l",
        "wire_bg",
        "wire_lbl",
        "wire_sub",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pr_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "sr_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_reg_l",
        placement: "top",
        text: "Producer envia o schema ao Registry. Se já existe e é compatível, recebe o **schema_id** existente. Serializa a mensagem prefixada com `[0x00][schema_id de 4 bytes]` — apenas 5 bytes de overhead para todo o contexto de schema.",
      },
    },
    {
      id: "s8",
      title: "Consumer: ler schema_id e deserializar",
      duration: 6500,
      add: [
        "pr_box",
        "sr_box",
        "ka_box",
        "co_box",
        "ll_pr",
        "ll_sr",
        "ll_ka",
        "ll_co",
        "s_prod",
        "s_prod_l",
        "s_pub",
        "s_pub_l",
        "s_read",
        "s_read_l",
        "s_read_r",
        "s_read_r_l",
        "s_proc",
        "s_proc_l",
        "wire_bg",
        "wire_lbl",
        "wire_sub",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "co_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "sr_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_read_l",
        placement: "top",
        text: "Consumer lê os primeiros 5 bytes: magic byte `0x00` + `schema_id`. Faz GET ao Registry para obter o schema (cache local após o primeiro fetch). Usa o schema para deserializar os bytes restantes.",
        why: "O cache local do consumer evita latência do Registry em cada mensagem — schemas raramente mudam.",
      },
    },
    {
      id: "s9",
      title: "Compatibility Modes: BACKWARD e FORWARD",
      duration: 6500,
      add: [
        "sr_box",
        "ll_sr",
        "compat_bg",
        "compat_title",
        "cm_bk_h",
        "cm_bk1",
        "cm_bk2",
        "cm_bk3",
        "cm_bk4",
        "cm_fw_h",
        "cm_fw1",
        "cm_fw2",
        "cm_fw3",
        "cm_fw4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "compat_bg",
          do: "highlight",
        },
        {
          at: 0,
          target: "sr_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "compat_bg",
        placement: "left",
        text: "**BACKWARD**: novo consumer pode ler mensagens antigas. Permite adicionar campo com default e remover campo.\n**FORWARD**: consumer antigo pode ler mensagens novas. Permite adicionar campo e remover campo com default.",
        why: "BACKWARD é o default e o mais comum: permite fazer deploy do consumer antes do producer (safe rollout).",
      },
    },
    {
      id: "s10",
      title: "FULL e Schema Evolution Rules",
      duration: 6500,
      add: [
        "sr_box",
        "ll_sr",
        "compat_bg",
        "compat_title",
        "cm_fl_h",
        "cm_fl1",
        "cm_fl2",
        "cm_no_h",
        "cm_no1",
        "evol_bg",
        "evol_t",
        "ev1",
        "ev2",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "evol_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "evol_bg",
        placement: "left",
        text: "**FULL** = BACKWARD + FORWARD: mais seguro mas mais restritivo. **NONE**: sem verificação — perigoso, apenas para desenvolvimento. Regra de ouro de evolution: sempre adicionar campos com `default`, nunca reutilizar field numbers (Protobuf) ou alterar tipos.",
      },
    },
    {
      id: "s11",
      title: "Subject naming e Registry na prática",
      duration: 6500,
      add: [
        "pr_box",
        "sr_box",
        "ka_box",
        "co_box",
        "ll_pr",
        "ll_sr",
        "ll_ka",
        "ll_co",
        "s_reg",
        "s_reg_l",
        "s_reg_r",
        "s_reg_r_l",
        "compat_bg",
        "compat_title",
        "cm_bk_h",
        "cm_bk3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "sr_box",
        placement: "right",
        text: "**Subject naming**: `{topic}-value` (ex: `orders-value`), `{topic}-key`, ou `{record-name}`. Confluent Schema Registry: REST API na porta 8081, suporta Avro/JSON Schema/Protobuf. Cache no cliente evita overhead. Schema IDs são imutáveis (nunca mudam de schema).",
      },
    },
    {
      id: "s12",
      title: "Quiz",
      duration: 6500,
      add: [
        "sr_box",
        "compat_bg",
        "compat_title",
        "cm_bk_h",
        "cm_bk1",
        "cm_bk2",
        "cm_bk3",
        "cm_bk4",
        "cm_fw_h",
        "cm_fw1",
        "cm_fw2",
        "cm_fw3",
        "cm_fw4",
      ],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question:
          "Você quer adicionar um novo campo opcional `coupon_code` a um schema Avro existente sem quebrar consumers antigos que não conhecem esse campo. Qual ação garante isso com BACKWARD compatibility?",
        options: [
          "Remover um campo existente para abrir espaço e renomear para coupon_code",
          'Adicionar o campo coupon_code com um valor default (ex: null ou "")',
          "Criar um novo schema com nome diferente e migrar todos os consumers manualmente",
          "Alterar o tipo do campo amount de int para string para acomodar o coupon_code",
        ],
        answer: 1,
        explain:
          "BACKWARD compatibility requer que novos schemas possam ser lidos por consumers que usam o schema mais recente para ler mensagens produzidas com schemas mais antigos. Adicionar um campo com **default value** é a operação segura: mensagens antigas (sem o campo) serão preenchidas com o default ao serem deserializadas pelo novo consumer. Remover campos (sem default), renomear ou mudar tipos são operações BREAKING.",
      },
    },
    {
      id: "s13",
      title: "Resumo: Kafka Serialization + Schema Registry",
      duration: 6500,
      add: [
        "json_bg",
        "json_title",
        "j3",
        "j4",
        "avro_bg",
        "avro_title",
        "av2",
        "av4",
        "av5",
        "proto_bg",
        "proto_title",
        "p2",
        "p4",
        "pr_box",
        "sr_box",
        "ka_box",
        "co_box",
        "ll_pr",
        "ll_sr",
        "ll_ka",
        "ll_co",
        "s_reg",
        "s_reg_l",
        "s_reg_r",
        "s_reg_r_l",
        "s_prod",
        "s_prod_l",
        "s_pub",
        "s_pub_l",
        "s_read",
        "s_read_l",
        "s_read_r",
        "s_read_r_l",
        "wire_bg",
        "wire_lbl",
        "compat_bg",
        "compat_title",
        "cm_bk_h",
        "cm_bk3",
        "cm_fw_h",
        "cm_fw3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "sr_box",
        placement: "right",
        text: "JSON: legível, sem schema, grande. Avro/Protobuf: binary, compacto, schema enforcement. Schema Registry: versiona schemas, atribui IDs, verifica compatibility. Wire format: [0x00][schema_id][payload]. BACKWARD: default values ao adicionar campos. FULL: mais seguro.",
      },
    },
  ],
};

export const kafkaSchema = validateExplainer(data);
