import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/load-balancer.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "load-balancer",
  title: "Load Balancer — L4, L7 e Algoritmos",
  category: "Infraestrutura & Cloud",
  tags: ["load balancer", "infra"],
  level: "intro",
  glossary: {},
  elements: [
    {
      id: "cli1",
      tone: "accent",
      kind: "box",
      at: {
        x: 25,
        y: 125,
        w: 113,
        h: 55,
      },
      label: "👤 Client",
      variant: "outline",
    },
    {
      id: "cli2",
      tone: "accent",
      kind: "box",
      at: {
        x: 25,
        y: 250,
        w: 113,
        h: 55,
      },
      label: "👤 Client",
      variant: "outline",
    },
    {
      id: "cli3",
      tone: "accent",
      kind: "box",
      at: {
        x: 25,
        y: 375,
        w: 113,
        h: 55,
      },
      label: "👤 Client",
      variant: "outline",
    },
    {
      id: "a_ccli1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 138,
        y: 153,
      },
      to: {
        x: 250,
        y: 263,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_ccli2",
      tone: "accent",
      kind: "connector",
      from: {
        x: 138,
        y: 278,
      },
      to: {
        x: 250,
        y: 263,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_ccli3",
      tone: "accent",
      kind: "connector",
      from: {
        x: 138,
        y: 403,
      },
      to: {
        x: 250,
        y: 263,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lb",
      tone: "warn",
      kind: "box",
      at: {
        x: 250,
        y: 213,
        w: 163,
        h: 100,
      },
      label: "⚖️ Load\nBalancer",
      variant: "outline",
    },
    {
      id: "lb_vip",
      kind: "label",
      at: {
        x: 232,
        y: 309,
        w: 198,
        h: 41,
      },
      text: "VIP: 203.0.113.10",
      align: "center",
    },
    {
      id: "a_ssrv1",
      tone: "good",
      kind: "connector",
      from: {
        x: 413,
        y: 263,
      },
      to: {
        x: 525,
        y: 131,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_ssrv2",
      tone: "good",
      kind: "connector",
      from: {
        x: 413,
        y: 263,
      },
      to: {
        x: 525,
        y: 256,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_ssrv3",
      tone: "good",
      kind: "connector",
      from: {
        x: 413,
        y: 263,
      },
      to: {
        x: 525,
        y: 381,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_ssrv4",
      tone: "good",
      kind: "connector",
      from: {
        x: 413,
        y: 263,
      },
      to: {
        x: 525,
        y: 506,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "srv1",
      tone: "good",
      kind: "box",
      at: {
        x: 525,
        y: 100,
        w: 163,
        h: 63,
      },
      label: "⚙️ Server 1",
      variant: "outline",
    },
    {
      id: "srv2",
      tone: "good",
      kind: "box",
      at: {
        x: 525,
        y: 225,
        w: 163,
        h: 63,
      },
      label: "⚙️ Server 2",
      variant: "outline",
    },
    {
      id: "srv3",
      tone: "accent2",
      kind: "box",
      at: {
        x: 525,
        y: 350,
        w: 163,
        h: 63,
      },
      label: "⚙️ Server 3",
      variant: "outline",
    },
    {
      id: "srv4",
      tone: "hot",
      kind: "box",
      at: {
        x: 525,
        y: 475,
        w: 163,
        h: 63,
      },
      label: "⚙️ Server 4\n(unhealthy)",
      variant: "outline",
    },
    {
      id: "srv4_x",
      tone: "hot",
      kind: "label",
      at: {
        x: 658,
        y: 474,
        w: 75,
        h: 41,
      },
      text: "❌ 503",
      align: "center",
    },
    {
      id: "l4_bg",
      kind: "box",
      at: {
        x: 750,
        y: 463,
        w: 813,
        h: 200,
      },
      variant: "outline",
    },
    {
      id: "l4_title",
      kind: "label",
      at: {
        x: 1005,
        y: 464,
        w: 302,
        h: 41,
      },
      text: "🔌 L4 vs L7 Load Balancing",
      align: "center",
    },
    {
      id: "l4h1",
      tone: "accent2",
      kind: "label",
      at: {
        x: 646,
        y: 497,
        w: 233,
        h: 41,
      },
      text: "L4 — Transport Layer",
      align: "center",
    },
    {
      id: "l4h2",
      tone: "good",
      kind: "label",
      at: {
        x: 1041,
        y: 497,
        w: 256,
        h: 41,
      },
      text: "L7 — Application Layer",
      align: "center",
    },
    {
      id: "l4v1",
      kind: "label",
      at: {
        x: 594,
        y: 524,
        w: 337,
        h: 41,
      },
      text: "Decisão por IP:port (TCP/UDP)",
      align: "center",
    },
    {
      id: "l4v2",
      kind: "label",
      at: {
        x: 965,
        y: 524,
        w: 407,
        h: 41,
      },
      text: "Decisão por HTTP headers/URL/cookie",
      align: "center",
    },
    {
      id: "l4v3",
      kind: "label",
      at: {
        x: 577,
        y: 549,
        w: 372,
        h: 41,
      },
      text: "Não abre o payload — mais rápido",
      align: "center",
    },
    {
      id: "l4v4",
      kind: "label",
      at: {
        x: 1047,
        y: 549,
        w: 244,
        h: 41,
      },
      text: "Content-based routing",
      align: "center",
    },
    {
      id: "l4v5",
      kind: "label",
      at: {
        x: 670,
        y: 574,
        w: 186,
        h: 41,
      },
      text: "NAT ou TCP proxy",
      align: "center",
    },
    {
      id: "l4v6",
      kind: "label",
      at: {
        x: 983,
        y: 574,
        w: 372,
        h: 41,
      },
      text: "SSL termination, sticky sessions",
      align: "center",
    },
    {
      id: "l4v7",
      kind: "label",
      at: {
        x: 594,
        y: 599,
        w: 337,
        h: 41,
      },
      text: "Ex: AWS NLB, HAProxy TCP mode",
      align: "center",
    },
    {
      id: "l4v8",
      kind: "label",
      at: {
        x: 1023,
        y: 599,
        w: 291,
        h: 41,
      },
      text: "Ex: AWS ALB, NGINX, Envoy",
      align: "center",
    },
    {
      id: "l4v9",
      kind: "label",
      at: {
        x: 577,
        y: 624,
        w: 372,
        h: 41,
      },
      text: "Menor latência, sem TLS overhead",
      align: "center",
    },
    {
      id: "l4v10",
      kind: "label",
      at: {
        x: 954,
        y: 624,
        w: 430,
        h: 41,
      },
      text: "Maior funcionalidade, maior custo CPU",
      align: "center",
    },
    {
      id: "alg_bg",
      kind: "box",
      at: {
        x: 750,
        y: 38,
        w: 813,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "alg_title",
      kind: "label",
      at: {
        x: 982,
        y: 39,
        w: 349,
        h: 41,
      },
      text: "🔄 Algoritmos de Balanceamento",
      align: "center",
    },
    {
      id: "alg_rr_h",
      tone: "accent",
      kind: "label",
      at: {
        x: 699,
        y: 72,
        w: 128,
        h: 41,
      },
      text: "Round Robin",
      align: "center",
    },
    {
      id: "alg_rr1",
      kind: "label",
      at: {
        x: 571,
        y: 97,
        w: 384,
        h: 41,
      },
      text: "1→2→3→1→2→3... sequência circular",
      align: "center",
    },
    {
      id: "alg_rr2",
      kind: "label",
      at: {
        x: 489,
        y: 117,
        w: 546,
        h: 41,
      },
      text: "Simples; assume servidores com capacidade igual",
      align: "center",
    },
    {
      id: "alg_wt_h",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1053,
        y: 72,
        w: 233,
        h: 41,
      },
      text: "Weighted Round Robin",
      align: "center",
    },
    {
      id: "alg_wt1",
      kind: "label",
      at: {
        x: 930,
        y: 97,
        w: 477,
        h: 41,
      },
      text: "A(w=3):B(w=1) → A recebe 3× mais requests",
      align: "center",
    },
    {
      id: "alg_wt2",
      kind: "label",
      at: {
        x: 948,
        y: 117,
        w: 442,
        h: 41,
      },
      text: "Usa pesos para servidores heterogêneos",
      align: "center",
    },
    {
      id: "alg_lc_h",
      tone: "good",
      kind: "label",
      at: {
        x: 664,
        y: 154,
        w: 198,
        h: 41,
      },
      text: "Least Connections",
      align: "center",
    },
    {
      id: "alg_lc1",
      kind: "label",
      at: {
        x: 495,
        y: 179,
        w: 535,
        h: 41,
      },
      text: "Rotear para servidor com menos conexões ativas",
      align: "center",
    },
    {
      id: "alg_lc2",
      kind: "label",
      at: {
        x: 466,
        y: 199,
        w: 593,
        h: 41,
      },
      text: "Ideal para requests de duração variável (long-poll)",
      align: "center",
    },
    {
      id: "alg_ih_h",
      tone: "warn",
      kind: "label",
      at: {
        x: 1128,
        y: 154,
        w: 81,
        h: 41,
      },
      text: "IP Hash",
      align: "center",
    },
    {
      id: "alg_ih1",
      kind: "label",
      at: {
        x: 930,
        y: 179,
        w: 477,
        h: 41,
      },
      text: "hash(client_IP) % N → mesmo server sempre",
      align: "center",
    },
    {
      id: "alg_ih2",
      kind: "label",
      at: {
        x: 890,
        y: 199,
        w: 558,
        h: 41,
      },
      text: "Pseudo-sticky (sem cookie); falha se server cair",
      align: "center",
    },
    {
      id: "alg_rl_h",
      tone: "accent2",
      kind: "label",
      at: {
        x: 725,
        y: 237,
        w: 75,
        h: 41,
      },
      text: "Random",
      align: "center",
    },
    {
      id: "alg_rl1",
      kind: "label",
      at: {
        x: 571,
        y: 262,
        w: 384,
        h: 41,
      },
      text: "Servidor escolhido aleatoriamente",
      align: "center",
    },
    {
      id: "alg_rl2",
      kind: "label",
      at: {
        x: 513,
        y: 282,
        w: 500,
        h: 41,
      },
      text: "Simples; performance similar ao Round Robin",
      align: "center",
    },
    {
      id: "alg_ch_h",
      tone: "good",
      kind: "label",
      at: {
        x: 1082,
        y: 237,
        w: 174,
        h: 41,
      },
      text: "Consistent Hash",
      align: "center",
    },
    {
      id: "alg_ch1",
      kind: "label",
      at: {
        x: 913,
        y: 262,
        w: 512,
        h: 41,
      },
      text: "hash(key) no ring → mesmo servidor por chave",
      align: "center",
    },
    {
      id: "alg_ch2",
      kind: "label",
      at: {
        x: 977,
        y: 282,
        w: 384,
        h: 41,
      },
      text: "Ideal para cache (cache affinity)",
      align: "center",
    },
    {
      id: "alg_hc_h",
      tone: "hot",
      kind: "label",
      at: {
        x: 670,
        y: 317,
        w: 186,
        h: 41,
      },
      text: "🏥 Health Checks",
      align: "center",
    },
    {
      id: "alg_hc1",
      kind: "label",
      at: {
        x: 460,
        y: 342,
        w: 605,
        h: 41,
      },
      text: "Active: GET /health a cada 5s → 2 falhas = unhealthy",
      align: "center",
    },
    {
      id: "alg_hc2",
      kind: "label",
      at: {
        x: 501,
        y: 364,
        w: 523,
        h: 41,
      },
      text: "Passive: erro na req real → penaliza servidor",
      align: "center",
    },
    {
      id: "alg_hc3",
      kind: "label",
      at: {
        x: 478,
        y: 387,
        w: 570,
        h: 41,
      },
      text: "Graceful drain: stop new requests antes de deploy",
      align: "center",
    },
    {
      id: "alg_hc4",
      kind: "label",
      at: {
        x: 489,
        y: 412,
        w: 546,
        h: 41,
      },
      text: "Connection draining: aguarda requests in-flight",
      align: "center",
    },
    {
      id: "ssl_bg",
      kind: "box",
      at: {
        x: 750,
        y: 250,
        w: 813,
        h: 200,
      },
      variant: "outline",
    },
    {
      id: "ssl_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 1052,
        y: 252,
        w: 209,
        h: 41,
      },
      text: "🔒 SSL Termination",
      align: "center",
    },
    {
      id: "ssl1",
      kind: "label",
      at: {
        x: 495,
        y: 284,
        w: 535,
        h: 41,
      },
      text: "LB decifra TLS → backend recebe HTTP (sem TLS)",
      align: "center",
    },
    {
      id: "ssl2",
      kind: "label",
      at: {
        x: 704,
        y: 309,
        w: 116,
        h: 41,
      },
      text: "Vantagens:",
      align: "center",
    },
    {
      id: "ssl3",
      tone: "good",
      kind: "label",
      at: {
        x: 518,
        y: 332,
        w: 488,
        h: 41,
      },
      text: "→ Certificados gerenciados num único lugar",
      align: "center",
    },
    {
      id: "ssl4",
      tone: "good",
      kind: "label",
      at: {
        x: 536,
        y: 354,
        w: 453,
        h: 41,
      },
      text: "→ Offload CPU de TLS (handshake é caro)",
      align: "center",
    },
    {
      id: "ssl5",
      tone: "good",
      kind: "label",
      at: {
        x: 495,
        y: 377,
        w: 535,
        h: 41,
      },
      text: "→ LB pode inspecionar/rotear por conteúdo HTTP",
      align: "center",
    },
    {
      id: "ssl6",
      kind: "label",
      at: {
        x: 449,
        y: 399,
        w: 628,
        h: 41,
      },
      text: "SSL Passthrough: LB não decifra → backend cuida do TLS",
      align: "center",
    },
    {
      id: "ssl7",
      kind: "label",
      at: {
        x: 431,
        y: 424,
        w: 663,
        h: 41,
      },
      text: "mTLS end-to-end: re-cifra no LB → backend (re-encryption)",
      align: "center",
    },
    {
      id: "glb_bg",
      kind: "box",
      at: {
        x: 750,
        y: 675,
        w: 813,
        h: 188,
      },
      variant: "outline",
    },
    {
      id: "glb_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1017,
        y: 677,
        w: 279,
        h: 41,
      },
      text: "🌍 Global Load Balancing",
      align: "center",
    },
    {
      id: "g1",
      kind: "label",
      at: {
        x: 437,
        y: 709,
        w: 651,
        h: 41,
      },
      text: "GeoDNS: resolve domínio para IP do servidor mais próximo",
      align: "center",
    },
    {
      id: "g2",
      kind: "label",
      at: {
        x: 344,
        y: 734,
        w: 837,
        h: 41,
      },
      text: "Anycast IP: mesmo IP anunciado em múltiplos PoPs — roteamento BGP decide",
      align: "center",
    },
    {
      id: "g3",
      kind: "label",
      at: {
        x: 466,
        y: 759,
        w: 593,
        h: 41,
      },
      text: "CDN: edge servers com cache → reduz latência global",
      align: "center",
    },
    {
      id: "g4",
      kind: "label",
      at: {
        x: 414,
        y: 784,
        w: 698,
        h: 41,
      },
      text: "Failover geográfico: região primária cai → secundária assume",
      align: "center",
    },
    {
      id: "g5",
      kind: "label",
      at: {
        x: 443,
        y: 809,
        w: 639,
        h: 41,
      },
      text: "Ex: Cloudflare, AWS Route 53 (latency routing), GCP GLB",
      align: "center",
    },
    {
      id: "g6",
      kind: "label",
      at: {
        x: 437,
        y: 834,
        w: 651,
        h: 41,
      },
      text: "Health check global: remover região inteira se unhealthy",
      align: "center",
    },
    {
      id: "l7f_bg",
      kind: "box",
      at: {
        x: 25,
        y: 538,
        w: 700,
        h: 138,
      },
      variant: "outline",
    },
    {
      id: "l7f_title",
      tone: "good",
      kind: "label",
      at: {
        x: 294,
        y: 539,
        w: 163,
        h: 41,
      },
      text: "🧠 L7 Features",
      align: "center",
    },
    {
      id: "l7f1",
      kind: "label",
      at: {
        x: -358,
        y: 564,
        w: 791,
        h: 41,
      },
      text: "Host routing: api.app.com → backend_api    www.app.com → backend_web",
      align: "center",
    },
    {
      id: "l7f2",
      kind: "label",
      at: {
        x: -329,
        y: 589,
        w: 732,
        h: 41,
      },
      text: "Path routing: /images/ → storage-service    /api/ → api-service",
      align: "center",
    },
    {
      id: "l7f3",
      kind: "label",
      at: {
        x: -288,
        y: 614,
        w: 651,
        h: 41,
      },
      text: "Sticky sessions: Set-Cookie: SERVERID=srv2 → sempre srv2",
      align: "center",
    },
    {
      id: "l7f4",
      kind: "label",
      at: {
        x: -282,
        y: 639,
        w: 639,
        h: 41,
      },
      text: "Rate limiting, WAF, header rewrite, A/B testing, canary",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: single server",
      duration: 6500,
      add: ["cli1", "cli2", "cli3", "srv1", "a_ccli1", "a_ccli2", "a_ccli3"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "srv1",
        placement: "right",
        text: "Um único servidor: **gargalo** de capacidade, **SPOF** (falha = downtime total), sem escala horizontal. Adicionar mais servidores sem coordenação → qual servidor o cliente acessa?",
      },
    },
    {
      id: "s2",
      title: "Load Balancer: 1 IP, N servidores",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "lb_vip",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "srv1",
        "srv2",
        "srv3",
        "srv4",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "a_ssrv4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "lb",
        placement: "right",
        text: "O LB recebe todas as requests no **VIP** (Virtual IP), decide qual backend atender, e encaminha. Clientes sempre falam com o mesmo IP — o LB é o ponto de entrada único.",
      },
    },
    {
      id: "s3",
      title: "L4 vs L7: onde a decisão acontece",
      duration: 6500,
      add: [
        "cli1",
        "lb",
        "srv1",
        "srv2",
        "a_ccli1",
        "a_ssrv1",
        "a_ssrv2",
        "l4_bg",
        "l4_title",
        "l4h1",
        "l4h2",
        "l4v1",
        "l4v2",
        "l4v3",
        "l4v4",
        "l4v5",
        "l4v6",
        "l4v7",
        "l4v8",
        "l4v9",
        "l4v10",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "l4_bg",
          do: "highlight",
        },
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l4_bg",
        placement: "left",
        text: "**L4**: decisão por IP:port — sem abrir o payload TCP/UDP. Mais rápido, menor latência. **L7**: abre o HTTP e decide por header/URL/cookie. Mais funcional, permite SSL termination e roteamento semântico.",
      },
    },
    {
      id: "s4",
      title: "Round Robin e Weighted Round Robin",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "alg_bg",
        "alg_title",
        "alg_rr_h",
        "alg_rr1",
        "alg_rr2",
        "alg_wt_h",
        "alg_wt1",
        "alg_wt2",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
        {
          at: 0,
          target: "srv1",
          do: "highlight",
        },
        {
          at: 0,
          target: "srv2",
          do: "highlight",
        },
        {
          at: 0,
          target: "srv3",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "alg_bg",
        placement: "left",
        text: "**Round Robin**: distribui requests em sequência circular 1→2→3→1→... Simples e justo quando os servidores têm a mesma capacidade.\n**Weighted**: se Server 1 tem 4 vCPUs e Server 2 tem 2 vCPUs, usar weights 2:1.",
      },
    },
    {
      id: "s5",
      title: "Least Connections e IP Hash",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "alg_bg",
        "alg_title",
        "alg_lc_h",
        "alg_lc1",
        "alg_lc2",
        "alg_ih_h",
        "alg_ih1",
        "alg_ih2",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "alg_bg",
        placement: "left",
        text: "**Least Connections**: envia para o servidor com menos conexões ativas — ideal quando requests têm durações muito diferentes (ex: upload vs query simples).\n**IP Hash**: `hash(IP) % N` → mesmo cliente sempre vai para o mesmo servidor. Útil para cache com affinity.",
        why: "IP Hash tem um problema: se um servidor cai, há redistribuição desigual — o Consistent Hash é mais robusto para isso.",
      },
    },
    {
      id: "s6",
      title: "Health Checks: detectar servidores falhos",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "srv4",
        "srv4_x",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "alg_bg",
        "alg_title",
        "alg_hc_h",
        "alg_hc1",
        "alg_hc2",
        "alg_hc3",
        "alg_hc4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "srv4",
          do: "highlight",
        },
        {
          at: 0,
          target: "srv4_x",
          do: "highlight",
        },
        {
          at: 0,
          target: "alg_hc_h",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "srv4",
        placement: "right",
        text: "**Active health check**: LB envia `GET /health` a cada 5s → 2 falhas consecutivas → servidor marcado como unhealthy → removido do pool. **Passive**: monitorar erros nas requisições reais.",
        why: "`/health` deve verificar dependências (banco, cache) — responder 200 só se o servidor consegue processar requests com sucesso.",
      },
    },
    {
      id: "s7",
      title: "SSL Termination: centralizando TLS no LB",
      duration: 6500,
      add: [
        "cli1",
        "lb",
        "srv1",
        "srv2",
        "a_ccli1",
        "a_ssrv1",
        "a_ssrv2",
        "ssl_bg",
        "ssl_title",
        "ssl1",
        "ssl2",
        "ssl3",
        "ssl4",
        "ssl5",
        "ssl6",
        "ssl7",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
        {
          at: 0,
          target: "ssl_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ssl_bg",
        placement: "left",
        text: "LB decifra TLS e encaminha HTTP para o backend. Vantagens: **1 único certificado** gerenciado no LB, **offload de CPU** (handshake TLS é computacionalmente caro), e permite ao L7 inspecionar o conteúdo HTTP.",
      },
    },
    {
      id: "s8",
      title: "Layer 7: roteamento por conteúdo HTTP",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "l7f_bg",
        "l7f_title",
        "l7f1",
        "l7f2",
        "l7f3",
        "l7f4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lb",
          do: "highlight",
        },
        {
          at: 0,
          target: "l7f_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "l7f_bg",
        placement: "top",
        text: "L7 LB permite **host-based routing** (`api.empresa.com` → cluster API, `www.empresa.com` → frontend), **path routing** (`/images/` → CDN origin), **sticky sessions** via cookie, e até WAF, rate limiting e canary deploys.",
      },
    },
    {
      id: "s9",
      title: "Consistent Hash e algoritmos avançados",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "alg_bg",
        "alg_title",
        "alg_ch_h",
        "alg_ch1",
        "alg_ch2",
        "alg_rl_h",
        "alg_rl1",
        "alg_rl2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "alg_bg",
        placement: "left",
        text: "**Consistent Hash** é superior ao IP Hash para cache affinity — quando um servidor cai, apenas ~1/N chaves precisam ser remapeadas (vs todos com `hash % N`). Perfeito para serviços stateful como cache.",
      },
    },
    {
      id: "s10",
      title: "Global Load Balancing",
      duration: 6500,
      add: [
        "cli1",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "a_ccli1",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "glb_bg",
        "glb_title",
        "g1",
        "g2",
        "g3",
        "g4",
        "g5",
        "g6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "glb_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "glb_bg",
        placement: "left",
        text: "**GeoDNS**: DNS resolve para o servidor mais próximo geograficamente. **Anycast**: mesmo IP anunciado em múltiplos data centers — BGP roteia para o mais próximo. Ambos reduzem latência global e permitem failover de região.",
      },
    },
    {
      id: "s11",
      title: "Quiz",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "srv1",
        "srv2",
        "srv3",
        "srv4",
        "srv4_x",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
      ],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question:
          "Qual algoritmo de balanceamento é mais adequado para requests com durações muito variadas (ex: uploads longos misturados com queries rápidas)?",
        options: [
          "Round Robin — distribui uniformemente em sequência circular",
          "Least Connections — envia para o servidor com menos conexões ativas",
          "IP Hash — garante que o mesmo cliente vai sempre para o mesmo servidor",
          "Random — escolha aleatória tem distribuição estatisticamente uniforme",
        ],
        answer: 1,
        explain:
          "**Least Connections** é o melhor para workloads com durações variadas: um servidor que está processando um upload de 5 minutos recebe menos requests novas do que um servidor que só faz queries de 10ms. Round Robin seria injusto — enviaria a mesma quantidade de requests para ambos, sobrecarregando o servidor com o upload longo.",
      },
    },
    {
      id: "s12",
      title: "Resumo: Load Balancer",
      duration: 6500,
      add: [
        "cli1",
        "cli2",
        "cli3",
        "lb",
        "lb_vip",
        "srv1",
        "srv2",
        "srv3",
        "srv4",
        "srv4_x",
        "a_ccli1",
        "a_ccli2",
        "a_ccli3",
        "a_ssrv1",
        "a_ssrv2",
        "a_ssrv3",
        "l4_bg",
        "l4_title",
        "l4h1",
        "l4h2",
        "l4v1",
        "l4v2",
        "alg_bg",
        "alg_title",
        "alg_rr_h",
        "alg_lc_h",
        "alg_ih_h",
        "alg_hc_h",
        "alg_hc1",
        "ssl_bg",
        "ssl_title",
        "ssl1",
        "ssl3",
        "glb_bg",
        "glb_title",
        "g1",
        "g2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "lb",
        placement: "right",
        text: "LB distribui tráfego entre N servidores via VIP único. L4 (IP:port, rápido) vs L7 (HTTP content, funcional). Algoritmos: Round Robin, Least Conn, IP Hash, Consistent Hash. Health checks removem unhealthy servers. SSL termination centraliza TLS. Global LB via GeoDNS/Anycast.",
      },
    },
  ],
};

export const loadBalancer = validateExplainer(data);
