import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/mcp.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "mcp",
  title: "Model Context Protocol (MCP)",
  subtitle: "Como LLMs se conectam a ferramentas e dados externos",
  category: "IA & Agentes",
  tags: ["mcp", "agentes", "protocolo"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "h_host",
      kind: "box",
      at: {
        x: 50,
        y: 38,
        w: 350,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "h_lbl",
      kind: "label",
      at: {
        x: 45,
        y: 47,
        w: 360,
        h: 41,
      },
      text: "HOST (app, IDE, Claude Desktop)",
      align: "center",
      muted: true,
    },
    {
      id: "h_llm",
      kind: "box",
      at: {
        x: 88,
        y: 88,
        w: 275,
        h: 88,
      },
      label: "🧠 LLM",
      variant: "outline",
    },
    {
      id: "h_client",
      kind: "box",
      at: {
        x: 88,
        y: 213,
        w: 275,
        h: 70,
      },
      label: "MCP Client",
      variant: "outline",
    },
    {
      id: "a_lc",
      tone: "accent",
      kind: "connector",
      from: {
        x: 225,
        y: 178,
      },
      to: {
        x: 225,
        y: 210,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "p_line",
      kind: "connector",
      from: {
        x: 800,
        y: 63,
      },
      to: {
        x: 800,
        y: 850,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "p_lbl",
      kind: "label",
      at: {
        x: 620,
        y: 27,
        w: 360,
        h: 41,
      },
      text: "JSON-RPC 2.0 (stdio / HTTP+SSE)",
      align: "center",
      muted: true,
    },
    {
      id: "s_fs",
      kind: "box",
      at: {
        x: 1063,
        y: 75,
        w: 325,
        h: 100,
      },
      label: "🗂️ MCP Server: Filesystem",
      sub: "Tools · Resources · Prompts",
      variant: "outline",
    },
    {
      id: "s_gh",
      kind: "box",
      at: {
        x: 1063,
        y: 225,
        w: 325,
        h: 100,
      },
      label: "🐙 MCP Server: GitHub",
      sub: "Tools · Resources · Prompts",
      variant: "outline",
    },
    {
      id: "s_db",
      kind: "box",
      at: {
        x: 1063,
        y: 375,
        w: 325,
        h: 100,
      },
      label: "🗄️ MCP Server: Database",
      sub: "Tools · Resources · Prompts",
      variant: "outline",
    },
    {
      id: "s_api",
      kind: "box",
      at: {
        x: 1063,
        y: 525,
        w: 325,
        h: 100,
      },
      label: "🌐 MCP Server: APIs externas",
      sub: "Tools · Resources · Prompts",
      variant: "outline",
    },
    {
      id: "m_init",
      tone: "accent",
      kind: "connector",
      from: {
        x: 400,
        y: 150,
      },
      to: {
        x: 788,
        y: 150,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_init_l",
      kind: "label",
      at: {
        x: 524,
        y: 113,
        w: 140,
        h: 41,
      },
      text: "initialize →",
      align: "center",
      muted: true,
    },
    {
      id: "m_init_r",
      tone: "good",
      kind: "connector",
      from: {
        x: 813,
        y: 200,
      },
      to: {
        x: 400,
        y: 200,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_init_r_l",
      kind: "label",
      at: {
        x: 525,
        y: 163,
        w: 163,
        h: 41,
      },
      text: "← capabilities",
      align: "center",
      muted: true,
    },
    {
      id: "m_tools",
      tone: "accent",
      kind: "connector",
      from: {
        x: 400,
        y: 275,
      },
      to: {
        x: 788,
        y: 275,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_tools_l",
      kind: "label",
      at: {
        x: 524,
        y: 238,
        w: 140,
        h: 41,
      },
      text: "tools/list →",
      align: "center",
      muted: true,
    },
    {
      id: "m_tools_r",
      tone: "good",
      kind: "connector",
      from: {
        x: 813,
        y: 325,
      },
      to: {
        x: 400,
        y: 325,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_tools_r_l",
      kind: "label",
      at: {
        x: 496,
        y: 288,
        w: 221,
        h: 41,
      },
      text: "← [tool_1, tool_2…]",
      align: "center",
      muted: true,
    },
    {
      id: "m_call",
      tone: "warn",
      kind: "connector",
      from: {
        x: 400,
        y: 425,
      },
      to: {
        x: 788,
        y: 425,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_call_l",
      kind: "label",
      at: {
        x: 437,
        y: 388,
        w: 314,
        h: 41,
      },
      text: "tools/call { name, args } →",
      align: "center",
      muted: true,
    },
    {
      id: "m_call_r",
      tone: "good",
      kind: "connector",
      from: {
        x: 813,
        y: 475,
      },
      to: {
        x: 400,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_call_r_l",
      kind: "label",
      at: {
        x: 537,
        y: 438,
        w: 140,
        h: 41,
      },
      text: "← { result }",
      align: "center",
      muted: true,
    },
    {
      id: "d_srv_inner",
      kind: "box",
      at: {
        x: 1063,
        y: 75,
        w: 325,
        h: 375,
      },
      variant: "outline",
    },
    {
      id: "d_srv_lbl",
      kind: "label",
      at: {
        x: 1126,
        y: 82,
        w: 198,
        h: 41,
      },
      text: "MCP Server expõe:",
      align: "center",
    },
    {
      id: "d_tools",
      kind: "token",
      at: {
        x: 1088,
        y: 125,
        w: 275,
        h: 65,
      },
      text: "🔧 Tools",
    },
    {
      id: "d_res",
      kind: "token",
      at: {
        x: 1088,
        y: 210,
        w: 275,
        h: 65,
      },
      text: "📄 Resources",
    },
    {
      id: "d_prm",
      kind: "token",
      at: {
        x: 1088,
        y: 295,
        w: 275,
        h: 65,
      },
      text: "💬 Prompts",
    },
    {
      id: "d_srv_cap_lbl",
      kind: "label",
      at: {
        x: 1004,
        y: 364,
        w: 442,
        h: 41,
      },
      text: "Servidor anuncia tudo via capabilities",
      align: "center",
      muted: true,
    },
    {
      id: "fl_lbl",
      kind: "label",
      at: {
        x: 602,
        y: 554,
        w: 395,
        h: 41,
      },
      text: "Fluxo de uma chamada de ferramenta",
      align: "center",
    },
    {
      id: "fl_1",
      kind: "token",
      at: {
        x: 38,
        y: 613,
        w: 213,
        h: 55,
      },
      text: "① LLM decide usar tool",
    },
    {
      id: "fl_2",
      kind: "token",
      at: {
        x: 288,
        y: 613,
        w: 213,
        h: 55,
      },
      text: "② Client envia call",
    },
    {
      id: "fl_3",
      kind: "token",
      at: {
        x: 538,
        y: 613,
        w: 213,
        h: 55,
      },
      text: "③ Server executa",
    },
    {
      id: "fl_4",
      kind: "token",
      at: {
        x: 788,
        y: 613,
        w: 213,
        h: 55,
      },
      text: "④ Resultado retorna",
    },
    {
      id: "fl_5",
      kind: "token",
      at: {
        x: 1038,
        y: 613,
        w: 213,
        h: 55,
      },
      text: "⑤ LLM usa resultado",
    },
    {
      id: "a_fl12",
      tone: "accent",
      kind: "connector",
      from: {
        x: 253,
        y: 640,
      },
      to: {
        x: 285,
        y: 640,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_fl23",
      tone: "accent",
      kind: "connector",
      from: {
        x: 503,
        y: 640,
      },
      to: {
        x: 535,
        y: 640,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_fl34",
      tone: "good",
      kind: "connector",
      from: {
        x: 753,
        y: 640,
      },
      to: {
        x: 785,
        y: 640,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_fl45",
      tone: "good",
      kind: "connector",
      from: {
        x: 1003,
        y: 640,
      },
      to: {
        x: 1035,
        y: 640,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "smp_lbl",
      kind: "label",
      at: {
        x: 556,
        y: 692,
        w: 488,
        h: 41,
      },
      text: "Sampling: servidor pede completions ao LLM",
      align: "center",
    },
    {
      id: "smp_box",
      kind: "box",
      at: {
        x: 475,
        y: 738,
        w: 650,
        h: 88,
      },
      label: "Server → sampling/createMessage → Host → LLM → resposta → Server",
      sub: "(fluxo inverso: servidor chama o modelo via host)",
      variant: "outline",
    },
    {
      id: "sec_box",
      kind: "box",
      at: {
        x: 125,
        y: 700,
        w: 1350,
        h: 100,
      },
      label: "🔒 Segurança: Host controla o que cada servidor pode fazer · Usuário aprova ações sensíveis",
      sub: "Cada servidor MCP roda em processo separado · Permissões declaradas nas capabilities",
      variant: "outline",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O problema: LLMs isolados do mundo",
      duration: 9000,
      add: ["h_host", "h_lbl", "h_llm"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "h_llm",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "h_llm",
        placement: "right",
        text: "LLMs são poderosos, mas vivem dentro de uma bolha: só enxergam o que está no prompt. Para ler arquivos, chamar APIs, consultar bancos de dados ou acessar dados em tempo real, precisam de uma ponte.",
        why: "Cada integração ad-hoc é única: um plugin de IDE não funciona numa CLI, um tool de um modelo não transfere para outro. O MCP padroniza isso.",
      },
    },
    {
      id: "s2",
      title: "MCP: Host, Client e Server",
      duration: 9000,
      add: ["h_client", "a_lc", "p_line", "p_lbl", "s_fs"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "h_client",
          do: "highlight",
        },
        {
          at: 0,
          target: "p_line",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_lbl",
        placement: "bottom",
        text: "O **Model Context Protocol** define três papéis: **Host** (a aplicação que hospeda o LLM), **Client** (gerencia conexões MCP dentro do host) e **Server** (processo externo que expõe capacidades).",
        why: "A separação é intencional: o servidor MCP pode ser escrito em qualquer linguagem e rodar em qualquer lugar — local ou remoto. O protocolo é JSON-RPC 2.0.",
      },
    },
    {
      id: "s3",
      title: "O que um servidor MCP expõe",
      duration: 9000,
      add: ["d_srv_inner", "d_srv_lbl", "d_tools", "d_res", "d_prm", "d_srv_cap_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_tools",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_res",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_prm",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "d_tools",
        placement: "left",
        text: "Cada servidor MCP pode expor até três primitivas: **Tools** (funções chamáveis pelo LLM, ex.: ler_arquivo, buscar_commits), **Resources** (dados acessíveis via URI, ex.: file:///logs.txt) e **Prompts** (templates de prompt reutilizáveis).",
        why: "Tools são controladas pelo LLM (model-controlled); Resources são controladas pela aplicação (app-controlled); Prompts são expostas ao usuário para seleção.",
      },
    },
    {
      id: "s4",
      title: "Inicialização: handshake de capabilities",
      duration: 9000,
      add: ["m_init", "m_init_l", "m_init_r", "m_init_r_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_init",
          do: "draw",
        },
        {
          at: 500,
          target: "m_init_r",
          do: "draw",
        },
        {
          at: 0,
          target: "h_client",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_fs",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_init_l",
        placement: "bottom",
        text: "A conexão começa com um **handshake**: o client envia `initialize` com sua versão do protocolo, e o servidor responde com suas **capabilities** (quais primitivas suporta: tools, resources, prompts, sampling).",
        why: "O handshake permite que cliente e servidor negociem compatibilidade de versão antes de qualquer chamada real. Conexões incompatíveis são rejeitadas cedo.",
      },
    },
    {
      id: "s5",
      title: "Listagem de ferramentas disponíveis",
      duration: 9000,
      add: ["m_tools", "m_tools_l", "m_tools_r", "m_tools_r_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_tools",
          do: "draw",
        },
        {
          at: 500,
          target: "m_tools_r",
          do: "draw",
        },
        {
          at: 0,
          target: "d_tools",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_tools_l",
        placement: "bottom",
        text: "O client pede `tools/list` e recebe a lista de tools disponíveis, cada uma com **nome**, **descrição** (texto que o LLM lê para decidir quando usar) e **schema de parâmetros** (JSON Schema).",
        why: "O LLM usa as descrições para raciocinar sobre qual tool escolher e como preencher os argumentos. Boas descrições são críticas para a qualidade da integração.",
      },
    },
    {
      id: "s6",
      title: "Chamada de ferramenta: fluxo completo",
      duration: 9000,
      add: [
        "m_call",
        "m_call_l",
        "m_call_r",
        "m_call_r_l",
        "fl_lbl",
        "fl_1",
        "fl_2",
        "fl_3",
        "fl_4",
        "fl_5",
        "a_fl12",
        "a_fl23",
        "a_fl34",
        "a_fl45",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_call",
          do: "draw",
        },
        {
          at: 600,
          target: "m_call_r",
          do: "draw",
        },
        {
          at: 200,
          target: "a_fl12",
          do: "draw",
        },
        {
          at: 320,
          target: "a_fl23",
          do: "draw",
        },
        {
          at: 440,
          target: "a_fl34",
          do: "draw",
        },
        {
          at: 560,
          target: "a_fl45",
          do: "draw",
        },
        {
          at: 0,
          target: "fl_1",
          do: "highlight",
        },
        {
          at: 0,
          target: "fl_3",
          do: "highlight",
        },
        {
          at: 0,
          target: "fl_5",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "fl_lbl",
        placement: "top",
        text: "O LLM emite um `tool_use` → o Client serializa como `tools/call` com nome e args → o Server executa a ação real → retorna o resultado → o Client injeta no próximo turno do LLM como `tool_result`.",
        why: "O LLM nunca executa código diretamente — ele apenas declara a intenção. O Host/Client é quem executa e decide se deve ou não prosseguir (pode pedir aprovação do usuário).",
      },
    },
    {
      id: "s7",
      title: "Múltiplos servidores simultâneos",
      duration: 9000,
      add: ["s_gh", "s_db", "s_api"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_fs",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_gh",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_db",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_api",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_gh",
        placement: "left",
        text: "Um único Host pode conectar-se a **vários servidores MCP ao mesmo tempo**: filesystem, GitHub, banco de dados, APIs externas. O LLM enxerga todas as tools como um pool unificado e decide qual usar.",
        why: "Isso é a vantagem chave do padrão: um ecossistema de servidores MCP reutilizáveis. A comunidade já tem servidores para Slack, PostgreSQL, Brave Search, Git, Notion e dezenas de outros.",
      },
    },
    {
      id: "s8",
      title: "Sampling: servidor pede ao LLM",
      duration: 9000,
      add: ["smp_lbl", "smp_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "smp_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "smp_box",
        placement: "top",
        text: "O MCP também suporta o fluxo **inverso**: o servidor pode pedir ao Host que chame o LLM para gerar um texto (`sampling/createMessage`). Isso permite agents compostos onde o servidor orquestra sub-tarefas.",
        why: "Sampling é uma primitiva poderosa: permite que servidores criem loops de agentic behavior sem expor as credenciais do LLM. O Host mantém o controle e pode aplicar guardrails antes de cada chamada.",
      },
    },
    {
      id: "s9",
      title: "Segurança e permissões",
      duration: 9000,
      add: ["sec_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sec_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sec_box",
        placement: "top",
        text: "O Host é o **ponto de controle**: ele decide quais servidores MCP podem se conectar, quais tools o LLM pode chamar e quando solicitar aprovação do usuário. Cada servidor roda em processo separado, limitando a superfície de ataque.",
        why: "MCP segue o princípio de menor privilégio: o servidor declara o que precisa; o Host aprova ou nega. O usuário sempre pode auditar e revogar acessos.",
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Verifique seu entendimento do MCP 👇",
      },
      quiz: {
        question: "Qual primitiva do MCP é controlada pelo LLM para executar ações?",
        options: [
          "Resources — dados acessíveis via URI",
          "Prompts — templates reutilizáveis de prompt",
          "Tools — funções que o LLM decide chamar com argumentos",
          "Sampling — completions solicitados pelo servidor",
        ],
        answer: 2,
        explain:
          "Tools são model-controlled: o LLM decide quando e com quais argumentos chamá-las. Resources são app-controlled (a aplicação decide o que expor) e Prompts são user-controlled (o usuário seleciona).",
      },
    },
    {
      id: "s11",
      title: "Resumo do MCP",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "h_llm",
          do: "pulse",
          times: 2,
        },
        {
          at: 80,
          target: "h_client",
          do: "pulse",
          times: 2,
        },
        {
          at: 160,
          target: "s_fs",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "s_gh",
          do: "pulse",
          times: 2,
        },
        {
          at: 320,
          target: "s_db",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "s_api",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "h_llm",
          do: "highlight",
        },
        {
          at: 0,
          target: "h_client",
          do: "highlight",
        },
        {
          at: 0,
          target: "p_line",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_fs",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_gh",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_db",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "O MCP padroniza como LLMs se conectam ao mundo: **Host** hospeda o LLM, **Client** gerencia protocolo, **Server** expõe Tools/Resources/Prompts via JSON-RPC. Um ecossistema de servidores reutilizáveis e seguros.",
        why: "MCP é para LLMs o que USB é para hardware: uma interface universal que elimina integrações one-off e constrói um ecossistema compartilhado.",
      },
    },
  ],
};

export const mcp = validateExplainer(data);
