import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/mfa.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "mfa",
  title: "MFA / 2FA — Autenticação Multifator",
  category: "Segurança & Autenticação",
  tags: ["mfa", "2fa", "auth"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "f_know",
      tone: "accent",
      kind: "box",
      at: {
        x: 75,
        y: 38,
        w: 400,
        h: 88,
      },
      label: "🧠 O que você\nSABE",
      variant: "outline",
    },
    {
      id: "f_have",
      tone: "accent2",
      kind: "box",
      at: {
        x: 563,
        y: 38,
        w: 400,
        h: 88,
      },
      label: "📱 O que você\nTEM",
      variant: "outline",
    },
    {
      id: "f_is",
      tone: "good",
      kind: "box",
      at: {
        x: 1050,
        y: 38,
        w: 400,
        h: 88,
      },
      label: "👤 O que você\nÉ",
      variant: "outline",
    },
    {
      id: "f_know_sub",
      kind: "label",
      at: {
        x: 112,
        y: 124,
        w: 326,
        h: 41,
      },
      text: "Senha, PIN, pergunta\nsecreta",
      align: "center",
    },
    {
      id: "f_have_sub",
      kind: "label",
      at: {
        x: 646,
        y: 124,
        w: 233,
        h: 41,
      },
      text: "TOTP, FIDO2,\nSMS OTP",
      align: "center",
    },
    {
      id: "f_is_sub",
      kind: "label",
      at: {
        x: 1047,
        y: 124,
        w: 407,
        h: 41,
      },
      text: "Biometria (face,\nimpressão digital)",
      align: "center",
    },
    {
      id: "totp_bg",
      kind: "box",
      at: {
        x: 525,
        y: 225,
        w: 313,
        h: 263,
      },
      variant: "outline",
    },
    {
      id: "totp_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 582,
        y: 227,
        w: 198,
        h: 41,
      },
      text: "⏱ TOTP (RFC 6238)",
      align: "center",
    },
    {
      id: "t1",
      kind: "label",
      at: {
        x: 491,
        y: 259,
        w: 93,
        h: 41,
      },
      text: "Fórmula:",
      align: "center",
    },
    {
      id: "totp_form",
      kind: "box",
      at: {
        x: 538,
        y: 298,
        w: 288,
        h: 33,
      },
      label: "HMAC-SHA1(secret, ⌊time/30⌋)",
      variant: "outline",
    },
    {
      id: "t2",
      kind: "label",
      at: {
        x: 392,
        y: 327,
        w: 291,
        h: 41,
      },
      text: "→ últimos 6 dígitos = OTP",
      align: "center",
    },
    {
      id: "t3",
      kind: "label",
      at: {
        x: 363,
        y: 352,
        w: 349,
        h: 41,
      },
      text: "Janela: ±1 passo (clock drift)",
      align: "center",
    },
    {
      id: "t4",
      kind: "label",
      at: {
        x: 392,
        y: 379,
        w: 291,
        h: 41,
      },
      text: "Secret: base32 no QR code",
      align: "center",
    },
    {
      id: "totp_qr",
      kind: "box",
      at: {
        x: 538,
        y: 423,
        w: 288,
        h: 35,
      },
      label: "otpauth://totp/App?secret=BASE32...",
      variant: "outline",
    },
    {
      id: "t5",
      kind: "label",
      at: {
        x: 398,
        y: 452,
        w: 279,
        h: 41,
      },
      text: "Apps: Google Auth, Authy",
      align: "center",
    },
    {
      id: "wa_bg",
      kind: "box",
      at: {
        x: 875,
        y: 213,
        w: 363,
        h: 275,
      },
      variant: "outline",
    },
    {
      id: "wa_title",
      tone: "good",
      kind: "label",
      at: {
        x: 946,
        y: 214,
        w: 221,
        h: 41,
      },
      text: "🔐 FIDO2 / WebAuthn",
      align: "center",
    },
    {
      id: "w1",
      kind: "label",
      at: {
        x: 835,
        y: 247,
        w: 105,
        h: 41,
      },
      text: "Registro:",
      align: "center",
    },
    {
      id: "w2",
      kind: "label",
      at: {
        x: 690,
        y: 272,
        w: 395,
        h: 41,
      },
      text: "credentials.create() → attestation",
      align: "center",
    },
    {
      id: "w3",
      kind: "label",
      at: {
        x: 643,
        y: 297,
        w: 488,
        h: 41,
      },
      text: "Servidor guarda public key + credential_id",
      align: "center",
    },
    {
      id: "w4",
      kind: "label",
      at: {
        x: 812,
        y: 327,
        w: 151,
        h: 41,
      },
      text: "Autenticação:",
      align: "center",
    },
    {
      id: "w5",
      kind: "label",
      at: {
        x: 667,
        y: 352,
        w: 442,
        h: 41,
      },
      text: "credentials.get() → assertion assinada",
      align: "center",
    },
    {
      id: "w6",
      kind: "label",
      at: {
        x: 661,
        y: 377,
        w: 453,
        h: 41,
      },
      text: "Servidor verifica com public key stored",
      align: "center",
    },
    {
      id: "w7",
      tone: "good",
      kind: "label",
      at: {
        x: 777,
        y: 407,
        w: 221,
        h: 41,
      },
      text: "Phishing-resistant:",
      align: "center",
    },
    {
      id: "w8",
      tone: "good",
      kind: "label",
      at: {
        x: 585,
        y: 432,
        w: 605,
        h: 41,
      },
      text: "challenge vinculado ao domínio → sites falsos falham",
      align: "center",
    },
    {
      id: "w9",
      tone: "good",
      kind: "label",
      at: {
        x: 707,
        y: 457,
        w: 360,
        h: 41,
      },
      text: "Private key NUNCA sai do device",
      align: "center",
    },
    {
      id: "sms_bg",
      kind: "box",
      at: {
        x: 875,
        y: 513,
        w: 363,
        h: 100,
      },
      variant: "outline",
    },
    {
      id: "sms_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 934,
        y: 514,
        w: 244,
        h: 41,
      },
      text: "📵 SMS OTP — Inseguro",
      align: "center",
    },
    {
      id: "sms1",
      tone: "hot",
      kind: "label",
      at: {
        x: 649,
        y: 539,
        w: 477,
        h: 41,
      },
      text: "SIM swap: atacante redireciona seu número",
      align: "center",
    },
    {
      id: "sms2",
      tone: "hot",
      kind: "label",
      at: {
        x: 643,
        y: 564,
        w: 488,
        h: 41,
      },
      text: "SS7 attack: intercepta SMS na rede telecom",
      align: "center",
    },
    {
      id: "sms3",
      tone: "warn",
      kind: "label",
      at: {
        x: 655,
        y: 587,
        w: 465,
        h: 41,
      },
      text: "Usar apenas como fallback, não único 2FA",
      align: "center",
    },
    {
      id: "lf_user",
      tone: "accent",
      kind: "box",
      at: {
        x: 75,
        y: 525,
        w: 163,
        h: 63,
      },
      label: "👤 Usuário",
      variant: "outline",
    },
    {
      id: "lf_app",
      tone: "accent2",
      kind: "box",
      at: {
        x: 325,
        y: 525,
        w: 163,
        h: 63,
      },
      label: "🌐 App",
      variant: "outline",
    },
    {
      id: "lf_srv",
      tone: "good",
      kind: "box",
      at: {
        x: 575,
        y: 525,
        w: 163,
        h: 63,
      },
      label: "⚙️ Servidor",
      variant: "outline",
    },
    {
      id: "lfa1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 238,
        y: 556,
      },
      to: {
        x: 325,
        y: 556,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa1_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 182,
        y: 521,
        w: 198,
        h: 41,
      },
      text: "① Usuário + Senha",
      align: "center",
    },
    {
      id: "lfa2",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 488,
        y: 556,
      },
      to: {
        x: 575,
        y: 556,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa2_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 438,
        y: 521,
        w: 186,
        h: 41,
      },
      text: "② Verifica senha",
      align: "center",
    },
    {
      id: "lfa3",
      tone: "warn",
      kind: "connector",
      from: {
        x: 575,
        y: 569,
      },
      to: {
        x: 325,
        y: 569,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa3_l",
      tone: "warn",
      kind: "label",
      at: {
        x: 363,
        y: 533,
        w: 174,
        h: 41,
      },
      text: "③ Pede 2º fator",
      align: "center",
    },
    {
      id: "lfa4",
      tone: "warn",
      kind: "connector",
      from: {
        x: 325,
        y: 575,
      },
      to: {
        x: 238,
        y: 575,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa4_l",
      tone: "warn",
      kind: "label",
      at: {
        x: 171,
        y: 539,
        w: 221,
        h: 41,
      },
      text: "③ Exibe TOTP prompt",
      align: "center",
    },
    {
      id: "lfa5",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 238,
        y: 588,
      },
      to: {
        x: 325,
        y: 588,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa5_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 159,
        y: 552,
        w: 244,
        h: 41,
      },
      text: "④ Código TOTP: 847291",
      align: "center",
    },
    {
      id: "lfa6",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 488,
        y: 588,
      },
      to: {
        x: 575,
        y: 588,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa6_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 456,
        y: 552,
        w: 151,
        h: 41,
      },
      text: "⑤ Valida TOTP",
      align: "center",
    },
    {
      id: "lfa7",
      tone: "good",
      kind: "connector",
      from: {
        x: 575,
        y: 600,
      },
      to: {
        x: 325,
        y: 600,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lfa7_l",
      tone: "good",
      kind: "label",
      at: {
        x: 363,
        y: 564,
        w: 174,
        h: 41,
      },
      text: "⑥ Sessão criada",
      align: "center",
    },
    {
      id: "bk_bg",
      kind: "box",
      at: {
        x: 75,
        y: 688,
        w: 700,
        h: 125,
      },
      variant: "outline",
    },
    {
      id: "bk_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 274,
        y: 689,
        w: 302,
        h: 41,
      },
      text: "🔑 Backup Codes & Recovery",
      align: "center",
    },
    {
      id: "bk1",
      kind: "label",
      at: {
        x: -209,
        y: 717,
        w: 593,
        h: 41,
      },
      text: "Gerados no setup → imprimir/guardar em lugar seguro",
      align: "center",
    },
    {
      id: "bk2",
      kind: "label",
      at: {
        x: -157,
        y: 742,
        w: 488,
        h: 41,
      },
      text: 'Uso único ("break glass" — perdi o device)',
      align: "center",
    },
    {
      id: "bk3",
      kind: "label",
      at: {
        x: -215,
        y: 767,
        w: 605,
        h: 41,
      },
      text: "8-10 códigos de 8 dígitos → guardar hash no servidor",
      align: "center",
    },
    {
      id: "phi_bg",
      kind: "box",
      at: {
        x: 800,
        y: 525,
        w: 450,
        h: 200,
      },
      variant: "outline",
    },
    {
      id: "phi_title",
      tone: "good",
      kind: "label",
      at: {
        x: 891,
        y: 527,
        w: 267,
        h: 41,
      },
      text: "🛡️ Phishing-Resistance",
      align: "center",
    },
    {
      id: "phi1",
      tone: "hot",
      kind: "label",
      at: {
        x: 638,
        y: 559,
        w: 349,
        h: 41,
      },
      text: "TOTP: NÃO é phishing-resistant",
      align: "center",
    },
    {
      id: "phi2",
      tone: "hot",
      kind: "label",
      at: {
        x: 580,
        y: 584,
        w: 465,
        h: 41,
      },
      text: "→ user pode digitar código em site falso",
      align: "center",
    },
    {
      id: "phi3",
      tone: "good",
      kind: "label",
      at: {
        x: 627,
        y: 614,
        w: 372,
        h: 41,
      },
      text: "FIDO2: SIM, é phishing-resistant",
      align: "center",
    },
    {
      id: "phi4",
      tone: "good",
      kind: "label",
      at: {
        x: 580,
        y: 639,
        w: 465,
        h: 41,
      },
      text: "→ challenge inclui origin (domínio real)",
      align: "center",
    },
    {
      id: "phi5",
      tone: "good",
      kind: "label",
      at: {
        x: 597,
        y: 664,
        w: 430,
        h: 41,
      },
      text: "→ falha silenciosamente em site falso",
      align: "center",
    },
    {
      id: "phi6",
      tone: "good",
      kind: "label",
      at: {
        x: 621,
        y: 689,
        w: 384,
        h: 41,
      },
      text: "→ recomendado para alta segurança",
      align: "center",
    },
    {
      id: "why_bg",
      kind: "box",
      at: {
        x: 75,
        y: 213,
        w: 425,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "why_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 125,
        y: 214,
        w: 326,
        h: 41,
      },
      text: "⚠️ Por que 1 fator não basta",
      align: "center",
    },
    {
      id: "why1",
      tone: "hot",
      kind: "label",
      at: {
        x: -133,
        y: 244,
        w: 442,
        h: 41,
      },
      text: "Phishing: roubo de senha em site falso",
      align: "center",
    },
    {
      id: "why2",
      tone: "hot",
      kind: "label",
      at: {
        x: -168,
        y: 269,
        w: 512,
        h: 41,
      },
      text: "Credential stuffing: 8B+ credenciais vazadas",
      align: "center",
    },
    {
      id: "why3",
      tone: "hot",
      kind: "label",
      at: {
        x: -99,
        y: 294,
        w: 372,
        h: 41,
      },
      text: "Keyloggers: captura de digitação",
      align: "center",
    },
    {
      id: "why4",
      tone: "good",
      kind: "label",
      at: {
        x: -162,
        y: 322,
        w: 500,
        h: 41,
      },
      text: "Com MFA: atacante precisa de senha + device",
      align: "center",
    },
    {
      id: "why5",
      tone: "good",
      kind: "label",
      at: {
        x: -110,
        y: 349,
        w: 395,
        h: 41,
      },
      text: "→ reduz 99.9% dos ataques de conta",
      align: "center",
    },
    {
      id: "why6",
      kind: "label",
      at: {
        x: -99,
        y: 377,
        w: 372,
        h: 41,
      },
      text: "   (Google internal study, 2019)",
      align: "center",
    },
    {
      id: "why7",
      kind: "label",
      at: {
        x: -139,
        y: 404,
        w: 453,
        h: 41,
      },
      text: "TOTP bom | FIDO2 melhor | SMS aceitável",
      align: "center",
    },
    {
      id: "why8",
      kind: "label",
      at: {
        x: -87,
        y: 429,
        w: 349,
        h: 41,
      },
      text: "(mas SMS melhor que sem nada!)",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Por que 1 fator não é suficiente",
      duration: 6500,
      add: [
        "f_know",
        "f_know_sub",
        "why_bg",
        "why_title",
        "why1",
        "why2",
        "why3",
        "why4",
        "why5",
        "why6",
        "why7",
        "why8",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "f_know",
        placement: "right",
        text: "Credenciais são roubadas constantemente: phishing, credential stuffing, keyloggers. Apenas senha = 1 ponto de falha. MFA adiciona um segundo fator independente.",
      },
    },
    {
      id: "s2",
      title: "Os 3 fatores de autenticação",
      duration: 6500,
      add: ["f_know", "f_know_sub", "f_have", "f_have_sub", "f_is", "f_is_sub"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "f_have",
        placement: "bottom",
        text: "**Saber** (senha, PIN): fácil de phishing. **Ter** (device com TOTP/FIDO2): precisa roubar o aparelho. **Ser** (biometria): não pode ser compartilhado. MFA combina ≥2 fatores **diferentes**.",
        why: '2FA com duas senhas diferentes não é MFA real — ambas pertencem ao mesmo fator "saber".',
      },
    },
    {
      id: "s3",
      title: "TOTP: senha que muda a cada 30s",
      duration: 6500,
      add: [
        "f_know",
        "f_know_sub",
        "f_have",
        "f_have_sub",
        "f_is",
        "f_is_sub",
        "totp_bg",
        "totp_title",
        "t1",
        "totp_form",
        "t2",
        "t3",
        "t4",
        "totp_qr",
        "t5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "f_have",
          do: "highlight",
        },
        {
          at: 0,
          target: "totp_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "totp_bg",
        placement: "right",
        text: "`HMAC-SHA1(secret, ⌊time/30⌋)` — ambos o app e servidor calculam o mesmo código com base no **tempo atual** e no segredo compartilhado. Código muda a cada 30s.",
        why: "O segredo está no QR code do setup. Sem acesso ao device (app authenticator), o código não pode ser gerado.",
      },
    },
    {
      id: "s4",
      title: "Setup TOTP: QR code e otpauth URI",
      duration: 6500,
      add: [
        "f_have",
        "f_have_sub",
        "totp_bg",
        "totp_title",
        "t1",
        "totp_form",
        "t2",
        "t3",
        "t4",
        "totp_qr",
        "t5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "totp_qr",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "totp_bg",
        placement: "right",
        text: "O QR code contém: `otpauth://totp/App?secret=BASE32ENCODED&issuer=MinhaApp`. O app authenticator escaneia, armazena o secret e começa a gerar OTPs — sem precisar de internet.",
      },
    },
    {
      id: "s5",
      title: "FIDO2 / WebAuthn: chave pública no servidor",
      duration: 6500,
      add: [
        "f_know",
        "f_know_sub",
        "f_have",
        "f_have_sub",
        "f_is",
        "f_is_sub",
        "wa_bg",
        "wa_title",
        "w1",
        "w2",
        "w3",
        "w4",
        "w5",
        "w6",
        "w7",
        "w8",
        "w9",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "f_have",
          do: "highlight",
        },
        {
          at: 0,
          target: "f_is",
          do: "highlight",
        },
        {
          at: 0,
          target: "wa_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "wa_bg",
        placement: "left",
        text: "O authenticator (YubiKey, biometria do phone) gera um par de chaves. O servidor guarda apenas a **chave pública**. A chave privada nunca sai do device.",
        why: "Mesmo que o servidor seja comprometido, o atacante não pode impersonar o usuário — a private key é inviolável no hardware.",
      },
    },
    {
      id: "s6",
      title: "WebAuthn: registro e autenticação",
      duration: 6500,
      add: [
        "f_have",
        "f_have_sub",
        "wa_bg",
        "wa_title",
        "w1",
        "w2",
        "w3",
        "w4",
        "w5",
        "w6",
        "w7",
        "w8",
        "w9",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "wa_bg",
        placement: "right",
        text: "**Registro**: `credentials.create()` → gera chave pública + attestation → servidor armazena.\n**Auth**: `credentials.get()` → assina challenge com private key → servidor verifica com public key. O challenge inclui o domínio → phishing falha.",
      },
    },
    {
      id: "s7",
      title: "SMS OTP: conveniente mas inseguro",
      duration: 6500,
      add: [
        "f_know",
        "f_know_sub",
        "f_have",
        "f_have_sub",
        "f_is",
        "f_is_sub",
        "sms_bg",
        "sms_title",
        "sms1",
        "sms2",
        "sms3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sms_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sms_bg",
        placement: "left",
        text: "**SIM swap**: atacante convence a operadora a transferir seu número. **SS7 attack**: falha na rede de telecomunicações permite interceptar SMS. SMS OTP é melhor que nada, mas não use como único 2FA.",
      },
    },
    {
      id: "s8",
      title: "Fluxo de login com MFA (TOTP)",
      duration: 6500,
      add: [
        "lf_user",
        "lf_app",
        "lf_srv",
        "lfa1",
        "lfa1_l",
        "lfa2",
        "lfa2_l",
        "lfa3",
        "lfa3_l",
        "lfa4",
        "lfa4_l",
        "lfa5",
        "lfa5_l",
        "lfa6",
        "lfa6_l",
        "lfa7",
        "lfa7_l",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "lf_srv",
        placement: "top",
        text: "① Usuário envia senha → ② servidor valida 1º fator → ③ pede código TOTP → ④ usuário abre app e digita código → ⑤ servidor valida TOTP → ⑥ sessão criada. Cada fator é verificado independentemente.",
      },
    },
    {
      id: "s9",
      title: "Backup Codes: break glass quando perde o device",
      duration: 6500,
      add: ["lf_user", "lf_app", "lf_srv", "bk_bg", "bk_title", "bk1", "bk2", "bk3"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "bk_bg",
        placement: "right",
        text: 'No momento do setup, o servidor gera 8-10 códigos de uso único. O usuário deve imprimí-los ou guardá-los seguramente. Servidor armazena apenas o hash. Cada código é marcado como "usado" após consumo.',
      },
    },
    {
      id: "s10",
      title: "Phishing-Resistance: TOTP vs FIDO2",
      duration: 6500,
      add: [
        "f_have",
        "f_have_sub",
        "totp_bg",
        "totp_title",
        "t1",
        "totp_form",
        "wa_bg",
        "wa_title",
        "w7",
        "w8",
        "w9",
        "phi_bg",
        "phi_title",
        "phi1",
        "phi2",
        "phi3",
        "phi4",
        "phi5",
        "phi6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "phi_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "phi_bg",
        placement: "left",
        text: "TOTP pode ser phished: o usuário é enganado a digitar o código em um site falso que o repassa em tempo real ao site real. FIDO2 vincula a assinatura ao **domínio de origem** — em site.com.br falso, o challenge falha silenciosamente.",
      },
    },
    {
      id: "s11",
      title: "Quiz",
      duration: 6500,
      add: ["f_know", "f_know_sub", "f_have", "f_have_sub", "f_is", "f_is_sub"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: 'Por que FIDO2/WebAuthn é considerado "phishing-resistant" enquanto TOTP não é?',
        options: [
          "FIDO2 usa um código mais longo (8 dígitos vs 6 do TOTP)",
          "TOTP expira em 30s, mas FIDO2 não expira nunca",
          "FIDO2 vincula a assinatura ao domínio real — um site falso não consegue o challenge válido",
          "FIDO2 requer conexão com internet enquanto TOTP funciona offline",
        ],
        answer: 2,
        explain:
          "No WebAuthn, o servidor inclui no challenge o domínio de origem (`rpId`). O authenticator assina o challenge junto com o domínio. Se o usuário está em `banco-falso.com`, a assinatura incluirá esse domínio — o servidor do banco real rejeitará porque o `rpId` não bate. Com TOTP, o código é válido em qualquer lugar.",
      },
    },
    {
      id: "s12",
      title: "Resumo: MFA / 2FA",
      duration: 6500,
      add: [
        "f_know",
        "f_know_sub",
        "f_have",
        "f_have_sub",
        "f_is",
        "f_is_sub",
        "totp_bg",
        "totp_title",
        "t1",
        "totp_form",
        "t2",
        "t3",
        "totp_qr",
        "wa_bg",
        "wa_title",
        "w1",
        "w2",
        "w3",
        "w4",
        "w5",
        "w6",
        "w7",
        "w8",
        "phi_bg",
        "phi_title",
        "phi3",
        "phi4",
        "phi5",
        "bk_bg",
        "bk_title",
        "bk1",
        "bk2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "f_have",
        placement: "bottom",
        text: "3 fatores: saber, ter, ser. TOTP (HMAC+tempo) = prático mas phishable. FIDO2 = phishing-resistant, private key no device. SMS = evitar. Backup codes = break glass. MFA reduz 99.9% dos ataques de conta.",
      },
    },
  ],
};

export const mfa = validateExplainer(data);
