import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/oauth.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "oauth",
  title: "OAuth 2.0 / OIDC",
  subtitle: "Authorization Code Flow · PKCE · Access Token · Refresh Token · OpenID Connect",
  category: "Segurança & Autenticação",
  tags: ["oauth", "auth"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "a_user",
      kind: "box",
      at: {
        x: 31,
        y: 50,
        w: 163,
        h: 58,
      },
      label: "👤 User",
      variant: "outline",
    },
    {
      id: "a_client",
      kind: "box",
      at: {
        x: 394,
        y: 50,
        w: 163,
        h: 58,
      },
      label: "📱 Client App",
      variant: "outline",
    },
    {
      id: "a_auth",
      kind: "box",
      at: {
        x: 819,
        y: 50,
        w: 163,
        h: 58,
      },
      label: "🔐 Auth Server",
      variant: "outline",
    },
    {
      id: "a_res",
      kind: "box",
      at: {
        x: 1281,
        y: 50,
        w: 163,
        h: 58,
      },
      label: "📦 Resource Srv",
      variant: "outline",
    },
    {
      id: "lf_u",
      tone: "accent",
      kind: "connector",
      from: {
        x: 113,
        y: 108,
      },
      to: {
        x: 113,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "lf_ca",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 475,
        y: 108,
      },
      to: {
        x: 475,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "lf_as",
      tone: "warn",
      kind: "connector",
      from: {
        x: 900,
        y: 108,
      },
      to: {
        x: 900,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "lf_rs",
      tone: "good",
      kind: "connector",
      from: {
        x: 1363,
        y: 108,
      },
      to: {
        x: 1363,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "prob_box",
      kind: "box",
      at: {
        x: 200,
        y: 125,
        w: 1200,
        h: 80,
      },
      variant: "outline",
    },
    {
      id: "prob_t",
      kind: "label",
      at: {
        x: 498,
        y: 129,
        w: 605,
        h: 41,
      },
      text: "❌  Old approach: app asks for your password directly",
      align: "center",
    },
    {
      id: "prob_s",
      kind: "label",
      at: {
        x: 498,
        y: 157,
        w: 605,
        h: 41,
      },
      text: "App stores your password → full access + breach risk",
      align: "center",
      muted: true,
    },
    {
      id: "s1_uc",
      tone: "accent",
      kind: "connector",
      from: {
        x: 199,
        y: 225,
      },
      to: {
        x: 389,
        y: 225,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s1_uc_l",
      kind: "label",
      at: {
        x: 172,
        y: 188,
        w: 244,
        h: 41,
      },
      text: '"Connect with Google"',
      align: "center",
      muted: true,
    },
    {
      id: "s1_rdr",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 561,
        y: 273,
      },
      to: {
        x: 814,
        y: 273,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s1_rdr_l",
      kind: "label",
      at: {
        x: 298,
        y: 236,
        w: 779,
        h: 41,
      },
      text: "GET /authorize?response_type=code&client_id=…&scope=email&state=xyz",
      align: "center",
      muted: true,
    },
    {
      id: "s1_note",
      kind: "token",
      at: {
        x: 488,
        y: 293,
        w: 400,
        h: 33,
      },
      text: "redirect_uri must match pre-registered",
    },
    {
      id: "consent_box",
      kind: "box",
      at: {
        x: 750,
        y: 335,
        w: 300,
        h: 100,
      },
      label: "🔐 Auth Server",
      sub: "Login form · Consent screen",
      variant: "outline",
    },
    {
      id: "s3_ac",
      tone: "warn",
      kind: "connector",
      from: {
        x: 986,
        y: 475,
      },
      to: {
        x: 389,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s3_ac_l",
      kind: "label",
      at: {
        x: 438,
        y: 438,
        w: 500,
        h: 41,
      },
      text: "302 → redirect_uri?code=AUTH_CODE&state=xyz",
      align: "center",
      muted: true,
    },
    {
      id: "s3_note",
      kind: "token",
      at: {
        x: 513,
        y: 495,
        w: 350,
        h: 33,
      },
      text: "code: ephemeral (10 min) · single-use",
    },
    {
      id: "s4_req",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 561,
        y: 550,
      },
      to: {
        x: 814,
        y: 550,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s4_req_l",
      kind: "label",
      at: {
        x: 426,
        y: 513,
        w: 523,
        h: 41,
      },
      text: "POST /token  code + client_id + client_secret",
      align: "center",
      muted: true,
    },
    {
      id: "s4_res",
      tone: "good",
      kind: "connector",
      from: {
        x: 986,
        y: 595,
      },
      to: {
        x: 389,
        y: 595,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s4_res_l",
      kind: "label",
      at: {
        x: 391,
        y: 558,
        w: 593,
        h: 41,
      },
      text: "{access_token, refresh_token, id_token, expires_in}",
      align: "center",
      muted: true,
    },
    {
      id: "s4_note",
      kind: "token",
      at: {
        x: 525,
        y: 615,
        w: 325,
        h: 33,
      },
      text: "server-to-server · user not in loop",
    },
    {
      id: "s5_req",
      tone: "accent",
      kind: "connector",
      from: {
        x: 561,
        y: 668,
      },
      to: {
        x: 1276,
        y: 668,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s5_req_l",
      kind: "label",
      at: {
        x: 605,
        y: 631,
        w: 628,
        h: 41,
      },
      text: "GET /api/profile  Authorization: Bearer <access_token>",
      align: "center",
      muted: true,
    },
    {
      id: "s5_res",
      tone: "good",
      kind: "connector",
      from: {
        x: 1449,
        y: 708,
      },
      to: {
        x: 389,
        y: 708,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "s5_res_l",
      kind: "label",
      at: {
        x: 692,
        y: 671,
        w: 453,
        h: 41,
      },
      text: '200 OK  {name:"Alice", email:"alice@…"}',
      align: "center",
      muted: true,
    },
    {
      id: "pkce_bg",
      kind: "box",
      at: {
        x: 925,
        y: 125,
        w: 650,
        h: 245,
      },
      variant: "outline",
    },
    {
      id: "pkce_ttl",
      kind: "label",
      at: {
        x: 1006,
        y: 132,
        w: 488,
        h: 41,
      },
      text: "PKCE — for Mobile / SPA (no client_secret)",
      align: "center",
    },
    {
      id: "pkce_1",
      kind: "label",
      at: {
        x: 938,
        y: 164,
        w: 523,
        h: 41,
      },
      text: "1. Generate  code_verifier = random(32 bytes)",
      align: "start",
      muted: true,
    },
    {
      id: "pkce_2",
      kind: "label",
      at: {
        x: 938,
        y: 189,
        w: 546,
        h: 41,
      },
      text: "2. Derive    code_challenge = BASE64(SHA256(v))",
      align: "start",
      muted: true,
    },
    {
      id: "pkce_3",
      kind: "label",
      at: {
        x: 938,
        y: 214,
        w: 477,
        h: 41,
      },
      text: "3. Send      code_challenge in /authorize",
      align: "start",
      muted: true,
    },
    {
      id: "pkce_4",
      kind: "label",
      at: {
        x: 938,
        y: 239,
        w: 523,
        h: 41,
      },
      text: "4. Verify    send verifier in /token exchange",
      align: "start",
      muted: true,
    },
    {
      id: "pkce_why",
      kind: "label",
      at: {
        x: 1006,
        y: 327,
        w: 488,
        h: 41,
      },
      text: "No secret needed — safe for public clients",
      align: "center",
      muted: true,
    },
    {
      id: "tok_bg",
      kind: "box",
      at: {
        x: 13,
        y: 600,
        w: 438,
        h: 245,
      },
      variant: "outline",
    },
    {
      id: "tok_ttl",
      kind: "label",
      at: {
        x: 162,
        y: 607,
        w: 140,
        h: 41,
      },
      text: "The 3 Tokens",
      align: "center",
    },
    {
      id: "tok_n0",
      kind: "token",
      at: {
        x: 25,
        y: 653,
        w: 194,
        h: 35,
      },
      text: "access_token",
    },
    {
      id: "tok_d0",
      kind: "label",
      at: {
        x: 231,
        y: 649,
        w: 430,
        h: 41,
      },
      text: "Short-lived (15m). Use for API calls.",
      align: "start",
      muted: true,
    },
    {
      id: "tok_n1",
      kind: "token",
      at: {
        x: 25,
        y: 698,
        w: 194,
        h: 35,
      },
      text: "refresh_token",
    },
    {
      id: "tok_d1",
      kind: "label",
      at: {
        x: 231,
        y: 694,
        w: 453,
        h: 41,
      },
      text: "Long-lived (7d). Get new access tokens.",
      align: "start",
      muted: true,
    },
    {
      id: "tok_n2",
      kind: "token",
      at: {
        x: 25,
        y: 743,
        w: 194,
        h: 35,
      },
      text: "id_token",
    },
    {
      id: "tok_d2",
      kind: "label",
      at: {
        x: 231,
        y: 739,
        w: 395,
        h: 41,
      },
      text: "OIDC only. JWT with user identity.",
      align: "start",
      muted: true,
    },
    {
      id: "tok_note",
      kind: "label",
      at: {
        x: 231,
        y: 777,
        w: 698,
        h: 41,
      },
      text: "access_token: Bearer header. refresh_token: HttpOnly cookie.",
      align: "start",
      muted: true,
    },
    {
      id: "tok_note2",
      kind: "label",
      at: {
        x: 231,
        y: 802,
        w: 535,
        h: 41,
      },
      text: "Never store tokens in localStorage (XSS risk).",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_bg",
      kind: "box",
      at: {
        x: 13,
        y: 375,
        w: 438,
        h: 215,
      },
      variant: "outline",
    },
    {
      id: "oidc_ttl",
      kind: "label",
      at: {
        x: 39,
        y: 382,
        w: 384,
        h: 41,
      },
      text: "OIDC — Adds Identity to OAuth 2.0",
      align: "center",
    },
    {
      id: "oidc_1",
      kind: "label",
      at: {
        x: 25,
        y: 414,
        w: 500,
        h: 41,
      },
      text: "OAuth 2.0 answers: can app access resource?",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_2",
      kind: "label",
      at: {
        x: 25,
        y: 439,
        w: 372,
        h: 41,
      },
      text: "OIDC adds:      who is the user?",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_3",
      kind: "label",
      at: {
        x: 25,
        y: 474,
        w: 500,
        h: 41,
      },
      text: "• id_token (JWT: sub, email, name, picture)",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_4",
      kind: "label",
      at: {
        x: 25,
        y: 499,
        w: 233,
        h: 41,
      },
      text: "• /userinfo endpoint",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_5",
      kind: "label",
      at: {
        x: 25,
        y: 524,
        w: 535,
        h: 41,
      },
      text: "• Discovery: /.well-known/openid-configuration",
      align: "start",
      muted: true,
    },
    {
      id: "oidc_note",
      kind: "label",
      at: {
        x: -77,
        y: 554,
        w: 616,
        h: 41,
      },
      text: "OIDC ≠ OAuth. OAuth = authorization, OIDC = identity.",
      align: "center",
      muted: true,
    },
    {
      id: "flows_bg",
      kind: "box",
      at: {
        x: 925,
        y: 380,
        w: 650,
        h: 213,
      },
      variant: "outline",
    },
    {
      id: "flows_ttl",
      kind: "label",
      at: {
        x: 1151,
        y: 387,
        w: 198,
        h: 41,
      },
      text: "Other Grant Types",
      align: "center",
    },
    {
      id: "flows_cc",
      kind: "label",
      at: {
        x: 938,
        y: 419,
        w: 581,
        h: 41,
      },
      text: "Client Credentials: M2M — client_id+secret → token",
      align: "start",
      muted: true,
    },
    {
      id: "flows_cc2",
      kind: "label",
      at: {
        x: 938,
        y: 439,
        w: 535,
        h: 41,
      },
      text: "  No user involved. Perfect for microservices.",
      align: "start",
      muted: true,
    },
    {
      id: "flows_dv",
      kind: "label",
      at: {
        x: 938,
        y: 474,
        w: 628,
        h: 41,
      },
      text: "Device Flow: TV/CLI — code on screen, confirm on phone",
      align: "start",
      muted: true,
    },
    {
      id: "flows_dv2",
      kind: "label",
      at: {
        x: 938,
        y: 494,
        w: 407,
        h: 41,
      },
      text: "  User polls /token until approval.",
      align: "start",
      muted: true,
    },
    {
      id: "flows_imp",
      kind: "label",
      at: {
        x: 938,
        y: 529,
        w: 558,
        h: 41,
      },
      text: "Implicit (deprecated): token in URL — never use.",
      align: "start",
      muted: true,
    },
    {
      id: "flows_rec",
      kind: "label",
      at: {
        x: 959,
        y: 554,
        w: 581,
        h: 41,
      },
      text: "✓  Auth Code + PKCE = recommended for all new apps",
      align: "center",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: Compartilhar a Senha",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "prob_box",
        "prob_t",
        "prob_s",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "prob_box",
        placement: "bottom",
        text: "Sem OAuth, uma app precisaria da sua senha para agir em seu nome. Resultado: a app tem acesso total, armazena sua senha, e um vazamento expõe sua conta inteira.",
        why: "OAuth resolve com **delegação granular**: você autoriza o acesso a escopos específicos (ex: só leitura de email) sem nunca revelar a senha.",
      },
    },
    {
      id: "s2",
      title: "Os 4 Atores do OAuth 2.0",
      duration: 9000,
      add: ["a_user", "a_client", "a_auth", "a_res", "lf_u", "lf_ca", "lf_as", "lf_rs"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_user",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_client",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_auth",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_res",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 580,
          y: 120,
        },
        placement: "bottom",
        text: "**Resource Owner**: o usuário dono dos dados. **Client**: o app que quer acesso. **Authorization Server**: autentica e emite tokens. **Resource Server**: guarda os dados protegidos.",
        why: "Separar Auth Server de Resource Server permite usar um IdP centralizado (Google, Okta, Auth0) para autenticar usuários de múltiplos apps e APIs.",
      },
    },
    {
      id: "s3",
      title: "Visão Geral do Authorization Code Flow",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s1_uc",
        "s1_uc_l",
        "s1_rdr",
        "s1_rdr_l",
        "s3_ac",
        "s3_ac_l",
        "s4_req",
        "s4_req_l",
        "s4_res",
        "s4_res_l",
        "s5_req",
        "s5_req_l",
        "s5_res",
        "s5_res_l",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 550,
          y: 380,
        },
        placement: "right",
        text: "5 etapas: **1** redirect ao Auth Server → **2** user autentica → **3** code retorna → **4** troca server-to-server por tokens → **5** usa access token.",
        why: "O design garante que tokens nunca viajam no URL do browser e que a troca de code por token exige o client_secret — seguro mesmo com redirect interceptado.",
      },
    },
    {
      id: "s4",
      title: "Step 1: Redirect para o Auth Server",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s1_uc",
        "s1_uc_l",
        "s1_rdr",
        "s1_rdr_l",
        "s1_note",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s1_uc",
          do: "draw",
        },
        {
          at: 400,
          target: "s1_rdr",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 550,
          y: 250,
        },
        placement: "bottom",
        text: "Client gera URL de autorização com: `response_type=code`, `client_id`, `redirect_uri`, `scope`, `state` (anti-CSRF nonce) e opcionalmente `code_challenge` (PKCE).",
        why: "O parâmetro `state` é um nonce gerado pelo client. Na resposta, se o state não bater, o flow é abortado — proteção contra CSRF em fluxos OAuth.",
      },
    },
    {
      id: "s5",
      title: "Step 2: Autenticação e Consent Screen",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s1_rdr",
        "s1_rdr_l",
        "consent_box",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "consent_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "a_auth",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "consent_box",
        placement: "right",
        text: "O Auth Server exibe **login form** e após autenticação, uma **consent screen**: 'App X quer acesso a: leitura de email, perfil.' — o usuário decide.",
        why: "Consent granular: o usuário vê exatamente o que está delegando. Pode revogar a qualquer momento sem trocar senha. Revogar = deletar o refresh token.",
      },
    },
    {
      id: "s6",
      title: "Step 3: Code de Autorização",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "consent_box",
        "s3_ac",
        "s3_ac_l",
        "s3_note",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s3_ac",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 550,
          y: 410,
        },
        placement: "bottom",
        text: "Auth Server redireciona para `redirect_uri?code=ABC&state=xyz`. O `code` é efêmero (10 min) e de uso único — não é ainda um token de acesso.",
        why: "Code no URL é menos sensível que token: expira rápido, é inútil sem o client_secret, e o state previne replay attacks.",
      },
    },
    {
      id: "s7",
      title: "Step 4: Troca de Code por Tokens",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s3_ac",
        "s3_ac_l",
        "s4_req",
        "s4_req_l",
        "s4_res",
        "s4_res_l",
        "s4_note",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s4_req",
          do: "draw",
        },
        {
          at: 500,
          target: "s4_res",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 550,
          y: 490,
        },
        placement: "bottom",
        text: "Client faz POST **server-to-server** com `code + client_id + client_secret`. Auth Server valida e retorna os tokens. O browser não vê nada disso.",
        why: "Server-to-server: o client_secret nunca fica exposto no frontend. Os tokens ficam no backend — o frontend pode receber apenas um session cookie de curto prazo.",
      },
    },
    {
      id: "s8",
      title: "Step 5: Usando o Access Token",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s4_res",
        "s4_res_l",
        "s5_req",
        "s5_req_l",
        "s5_res",
        "s5_res_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s5_req",
          do: "draw",
        },
        {
          at: 400,
          target: "s5_res",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 735,
          y: 560,
        },
        placement: "top",
        text: "Client inclui `Authorization: Bearer <access_token>` em cada request. Resource Server valida o token (JWT verify ou introspection) e retorna os dados.",
        why: "Bearer = quem apresenta, acessa. Por isso HTTPS é obrigatório e tokens não devem ficar em localStorage (XSS). Use HttpOnly cookie ou memory do app.",
      },
    },
    {
      id: "s9",
      title: "PKCE: Proteção Para Apps Públicas",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "pkce_bg",
        "pkce_ttl",
        "pkce_1",
        "pkce_2",
        "pkce_3",
        "pkce_4",
        "pkce_why",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pkce_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 1000,
          y: 306,
        },
        placement: "bottom",
        text: "Apps públicas (SPA, mobile) não podem guardar `client_secret`. **PKCE**: gera verifier aleatório, envia o hash no redirect, verifica na troca de token — sem secret.",
        why: "Se o code for interceptado, o atacante não consegue trocá-lo por token sem o verifier original. O verifier ficou no app legítimo.",
      },
    },
    {
      id: "s10",
      title: "Os 3 Tokens",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "tok_bg",
        "tok_ttl",
        "tok_n0",
        "tok_d0",
        "tok_n1",
        "tok_d1",
        "tok_n2",
        "tok_d2",
        "tok_note",
        "tok_note2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "tok_bg",
        placement: "right",
        text: "**access_token**: curto (15min) — para chamadas de API. **refresh_token**: longo (7d) — para renovar o access sem login. **id_token**: OIDC JWT — identidade do usuário.",
        why: "Access token curto limita a janela de abuso em vazamento. Refresh rotation: cada uso gera um novo refresh token e invalida o anterior.",
      },
    },
    {
      id: "s11",
      title: "OIDC: Identidade Sobre OAuth",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "oidc_bg",
        "oidc_ttl",
        "oidc_1",
        "oidc_2",
        "oidc_3",
        "oidc_4",
        "oidc_5",
        "oidc_note",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "oidc_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "oidc_bg",
        placement: "right",
        text: "**OAuth 2.0**: autorização — 'pode acessar?'. **OIDC**: identidade — 'quem é?'. OIDC adiciona `id_token` JWT com claims (sub, email, name) e `/userinfo` endpoint.",
        why: "Sem OIDC, cada provider inventa como expor dados do usuário. OIDC standardiza isso — permite federar logins ('Continue with Google') de forma interoperável.",
      },
    },
    {
      id: "s12",
      title: "Outros Flows: Client Credentials e Device",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "flows_bg",
        "flows_ttl",
        "flows_cc",
        "flows_cc2",
        "flows_dv",
        "flows_dv2",
        "flows_imp",
        "flows_rec",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "flows_bg",
        placement: "left",
        text: "**Client Credentials**: M2M sem usuário (microserviços). **Device Flow**: TV/CLI — código no device, aprovação no celular. **Implicit**: obsoleto, token na URL, não use.",
        why: "Client Credentials é o padrão para background jobs e microserviços que precisam se autenticar entre si sem intervençáo humana.",
      },
    },
    {
      id: "s13",
      title: "Quiz",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Teste seu conhecimento sobre OAuth 2.0:",
      },
      quiz: {
        question:
          "Por que o Authorization Code Flow usa uma etapa separada de troca server-to-server (ao invés de retornar tokens direto no redirect)?",
        options: [
          "Para reduzir latência e evitar uma conexão TCP extra",
          "Para que tokens nunca viajem na URL do browser, que pode ser logada em proxies e histórico",
          "Porque o Protobuf não suporta tokens em query parameters",
          "Para garantir que o usuário confirme o acesso uma segunda vez",
        ],
        answer: 1,
        explain:
          "URLs ficam em logs de servidores, proxies e histórico do browser. O code é efêmero e inútil sem o client_secret. Tokens só saem no canal server-to-server HTTPS POST — nunca expostos no browser.",
      },
    },
    {
      id: "s14",
      title: "Resumo",
      duration: 9000,
      add: [
        "a_user",
        "a_client",
        "a_auth",
        "a_res",
        "lf_u",
        "lf_ca",
        "lf_as",
        "lf_rs",
        "s1_uc",
        "s1_uc_l",
        "s1_rdr",
        "s1_rdr_l",
        "s3_ac",
        "s3_ac_l",
        "s4_req",
        "s4_req_l",
        "s4_res",
        "s4_res_l",
        "s5_req",
        "s5_req_l",
        "s5_res",
        "s5_res_l",
        "tok_bg",
        "tok_ttl",
        "tok_n0",
        "tok_d0",
        "tok_n1",
        "tok_d1",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 550,
          y: 380,
        },
        placement: "right",
        text: "**OAuth 2.0** = delegação de autorização. Auth Code Flow: redirect → code → server-to-server troca → bearer token. **PKCE** para apps públicas. **OIDC** para identidade. Tokens: access (curto) + refresh (longo).",
        why: "OAuth não é autenticação — é autorização. Para login, use OIDC. Para segurança máxima: access token curto + refresh rotation + HTTPS + HttpOnly cookie.",
      },
    },
  ],
};

export const oauth = validateExplainer(data);
