import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/prompt-eng.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "prompt-eng",
  title: "Engenharia de Prompt",
  subtitle: "Zero-shot, Few-shot, CoT, ReAct e boas práticas",
  category: "IA & Agentes",
  tags: ["prompt", "llm"],
  level: "intro",
  glossary: {},
  elements: [
    {
      id: "llm_box",
      kind: "box",
      at: {
        x: 738,
        y: 350,
        w: 250,
        h: 200,
      },
      label: "🧠",
      sub: "LLM",
      variant: "outline",
    },
    {
      id: "llm_lbl",
      kind: "label",
      at: {
        x: 752,
        y: 307,
        w: 221,
        h: 41,
      },
      text: "modelo de linguagem",
      align: "center",
      muted: true,
    },
    {
      id: "a_p_llm",
      tone: "accent",
      kind: "connector",
      from: {
        x: 675,
        y: 450,
      },
      to: {
        x: 738,
        y: 450,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_llm_o",
      tone: "good",
      kind: "connector",
      from: {
        x: 988,
        y: 450,
      },
      to: {
        x: 1125,
        y: 450,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "p_lbl",
      kind: "label",
      at: {
        x: 282,
        y: 267,
        w: 186,
        h: 41,
      },
      text: "Prompt (entrada)",
      align: "center",
    },
    {
      id: "o_lbl",
      kind: "label",
      at: {
        x: 1256,
        y: 267,
        w: 163,
        h: 41,
      },
      text: "Output (saída)",
      align: "center",
    },
    {
      id: "p_zero",
      kind: "box",
      at: {
        x: 75,
        y: 275,
        w: 600,
        h: 85,
      },
      label: "Traduza para inglês:",
      sub: '"O céu é azul."',
      variant: "outline",
    },
    {
      id: "o_zero",
      kind: "box",
      at: {
        x: 1125,
        y: 300,
        w: 425,
        h: 63,
      },
      label: '"The sky is blue."',
      variant: "outline",
    },
    {
      id: "zero_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 213,
        w: 250,
        h: 45,
      },
      text: "Zero-shot",
    },
    {
      id: "p_few",
      kind: "box",
      at: {
        x: 75,
        y: 200,
        w: 600,
        h: 183,
      },
      label: "Classifique o sentimento:",
      sub: "Ex: 'Amo este produto!' → positivo · Ex: 'Horrível experiência.' → negativo ·  · Classifique: 'Entrega rápida!'",
      variant: "outline",
    },
    {
      id: "o_few",
      kind: "box",
      at: {
        x: 1125,
        y: 350,
        w: 425,
        h: 63,
      },
      label: "→ positivo",
      variant: "outline",
    },
    {
      id: "few_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 138,
        w: 250,
        h: 45,
      },
      text: "Few-shot",
    },
    {
      id: "few_ex",
      kind: "label",
      at: {
        x: 148,
        y: 554,
        w: 453,
        h: 41,
      },
      text: "Exemplos guiam o formato e o raciocínio",
      align: "center",
      muted: true,
    },
    {
      id: "p_cot",
      kind: "box",
      at: {
        x: 75,
        y: 150,
        w: 600,
        h: 150,
      },
      label: "Pense passo a passo:",
      sub: "Roger tem 5 bolas. Ganha 2 mais. · Cada nova caixa tem 3 bolas. · Recebeu 2 caixas novas. Quantas bolas?",
      variant: "outline",
    },
    {
      id: "o_cot",
      kind: "box",
      at: {
        x: 1125,
        y: 150,
        w: 425,
        h: 183,
      },
      label: "Raciocínio:",
      sub: "• Começa: 5 bolas · • +2 bolas = 7 · • 2 caixas × 3 = 6 · • Total: 7+6 = 13 bolas",
      variant: "outline",
    },
    {
      id: "cot_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 75,
        w: 275,
        h: 45,
      },
      text: "Chain-of-Thought (CoT)",
    },
    {
      id: "cot_note",
      kind: "label",
      at: {
        x: 44,
        y: 642,
        w: 663,
        h: 41,
      },
      text: '"Pense passo a passo" aumenta acurácia em tarefas lógicas',
      align: "center",
      muted: true,
    },
    {
      id: "p_role",
      kind: "box",
      at: {
        x: 75,
        y: 200,
        w: 600,
        h: 118,
      },
      label: "Você é um sênior de segurança.",
      sub: "Revise este código Python e liste · vulnerabilidades de SQL injection:",
      variant: "outline",
    },
    {
      id: "o_role",
      kind: "box",
      at: {
        x: 1125,
        y: 275,
        w: 425,
        h: 118,
      },
      label: "1. Linha 14: f-string em query",
      sub: "2. Sem sanitização de entrada · 3. Recomendação: use parameterized queries",
      variant: "outline",
    },
    {
      id: "role_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 138,
        w: 275,
        h: 45,
      },
      text: "Role / Persona",
    },
    {
      id: "p_fmt",
      kind: "box",
      at: {
        x: 75,
        y: 150,
        w: 600,
        h: 118,
      },
      label: "Extraia os dados e retorne JSON:",
      sub: 'Nome, email e cidade. · "João Silva, joao@example.com, SP"',
      variant: "outline",
    },
    {
      id: "o_fmt",
      kind: "box",
      at: {
        x: 1125,
        y: 125,
        w: 425,
        h: 183,
      },
      label: "{",
      sub: '  "nome": "João Silva", ·   "email": "joao@...", ·   "cidade": "SP" · }',
      variant: "outline",
    },
    {
      id: "fmt_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 75,
        w: 325,
        h: 45,
      },
      text: "Especificar formato de saída",
    },
    {
      id: "fmt_note",
      kind: "label",
      at: {
        x: 26,
        y: 642,
        w: 698,
        h: 41,
      },
      text: "JSON Schema ou exemplos concretos evitam outputs inesperados",
      align: "center",
      muted: true,
    },
    {
      id: "p_react",
      kind: "box",
      at: {
        x: 75,
        y: 75,
        w: 600,
        h: 85,
      },
      label: "Responda usando ferramentas.",
      sub: "Raciocine antes de cada ação.",
      variant: "outline",
    },
    {
      id: "o_react",
      kind: "box",
      at: {
        x: 1125,
        y: 63,
        w: 425,
        h: 183,
      },
      label: "Thought: preciso do preço atual.",
      sub: "Action: search('preço iPhone 15') · Observation: R$ 4.799 · Thought: já tenho a resposta. · Answer: iPhone 15 custa R$ 4.799",
      variant: "outline",
    },
    {
      id: "react_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 13,
        w: 250,
        h: 45,
      },
      text: "ReAct (Reason + Act)",
    },
    {
      id: "react_note",
      kind: "label",
      at: {
        x: 1111,
        y: 679,
        w: 453,
        h: 41,
      },
      text: "Thought → Action → Observation → Answer",
      align: "center",
      muted: true,
    },
    {
      id: "p_xml",
      kind: "box",
      at: {
        x: 75,
        y: 125,
        w: 600,
        h: 183,
      },
      label: "<task>Resuma o texto abaixo.</task>",
      sub: "<context> ·   {texto do artigo aqui} · </context> · <format>3 bullet points</format>",
      variant: "outline",
    },
    {
      id: "o_xml",
      kind: "box",
      at: {
        x: 1125,
        y: 225,
        w: 425,
        h: 118,
      },
      label: "• Ponto 1: …",
      sub: "• Ponto 2: … · • Ponto 3: …",
      variant: "outline",
    },
    {
      id: "xml_lbl",
      kind: "token",
      at: {
        x: 75,
        y: 63,
        w: 275,
        h: 45,
      },
      text: "XML Tags para estrutura",
    },
    {
      id: "xml_note",
      kind: "label",
      at: {
        x: -3,
        y: 629,
        w: 756,
        h: 41,
      },
      text: "Tags delimitam contextos — evitam confusão entre instrução e dado",
      align: "center",
      muted: true,
    },
    {
      id: "anti_box",
      kind: "box",
      at: {
        x: 75,
        y: 75,
        w: 1450,
        h: 700,
      },
      variant: "outline",
    },
    {
      id: "anti_lbl",
      kind: "label",
      at: {
        x: 631,
        y: 82,
        w: 337,
        h: 41,
      },
      text: "Anti-padrões: o que NÃO fazer",
      align: "center",
    },
    {
      id: "a1_b",
      kind: "box",
      at: {
        x: 100,
        y: 125,
        w: 413,
        h: 125,
      },
      label: "❌ Ambiguidade",
      sub: '"Escreva algo legal sobre IA"',
      variant: "outline",
    },
    {
      id: "a2_b",
      kind: "box",
      at: {
        x: 563,
        y: 125,
        w: 413,
        h: 125,
      },
      label: "❌ Excesso de restrições",
      sub: '"Não faça X, não diga Y, evite Z, nunca W…"',
      variant: "outline",
    },
    {
      id: "a3_b",
      kind: "box",
      at: {
        x: 1025,
        y: 125,
        w: 413,
        h: 125,
      },
      label: "❌ Prompt monolítico",
      sub: "Instruções, contexto e dados misturados sem estrutura",
      variant: "outline",
    },
    {
      id: "a1_g",
      kind: "box",
      at: {
        x: 100,
        y: 300,
        w: 413,
        h: 125,
      },
      label: "✓ Seja específico",
      sub: '"Escreva 3 vantagens do RAG para empresas de e-commerce"',
      variant: "outline",
    },
    {
      id: "a2_g",
      kind: "box",
      at: {
        x: 563,
        y: 300,
        w: 413,
        h: 125,
      },
      label: "✓ Diga o que quer",
      sub: '"Responda em tom formal, 2 parágrafos, em português"',
      variant: "outline",
    },
    {
      id: "a3_g",
      kind: "box",
      at: {
        x: 1025,
        y: 300,
        w: 413,
        h: 125,
      },
      label: "✓ Use estrutura clara",
      sub: "<task> <context> <format> separam responsabilidades",
      variant: "outline",
    },
    {
      id: "a1_a",
      tone: "good",
      kind: "connector",
      from: {
        x: 306,
        y: 253,
      },
      to: {
        x: 306,
        y: 298,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a2_a",
      tone: "good",
      kind: "connector",
      from: {
        x: 769,
        y: 253,
      },
      to: {
        x: 769,
        y: 298,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a3_a",
      tone: "good",
      kind: "connector",
      from: {
        x: 1231,
        y: 253,
      },
      to: {
        x: 1231,
        y: 298,
      },
      route: "line",
      arrow: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Por que o prompt importa tanto",
      duration: 9000,
      add: ["llm_box", "llm_lbl", "a_p_llm", "a_llm_o", "p_lbl", "o_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "llm_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "llm_box",
        placement: "bottom",
        text: "O mesmo modelo pode dar respostas radicalmente diferentes dependendo de como o prompt é escrito. **Engenharia de Prompt** é a disciplina de estruturar instruções para extrair o máximo de um LLM.",
        why: "Um prompt bem escrito não muda o modelo — muda o que o modelo *ativa*. É como dar contexto e instrução a um especialista: quanto mais claro, melhor o resultado.",
      },
    },
    {
      id: "s2",
      title: "Zero-shot: sem exemplos",
      duration: 9000,
      add: ["zero_lbl", "p_zero", "o_zero"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_zero",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_zero",
        placement: "right",
        text: "**Zero-shot**: você instrui o modelo sem dar exemplos. Funciona bem para tarefas simples que o modelo já conhece do treinamento (tradução, resumo, classificação básica).",
        why: "Use zero-shot como ponto de partida. Se a qualidade não for suficiente, adicione exemplos (few-shot). Não complique o que já funciona simples.",
      },
    },
    {
      id: "s3",
      title: "Few-shot: exemplos guiam o modelo",
      duration: 9000,
      add: ["few_lbl", "p_few", "o_few", "few_ex"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_few",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_few",
        placement: "right",
        text: "**Few-shot**: você inclui 2-5 exemplos de input→output antes da sua tarefa real. O modelo aprende o padrão desejado pelo contexto, sem treinar nada.",
        why: "Few-shot é especialmente eficaz para: formatos específicos, classificações com categorias incomuns e tarefas onde o modelo precisa imitar um estilo particular.",
      },
    },
    {
      id: "s4",
      title: "Chain-of-Thought: pensar passo a passo",
      duration: 9000,
      add: ["cot_lbl", "p_cot", "o_cot", "cot_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_cot",
          do: "highlight",
        },
        {
          at: 0,
          target: "o_cot",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_cot",
        placement: "right",
        text: '**Chain-of-Thought (CoT)**: instruir o modelo a mostrar o raciocínio antes da resposta. Simples como adicionar "Pense passo a passo" ou mostrar um exemplo com etapas de raciocínio.',
        why: "CoT melhora dramaticamente a acurácia em matemática, lógica e multi-step reasoning. O modelo que 'pensa em voz alta' comete menos erros que o que pula direto à conclusão.",
      },
    },
    {
      id: "s5",
      title: "Role prompting: definir um papel",
      duration: 9000,
      add: ["role_lbl", "p_role", "o_role"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_role",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_role",
        placement: "right",
        text: '**Role Prompting**: atribuir uma persona ou papel ao modelo. "Você é um sênior de segurança" ativa conhecimento e estilo de raciocínio específico do domínio.',
        why: "Personas eficazes são específicas: 'sênior de segurança Python com foco em OWASP' é melhor que 'especialista'. A especificidade afunila o espaço de respostas.",
      },
    },
    {
      id: "s6",
      title: "Especificar o formato de saída",
      duration: 9000,
      add: ["fmt_lbl", "p_fmt", "o_fmt", "fmt_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_fmt",
          do: "highlight",
        },
        {
          at: 0,
          target: "o_fmt",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_fmt",
        placement: "right",
        text: "Dizer exatamente **qual formato você quer** (JSON, markdown, lista numerada, XML) evita pós-processamento. Use JSON Schema ou mostre um exemplo do formato esperado no próprio prompt.",
        why: "LLMs são otimizados para ser úteis, mas 'útil' é vago. Especificar o formato fecha o espaço de respostas válidas e torna a saída programaticamente processável.",
      },
    },
    {
      id: "s7",
      title: "ReAct: Raciocinar + Agir",
      duration: 9000,
      add: ["react_lbl", "p_react", "o_react", "react_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "o_react",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "o_react",
        placement: "left",
        text: "**ReAct (Reason + Act)**: o modelo alterna entre *Thought* (raciocínio), *Action* (chamada de ferramenta) e *Observation* (resultado). É a base dos agentes que usam tools.",
        why: "ReAct é mais confiável que agentes que agem sem raciocinar: o Thought explica a lógica da Action, permitindo detectar erros antes de executar e auditar o processo depois.",
      },
    },
    {
      id: "s8",
      title: "XML tags para estrutura e delimitação",
      duration: 9000,
      add: ["xml_lbl", "p_xml", "o_xml", "xml_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "p_xml",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "p_xml",
        placement: "right",
        text: "**XML Tags** como `<task>`, `<context>`, `<format>` delimitam cada parte do prompt, evitando que o modelo confunda instrução com dado de entrada.",
        why: "Claude e outros modelos são treinados para entender e respeitar XML tags. Elas tornam o prompt modular: é fácil trocar só o contexto sem reescrever as instruções.",
      },
    },
    {
      id: "s9",
      title: "Anti-padrões: o que evitar",
      duration: 9000,
      add: ["anti_box", "anti_lbl", "a1_b", "a2_b", "a3_b", "a1_a", "a2_a", "a3_a", "a1_g", "a2_g", "a3_g"],
      remove: [],
      set: {},
      cues: [
        {
          at: 400,
          target: "a1_a",
          do: "draw",
        },
        {
          at: 500,
          target: "a2_a",
          do: "draw",
        },
        {
          at: 600,
          target: "a3_a",
          do: "draw",
        },
        {
          at: 0,
          target: "a1_g",
          do: "highlight",
        },
        {
          at: 0,
          target: "a2_g",
          do: "highlight",
        },
        {
          at: 0,
          target: "a3_g",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "anti_lbl",
        placement: "bottom",
        text: "Os três anti-padrões mais comuns: **ambiguidade** (tarefa vaga), **excesso de restrições negativas** (dizer o que não quer em vez do que quer) e **prompt monolítico** sem estrutura.",
        why: 'Prompts negativos ("não faça X") são menos eficazes que positivos ("faça Y"). O modelo precisa imaginar X para evitá-lo — e às vezes acaba fazendo mesmo.',
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Confirme o que você aprendeu sobre Prompt Engineering 👇",
      },
      quiz: {
        question: "Por que Chain-of-Thought (CoT) melhora a acurácia em tarefas de raciocínio?",
        options: [
          "Porque usa mais tokens, o que faz o modelo 'pensar mais'",
          "Porque o raciocínio explícito reduz atalhos e força o modelo a validar cada passo antes de concluir",
          "Porque instrui o modelo a usar ferramentas externas para calcular",
          "Porque permite ao modelo ignorar exemplos incorretos no few-shot",
        ],
        answer: 1,
        explain:
          "CoT funciona porque o raciocínio explícito cria uma 'cadeia de verificação': cada etapa se apoia na anterior. Erros são detectados antes de se propagar à conclusão, o que não acontece quando o modelo pula direto à resposta.",
      },
    },
    {
      id: "s11",
      title: "Resumo: técnicas de Prompt Engineering",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "llm_box",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "llm_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "llm_box",
        placement: "right",
        text: "Técnicas em ordem crescente de complexidade: **Zero-shot → Few-shot → CoT → Role → Formato → ReAct → XML**. Comece simples e adicione complexidade só se necessário. Itere, avalie e meça.",
        why: "A melhor técnica depende da tarefa: CoT para raciocínio, few-shot para formatos específicos, ReAct para agentes com tools. Combine-as — não são exclusivas.",
      },
    },
  ],
};

export const promptEng = validateExplainer(data);
