import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/rag.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "rag",
  title: "RAG — Retrieval-Augmented Generation",
  subtitle: "Como fundamentar respostas de LLMs em dados reais",
  category: "IA & Agentes",
  tags: ["rag", "llm", "embeddings"],
  level: "medio",
  glossary: {
    "Vector DB":
      "Banco de dados especializado em armazenar e buscar vetores de alta dimensão por similaridade.",
  },
  elements: [
    {
      id: "pi_query",
      kind: "box",
      at: {
        x: 38,
        y: 75,
        w: 325,
        h: 60,
      },
      label: "1 · Query do usuário",
      variant: "outline",
    },
    {
      id: "a_q_e",
      kind: "connector",
      from: {
        x: 200,
        y: 135,
      },
      to: {
        x: 200,
        y: 175,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_embed",
      kind: "box",
      at: {
        x: 38,
        y: 175,
        w: 325,
        h: 60,
      },
      label: "2 · Embedding da query",
      variant: "outline",
    },
    {
      id: "a_e_v",
      kind: "connector",
      from: {
        x: 200,
        y: 235,
      },
      to: {
        x: 200,
        y: 275,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_vdb",
      kind: "box",
      at: {
        x: 38,
        y: 275,
        w: 325,
        h: 60,
      },
      label: "3 · Vector DB (busca)",
      variant: "outline",
    },
    {
      id: "a_v_r",
      kind: "connector",
      from: {
        x: 200,
        y: 335,
      },
      to: {
        x: 200,
        y: 375,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_ret",
      kind: "box",
      at: {
        x: 38,
        y: 375,
        w: 325,
        h: 60,
      },
      label: "4 · Chunks recuperados",
      variant: "outline",
    },
    {
      id: "a_r_a",
      kind: "connector",
      from: {
        x: 200,
        y: 435,
      },
      to: {
        x: 200,
        y: 475,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_aug",
      kind: "box",
      at: {
        x: 38,
        y: 475,
        w: 325,
        h: 60,
      },
      label: "5 · Prompt aumentado",
      variant: "outline",
    },
    {
      id: "a_a_l",
      kind: "connector",
      from: {
        x: 200,
        y: 535,
      },
      to: {
        x: 200,
        y: 575,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_llm",
      kind: "box",
      at: {
        x: 38,
        y: 575,
        w: 325,
        h: 60,
      },
      label: "6 · LLM gera resposta",
      variant: "outline",
    },
    {
      id: "a_l_o",
      kind: "connector",
      from: {
        x: 200,
        y: 635,
      },
      to: {
        x: 200,
        y: 675,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pi_out",
      kind: "box",
      at: {
        x: 38,
        y: 675,
        w: 325,
        h: 60,
      },
      label: "✓ Resposta fundamentada",
      variant: "outline",
    },
    {
      id: "d_llm_alone",
      kind: "box",
      at: {
        x: 650,
        y: 150,
        w: 375,
        h: 100,
      },
      label: "LLM (sem contexto externo)",
      sub: "Treinado até data X",
      variant: "outline",
    },
    {
      id: "d_question",
      kind: "token",
      at: {
        x: 675,
        y: 300,
        w: 325,
        h: 55,
      },
      text: '"Qual o preço atual do produto Y?"',
    },
    {
      id: "d_halluc",
      kind: "token",
      at: {
        x: 675,
        y: 400,
        w: 325,
        h: 55,
      },
      text: "⚠️ Resposta inventada (alucinação)",
    },
    {
      id: "a_q_h",
      tone: "hot",
      kind: "connector",
      from: {
        x: 838,
        y: 358,
      },
      to: {
        x: 838,
        y: 398,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "d_doc",
      kind: "box",
      at: {
        x: 650,
        y: 100,
        w: 425,
        h: 100,
      },
      label: "📄 Documento original",
      sub: "(artigo, manual, base de conhecimento)",
      variant: "outline",
    },
    {
      id: "d_ch1",
      kind: "token",
      at: {
        x: 650,
        y: 263,
        w: 125,
        h: 68,
      },
      text: "Chunk 1",
    },
    {
      id: "d_ch2",
      kind: "token",
      at: {
        x: 794,
        y: 263,
        w: 125,
        h: 68,
      },
      text: "Chunk 2",
    },
    {
      id: "d_ch3",
      kind: "token",
      at: {
        x: 938,
        y: 263,
        w: 125,
        h: 68,
      },
      text: "Chunk 3",
    },
    {
      id: "d_ch4",
      kind: "token",
      at: {
        x: 650,
        y: 363,
        w: 125,
        h: 68,
      },
      text: "Chunk 4",
    },
    {
      id: "d_ch5",
      kind: "token",
      at: {
        x: 794,
        y: 363,
        w: 125,
        h: 68,
      },
      text: "Chunk 5",
    },
    {
      id: "d_ch6",
      kind: "token",
      at: {
        x: 938,
        y: 363,
        w: 125,
        h: 68,
      },
      text: "Chunk 6",
    },
    {
      id: "d_chunk_lbl",
      kind: "label",
      at: {
        x: 653,
        y: 467,
        w: 419,
        h: 41,
      },
      text: "Cada chunk → vetor no banco vetorial",
      align: "center",
      muted: true,
    },
    {
      id: "d_qvec_lbl",
      kind: "label",
      at: {
        x: 711,
        y: 79,
        w: 302,
        h: 41,
      },
      text: "Query → vetor de embedding",
      align: "center",
    },
    {
      id: "d_qvec",
      tone: "accent",
      kind: "bars",
      at: {
        x: 663,
        y: 125,
        w: 35,
        h: 150,
      },
      values: [0.7, 0.3, 0.9, 0.5, 0.8, 0.4, 0.6],
    },
    {
      id: "d_qvec2",
      tone: "accent",
      kind: "bars",
      at: {
        x: 706,
        y: 125,
        w: 35,
        h: 150,
      },
      values: [0.4, 0.8, 0.2, 0.9, 0.3, 0.7, 0.5],
    },
    {
      id: "d_qvec3",
      tone: "accent",
      kind: "bars",
      at: {
        x: 750,
        y: 125,
        w: 35,
        h: 150,
      },
      values: [0.6, 0.5, 0.7, 0.3, 0.9, 0.2, 0.8],
    },
    {
      id: "d_dim_lbl",
      kind: "label",
      at: {
        x: 637,
        y: 273,
        w: 163,
        h: 41,
      },
      text: "1536 dimensões",
      align: "center",
      muted: true,
    },
    {
      id: "d_sim_lbl",
      kind: "label",
      at: {
        x: 682,
        y: 49,
        w: 360,
        h: 41,
      },
      text: "Scores de similaridade (cosine)",
      align: "center",
    },
    {
      id: "d_s1",
      tone: "good",
      kind: "bars",
      at: {
        x: 663,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.92],
    },
    {
      id: "d_s2",
      tone: "good",
      kind: "bars",
      at: {
        x: 725,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.78],
    },
    {
      id: "d_s3",
      tone: "accent",
      kind: "bars",
      at: {
        x: 788,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.61],
    },
    {
      id: "d_s4",
      kind: "bars",
      at: {
        x: 850,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.45],
    },
    {
      id: "d_s5",
      kind: "bars",
      at: {
        x: 913,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.31],
    },
    {
      id: "d_s6",
      kind: "bars",
      at: {
        x: 975,
        y: 100,
        w: 40,
        h: 163,
      },
      values: [0.18],
    },
    {
      id: "d_sl1",
      kind: "label",
      at: {
        x: 645,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.92",
      align: "center",
      muted: true,
    },
    {
      id: "d_sl2",
      kind: "label",
      at: {
        x: 708,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.78",
      align: "center",
      muted: true,
    },
    {
      id: "d_sl3",
      kind: "label",
      at: {
        x: 770,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.61",
      align: "center",
      muted: true,
    },
    {
      id: "d_sl4",
      kind: "label",
      at: {
        x: 833,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.45",
      align: "center",
      muted: true,
    },
    {
      id: "d_sl5",
      kind: "label",
      at: {
        x: 895,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.31",
      align: "center",
      muted: true,
    },
    {
      id: "d_sl6",
      kind: "label",
      at: {
        x: 958,
        y: 262,
        w: 75,
        h: 41,
      },
      text: "0.18",
      align: "center",
      muted: true,
    },
    {
      id: "d_topk_lbl",
      kind: "label",
      at: {
        x: 694,
        y: 304,
        w: 337,
        h: 41,
      },
      text: "Top-K = 2 chunks selecionados",
      align: "center",
      muted: true,
    },
    {
      id: "d_ret1",
      kind: "box",
      at: {
        x: 650,
        y: 100,
        w: 425,
        h: 88,
      },
      label: "✓ Chunk 1 (0.92)",
      sub: '"O produto Y custa R$ 199 em junho 2025…"',
      variant: "outline",
    },
    {
      id: "d_ret2",
      kind: "box",
      at: {
        x: 650,
        y: 213,
        w: 425,
        h: 88,
      },
      label: "✓ Chunk 2 (0.78)",
      sub: '"Promoção de 10% válida até julho…"',
      variant: "outline",
    },
    {
      id: "d_ret_lbl",
      kind: "label",
      at: {
        x: 700,
        y: 304,
        w: 326,
        h: 41,
      },
      text: "Top-2 chunks mais relevantes",
      align: "center",
      muted: true,
    },
    {
      id: "d_aug_box",
      kind: "box",
      at: {
        x: 650,
        y: 75,
        w: 425,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "d_aug_sys",
      kind: "token",
      at: {
        x: 663,
        y: 95,
        w: 400,
        h: 48,
      },
      text: "System: Você é um assistente preciso.",
    },
    {
      id: "d_aug_ctx",
      kind: "token",
      at: {
        x: 663,
        y: 155,
        w: 400,
        h: 113,
      },
      text: "[Contexto recuperado]",
    },
    {
      id: "d_aug_usr",
      kind: "token",
      at: {
        x: 663,
        y: 280,
        w: 400,
        h: 48,
      },
      text: "User: Qual o preço atual do produto Y?",
    },
    {
      id: "d_aug_lbl",
      kind: "label",
      at: {
        x: 706,
        y: 327,
        w: 314,
        h: 41,
      },
      text: "Contexto embutido no prompt",
      align: "center",
      muted: true,
    },
    {
      id: "d_resp_box",
      kind: "box",
      at: {
        x: 650,
        y: 100,
        w: 425,
        h: 163,
      },
      label: '✓ "O produto Y custa R$ 199.',
      sub: 'Com a promoção de 10%, fica R$ 179,10. · Oferta válida até julho de 2025."',
      variant: "outline",
    },
    {
      id: "d_resp_src",
      kind: "token",
      at: {
        x: 663,
        y: 280,
        w: 400,
        h: 45,
      },
      text: "Fonte: base de conhecimento (fundamentado)",
    },
    {
      id: "d_cmp_lbl",
      kind: "label",
      at: {
        x: 758,
        y: 44,
        w: 209,
        h: 41,
      },
      text: "Sem RAG vs Com RAG",
      align: "center",
    },
    {
      id: "d_no_rag",
      kind: "box",
      at: {
        x: 650,
        y: 88,
        w: 194,
        h: 375,
      },
      label: "❌ Sem RAG",
      sub: " · Conhecimento · congelado no · treinamento. ·  · Alucina datas, · preços e fatos · recentes.",
      variant: "outline",
    },
    {
      id: "d_yes_rag",
      kind: "box",
      at: {
        x: 881,
        y: 88,
        w: 194,
        h: 375,
      },
      label: "✓ Com RAG",
      sub: " · Busca docs · em tempo real. ·  · Resposta · atualizada e · com fonte · verificável.",
      variant: "outline",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O problema: LLMs sem contexto externo",
      duration: 9000,
      add: ["d_llm_alone", "d_question", "a_q_h", "d_halluc"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_halluc",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "d_halluc",
        placement: "bottom",
        text: "Um LLM treinado até uma data fixa não sabe de eventos recentes. Quando perguntado sobre dados que não estão no seu treinamento, ele tende a **alucinar**: inventar informações plausíveis mas incorretas.",
        why: "O RAG resolve isso conectando o LLM a uma base de conhecimento atualizada em tempo de consulta — sem precisar retreinar o modelo.",
      },
    },
    {
      id: "s2",
      title: "RAG: a arquitetura de solução",
      duration: 9000,
      add: [
        "pi_query",
        "a_q_e",
        "pi_embed",
        "a_e_v",
        "pi_vdb",
        "a_v_r",
        "pi_ret",
        "a_r_a",
        "pi_aug",
        "a_a_l",
        "pi_llm",
        "a_l_o",
        "pi_out",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_query",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_out",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 160,
          y: 400,
        },
        placement: "right",
        text: "O **RAG (Retrieval-Augmented Generation)** tem dois estágios: **Retrieval** (buscar os documentos certos) e **Generation** (o LLM gera com esse contexto). O resultado é uma resposta fundamentada em dados reais.",
        why: "RAG é preferível ao fine-tuning para conhecimento que muda frequentemente: você atualiza o banco de dados, não o modelo.",
      },
    },
    {
      id: "s3",
      title: "Pré-processamento: chunking de documentos",
      duration: 9000,
      add: ["d_doc", "d_ch1", "d_ch2", "d_ch3", "d_ch4", "d_ch5", "d_ch6", "d_chunk_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_doc",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "d_doc",
        placement: "bottom",
        text: "Antes de qualquer consulta, os documentos são **divididos em chunks** (pedaços de texto com tamanho fixo ou semântico). Cada chunk é convertido num vetor e armazenado no {{Vector DB}}.",
        why: "Chunks menores permitem recuperar só o trecho relevante, sem passar o documento inteiro ao LLM. O tamanho ideal depende do modelo e do tipo de conteúdo.",
      },
    },
    {
      id: "s4",
      title: "Embedding da query do usuário",
      duration: 9000,
      add: ["d_qvec_lbl", "d_qvec", "d_qvec2", "d_qvec3", "d_dim_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_embed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "pi_embed",
        placement: "right",
        text: "Quando o usuário faz uma pergunta, ela passa pelo **mesmo modelo de embedding** usado nos documentos. O resultado é um **vetor de alta dimensão** (ex.: 1536 dimensões) que representa o *significado* semântico da query.",
        why: "Usar o mesmo espaço vetorial é crucial: documentos e query precisam ser comparáveis. Modelos como ada-002 ou text-embedding-3 são populares para isso.",
      },
    },
    {
      id: "s5",
      title: "Busca vetorial por similaridade",
      duration: 9000,
      add: [
        "d_sim_lbl",
        "d_s1",
        "d_s2",
        "d_s3",
        "d_s4",
        "d_s5",
        "d_s6",
        "d_sl1",
        "d_sl2",
        "d_sl3",
        "d_sl4",
        "d_sl5",
        "d_sl6",
        "d_topk_lbl",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_s1",
          do: "setBars",
          values: [0.92],
        },
        {
          at: 100,
          target: "d_s2",
          do: "setBars",
          values: [0.78],
        },
        {
          at: 200,
          target: "d_s3",
          do: "setBars",
          values: [0.61],
        },
        {
          at: 300,
          target: "d_s4",
          do: "setBars",
          values: [0.45],
        },
        {
          at: 400,
          target: "d_s5",
          do: "setBars",
          values: [0.31],
        },
        {
          at: 500,
          target: "d_s6",
          do: "setBars",
          values: [0.18],
        },
        {
          at: 0,
          target: "pi_vdb",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_s1",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_s2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "pi_vdb",
        placement: "right",
        text: "O Vector DB compara o vetor da query com todos os vetores dos chunks usando **similaridade de cosseno** (ou produto escalar). Os chunks com maior score são os mais semanticamente próximos da pergunta.",
        why: "A busca vetorial encontra resultados relevantes mesmo sem correspondência exata de palavras — ela entende o significado. Bancos como Pinecone, Weaviate, pgvector ou Qdrant fazem isso eficientemente.",
      },
    },
    {
      id: "s6",
      title: "Top-K chunks recuperados",
      duration: 9000,
      add: ["d_ret1", "d_ret2", "d_ret_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_ret",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_ret1",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_ret2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "d_ret1",
        placement: "right",
        text: "Os **K chunks** com maior similaridade (aqui K=2) são recuperados. Eles contêm o contexto específico para responder a pergunta: preço atual, condições de promoção e prazo.",
        why: "O valor de K é um trade-off: mais chunks = mais contexto mas também mais tokens e risco de diluir a relevância. Reranking (um modelo auxiliar que reordena os resultados) pode melhorar a qualidade.",
      },
    },
    {
      id: "s7",
      title: "Montagem do prompt aumentado",
      duration: 9000,
      add: ["d_aug_box", "d_aug_sys", "d_aug_ctx", "d_aug_usr", "d_aug_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_aug",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_aug_ctx",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "pi_aug",
        placement: "right",
        text: "Os chunks recuperados são **embutidos no prompt** como contexto adicional, junto ao system prompt e à pergunta original. O LLM agora enxerga os fatos relevantes antes de gerar a resposta.",
        why: "A ordem importa: colocar o contexto antes da pergunta ajuda a maioria dos modelos. O prompt precisa instruir o LLM a citar a fonte e admitir quando o contexto não é suficiente.",
      },
    },
    {
      id: "s8",
      title: "LLM gera a resposta fundamentada",
      duration: 9000,
      add: ["d_resp_box", "d_resp_src"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_llm",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_out",
          do: "highlight",
        },
        {
          at: 0,
          target: "d_resp_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "pi_out",
        placement: "right",
        text: "Com o contexto embutido, o LLM gera uma resposta **precisa e verificável**: cita o preço real, a promoção e o prazo — tudo extraído dos chunks, não inventado.",
        why: "O LLM atua como um sintetizador inteligente, não como uma memória. Ele organiza e articula o que os chunks trouxeram, reduzindo drasticamente as alucinações.",
      },
    },
    {
      id: "s9",
      title: "Sem RAG vs Com RAG",
      duration: 9000,
      add: ["d_cmp_lbl", "d_no_rag", "d_yes_rag"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "d_yes_rag",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "d_yes_rag",
        placement: "right",
        text: "O comparativo é claro: sem RAG, o LLM usa só o que aprendeu no treino (limitado e possivelmente desatualizado). Com RAG, ele acessa dados atuais da empresa, docs, wikis e muito mais — em tempo real.",
        why: "RAG não substitui fine-tuning para adaptar o estilo ou comportamento do modelo, mas é muito mais eficiente para **conhecimento factual e dinâmico**.",
      },
    },
    {
      id: "s10",
      title: "Onde o RAG pode falhar",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_vdb",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_embed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 160,
          y: 360,
        },
        placement: "right",
        text: "O RAG falha quando: (1) o chunk certo não foi indexado; (2) a query e o documento usam vocabulário diferente; (3) K é pequeno demais; (4) os chunks são grandes demais. **Chunking, embedding e K são parâmetros críticos.**",
        why: "Avaliar um sistema RAG exige métricas como recall@K (o chunk certo está nos K recuperados?) e faithfulness (a resposta cita o contexto fielmente?).",
      },
    },
    {
      id: "s11",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 160,
          y: 400,
        },
        placement: "right",
        text: "Teste seu entendimento do RAG 👇",
      },
      quiz: {
        question: "Por que o RAG usa o mesmo modelo de embedding para documentos e para a query do usuário?",
        options: [
          "Para economizar custo de API chamando o modelo uma vez só",
          "Para que documentos e query existam no mesmo espaço vetorial e sejam comparáveis por similaridade",
          "Porque modelos diferentes não conseguem processar texto em português",
          "Para garantir que o LLM não precise ser retreinado",
        ],
        answer: 1,
        explain:
          "Documentos e query precisam estar no mesmo espaço vetorial para que a distância entre eles tenha significado. Se usassem modelos diferentes, os vetores seriam incomparáveis.",
      },
    },
    {
      id: "s12",
      title: "Resumo do RAG",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "pi_query",
          do: "pulse",
          times: 2,
        },
        {
          at: 100,
          target: "pi_embed",
          do: "pulse",
          times: 2,
        },
        {
          at: 200,
          target: "pi_vdb",
          do: "pulse",
          times: 2,
        },
        {
          at: 300,
          target: "pi_ret",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "pi_aug",
          do: "pulse",
          times: 2,
        },
        {
          at: 500,
          target: "pi_llm",
          do: "pulse",
          times: 2,
        },
        {
          at: 600,
          target: "pi_out",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "pi_query",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_embed",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_vdb",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_ret",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_aug",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_llm",
          do: "highlight",
        },
        {
          at: 0,
          target: "pi_out",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 160,
          y: 400,
        },
        placement: "right",
        text: "O fluxo RAG em 6 passos: **query → embedding → busca vetorial → top-K chunks → prompt aumentado → LLM → resposta fundamentada**. O LLM fica estático; o conhecimento atualiza via o banco vetorial.",
        why: "RAG é hoje a arquitetura padrão para sistemas de Q&A sobre documentos, chatbots de suporte, assistentes de código e qualquer cenário onde o conhecimento muda com o tempo.",
      },
    },
  ],
};

export const rag = validateExplainer(data);
