import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/sdd.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "sdd",
  title: "Spec-Driven Development (SDD)",
  subtitle: "Spec → IA gera → Testes validam → Feedback → Spec evolui",
  category: "IA & Agentes",
  tags: ["spec-driven", "agentes"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "n_spec",
      kind: "box",
      at: {
        x: 450,
        y: 250,
        w: 238,
        h: 100,
      },
      label: "📝 Spec",
      sub: "(comportamento esperado)",
      variant: "outline",
    },
    {
      id: "n_gen",
      kind: "box",
      at: {
        x: 713,
        y: 250,
        w: 238,
        h: 100,
      },
      label: "🤖 IA Gera",
      sub: "(código / implementação)",
      variant: "outline",
    },
    {
      id: "n_test",
      kind: "box",
      at: {
        x: 713,
        y: 500,
        w: 238,
        h: 100,
      },
      label: "🧪 Testes Validam",
      sub: "(automatizados)",
      variant: "outline",
    },
    {
      id: "n_feed",
      kind: "box",
      at: {
        x: 450,
        y: 500,
        w: 238,
        h: 100,
      },
      label: "🔄 Feedback",
      sub: "(o que falhou e por quê)",
      variant: "outline",
    },
    {
      id: "a_sg",
      tone: "accent",
      kind: "connector",
      from: {
        x: 688,
        y: 300,
      },
      to: {
        x: 713,
        y: 300,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_gt",
      tone: "good",
      kind: "connector",
      from: {
        x: 831,
        y: 350,
      },
      to: {
        x: 831,
        y: 500,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_tf",
      tone: "warn",
      kind: "connector",
      from: {
        x: 713,
        y: 550,
      },
      to: {
        x: 688,
        y: 550,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_fs",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 569,
        y: 500,
      },
      to: {
        x: 569,
        y: 350,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lbl_sg",
      kind: "label",
      at: {
        x: 624,
        y: 211,
        w: 140,
        h: 41,
      },
      text: "IA lê a spec",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_gt",
      kind: "label",
      at: {
        x: 774,
        y: 386,
        w: 128,
        h: 41,
      },
      text: "roda testes",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_tf",
      kind: "label",
      at: {
        x: 601,
        y: 598,
        w: 186,
        h: 41,
      },
      text: "erros → feedback",
      align: "center",
      muted: true,
    },
    {
      id: "lbl_fs",
      kind: "label",
      at: {
        x: 350,
        y: 386,
        w: 174,
        h: 41,
      },
      text: "spec atualizada",
      align: "center",
      muted: true,
    },
    {
      id: "success",
      kind: "token",
      at: {
        x: 975,
        y: 400,
        w: 225,
        h: 63,
      },
      text: "✅ Todos passam\n→ entrega!",
    },
    {
      id: "a_success",
      tone: "good",
      kind: "connector",
      from: {
        x: 950,
        y: 550,
      },
      to: {
        x: 975,
        y: 431,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "spec_box",
      kind: "box",
      at: {
        x: 1050,
        y: 50,
        w: 500,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "spec_ttl",
      kind: "label",
      at: {
        x: 1213,
        y: 57,
        w: 174,
        h: 41,
      },
      text: "Exemplo de Spec",
      align: "center",
    },
    {
      id: "spec_l1",
      kind: "token",
      at: {
        x: 1070,
        y: 100,
        w: 460,
        h: 50,
      },
      text: "Feature: Autenticação de usuário",
    },
    {
      id: "spec_l2",
      kind: "token",
      at: {
        x: 1070,
        y: 163,
        w: 460,
        h: 50,
      },
      text: "GIVEN: usuário com email válido",
    },
    {
      id: "spec_l3",
      kind: "token",
      at: {
        x: 1070,
        y: 223,
        w: 460,
        h: 50,
      },
      text: "WHEN: envia senha correta",
    },
    {
      id: "spec_l4",
      kind: "token",
      at: {
        x: 1070,
        y: 283,
        w: 460,
        h: 50,
      },
      text: "THEN: retorna JWT + status 200",
    },
    {
      id: "spec_l5",
      kind: "token",
      at: {
        x: 1070,
        y: 343,
        w: 460,
        h: 50,
      },
      text: "WHEN: senha errada → 401 Unauthorized",
    },
    {
      id: "spec_note",
      kind: "label",
      at: {
        x: 1033,
        y: 399,
        w: 535,
        h: 41,
      },
      text: "Spec descreve COMPORTAMENTO, não implementação",
      align: "center",
      muted: true,
    },
    {
      id: "gen_box",
      kind: "box",
      at: {
        x: 1050,
        y: 500,
        w: 500,
        h: 225,
      },
      variant: "outline",
    },
    {
      id: "gen_ttl",
      kind: "label",
      at: {
        x: 1178,
        y: 507,
        w: 244,
        h: 41,
      },
      text: "Código gerado pela IA",
      align: "center",
    },
    {
      id: "gen_l1",
      kind: "token",
      at: {
        x: 1070,
        y: 550,
        w: 460,
        h: 50,
      },
      text: "def login(email, password):",
      mono: true,
    },
    {
      id: "gen_l2",
      kind: "token",
      at: {
        x: 1070,
        y: 610,
        w: 460,
        h: 50,
      },
      text: "  user = User.find(email)",
      mono: true,
    },
    {
      id: "gen_l3",
      kind: "token",
      at: {
        x: 1070,
        y: 670,
        w: 460,
        h: 50,
      },
      text: "  return jwt.encode(user) if valid",
      mono: true,
    },
    {
      id: "cmp_box",
      kind: "box",
      at: {
        x: 50,
        y: 625,
        w: 550,
        h: 238,
      },
      variant: "outline",
    },
    {
      id: "cmp_ttl",
      kind: "label",
      at: {
        x: 226,
        y: 629,
        w: 198,
        h: 41,
      },
      text: "SDD vs TDD vs BDD",
      align: "center",
    },
    {
      id: "cmp_tdd",
      kind: "token",
      at: {
        x: 70,
        y: 670,
        w: 510,
        h: 50,
      },
      text: "TDD: escreva o teste, depois o código",
    },
    {
      id: "cmp_bdd",
      kind: "token",
      at: {
        x: 70,
        y: 730,
        w: 510,
        h: 50,
      },
      text: "BDD: especifique em Gherkin (Given/When/Then)",
    },
    {
      id: "cmp_sdd",
      kind: "token",
      at: {
        x: 70,
        y: 790,
        w: 510,
        h: 50,
      },
      text: "SDD: spec → IA gera tudo → humano valida",
    },
    {
      id: "trace_box",
      kind: "box",
      at: {
        x: 50,
        y: 50,
        w: 463,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "trace_ttl",
      kind: "label",
      at: {
        x: 72,
        y: 54,
        w: 419,
        h: 41,
      },
      text: "Rastreabilidade Spec ↔ Código ↔ Test",
      align: "center",
    },
    {
      id: "trace_1",
      kind: "token",
      at: {
        x: 70,
        y: 95,
        w: 423,
        h: 50,
      },
      text: "spec: autenticação #AUTH-01",
    },
    {
      id: "a_t1",
      kind: "connector",
      from: {
        x: 281,
        y: 148,
      },
      to: {
        x: 281,
        y: 163,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "trace_2",
      kind: "token",
      at: {
        x: 70,
        y: 165,
        w: 423,
        h: 50,
      },
      text: "código: auth.py (gerado de #AUTH-01)",
    },
    {
      id: "a_t2",
      kind: "connector",
      from: {
        x: 281,
        y: 218,
      },
      to: {
        x: 281,
        y: 233,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "trace_3",
      kind: "token",
      at: {
        x: 70,
        y: 235,
        w: 423,
        h: 50,
      },
      text: "test: test_auth.py (valida #AUTH-01)",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que é Spec-Driven Development",
      duration: 9000,
      add: [
        "n_spec",
        "n_gen",
        "n_test",
        "n_feed",
        "a_sg",
        "a_gt",
        "a_tf",
        "a_fs",
        "lbl_sg",
        "lbl_gt",
        "lbl_tf",
        "lbl_fs",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_sg",
          do: "draw",
        },
        {
          at: 200,
          target: "a_gt",
          do: "draw",
        },
        {
          at: 400,
          target: "a_tf",
          do: "draw",
        },
        {
          at: 600,
          target: "a_fs",
          do: "draw",
        },
        {
          at: 0,
          target: "n_spec",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "n_spec",
        placement: "left",
        text: "**SDD** é uma metodologia onde a **Spec** (especificação de comportamento) é a única fonte de verdade. A IA gera o código a partir da spec, testes automatizados validam, e o feedback refina a spec — iterativamente.",
        why: "SDD inverte o processo tradicional: em vez de escrever código e depois documentar, você descreve o comportamento primeiro e deixa a IA implementar. O humano se concentra no 'o quê', não no 'como'.",
      },
    },
    {
      id: "s2",
      title: "A Spec: comportamento, não implementação",
      duration: 9000,
      add: ["spec_box", "spec_ttl", "spec_l1", "spec_l2", "spec_l3", "spec_l4", "spec_l5", "spec_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_spec",
          do: "highlight",
        },
        {
          at: 0,
          target: "spec_l4",
          do: "highlight",
        },
        {
          at: 0,
          target: "spec_l5",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "spec_box",
        placement: "left",
        text: "A spec descreve **o que o sistema deve fazer**, não como implementar. Usa linguagem Given/When/Then (BDD) para ser legível por humanos e processável pela IA.",
        why: "Uma spec de comportamento é agnóstica à tecnologia: você pode mudar de Python para Go sem reescrever a spec. Ela também serve como documentação viva — sempre sincronizada com o código gerado.",
      },
    },
    {
      id: "s3",
      title: "IA gera o código a partir da spec",
      duration: 9000,
      add: ["gen_box", "gen_ttl", "gen_l1", "gen_l2", "gen_l3"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_gen",
          do: "highlight",
        },
        {
          at: 0,
          target: "gen_l1",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "n_gen",
        placement: "right",
        text: "A IA (Claude, GPT, etc.) lê a spec e gera o código de implementação. O agente de código sabe: (1) o comportamento esperado, (2) o stack tecnológico, (3) os padrões do projeto — e entrega uma implementação inicial.",
        why: "A IA gera rapidamente, mas pode errar. Por isso os testes automatizados são a verificação objetiva. A IA não decide se está certa — os testes decidem.",
      },
    },
    {
      id: "s4",
      title: "Testes automatizados validam",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_test",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "n_test",
        placement: "right",
        text: "Os testes (que a IA também pode gerar a partir da spec) são executados contra o código gerado. Cada teste verifica um cenário da spec: **se passou, o comportamento está correto**. Se falhou, sabe-se exatamente qual cenário quebrou.",
        why: "Testes como fonte de verdade: não é o julgamento humano que diz se o código está certo, são os testes. Isso torna a avaliação objetiva e reproduzível.",
      },
    },
    {
      id: "s5",
      title: "Feedback: o que falhou e por quê",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_feed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "n_feed",
        placement: "left",
        text: "Quando testes falham, o **feedback** é preciso: qual teste, qual asserção, qual valor esperado vs. recebido. Esse feedback é passado de volta à IA (ou ao humano) para refinar a implementação ou a spec.",
        why: "Feedback estruturado é o que torna o ciclo SDD eficiente: a IA recebe 'o teste LOGIN_WRONG_PASSWORD falhou esperando 401 mas recebeu 200' — não 'algo está errado'. Precisão acelera a correção.",
      },
    },
    {
      id: "s6",
      title: "Iteração: spec evolui com o aprendizado",
      duration: 9000,
      add: ["success", "a_success"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_success",
          do: "draw",
        },
        {
          at: 0,
          target: "n_spec",
          do: "highlight",
        },
        {
          at: 0,
          target: "success",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "success",
        placement: "left",
        text: "Cada ciclo refina o sistema: testes que falharam revelam casos de borda não especificados → a spec cresce → a IA reimplementa → mais testes passam. Quando **todos os testes passam**, o ciclo termina com uma entrega.",
        why: "Specs incompletas são normais no início. O ciclo SDD torna as lacunas visíveis rapidamente através dos testes, ao invés de descobrir em produção.",
      },
    },
    {
      id: "s7",
      title: "Spec como fonte de verdade",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_spec",
          do: "highlight",
        },
        {
          at: 0,
          target: "spec_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "n_spec",
        placement: "right",
        text: "A **Spec é a fonte de verdade única**: código e testes são derivados dela. Se o produto muda, você atualiza a spec → a IA re-gera → os testes confirmam. Nenhuma documentação fica desatualizada.",
        why: "Em projetos tradicionais, o código é o que 'manda' e a documentação fica obsoleta. Em SDD, a spec manda — e o código é apenas sua expressão em linguagem de máquina.",
      },
    },
    {
      id: "s8",
      title: "Rastreabilidade: spec ↔ código ↔ test",
      duration: 9000,
      add: ["trace_box", "trace_ttl", "trace_1", "a_t1", "trace_2", "a_t2", "trace_3"],
      remove: [],
      set: {},
      cues: [
        {
          at: 200,
          target: "a_t1",
          do: "draw",
        },
        {
          at: 450,
          target: "a_t2",
          do: "draw",
        },
        {
          at: 0,
          target: "trace_1",
          do: "highlight",
        },
        {
          at: 0,
          target: "trace_2",
          do: "highlight",
        },
        {
          at: 0,
          target: "trace_3",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "trace_box",
        placement: "right",
        text: "Cada item da spec tem um ID (ex.: #AUTH-01) que aparece no código (comentários gerados) e nos testes. Isso permite rastrear: 'qual código implementa esta spec?' e 'quais testes cobrem este requisito?'",
        why: "Rastreabilidade é essencial para compliance, auditorias e debugging. Saber que test_auth.py testa o requisito #AUTH-01 da spec torna a revisão de conformidade trivial.",
      },
    },
    {
      id: "s9",
      title: "SDD vs TDD vs BDD",
      duration: 9000,
      add: ["cmp_box", "cmp_ttl", "cmp_tdd", "cmp_bdd", "cmp_sdd"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cmp_sdd",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cmp_sdd",
        placement: "right",
        text: "**TDD**: humano escreve teste → humano escreve código. **BDD**: spec em Gherkin → humano implementa. **SDD**: spec em linguagem natural → IA gera código E testes → humano valida e refina.",
        why: "SDD não substitui TDD ou BDD — ele os amplifica com IA. O humano ainda define o comportamento (spec) e valida o resultado, mas a IA faz o trabalho de implementação e teste inicial.",
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 560,
          y: 340,
        },
        placement: "right",
        text: "Confirme o que você aprendeu sobre SDD 👇",
      },
      quiz: {
        question: "Na metodologia SDD, qual é a fonte de verdade do sistema?",
        options: [
          "O código gerado pela IA, pois é a implementação real",
          "Os testes automatizados, pois verificam o comportamento objetivamente",
          "A Spec de comportamento, da qual código e testes são derivados",
          "O feedback de erros, pois revela o que a spec não cobriu",
        ],
        answer: 2,
        explain:
          "A Spec é a fonte de verdade no SDD. Código e testes são derivados dela e podem ser regenerados. Quando o produto muda, a spec muda primeiro — código e testes seguem. Isso mantém tudo sincronizado.",
      },
    },
    {
      id: "s11",
      title: "Resumo: Spec-Driven Development",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "n_spec",
          do: "pulse",
          times: 2,
        },
        {
          at: 100,
          target: "n_gen",
          do: "pulse",
          times: 2,
        },
        {
          at: 200,
          target: "n_test",
          do: "pulse",
          times: 2,
        },
        {
          at: 300,
          target: "n_feed",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "n_spec",
          do: "highlight",
        },
        {
          at: 0,
          target: "n_gen",
          do: "highlight",
        },
        {
          at: 0,
          target: "n_test",
          do: "highlight",
        },
        {
          at: 0,
          target: "n_feed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 560,
          y: 340,
        },
        placement: "right",
        text: "SDD em 4 passos: **Spec → IA gera código → Testes validam → Feedback refina spec**. A spec é a única fonte de verdade. Humano define comportamento; IA implementa; testes verificam.",
        why: "SDD é especialmente poderoso quando combinado com agentes de código (como Claude Code): o humano escreve a spec em linguagem natural e o agente executa o ciclo inteiro autonomamente.",
      },
    },
  ],
};

export const sdd = validateExplainer(data);
