import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/sessions.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "sessions",
  title: "Sessions & Cookies",
  category: "Segurança & Autenticação",
  tags: ["sessions", "cookies", "auth"],
  level: "intro",
  glossary: {},
  elements: [
    {
      id: "col_b",
      tone: "accent",
      kind: "box",
      at: {
        x: 63,
        y: 100,
        w: 175,
        h: 75,
      },
      label: "🌐 Browser",
      variant: "outline",
    },
    {
      id: "col_a",
      tone: "good",
      kind: "box",
      at: {
        x: 613,
        y: 100,
        w: 175,
        h: 75,
      },
      label: "⚙️ API Server",
      variant: "outline",
    },
    {
      id: "col_r",
      tone: "accent2",
      kind: "box",
      at: {
        x: 1138,
        y: 100,
        w: 175,
        h: 75,
      },
      label: "🗄️ Session\nStore (Redis)",
      variant: "outline",
    },
    {
      id: "ll_b",
      kind: "connector",
      from: {
        x: 150,
        y: 175,
      },
      to: {
        x: 150,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_a",
      kind: "connector",
      from: {
        x: 700,
        y: 175,
      },
      to: {
        x: 700,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_r",
      kind: "connector",
      from: {
        x: 1225,
        y: 175,
      },
      to: {
        x: 1225,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "msg_login",
      tone: "accent",
      kind: "connector",
      from: {
        x: 150,
        y: 225,
      },
      to: {
        x: 700,
        y: 225,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_login_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 291,
        y: 189,
        w: 267,
        h: 41,
      },
      text: "POST /login {user,pass}",
      align: "center",
    },
    {
      id: "msg_store",
      tone: "good",
      kind: "connector",
      from: {
        x: 700,
        y: 313,
      },
      to: {
        x: 1225,
        y: 313,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_store_l",
      tone: "good",
      kind: "label",
      at: {
        x: 806,
        y: 277,
        w: 314,
        h: 41,
      },
      text: "SET session:abc123 {userId}",
      align: "center",
    },
    {
      id: "msg_cookie",
      tone: "good",
      kind: "connector",
      from: {
        x: 700,
        y: 400,
      },
      to: {
        x: 150,
        y: 400,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_cookie_l",
      tone: "good",
      kind: "label",
      at: {
        x: 193,
        y: 364,
        w: 465,
        h: 41,
      },
      text: "Set-Cookie: sid=abc123; HttpOnly; Secure",
      align: "center",
    },
    {
      id: "msg_req2",
      tone: "accent",
      kind: "connector",
      from: {
        x: 150,
        y: 500,
      },
      to: {
        x: 700,
        y: 500,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_req2_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 227,
        y: 464,
        w: 395,
        h: 41,
      },
      text: "GET /dashboard  Cookie: sid=abc123",
      align: "center",
    },
    {
      id: "msg_sread",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 700,
        y: 588,
      },
      to: {
        x: 1225,
        y: 588,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_sread_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 858,
        y: 552,
        w: 209,
        h: 41,
      },
      text: "GET session:abc123",
      align: "center",
    },
    {
      id: "msg_sresp",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 1225,
        y: 650,
      },
      to: {
        x: 700,
        y: 650,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_sresp_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 806,
        y: 614,
        w: 314,
        h: 41,
      },
      text: '{userId: 42, role: "admin"}',
      align: "center",
    },
    {
      id: "msg_resp2",
      tone: "good",
      kind: "connector",
      from: {
        x: 700,
        y: 713,
      },
      to: {
        x: 150,
        y: 713,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_resp2_l",
      tone: "good",
      kind: "label",
      at: {
        x: 280,
        y: 677,
        w: 291,
        h: 41,
      },
      text: "200 OK {dados do usuário}",
      align: "center",
    },
    {
      id: "msg_logout",
      tone: "hot",
      kind: "connector",
      from: {
        x: 150,
        y: 788,
      },
      to: {
        x: 700,
        y: 788,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_logout_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 355,
        y: 752,
        w: 140,
        h: 41,
      },
      text: "POST /logout",
      align: "center",
    },
    {
      id: "msg_sdel",
      tone: "hot",
      kind: "connector",
      from: {
        x: 700,
        y: 844,
      },
      to: {
        x: 1225,
        y: 844,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_sdel_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 858,
        y: 808,
        w: 209,
        h: 41,
      },
      text: "DEL session:abc123",
      align: "center",
    },
    {
      id: "msg_clear",
      tone: "hot",
      kind: "connector",
      from: {
        x: 700,
        y: 875,
      },
      to: {
        x: 150,
        y: 875,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "msg_clear_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 268,
        y: 839,
        w: 314,
        h: 41,
      },
      text: "Set-Cookie: sid=; Max-Age=0",
      align: "center",
    },
    {
      id: "cookie_bg",
      kind: "box",
      at: {
        x: 350,
        y: 613,
        w: 300,
        h: 163,
      },
      variant: "outline",
    },
    {
      id: "cookie_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 366,
        y: 614,
        w: 267,
        h: 41,
      },
      text: "🍪 Set-Cookie Atributos",
      align: "center",
    },
    {
      id: "ca1",
      kind: "label",
      at: {
        x: 206,
        y: 642,
        w: 314,
        h: 41,
      },
      text: "HttpOnly  → JS não pode ler",
      align: "center",
    },
    {
      id: "ca2",
      kind: "label",
      at: {
        x: 223,
        y: 667,
        w: 279,
        h: 41,
      },
      text: "Secure    → só via HTTPS",
      align: "center",
    },
    {
      id: "ca3",
      kind: "label",
      at: {
        x: 217,
        y: 692,
        w: 291,
        h: 41,
      },
      text: "SameSite  → bloqueia CSRF",
      align: "center",
    },
    {
      id: "ca4",
      kind: "label",
      at: {
        x: 206,
        y: 717,
        w: 314,
        h: 41,
      },
      text: "Max-Age   → TTL em segundos",
      align: "center",
    },
    {
      id: "ca5",
      kind: "label",
      at: {
        x: 217,
        y: 742,
        w: 291,
        h: 41,
      },
      text: "Path      → escopo de URL",
      align: "center",
    },
    {
      id: "store_bg",
      kind: "box",
      at: {
        x: 675,
        y: 613,
        w: 450,
        h: 163,
      },
      variant: "outline",
    },
    {
      id: "store_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 749,
        y: 614,
        w: 302,
        h: 41,
      },
      text: "🗄️ Onde Guardar Sessions?",
      align: "center",
    },
    {
      id: "ss1",
      tone: "hot",
      kind: "label",
      at: {
        x: 403,
        y: 642,
        w: 570,
        h: 41,
      },
      text: "In-memory  → rápido, mas não escala (1 instância)",
      align: "center",
    },
    {
      id: "ss2",
      tone: "good",
      kind: "label",
      at: {
        x: 467,
        y: 669,
        w: 442,
        h: 41,
      },
      text: "Redis      → distribuído, TTL nativo ✓",
      align: "center",
    },
    {
      id: "ss3",
      tone: "warn",
      kind: "label",
      at: {
        x: 432,
        y: 694,
        w: 512,
        h: 41,
      },
      text: "Banco SQL  → durável, mas lento para sessões",
      align: "center",
    },
    {
      id: "ss4",
      tone: "hot",
      kind: "label",
      at: {
        x: 385,
        y: 719,
        w: 605,
        h: 41,
      },
      text: "Sticky sessions → evitar! acopla cliente ao servidor",
      align: "center",
    },
    {
      id: "ss5",
      kind: "label",
      at: {
        x: 472,
        y: 744,
        w: 430,
        h: 41,
      },
      text: "Redis Cluster → multi-nó com sharding",
      align: "center",
    },
    {
      id: "csrf_bg",
      kind: "box",
      at: {
        x: 350,
        y: 425,
        w: 300,
        h: 150,
      },
      variant: "outline",
    },
    {
      id: "csrf_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 395,
        y: 427,
        w: 209,
        h: 41,
      },
      text: "🛡️ CSRF / Ataques",
      align: "center",
    },
    {
      id: "crf1",
      tone: "good",
      kind: "label",
      at: {
        x: 182,
        y: 452,
        w: 360,
        h: 41,
      },
      text: "SameSite=Strict → melhor defesa",
      align: "center",
    },
    {
      id: "crf2",
      kind: "label",
      at: {
        x: 171,
        y: 477,
        w: 384,
        h: 41,
      },
      text: "CSRF Token → campo oculto no form",
      align: "center",
    },
    {
      id: "crf3",
      kind: "label",
      at: {
        x: 159,
        y: 502,
        w: 407,
        h: 41,
      },
      text: "Session fixation → regen session_id",
      align: "center",
    },
    {
      id: "crf4",
      kind: "label",
      at: {
        x: 136,
        y: 527,
        w: 453,
        h: 41,
      },
      text: "Hijacking → detectar user-agent changes",
      align: "center",
    },
    {
      id: "lbl_login",
      tone: "accent",
      kind: "label",
      at: {
        x: -25,
        y: 194,
        w: 75,
        h: 41,
      },
      text: "Login",
      align: "center",
    },
    {
      id: "lbl_req",
      kind: "label",
      at: {
        x: -28,
        y: 469,
        w: 81,
        h: 41,
      },
      text: "Request",
      align: "center",
    },
    {
      id: "lbl_out",
      tone: "hot",
      kind: "label",
      at: {
        x: -25,
        y: 757,
        w: 75,
        h: 41,
      },
      text: "Logout",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: HTTP é Stateless",
      duration: 6500,
      add: ["col_b", "col_a", "col_r", "ll_b", "ll_a", "ll_r", "lbl_login", "lbl_req", "lbl_out"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "col_a",
        placement: "top",
        text: "HTTP não tem memória — cada request é independente. O servidor não sabe se a request vem do mesmo usuário que fez login.",
        why: 'Precisamos de um mecanismo para "lembrar" o estado do usuário entre requests.',
      },
    },
    {
      id: "s2",
      title: "① Login: servidor cria session no store",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "lbl_login",
        "msg_login",
        "msg_login_l",
        "msg_store",
        "msg_store_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_a",
          do: "highlight",
        },
        {
          at: 0,
          target: "col_r",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "msg_store_l",
        placement: "top",
        text: "Após validar as credenciais, o servidor gera um **session_id** aleatório (ex: UUID v4) e armazena `{userId, role, ...}` no Redis com `SET session:abc123 ...`.",
        why: "O session_id deve ser criptograficamente aleatório — não sequencial ou previsível.",
      },
    },
    {
      id: "s3",
      title: "② Set-Cookie: session_id para o browser",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "lbl_login",
        "msg_login",
        "msg_login_l",
        "msg_store",
        "msg_store_l",
        "msg_cookie",
        "msg_cookie_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_b",
          do: "highlight",
        },
        {
          at: 0,
          target: "msg_cookie",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "msg_cookie_l",
        placement: "top",
        text: "`Set-Cookie: sid=abc123; HttpOnly; Secure; SameSite=Strict`\n\nO browser armazena o cookie e o enviará automaticamente em toda request futura.",
      },
    },
    {
      id: "s4",
      title: "🍪 Atributos do Cookie",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "lbl_login",
        "msg_login",
        "msg_login_l",
        "msg_cookie",
        "msg_cookie_l",
        "cookie_bg",
        "cookie_title",
        "ca1",
        "ca2",
        "ca3",
        "ca4",
        "ca5",
        "csrf_bg",
        "csrf_title",
        "crf1",
        "crf2",
        "crf3",
        "crf4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cookie_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cookie_bg",
        placement: "right",
        text: "**HttpOnly**: protege contra XSS (JS não acessa o cookie).\n**Secure**: só trafega em HTTPS.\n**SameSite=Strict**: bloqueia envio cross-site → principal defesa contra CSRF.",
        why: "Sem HttpOnly, um script malicioso pode roubar o session_id via `document.cookie`.",
      },
    },
    {
      id: "s5",
      title: "③ Request subsequente: browser envia cookie automaticamente",
      duration: 6500,
      add: ["col_b", "col_a", "col_r", "ll_b", "ll_a", "ll_r", "lbl_req", "msg_req2", "msg_req2_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_b",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "msg_req2_l",
        placement: "top",
        text: "O browser anexa automaticamente o cookie a toda request no mesmo domínio: `Cookie: sid=abc123`. O usuário não precisa fazer nada.",
      },
    },
    {
      id: "s6",
      title: "④ Servidor valida session no store",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "lbl_req",
        "msg_req2",
        "msg_req2_l",
        "msg_sread",
        "msg_sread_l",
        "msg_sresp",
        "msg_sresp_l",
        "msg_resp2",
        "msg_resp2_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_a",
          do: "highlight",
        },
        {
          at: 0,
          target: "col_r",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "msg_sresp_l",
        placement: "left",
        text: 'Servidor faz `GET session:abc123` no Redis. Se encontrar, recupera `{userId: 42, role: "admin"}` e processa a request. Se expirado ou inexistente → 401.',
      },
    },
    {
      id: "s7",
      title: "Session Store: onde guardar?",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "store_bg",
        "store_title",
        "ss1",
        "ss2",
        "ss3",
        "ss4",
        "ss5",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_r",
          do: "highlight",
        },
        {
          at: 0,
          target: "store_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "store_bg",
        placement: "left",
        text: "**Redis** é o padrão para session stores distribuídos: O(1) GET/SET, TTL nativo (auto-expire), suporte a cluster. Evite sticky sessions — acoplam usuários a servidores específicos.",
        why: "In-memory funciona apenas com uma instância — morre junto com o processo.",
      },
    },
    {
      id: "s8",
      title: "CSRF e Session Attacks",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "csrf_bg",
        "csrf_title",
        "crf1",
        "crf2",
        "crf3",
        "crf4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "csrf_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "csrf_bg",
        placement: "right",
        text: "**CSRF**: site malicioso faz request em nome do usuário usando seu cookie. **Session fixation**: atacante força um session_id — regenerar ID após login. **Hijacking**: detectar mudanças de IP/User-Agent.",
      },
    },
    {
      id: "s9",
      title: "⑤ Logout: deletar session + limpar cookie",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "lbl_out",
        "msg_logout",
        "msg_logout_l",
        "msg_sdel",
        "msg_sdel_l",
        "msg_clear",
        "msg_clear_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_r",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "msg_sdel_l",
        placement: "top",
        text: "Logout **deve** deletar a session do store (`DEL session:abc123`) E expirar o cookie (`Max-Age=0`). Só limpar o cookie é insuficiente — token ainda seria válido no store.",
        why: "Se apenas o cookie for removido, alguém com o session_id ainda teria acesso.",
      },
    },
    {
      id: "s10",
      title: "Sessions vs JWT — quando usar cada?",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "store_bg",
        "store_title",
        "ss1",
        "ss2",
        "ss3",
        "ss4",
        "ss5",
        "cookie_bg",
        "cookie_title",
        "ca1",
        "ca2",
        "ca3",
        "ca4",
        "ca5",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "store_bg",
        placement: "top",
        text: "**Sessions**: revogação imediata, dados server-side (menores cookies). Requer session store.\n**JWT**: stateless, sem store, escala horizontal — mas revogação complexa. Sessions são preferíveis para web apps tradicionais.",
      },
    },
    {
      id: "s11",
      title: "Quiz",
      duration: 6500,
      add: ["col_b", "col_a", "col_r", "ll_b", "ll_a", "ll_r"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: "Por que o atributo `HttpOnly` num cookie de sessão é importante?",
        options: [
          "Garante que o cookie só trafega por HTTP (não HTTPS)",
          "Impede que JavaScript acesse o valor do cookie, protegendo contra XSS",
          "Faz o cookie expirar ao fechar o browser",
          "Permite que o cookie seja enviado em requests cross-origin",
        ],
        answer: 1,
        explain:
          "`HttpOnly` impede que scripts JavaScript acessem `document.cookie`, o que bloqueia ataques XSS de roubar o session_id. Sem esse atributo, qualquer script injetado na página pode exfiltrar o cookie e sequestrar a sessão.",
      },
    },
    {
      id: "s12",
      title: "Resumo: Sessions & Cookies",
      duration: 6500,
      add: [
        "col_b",
        "col_a",
        "col_r",
        "ll_b",
        "ll_a",
        "ll_r",
        "msg_login",
        "msg_login_l",
        "msg_store",
        "msg_store_l",
        "msg_cookie",
        "msg_cookie_l",
        "msg_req2",
        "msg_req2_l",
        "msg_sread",
        "msg_sread_l",
        "msg_sresp",
        "msg_sresp_l",
        "msg_resp2",
        "msg_resp2_l",
        "msg_logout",
        "msg_logout_l",
        "msg_sdel",
        "msg_sdel_l",
        "msg_clear",
        "msg_clear_l",
        "cookie_bg",
        "cookie_title",
        "ca1",
        "ca2",
        "ca3",
        "store_bg",
        "store_title",
        "ss2",
        "lbl_login",
        "lbl_req",
        "lbl_out",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "col_a",
        placement: "right",
        text: "Session-based auth: ID aleatório no cookie HttpOnly/Secure → estado no Redis. Logout deleta do store + expira cookie. SameSite bloqueia CSRF. Escala com Redis distribuído.",
      },
    },
  ],
};

export const sessions = validateExplainer(data);
