import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/skills.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "skills",
  title: "Skills — Capacidades de Agentes de IA",
  subtitle: "Registry, anatomia, trigger, execução e composição",
  category: "IA & Agentes",
  tags: ["agentes", "ferramentas"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "reg_box",
      kind: "box",
      at: {
        x: 50,
        y: 75,
        w: 475,
        h: 700,
      },
      variant: "outline",
    },
    {
      id: "reg_lbl",
      kind: "label",
      at: {
        x: 189,
        y: 82,
        w: 198,
        h: 41,
      },
      text: "📚 Skill Registry",
      align: "center",
    },
    {
      id: "reg_sub",
      kind: "label",
      at: {
        x: 96,
        y: 104,
        w: 384,
        h: 41,
      },
      text: "capacidades registradas do agente",
      align: "center",
      muted: true,
    },
    {
      id: "sk_code",
      kind: "box",
      at: {
        x: 63,
        y: 150,
        w: 450,
        h: 113,
      },
      label: "💻 run-code",
      sub: 'Trigger: "execute / run / test"',
      variant: "outline",
    },
    {
      id: "sk_web",
      kind: "box",
      at: {
        x: 63,
        y: 280,
        w: 450,
        h: 113,
      },
      label: "🌐 web-search",
      sub: 'Trigger: "search / find / look up"',
      variant: "outline",
    },
    {
      id: "sk_file",
      kind: "box",
      at: {
        x: 63,
        y: 410,
        w: 450,
        h: 113,
      },
      label: "📁 read-write-file",
      sub: 'Trigger: "open / save / edit file"',
      variant: "outline",
    },
    {
      id: "sk_review",
      kind: "box",
      at: {
        x: 63,
        y: 540,
        w: 450,
        h: 113,
      },
      label: "🔍 code-review",
      sub: 'Trigger: "review / check / lint"',
      variant: "outline",
    },
    {
      id: "sk_notify",
      kind: "box",
      at: {
        x: 63,
        y: 658,
        w: 450,
        h: 113,
      },
      label: "🔔 notify",
      sub: 'Trigger: "alert / notify / send"',
      variant: "outline",
    },
    {
      id: "llm_box",
      kind: "box",
      at: {
        x: 650,
        y: 325,
        w: 250,
        h: 150,
      },
      label: "🧠 LLM",
      sub: "(agente)",
      variant: "outline",
    },
    {
      id: "usr_box",
      kind: "token",
      at: {
        x: 650,
        y: 75,
        w: 250,
        h: 63,
      },
      text: '👤 "Execute os testes do projeto"',
    },
    {
      id: "a_usr_llm",
      tone: "accent",
      kind: "connector",
      from: {
        x: 775,
        y: 140,
      },
      to: {
        x: 775,
        y: 323,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "decide_lbl",
      kind: "label",
      at: {
        x: 647,
        y: 229,
        w: 256,
        h: 41,
      },
      text: "match: 'execute / run'",
      align: "center",
      muted: true,
    },
    {
      id: "a_llm_sk",
      tone: "accent",
      kind: "connector",
      from: {
        x: 775,
        y: 478,
      },
      to: {
        x: 775,
        y: 538,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "inv_box",
      kind: "box",
      at: {
        x: 650,
        y: 540,
        w: 250,
        h: 75,
      },
      label: "Invocação:",
      sub: "run-code(cmd='pytest')",
      variant: "outline",
    },
    {
      id: "a_inv_ex",
      tone: "warn",
      kind: "connector",
      from: {
        x: 775,
        y: 618,
      },
      to: {
        x: 775,
        y: 668,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "exec_box",
      kind: "box",
      at: {
        x: 650,
        y: 670,
        w: 250,
        h: 75,
      },
      label: "⚙️ Handler executa",
      sub: "$ pytest ./tests",
      variant: "outline",
    },
    {
      id: "a_ex_res",
      tone: "good",
      kind: "connector",
      from: {
        x: 775,
        y: 748,
      },
      to: {
        x: 775,
        y: 798,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "res_box",
      kind: "box",
      at: {
        x: 650,
        y: 800,
        w: 250,
        h: 75,
      },
      label: "✓ 12 passed, 0 failed",
      sub: "(retorna ao LLM)",
      variant: "outline",
    },
    {
      id: "anat_box",
      kind: "box",
      at: {
        x: 975,
        y: 75,
        w: 575,
        h: 400,
      },
      variant: "outline",
    },
    {
      id: "anat_lbl",
      kind: "label",
      at: {
        x: 1140,
        y: 82,
        w: 244,
        h: 41,
      },
      text: "Anatomia de uma Skill",
      align: "center",
    },
    {
      id: "anat_name",
      kind: "token",
      at: {
        x: 1000,
        y: 125,
        w: 525,
        h: 55,
      },
      text: 'name: "run-code"',
    },
    {
      id: "anat_desc",
      kind: "token",
      at: {
        x: 1000,
        y: 193,
        w: 525,
        h: 55,
      },
      text: 'description: "Executa código e retorna output"',
    },
    {
      id: "anat_trig",
      kind: "token",
      at: {
        x: 1000,
        y: 260,
        w: 525,
        h: 55,
      },
      text: 'trigger: ["execute", "run", "test"]',
    },
    {
      id: "anat_input",
      kind: "token",
      at: {
        x: 1000,
        y: 328,
        w: 525,
        h: 55,
      },
      text: "input: { cmd: string, timeout?: number }",
    },
    {
      id: "anat_output",
      kind: "token",
      at: {
        x: 1000,
        y: 395,
        w: 525,
        h: 55,
      },
      text: "output: { stdout, stderr, exit_code }",
    },
    {
      id: "comp_box",
      kind: "box",
      at: {
        x: 975,
        y: 525,
        w: 575,
        h: 325,
      },
      variant: "outline",
    },
    {
      id: "comp_lbl",
      kind: "label",
      at: {
        x: 1036,
        y: 532,
        w: 453,
        h: 41,
      },
      text: "Composição: Skills chamam outras Skills",
      align: "center",
    },
    {
      id: "comp_sk1",
      kind: "token",
      at: {
        x: 1000,
        y: 573,
        w: 225,
        h: 55,
      },
      text: "code-review",
    },
    {
      id: "a_comp1",
      kind: "connector",
      from: {
        x: 1113,
        y: 630,
      },
      to: {
        x: 1113,
        y: 663,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "comp_sk2",
      kind: "token",
      at: {
        x: 1000,
        y: 665,
        w: 225,
        h: 55,
      },
      text: "→ read-write-file",
    },
    {
      id: "a_comp2",
      kind: "connector",
      from: {
        x: 1113,
        y: 723,
      },
      to: {
        x: 1113,
        y: 755,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "comp_sk3",
      kind: "token",
      at: {
        x: 1000,
        y: 758,
        w: 225,
        h: 55,
      },
      text: "→ run-code (lint)",
    },
    {
      id: "comp_note",
      kind: "label",
      at: {
        x: 1300,
        y: 579,
        w: 186,
        h: 41,
      },
      text: "Skills compostas",
      align: "start",
      muted: true,
    },
    {
      id: "comp_note2",
      kind: "label",
      at: {
        x: 1300,
        y: 604,
        w: 244,
        h: 41,
      },
      text: "orquestram sub-skills",
      align: "start",
      muted: true,
    },
    {
      id: "comp_note3",
      kind: "label",
      at: {
        x: 1300,
        y: 629,
        w: 209,
        h: 41,
      },
      text: "sem o LLM precisar",
      align: "start",
      muted: true,
    },
    {
      id: "comp_note4",
      kind: "label",
      at: {
        x: 1300,
        y: 654,
        w: 233,
        h: 41,
      },
      text: "gerenciar cada passo",
      align: "start",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que são Skills de agentes",
      duration: 9000,
      add: ["reg_box", "reg_lbl", "reg_sub"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "reg_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "reg_box",
        placement: "right",
        text: "Uma **Skill** é uma capacidade nomeada e descrita que o agente pode invocar. Ela encapsula uma ação (executar código, buscar na web, ler arquivo) com um contrato claro de input/output.",
        why: "Skills são a ponte entre o raciocínio do LLM e a execução de ações no mundo real. Elas são mais ricas que tools MCP porque incluem lógica de trigger e podem ser compostas.",
      },
    },
    {
      id: "s2",
      title: "O Registry de Skills",
      duration: 9000,
      add: ["sk_code", "sk_web", "sk_file", "sk_review", "sk_notify"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sk_code",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_web",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sk_web",
        placement: "right",
        text: "O **Skill Registry** é o catálogo de capacidades do agente. Cada skill tem nome, descrição (para o LLM entender quando usar) e triggers (palavras-chave que ativam a escolha).",
        why: "O registry é dinâmico: skills podem ser adicionadas, removidas ou desabilitadas sem mudar o modelo. Isso torna o agente extensível e configurável por domínio.",
      },
    },
    {
      id: "s3",
      title: "Anatomia de uma Skill",
      duration: 9000,
      add: ["anat_box", "anat_lbl", "anat_name", "anat_desc", "anat_trig", "anat_input", "anat_output"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "anat_trig",
          do: "highlight",
        },
        {
          at: 0,
          target: "anat_input",
          do: "highlight",
        },
        {
          at: 0,
          target: "anat_output",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "anat_box",
        placement: "left",
        text: "Cada Skill tem 5 componentes: **name** (identificador único), **description** (texto que o LLM lê), **trigger** (palavras que ativam), **input schema** e **output schema**.",
        why: "A description é o componente mais crítico: o LLM decide qual skill invocar lendo as descriptions e comparando com a tarefa. Uma boa description é concisa, específica e com exemplos de uso.",
      },
    },
    {
      id: "s4",
      title: "Trigger: o LLM decide qual skill usar",
      duration: 9000,
      add: ["llm_box", "usr_box", "a_usr_llm", "decide_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_usr_llm",
          do: "draw",
        },
        {
          at: 0,
          target: "llm_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_code",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "llm_box",
        placement: "right",
        text: "Quando o usuário pede algo, o LLM analisa a mensagem e **compara com os triggers** de cada skill no registry. Ao detectar 'execute os testes', faz match com run-code (trigger: 'execute', 'run', 'test').",
        why: "O trigger não é só pattern matching — o LLM faz match semântico usando as descriptions. Isso permite que 'rode os unit tests' acione run-code mesmo sem a palavra exata 'execute'.",
      },
    },
    {
      id: "s5",
      title: "Invocação da Skill",
      duration: 9000,
      add: ["a_llm_sk", "inv_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_llm_sk",
          do: "draw",
        },
        {
          at: 0,
          target: "inv_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_code",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "inv_box",
        placement: "right",
        text: "O LLM emite uma chamada de skill com o **nome da skill e os argumentos** preenchidos conforme o input schema: `run-code(cmd='pytest')`. O framework valida os args antes de executar.",
        why: "Validar o input schema antes de executar evita que o LLM passe argumentos inválidos ao handler — o que causaria erros difíceis de diagnosticar no runtime.",
      },
    },
    {
      id: "s6",
      title: "Execução do Handler",
      duration: 9000,
      add: ["a_inv_ex", "exec_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_inv_ex",
          do: "draw",
        },
        {
          at: 0,
          target: "exec_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "exec_box",
        placement: "right",
        text: "O **handler** é a implementação real da skill: código que roda pytest, faz uma chamada de API, lê um arquivo. O handler é isolado do LLM e pode ser escrito em qualquer linguagem.",
        why: "Separar handler da descrição é fundamental: o LLM não precisa saber como a skill é implementada — só o contrato (input/output). Isso permite trocar a implementação sem mudar o agente.",
      },
    },
    {
      id: "s7",
      title: "Resultado retorna ao LLM",
      duration: 9000,
      add: ["a_ex_res", "res_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_ex_res",
          do: "draw",
        },
        {
          at: 0,
          target: "res_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "res_box",
        placement: "right",
        text: "O handler executa e retorna o resultado conforme o **output schema**: stdout, stderr, exit_code. O framework serializa e injeta como `tool_result` no próximo turno do LLM.",
        why: "O LLM recebe o resultado e decide o próximo passo: responder ao usuário, invocar outra skill, ou pedir mais informações. O loop continua até a tarefa ser concluída.",
      },
    },
    {
      id: "s8",
      title: "Composição: Skills chamam outras Skills",
      duration: 9000,
      add: [
        "comp_box",
        "comp_lbl",
        "comp_sk1",
        "a_comp1",
        "comp_sk2",
        "a_comp2",
        "comp_sk3",
        "comp_note",
        "comp_note2",
        "comp_note3",
        "comp_note4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 200,
          target: "a_comp1",
          do: "draw",
        },
        {
          at: 450,
          target: "a_comp2",
          do: "draw",
        },
        {
          at: 0,
          target: "comp_sk1",
          do: "highlight",
        },
        {
          at: 0,
          target: "comp_sk2",
          do: "highlight",
        },
        {
          at: 0,
          target: "comp_sk3",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "comp_box",
        placement: "left",
        text: "**Skills compostas** orquestram sub-skills internamente. Ex.: code-review primeiro lê o arquivo (read-write-file) e depois faz lint (run-code). O LLM invoca só a skill de alto nível.",
        why: "Composição cria uma hierarquia de abstração: o LLM raciocina em alto nível (review my PR) e a skill cuida dos detalhes (ler arquivos, rodar lint, formatar resultado). Reduz a carga cognitiva do LLM.",
      },
    },
    {
      id: "s9",
      title: "Skills built-in vs customizadas",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sk_code",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_web",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_notify",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sk_notify",
        placement: "right",
        text: "**Built-in**: skills que vêm com o framework (web-search, run-code, read-file). **Customizadas**: skills específicas do seu domínio (consultar-CRM, gerar-relatorio, aprovar-pedido). O registry é extensível.",
        why: "Skills customizadas são onde o valor de negócio mora. Elas encapsulam processos internos da empresa e permitem que o agente execute tarefas específicas do domínio sem o LLM precisar conhecer detalhes de implementação.",
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Confirme o que você aprendeu sobre Skills 👇",
      },
      quiz: {
        question: "Por que a description de uma Skill é o componente mais crítico para o LLM?",
        options: [
          "Porque o LLM usa a description para gerar o código do handler",
          "Porque o LLM lê as descriptions para decidir semanticamente qual skill invocar — uma description ruim causa escolhas erradas",
          "Porque o framework valida o input schema usando a description como documentação",
          "Porque descriptions são exibidas ao usuário final para explicar o que o agente fez",
        ],
        answer: 1,
        explain:
          "O LLM não vê o código do handler — só as descriptions. Ele compara a tarefa do usuário com as descriptions de todas as skills disponíveis e escolhe a mais adequada. Uma description vaga ou imprecisa resulta em escolhas incorretas ou na skill errada sendo acionada.",
      },
    },
    {
      id: "s11",
      title: "Resumo: Skills de Agentes",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sk_code",
          do: "pulse",
          times: 2,
        },
        {
          at: 80,
          target: "sk_web",
          do: "pulse",
          times: 2,
        },
        {
          at: 160,
          target: "sk_file",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "sk_review",
          do: "pulse",
          times: 2,
        },
        {
          at: 320,
          target: "sk_notify",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "sk_code",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_web",
          do: "highlight",
        },
        {
          at: 0,
          target: "sk_file",
          do: "highlight",
        },
        {
          at: 0,
          target: "anat_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "comp_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "right",
        text: "**Skills** = capacidades nomeadas com description, trigger, input/output schema e handler. O LLM lê descriptions para decidir qual invocar. Skills compostas orquestram sub-skills. Registry é extensível por domínio.",
        why: "Skills são o que transforma um LLM genérico num agente especializado: elas definem o que o agente CAN DO, e as descriptions definem como o agente SABE que pode fazer.",
      },
    },
  ],
};

export const skills = validateExplainer(data);
