import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/specs.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "specs",
  title: "Specs para Agentes de IA",
  subtitle: "O documento que define comportamento, tools, contratos e exemplos",
  category: "IA & Agentes",
  tags: ["especificação", "agentes"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "doc_border",
      kind: "box",
      at: {
        x: 40,
        y: 38,
        w: 670,
        h: 825,
      },
      variant: "outline",
    },
    {
      id: "doc_title",
      kind: "label",
      at: {
        x: 276,
        y: 47,
        w: 198,
        h: 41,
      },
      text: "📄 Spec do Agente",
      align: "center",
    },
    {
      id: "doc_ver",
      kind: "label",
      at: {
        x: 206,
        y: 69,
        w: 337,
        h: 41,
      },
      text: "v2.3 · revisado em 2025-06-26",
      align: "center",
      muted: true,
    },
    {
      id: "s_ctx",
      kind: "box",
      at: {
        x: 50,
        y: 110,
        w: 650,
        h: 75,
      },
      label: "🌍 Contexto e objetivo",
      variant: "outline",
    },
    {
      id: "s_res",
      kind: "box",
      at: {
        x: 50,
        y: 198,
        w: 650,
        h: 75,
      },
      label: "⛔ Restrições e limites",
      variant: "outline",
    },
    {
      id: "s_tools",
      kind: "box",
      at: {
        x: 50,
        y: 285,
        w: 650,
        h: 75,
      },
      label: "🔧 Tools disponíveis",
      variant: "outline",
    },
    {
      id: "s_io",
      kind: "box",
      at: {
        x: 50,
        y: 373,
        w: 650,
        h: 75,
      },
      label: "📤 Contratos de I/O",
      variant: "outline",
    },
    {
      id: "s_ex",
      kind: "box",
      at: {
        x: 50,
        y: 460,
        w: 650,
        h: 125,
      },
      label: "💡 Exemplos (few-shot)",
      variant: "outline",
    },
    {
      id: "s_gr",
      kind: "box",
      at: {
        x: 50,
        y: 598,
        w: 650,
        h: 75,
      },
      label: "🛡️ Guardrails",
      variant: "outline",
    },
    {
      id: "s_ver",
      kind: "box",
      at: {
        x: 50,
        y: 685,
        w: 650,
        h: 75,
      },
      label: "🔖 Versionamento",
      variant: "outline",
    },
    {
      id: "s_val",
      kind: "box",
      at: {
        x: 50,
        y: 773,
        w: 650,
        h: 75,
      },
      label: "✅ Validação da spec",
      variant: "outline",
    },
    {
      id: "d_ctx",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 225,
      },
      variant: "outline",
    },
    {
      id: "d_ctx_ttl",
      kind: "label",
      at: {
        x: 1018,
        y: 79,
        w: 302,
        h: 41,
      },
      text: "Contexto: o QUÊ e o PORQUÊ",
      align: "center",
    },
    {
      id: "d_ctx_1",
      kind: "token",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 50,
      },
      text: "Nome: agente-suporte-vendas",
    },
    {
      id: "d_ctx_2",
      kind: "token",
      at: {
        x: 813,
        y: 180,
        w: 713,
        h: 50,
      },
      text: "Objetivo: responder clientes sobre produtos e pedidos",
    },
    {
      id: "d_ctx_3",
      kind: "token",
      at: {
        x: 813,
        y: 240,
        w: 713,
        h: 50,
      },
      text: "Usuário: cliente final · Canal: chat do site",
    },
    {
      id: "d_res",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "d_res_ttl",
      kind: "label",
      at: {
        x: 930,
        y: 79,
        w: 477,
        h: 41,
      },
      text: "Restrições: o que o agente NÃO pode fazer",
      align: "center",
    },
    {
      id: "d_res_1",
      kind: "token",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 50,
      },
      text: "❌ Nunca prometer prazos sem consultar o sistema",
    },
    {
      id: "d_res_2",
      kind: "token",
      at: {
        x: 813,
        y: 180,
        w: 713,
        h: 50,
      },
      text: "❌ Não discutir preços de concorrentes",
    },
    {
      id: "d_res_3",
      kind: "token",
      at: {
        x: 813,
        y: 240,
        w: 713,
        h: 50,
      },
      text: "⚠️ Escalar para humano em casos de cancelamento",
    },
    {
      id: "d_tools",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 275,
      },
      variant: "outline",
    },
    {
      id: "d_tools_ttl",
      kind: "label",
      at: {
        x: 1006,
        y: 79,
        w: 326,
        h: 41,
      },
      text: "Tools: capacidades do agente",
      align: "center",
    },
    {
      id: "d_t1",
      kind: "token",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 50,
      },
      text: "buscar_pedido(order_id) → { status, items, eta }",
    },
    {
      id: "d_t2",
      kind: "token",
      at: {
        x: 813,
        y: 180,
        w: 713,
        h: 50,
      },
      text: "listar_produtos(categoria?) → [{ id, nome, preco }]",
    },
    {
      id: "d_t3",
      kind: "token",
      at: {
        x: 813,
        y: 240,
        w: 713,
        h: 50,
      },
      text: "criar_ticket(motivo, prioridade) → ticket_id",
    },
    {
      id: "d_tools_note",
      kind: "label",
      at: {
        x: 878,
        y: 289,
        w: 581,
        h: 41,
      },
      text: "Cada tool com nome, assinatura e schema de retorno",
      align: "center",
      muted: true,
    },
    {
      id: "d_io",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 275,
      },
      variant: "outline",
    },
    {
      id: "d_io_ttl",
      kind: "label",
      at: {
        x: 1076,
        y: 79,
        w: 186,
        h: 41,
      },
      text: "Contratos de I/O",
      align: "center",
    },
    {
      id: "d_io_in",
      kind: "token",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 75,
      },
      text: "Input: { message: string, session_id: string,",
    },
    {
      id: "d_io_out",
      kind: "token",
      at: {
        x: 813,
        y: 205,
        w: 713,
        h: 75,
      },
      text: "Output: { reply: string, actions_taken: string[],",
    },
    {
      id: "d_io_note",
      kind: "label",
      at: {
        x: 808,
        y: 284,
        w: 721,
        h: 41,
      },
      text: "Contratos permitem validar e testar o agente programaticamente",
      align: "center",
      muted: true,
    },
    {
      id: "d_ex",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 350,
      },
      variant: "outline",
    },
    {
      id: "d_ex_ttl",
      kind: "label",
      at: {
        x: 1023,
        y: 79,
        w: 291,
        h: 41,
      },
      text: "Exemplos few-shot na spec",
      align: "center",
    },
    {
      id: "d_ex_1u",
      kind: "token",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 50,
      },
      text: "User: Onde está meu pedido #12345?",
    },
    {
      id: "d_ex_1a",
      kind: "token",
      at: {
        x: 813,
        y: 180,
        w: 713,
        h: 75,
      },
      text: "Agente: Consultei o pedido #12345. Status: em trânsito,",
    },
    {
      id: "d_ex_2u",
      kind: "token",
      at: {
        x: 813,
        y: 265,
        w: 713,
        h: 50,
      },
      text: "User: Quero cancelar.",
    },
    {
      id: "d_ex_2a",
      kind: "token",
      at: {
        x: 813,
        y: 323,
        w: 713,
        h: 75,
      },
      text: "Agente: [escalate: true] Vou transferir para nossa equipe",
    },
    {
      id: "cmp_box",
      kind: "box",
      at: {
        x: 800,
        y: 75,
        w: 738,
        h: 425,
      },
      variant: "outline",
    },
    {
      id: "cmp_ttl",
      kind: "label",
      at: {
        x: 971,
        y: 79,
        w: 395,
        h: 41,
      },
      text: "Spec vs System Prompt vs CLAUDE.md",
      align: "center",
    },
    {
      id: "cmp_sp",
      kind: "box",
      at: {
        x: 813,
        y: 120,
        w: 713,
        h: 88,
      },
      label: "System Prompt: instruções em tempo de execução",
      sub: "(enviado ao LLM a cada chamada, limita-se a texto)",
      variant: "outline",
    },
    {
      id: "cmp_cl",
      kind: "box",
      at: {
        x: 813,
        y: 218,
        w: 713,
        h: 88,
      },
      label: "CLAUDE.md: contexto do projeto para o agente de código",
      sub: "(estrutura do repositório, comandos, convenções)",
      variant: "outline",
    },
    {
      id: "cmp_sp2",
      kind: "box",
      at: {
        x: 813,
        y: 315,
        w: 713,
        h: 113,
      },
      label: "Spec: documento versionado de comportamento,",
      sub: "contrato de I/O, tools e exemplos. É a fonte de verdade. · Sistema Prompt é derivado da Spec.",
      variant: "outline",
    },
    {
      id: "agent_box",
      kind: "box",
      at: {
        x: 800,
        y: 550,
        w: 275,
        h: 88,
      },
      label: "🤖 Agente",
      sub: '"leu a spec, ready"',
      variant: "outline",
    },
    {
      id: "a_doc_agent",
      tone: "accent",
      kind: "connector",
      from: {
        x: 700,
        y: 438,
      },
      to: {
        x: 800,
        y: 575,
      },
      route: "line",
      arrow: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O que são Specs para agentes de IA",
      duration: 9000,
      add: [
        "doc_border",
        "doc_title",
        "doc_ver",
        "s_ctx",
        "s_res",
        "s_tools",
        "s_io",
        "s_ex",
        "s_gr",
        "s_ver",
        "s_val",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "doc_border",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "doc_title",
        placement: "right",
        text: "Uma **Spec de agente** é um documento estruturado que define completamente como o agente deve se comportar: objetivo, restrições, tools disponíveis, contratos de I/O e exemplos. É mais rica e durável que um system prompt.",
        why: "Specs vivem no repositório, são versionadas com o código e se tornam a fonte de verdade para gerar system prompts, testes e até o agente em si. São documentação que não fica obsoleta.",
      },
    },
    {
      id: "s2",
      title: "Seção 1: Contexto e objetivo",
      duration: 9000,
      add: ["d_ctx", "d_ctx_ttl", "d_ctx_1", "d_ctx_2", "d_ctx_3"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_ctx",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_ctx",
        placement: "right",
        text: "O **Contexto** responde três perguntas: *Quem é o agente?* (nome, domínio), *O que ele faz?* (objetivo principal) e *Para quem?* (usuário-alvo e canal de comunicação).",
        why: "Contexto mal definido leva a um agente que tenta fazer tudo e não faz nada bem. Quanto mais específico o contexto, melhor o modelo entende os limites e o tom adequado.",
      },
    },
    {
      id: "s3",
      title: "Seção 2: Restrições — o que não pode fazer",
      duration: 9000,
      add: ["d_res", "d_res_ttl", "d_res_1", "d_res_2", "d_res_3"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_res",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_res",
        placement: "right",
        text: "Restrições definem os **limites de atuação** do agente: o que nunca pode fazer (❌), o que requer cautela (⚠️) e quando escalar para humanos. Devem ser explícitas, não implícitas.",
        why: "LLMs sem restrições tentam ser úteis de formas inesperadas. Restrições claras na spec tornam-se parte do system prompt e são muito mais confiáveis do que esperar que o modelo inferira os limites.",
      },
    },
    {
      id: "s4",
      title: "Seção 3: Tools disponíveis",
      duration: 9000,
      add: ["d_tools", "d_tools_ttl", "d_t1", "d_t2", "d_t3", "d_tools_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_tools",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_tools",
        placement: "right",
        text: "A seção de **Tools** lista todas as capacidades do agente com assinaturas completas: nome da tool, parâmetros (com tipos) e formato de retorno. O LLM usa isso para decidir qual tool chamar.",
        why: "Documentar tools na spec cria um contrato: o desenvolvedor sabe o que o agente pode fazer, o LLM sabe como usar cada tool, e os testes validam que cada tool funciona conforme o esperado.",
      },
    },
    {
      id: "s5",
      title: "Seção 4: Contratos de I/O",
      duration: 9000,
      add: ["d_io", "d_io_ttl", "d_io_in", "d_io_out", "d_io_note"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_io",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_io",
        placement: "right",
        text: "Os **Contratos de I/O** definem o formato exato das entradas e saídas do agente, com tipos e campos opcionais. Isso permite criar **testes automatizados** e validar o comportamento do agente programaticamente.",
        why: "Contratos transformam o agente em um componente de software com interface bem definida — como uma API. Isso permite integrá-lo, testá-lo e monitorá-lo como qualquer outro serviço.",
      },
    },
    {
      id: "s6",
      title: "Seção 5: Exemplos (few-shot na spec)",
      duration: 9000,
      add: ["d_ex", "d_ex_ttl", "d_ex_1u", "d_ex_1a", "d_ex_2u", "d_ex_2a"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_ex",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_ex",
        placement: "right",
        text: "Exemplos concretos de interação mostram o comportamento esperado em situações reais. São usados como **few-shot** no system prompt gerado, calibrando o tom, formato e tomada de decisão do agente.",
        why: "Exemplos são mais eficazes que regras abstratas: 'responda de forma empática' é vago; um exemplo de resposta empática é preciso. O modelo aprende o padrão pelo exemplo.",
      },
    },
    {
      id: "s7",
      title: "O agente lê a spec e fica pronto",
      duration: 9000,
      add: ["agent_box", "a_doc_agent"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a_doc_agent",
          do: "draw",
        },
        {
          at: 0,
          target: "agent_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "agent_box",
        placement: "right",
        text: "O agente instanciado **recebe a spec** (ou o system prompt derivado dela) e está pronto para operar dentro dos limites definidos: sabe o que pode fazer, o que não pode, quais tools tem e como responder.",
        why: "A spec é a 'carta de trabalho' do agente. Mudou a spec → rebuild do system prompt → comportamento atualizado. Sem a spec, qualquer mudança exige edição manual do system prompt.",
      },
    },
    {
      id: "s8",
      title: "Spec vs System Prompt vs CLAUDE.md",
      duration: 9000,
      add: ["cmp_box", "cmp_ttl", "cmp_sp", "cmp_cl", "cmp_sp2"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cmp_sp2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cmp_sp2",
        placement: "left",
        text: "**System Prompt**: texto enviado a cada chamada — gerado a partir da spec. **CLAUDE.md**: contexto do repositório para agentes de código. **Spec**: documento versionado completo, fonte de verdade de onde tudo é derivado.",
        why: "Confundir os três leva a duplicação: equipes gerenciam system prompts manualmente, perdem track de quem mudou o quê. A Spec no repositório resolve isso — é o único lugar para editar o comportamento.",
      },
    },
    {
      id: "s9",
      title: "Versionamento e validação da spec",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_ver",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_val",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "s_val",
        placement: "right",
        text: "Specs são arquivos de texto (YAML, Markdown) no repositório — **versionadas com Git** como qualquer código. Validação automatizada verifica se a spec tem todos os campos obrigatórios e se os contratos de I/O são consistentes.",
        why: "Versionamento permite: comparar duas versões do agente, fazer rollback, criar branches de spec para A/B testing de comportamento. A spec é código, não documentação separada.",
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "right",
        text: "Confirme seu entendimento sobre Specs 👇",
      },
      quiz: {
        question: "Qual a diferença principal entre uma Spec e um System Prompt?",
        options: [
          "Specs usam linguagem natural; System Prompts usam JSON",
          "Specs são mais longas e detalhadas que System Prompts",
          "A Spec é a fonte de verdade versionada; o System Prompt é gerado a partir dela para cada chamada",
          "System Prompts incluem tools e contratos; Specs são apenas texto descritivo",
        ],
        answer: 2,
        explain:
          "A Spec é o documento de referência versionado no repositório. O System Prompt é a 'compilação' da Spec para o formato que o LLM recebe a cada chamada. Editar a Spec regenera o System Prompt — não o contrário.",
      },
    },
    {
      id: "s11",
      title: "Resumo: Specs para Agentes",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "s_ctx",
          do: "pulse",
          times: 2,
        },
        {
          at: 80,
          target: "s_res",
          do: "pulse",
          times: 2,
        },
        {
          at: 160,
          target: "s_tools",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "s_io",
          do: "pulse",
          times: 2,
        },
        {
          at: 320,
          target: "s_ex",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "s_gr",
          do: "pulse",
          times: 2,
        },
        {
          at: 480,
          target: "s_ver",
          do: "pulse",
          times: 2,
        },
        {
          at: 560,
          target: "s_val",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "s_ctx",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_res",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_tools",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_io",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_ex",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_gr",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_ver",
          do: "highlight",
        },
        {
          at: 0,
          target: "s_val",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 280,
          y: 360,
        },
        placement: "right",
        text: "Uma Spec completa tem: **Contexto → Restrições → Tools → Contratos I/O → Exemplos → Guardrails → Versionamento → Validação**. É a fonte de verdade versionada da qual system prompt, testes e docs são derivados.",
        why: "Adotar Specs transforma agentes de 'caixas pretas com system prompt hardcoded' em componentes de software gerenciáveis, testáveis e auditáveis — como qualquer outro serviço no stack.",
      },
    },
  ],
};

export const specs = validateExplainer(data);
