import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/sso.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "sso",
  title: "SSO — Single Sign-On",
  category: "Segurança & Autenticação",
  tags: ["sso", "auth"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "user",
      tone: "accent",
      kind: "box",
      at: {
        x: 19,
        y: 338,
        w: 163,
        h: 75,
      },
      label: "👤 Usuário",
      variant: "outline",
    },
    {
      id: "idp",
      tone: "good",
      kind: "box",
      at: {
        x: 575,
        y: 375,
        w: 250,
        h: 100,
      },
      label: "🏛️ Identity Provider\n(IdP)",
      variant: "outline",
    },
    {
      id: "idp_sub",
      kind: "label",
      at: {
        x: 537,
        y: 477,
        w: 326,
        h: 41,
      },
      text: "ex: Okta, Keycloak, Azure AD",
      align: "center",
    },
    {
      id: "sp1",
      tone: "accent2",
      kind: "box",
      at: {
        x: 100,
        y: 150,
        w: 188,
        h: 75,
      },
      label: "App 1\n(SP1)",
      variant: "outline",
    },
    {
      id: "sp2",
      tone: "accent2",
      kind: "box",
      at: {
        x: 100,
        y: 600,
        w: 188,
        h: 75,
      },
      label: "App 2\n(SP2)",
      variant: "outline",
    },
    {
      id: "sp3",
      tone: "accent2",
      kind: "box",
      at: {
        x: 1225,
        y: 375,
        w: 188,
        h: 75,
      },
      label: "App 3\n(SP3)",
      variant: "outline",
    },
    {
      id: "a_u_sp1",
      tone: "warn",
      kind: "connector",
      from: {
        x: 181,
        y: 350,
      },
      to: {
        x: 100,
        y: 188,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_u_sp1_l",
      tone: "warn",
      kind: "label",
      at: {
        x: 65,
        y: 236,
        w: 151,
        h: 41,
      },
      text: "① Acessa App1",
      align: "center",
    },
    {
      id: "a_sp1_idp",
      tone: "hot",
      kind: "connector",
      from: {
        x: 288,
        y: 188,
      },
      to: {
        x: 575,
        y: 400,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_sp1_idp_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 286,
        y: 261,
        w: 291,
        h: 41,
      },
      text: "② AuthnRequest\n(redirect)",
      align: "center",
    },
    {
      id: "a_idp_user_login",
      kind: "connector",
      from: {
        x: 575,
        y: 425,
      },
      to: {
        x: 181,
        y: 388,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_idp_user_login_l",
      kind: "label",
      at: {
        x: 291,
        y: 373,
        w: 174,
        h: 41,
      },
      text: "③ Tela de login",
      align: "center",
    },
    {
      id: "a_user_creds",
      tone: "good",
      kind: "connector",
      from: {
        x: 181,
        y: 388,
      },
      to: {
        x: 575,
        y: 438,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_user_creds_l",
      tone: "good",
      kind: "label",
      at: {
        x: 303,
        y: 379,
        w: 151,
        h: 41,
      },
      text: "④ Credenciais",
      align: "center",
    },
    {
      id: "a_idp_sp1",
      tone: "good",
      kind: "connector",
      from: {
        x: 575,
        y: 388,
      },
      to: {
        x: 288,
        y: 175,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_idp_sp1_l",
      tone: "good",
      kind: "label",
      at: {
        x: 332,
        y: 248,
        w: 198,
        h: 41,
      },
      text: "⑤ Assertion/Token",
      align: "center",
    },
    {
      id: "sso_cookie",
      tone: "warn",
      kind: "box",
      at: {
        x: 400,
        y: 500,
        w: 163,
        h: 63,
      },
      label: "🍪 SSO Session\nCookie (IdP)",
      variant: "outline",
    },
    {
      id: "a_u_sp2",
      tone: "warn",
      kind: "connector",
      from: {
        x: 181,
        y: 400,
      },
      to: {
        x: 100,
        y: 625,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_u_sp2_l",
      tone: "warn",
      kind: "label",
      at: {
        x: 65,
        y: 479,
        w: 151,
        h: 41,
      },
      text: "⑥ Acessa App2",
      align: "center",
    },
    {
      id: "a_sp2_idp",
      tone: "hot",
      kind: "connector",
      from: {
        x: 288,
        y: 625,
      },
      to: {
        x: 575,
        y: 450,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_sp2_idp_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 350,
        y: 504,
        w: 163,
        h: 41,
      },
      text: "⑦ AuthnRequest",
      align: "center",
    },
    {
      id: "a_idp_sp2",
      tone: "good",
      kind: "connector",
      from: {
        x: 575,
        y: 463,
      },
      to: {
        x: 288,
        y: 638,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_idp_sp2_l",
      tone: "good",
      kind: "label",
      at: {
        x: 274,
        y: 517,
        w: 314,
        h: 41,
      },
      text: "⑧ Assertion\n(sem re-login!)",
      align: "center",
    },
    {
      id: "a_u_sp3",
      kind: "connector",
      from: {
        x: 181,
        y: 369,
      },
      to: {
        x: 1225,
        y: 413,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_u_sp3_l",
      kind: "label",
      at: {
        x: 666,
        y: 358,
        w: 75,
        h: 41,
      },
      text: "",
      align: "center",
    },
    {
      id: "a_idp_sp3",
      tone: "good",
      kind: "connector",
      from: {
        x: 825,
        y: 425,
      },
      to: {
        x: 1225,
        y: 413,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "a_idp_sp3_l",
      tone: "good",
      kind: "label",
      at: {
        x: 979,
        y: 386,
        w: 93,
        h: 41,
      },
      text: "⑤b Token",
      align: "center",
    },
    {
      id: "proto_bg",
      kind: "box",
      at: {
        x: 975,
        y: 100,
        w: 575,
        h: 250,
      },
      variant: "outline",
    },
    {
      id: "proto_title",
      kind: "label",
      at: {
        x: 1129,
        y: 104,
        w: 267,
        h: 41,
      },
      text: "📋 SAML 2.0 vs OIDC SSO",
      align: "center",
    },
    {
      id: "proto_saml_h",
      tone: "hot",
      kind: "label",
      at: {
        x: 991,
        y: 139,
        w: 93,
        h: 41,
      },
      text: "SAML 2.0",
      align: "center",
    },
    {
      id: "proto_oidc_h",
      tone: "good",
      kind: "label",
      at: {
        x: 1279,
        y: 139,
        w: 93,
        h: 41,
      },
      text: "OIDC SSO",
      align: "center",
    },
    {
      id: "ps1",
      kind: "label",
      at: {
        x: 956,
        y: 169,
        w: 163,
        h: 41,
      },
      text: "XML assertions",
      align: "center",
    },
    {
      id: "po1",
      kind: "label",
      at: {
        x: 1267,
        y: 169,
        w: 116,
        h: 41,
      },
      text: "JWT / JSON",
      align: "center",
    },
    {
      id: "ps2",
      kind: "label",
      at: {
        x: 939,
        y: 194,
        w: 198,
        h: 41,
      },
      text: "HTTP-POST binding",
      align: "center",
    },
    {
      id: "po2",
      kind: "label",
      at: {
        x: 1191,
        y: 194,
        w: 267,
        h: 41,
      },
      text: "Authorization Code Flow",
      align: "center",
    },
    {
      id: "ps3",
      kind: "label",
      at: {
        x: 962,
        y: 219,
        w: 151,
        h: 41,
      },
      text: "Metadados XML",
      align: "center",
    },
    {
      id: "po3",
      kind: "label",
      at: {
        x: 1168,
        y: 219,
        w: 314,
        h: 41,
      },
      text: "Discovery doc (.well-known)",
      align: "center",
    },
    {
      id: "ps4",
      kind: "label",
      at: {
        x: 927,
        y: 244,
        w: 221,
        h: 41,
      },
      text: "Enterprise / legacy",
      align: "center",
    },
    {
      id: "po4",
      kind: "label",
      at: {
        x: 1197,
        y: 244,
        w: 256,
        h: 41,
      },
      text: "Cloud-native / moderno",
      align: "center",
    },
    {
      id: "ps5",
      kind: "label",
      at: {
        x: 933,
        y: 269,
        w: 209,
        h: 41,
      },
      text: "Verboso / complexo",
      align: "center",
    },
    {
      id: "po5",
      kind: "label",
      at: {
        x: 1232,
        y: 269,
        w: 186,
        h: 41,
      },
      text: "Simples e leve ✓",
      align: "center",
    },
    {
      id: "ps6",
      kind: "label",
      at: {
        x: 875,
        y: 294,
        w: 326,
        h: 41,
      },
      text: "SP-initiated / IdP-initiated",
      align: "center",
    },
    {
      id: "po6",
      kind: "label",
      at: {
        x: 1215,
        y: 294,
        w: 221,
        h: 41,
      },
      text: "SP-initiated padrão",
      align: "center",
    },
    {
      id: "slo_bg",
      kind: "box",
      at: {
        x: 975,
        y: 375,
        w: 575,
        h: 150,
      },
      variant: "outline",
    },
    {
      id: "slo_title",
      tone: "hot",
      kind: "label",
      at: {
        x: 1135,
        y: 379,
        w: 256,
        h: 41,
      },
      text: "🚪 Single Logout (SLO)",
      align: "center",
    },
    {
      id: "slo1",
      kind: "label",
      at: {
        x: 857,
        y: 414,
        w: 360,
        h: 41,
      },
      text: "1. User faz logout no SP ou IdP",
      align: "center",
    },
    {
      id: "slo2",
      kind: "label",
      at: {
        x: 840,
        y: 439,
        w: 395,
        h: 41,
      },
      text: "2. IdP invalida SSO session cookie",
      align: "center",
    },
    {
      id: "slo3",
      kind: "label",
      at: {
        x: 834,
        y: 464,
        w: 407,
        h: 41,
      },
      text: "3. IdP notifica todos os SPs ativos",
      align: "center",
    },
    {
      id: "slo4",
      kind: "label",
      at: {
        x: 857,
        y: 489,
        w: 360,
        h: 41,
      },
      text: "4. SPs invalidam sessões locais",
      align: "center",
    },
    {
      id: "fatigue_bg",
      kind: "box",
      at: {
        x: 975,
        y: 550,
        w: 575,
        h: 150,
      },
      variant: "outline",
    },
    {
      id: "fatigue_title",
      tone: "warn",
      kind: "label",
      at: {
        x: 1140,
        y: 554,
        w: 244,
        h: 41,
      },
      text: "😓 Credential Fatigue",
      align: "center",
    },
    {
      id: "fat1",
      kind: "label",
      at: {
        x: 875,
        y: 589,
        w: 326,
        h: 41,
      },
      text: "Sem SSO: senha para cada app",
      align: "center",
    },
    {
      id: "fat2",
      tone: "hot",
      kind: "label",
      at: {
        x: 898,
        y: 614,
        w: 279,
        h: 41,
      },
      text: "→ reutilização de senhas",
      align: "center",
    },
    {
      id: "fat3",
      tone: "hot",
      kind: "label",
      at: {
        x: 869,
        y: 639,
        w: 337,
        h: 41,
      },
      text: "→ superfície de ataque enorme",
      align: "center",
    },
    {
      id: "fat4",
      tone: "warn",
      kind: "label",
      at: {
        x: 881,
        y: 664,
        w: 314,
        h: 41,
      },
      text: "→ fadiga e erros de usuário",
      align: "center",
    },
    {
      id: "leg_title",
      kind: "label",
      at: {
        x: -23,
        y: 779,
        w: 546,
        h: 41,
      },
      text: "SP = Service Provider   IdP = Identity Provider",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: N apps, N senhas",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "fatigue_bg",
        "fatigue_title",
        "fat1",
        "fat2",
        "fat3",
        "fat4",
        "leg_title",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "user",
        placement: "right",
        text: "Cada app tem login próprio. Usuário precisa lembrar N senhas → reutilização → risco.",
      },
    },
    {
      id: "s2",
      title: "SSO: 1 login, acesso múltiplo",
      duration: 6500,
      add: ["user", "sp1", "sp2", "sp3", "idp", "idp_sub", "leg_title"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "idp",
        placement: "left",
        text: "Com SSO, o usuário autentica UMA vez no IdP e acessa todas as apps sem re-login.",
        why: 'O IdP emite "assertions" de identidade confiadas pelos Service Providers.',
      },
    },
    {
      id: "s3",
      title: "Os Atores: User, SP, IdP",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "leg_title",
        "proto_bg",
        "proto_title",
        "proto_saml_h",
        "proto_oidc_h",
        "ps1",
        "po1",
        "ps2",
        "po2",
        "ps3",
        "po3",
        "ps4",
        "po4",
        "ps5",
        "po5",
        "ps6",
        "po6",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "idp",
        placement: "left",
        text: "**User** = quem autentica. **SP** (Service Provider) = a app. **IdP** = servidor de identidade central.",
      },
    },
    {
      id: "s4",
      title: "① SP-initiated: User acessa App1 sem sessão",
      duration: 6500,
      add: ["user", "sp1", "sp2", "sp3", "idp", "idp_sub", "leg_title", "a_u_sp1", "a_u_sp1_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sp1",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sp1",
        placement: "right",
        text: "O usuário tenta acessar App1. SP1 verifica: não há sessão ativa.",
        why: "SP checa um cookie de sessão local — se não existir, inicia o SP-initiated flow.",
      },
    },
    {
      id: "s5",
      title: "② SP redireciona para IdP com AuthnRequest",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "leg_title",
        "a_u_sp1",
        "a_u_sp1_l",
        "a_sp1_idp",
        "a_sp1_idp_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sp1",
          do: "highlight",
        },
        {
          at: 0,
          target: "idp",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "a_sp1_idp_l",
        placement: "top",
        text: "SP1 gera um `AuthnRequest` e redireciona o browser para o IdP com parâmetros como `entityID`, `RelayState` e `redirect_uri`.",
      },
    },
    {
      id: "s6",
      title: "③-④ IdP apresenta tela de login e autentica",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "leg_title",
        "a_u_sp1",
        "a_u_sp1_l",
        "a_sp1_idp",
        "a_sp1_idp_l",
        "a_idp_user_login",
        "a_idp_user_login_l",
        "a_user_creds",
        "a_user_creds_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "idp",
          do: "highlight",
        },
        {
          at: 0,
          target: "user",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "idp",
        placement: "left",
        text: "IdP mostra formulário de login (pode incluir MFA). Usuário submete credenciais diretamente ao IdP — o SP nunca vê a senha.",
        why: "Principal vantagem de SSO: credenciais só trafegam com o IdP confiável.",
      },
    },
    {
      id: "s7",
      title: "⑤ IdP cria SSO Session e emite Assertion ao SP1",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "sso_cookie",
        "leg_title",
        "a_u_sp1",
        "a_u_sp1_l",
        "a_sp1_idp",
        "a_sp1_idp_l",
        "a_idp_user_login",
        "a_idp_user_login_l",
        "a_user_creds",
        "a_user_creds_l",
        "a_idp_sp1",
        "a_idp_sp1_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "idp",
          do: "highlight",
        },
        {
          at: 0,
          target: "sso_cookie",
          do: "highlight",
        },
        {
          at: 0,
          target: "sp1",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sso_cookie",
        placement: "bottom",
        text: "IdP grava SSO session cookie no **seu próprio domínio** (ex: `sso.empresa.com`). Depois envia Assertion (SAML) ou `id_token` (OIDC) ao SP1.",
      },
    },
    {
      id: "s8",
      title: "⑥-⑦ User acessa App2 — sem re-login!",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "sso_cookie",
        "leg_title",
        "a_u_sp1",
        "a_u_sp1_l",
        "a_idp_sp1",
        "a_idp_sp1_l",
        "a_u_sp2",
        "a_u_sp2_l",
        "a_sp2_idp",
        "a_sp2_idp_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sp2",
          do: "highlight",
        },
        {
          at: 0,
          target: "idp",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sp2",
        placement: "right",
        text: "SP2 redireciona ao IdP. O IdP encontra o SSO session cookie ativo — não exige nova autenticação.",
      },
    },
    {
      id: "s9",
      title: "⑧ IdP emite Assertion ao SP2 direto",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "sso_cookie",
        "leg_title",
        "a_u_sp2",
        "a_u_sp2_l",
        "a_sp2_idp",
        "a_sp2_idp_l",
        "a_idp_sp2",
        "a_idp_sp2_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "idp",
          do: "highlight",
        },
        {
          at: 0,
          target: "sp2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "a_idp_sp2_l",
        placement: "right",
        text: "IdP emite nova assertion para SP2. Usuário obtém acesso sem digitar senha — **esse é o valor do SSO**.",
      },
    },
    {
      id: "s10",
      title: "SAML 2.0 vs OIDC SSO",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "leg_title",
        "proto_bg",
        "proto_title",
        "proto_saml_h",
        "proto_oidc_h",
        "ps1",
        "po1",
        "ps2",
        "po2",
        "ps3",
        "po3",
        "ps4",
        "po4",
        "ps5",
        "po5",
        "ps6",
        "po6",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "proto_bg",
        placement: "left",
        text: "**SAML 2.0**: padrão enterprise, XML verboso, muito usado com apps legadas. **OIDC**: baseado em OAuth 2.0, JSON/JWT, cloud-native — tendência moderna.",
        why: "Novos sistemas quase sempre preferem OIDC pela simplicidade e tooling moderno.",
      },
    },
    {
      id: "s11",
      title: "Single Logout (SLO)",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "sso_cookie",
        "leg_title",
        "slo_bg",
        "slo_title",
        "slo1",
        "slo2",
        "slo3",
        "slo4",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sso_cookie",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "slo_bg",
        placement: "left",
        text: "Quando o usuário faz logout, o IdP invalida o SSO session cookie e notifica todos os SPs para encerrar sessões locais — desafio em sistemas legados.",
        why: "SLO é difícil: nem todos os SPs implementam corretamente o endpoint de logout.",
      },
    },
    {
      id: "s12",
      title: "Quiz",
      duration: 6500,
      add: ["user", "sp1", "sp2", "sp3", "idp", "idp_sub", "leg_title"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: "No SSO SP-initiated, onde o SSO Session Cookie é armazenado?",
        options: [
          "No browser, com domínio do Service Provider (SP)",
          "No banco de dados do SP",
          "No browser, com domínio do Identity Provider (IdP)",
          "No localStorage do browser, acessível por qualquer SP",
        ],
        answer: 2,
        explain:
          "O SSO session cookie fica no domínio do **IdP** (ex: sso.empresa.com). Isso permite que o IdP reconheça sessões ativas quando qualquer SP redireciona o usuário para autenticação — os SPs nunca leem esse cookie diretamente.",
      },
    },
    {
      id: "s13",
      title: "Resumo: SSO",
      duration: 6500,
      add: [
        "user",
        "sp1",
        "sp2",
        "sp3",
        "idp",
        "idp_sub",
        "sso_cookie",
        "leg_title",
        "a_u_sp1",
        "a_u_sp1_l",
        "a_sp1_idp",
        "a_sp1_idp_l",
        "a_idp_sp1",
        "a_idp_sp1_l",
        "a_u_sp2",
        "a_u_sp2_l",
        "a_idp_sp2",
        "a_idp_sp2_l",
        "a_idp_sp3",
        "a_idp_sp3_l",
        "proto_bg",
        "proto_title",
        "proto_saml_h",
        "proto_oidc_h",
        "ps1",
        "po1",
        "ps2",
        "po2",
        "ps4",
        "po4",
        "slo_bg",
        "slo_title",
        "slo1",
        "slo2",
        "slo3",
        "slo4",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "idp",
        placement: "left",
        text: "**SSO** centraliza autenticação num IdP. Uma sessão → acesso a N apps. SAML (enterprise) ou OIDC (moderno). SLO encerra sessões em todos os SPs.",
      },
    },
  ],
};

export const sso = validateExplainer(data);
