import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/subagents.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "subagents",
  title: "SubAgentes — Arquitetura multi-agente",
  subtitle: "Orquestrador, especialização, paralelismo e agregação de resultados",
  category: "IA & Agentes",
  tags: ["agentes", "orquestração"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "orch",
      kind: "box",
      at: {
        x: 625,
        y: 75,
        w: 350,
        h: 88,
      },
      label: "🎯 Agente Orquestrador",
      sub: "planeja e delega tarefas",
      variant: "outline",
    },
    {
      id: "orch_ctx",
      kind: "token",
      at: {
        x: 625,
        y: 175,
        w: 350,
        h: 45,
      },
      text: "Contexto + Objetivo global",
    },
    {
      id: "sp0",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 163,
      },
      to: {
        x: 275,
        y: 325,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "sp1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 163,
      },
      to: {
        x: 800,
        y: 325,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "sp2",
      tone: "accent",
      kind: "connector",
      from: {
        x: 800,
        y: 163,
      },
      to: {
        x: 1325,
        y: 325,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "sp_lbl",
      kind: "label",
      at: {
        x: 608,
        y: 287,
        w: 384,
        h: 41,
      },
      text: "spawn (prompt + contexto isolado)",
      align: "center",
      muted: true,
    },
    {
      id: "sa0",
      kind: "box",
      at: {
        x: 88,
        y: 325,
        w: 375,
        h: 163,
      },
      label: "🔍 Subagente: Pesquisador",
      sub: "busca docs, web, bancos",
      variant: "outline",
    },
    {
      id: "sa0_t1",
      kind: "token",
      at: {
        x: 113,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: search",
    },
    {
      id: "sa0_t2",
      kind: "token",
      at: {
        x: 293,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: read_url",
    },
    {
      id: "sa1",
      kind: "box",
      at: {
        x: 613,
        y: 325,
        w: 375,
        h: 163,
      },
      label: "💻 Subagente: Coder",
      sub: "implementa e refatora código",
      variant: "outline",
    },
    {
      id: "sa1_t1",
      kind: "token",
      at: {
        x: 638,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: edit_file",
    },
    {
      id: "sa1_t2",
      kind: "token",
      at: {
        x: 818,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: run_tests",
    },
    {
      id: "sa2",
      kind: "box",
      at: {
        x: 1138,
        y: 325,
        w: 375,
        h: 163,
      },
      label: "🔎 Subagente: Revisor",
      sub: "valida, critica e sugere melhorias",
      variant: "outline",
    },
    {
      id: "sa2_t1",
      kind: "token",
      at: {
        x: 1163,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: lint",
    },
    {
      id: "sa2_t2",
      kind: "token",
      at: {
        x: 1343,
        y: 500,
        w: 150,
        h: 43,
      },
      text: "tool: sec_scan",
    },
    {
      id: "par_lbl",
      kind: "label",
      at: {
        x: 591,
        y: 547,
        w: 419,
        h: 41,
      },
      text: "⇒ execução paralela e independente ⇐",
      align: "center",
      muted: true,
    },
    {
      id: "par_line",
      kind: "connector",
      from: {
        x: 75,
        y: 575,
      },
      to: {
        x: 1525,
        y: 575,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "iso_lbl",
      kind: "label",
      at: {
        x: 463,
        y: 592,
        w: 674,
        h: 41,
      },
      text: "Cada subagente tem janela de contexto própria (isolamento)",
      align: "center",
      muted: true,
    },
    {
      id: "res0_lbl",
      kind: "token",
      at: {
        x: 113,
        y: 638,
        w: 325,
        h: 68,
      },
      text: "📑 Resultado A",
    },
    {
      id: "res1_lbl",
      kind: "token",
      at: {
        x: 638,
        y: 638,
        w: 325,
        h: 68,
      },
      text: "📑 Resultado B",
    },
    {
      id: "res2_lbl",
      kind: "token",
      at: {
        x: 1163,
        y: 638,
        w: 325,
        h: 68,
      },
      text: "📑 Resultado C",
    },
    {
      id: "rt0",
      tone: "good",
      kind: "connector",
      from: {
        x: 275,
        y: 635,
      },
      to: {
        x: 763,
        y: 163,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rt1",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 800,
        y: 635,
      },
      to: {
        x: 800,
        y: 163,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "rt2",
      tone: "warn",
      kind: "connector",
      from: {
        x: 1325,
        y: 635,
      },
      to: {
        x: 838,
        y: 163,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "agg_box",
      kind: "box",
      at: {
        x: 450,
        y: 738,
        w: 700,
        h: 100,
      },
      label: "🎯 Orquestrador agrega resultados",
      sub: "sintetiza, decide próximo passo ou entrega resposta final",
      variant: "outline",
    },
    {
      id: "fail_box",
      kind: "box",
      at: {
        x: 38,
        y: 763,
        w: 250,
        h: 75,
      },
      label: "⚠️ Subagente falha",
      sub: "timeout / erro",
      variant: "outline",
    },
    {
      id: "retry_box",
      kind: "token",
      at: {
        x: 38,
        y: 858,
        w: 250,
        h: 43,
      },
      text: "↩ retry ou fallback",
    },
    {
      id: "a_fail_r",
      tone: "accent",
      kind: "connector",
      from: {
        x: 163,
        y: 840,
      },
      to: {
        x: 163,
        y: 855,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "lim_box",
      kind: "box",
      at: {
        x: 1125,
        y: 738,
        w: 438,
        h: 125,
      },
      label: "Agente único seria lento e limitado:",
      sub: "• contexto único (sem paralelismo) · • sem especialização por domínio · • tarefas longas esgotam janela",
      variant: "outline",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Limitação do agente único",
      duration: 9000,
      add: ["lim_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lim_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "lim_box",
        placement: "left",
        text: "Um único agente tem uma **janela de contexto finita**, não pode fazer múltiplas coisas em paralelo e acumula erros em tarefas longas. Para problemas complexos, isso se torna um gargalo.",
        why: "Assim como times de pessoas são mais produtivos que indivíduos isolados em tarefas complexas, múltiplos agentes especializados superam um único agente genérico.",
      },
    },
    {
      id: "s2",
      title: "O Agente Orquestrador",
      duration: 9000,
      add: ["orch", "orch_ctx"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "orch",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "orch",
        placement: "right",
        text: "O **Orquestrador** recebe o objetivo de alto nível e faz o planejamento: quebra a tarefa em subtarefas, decide quais agentes usar, em que ordem e com qual contexto.",
        why: "O orquestrador não executa as tarefas — ele coordena. Isso preserva sua janela de contexto para raciocínio e tomada de decisão, não para execução.",
      },
    },
    {
      id: "s3",
      title: "Spawn de subagentes",
      duration: 9000,
      add: ["sp0", "sp1", "sp2", "sp_lbl", "sa0", "sa1", "sa2"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sp0",
          do: "draw",
        },
        {
          at: 150,
          target: "sp1",
          do: "draw",
        },
        {
          at: 300,
          target: "sp2",
          do: "draw",
        },
        {
          at: 0,
          target: "sa0",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa1",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sp_lbl",
        placement: "bottom",
        text: "O orquestrador **spawna subagentes** — novos processos de LLM com prompts e contextos próprios e isolados. Cada subagente recebe uma tarefa específica: pesquisar, codar ou revisar.",
        why: "O isolamento de contexto é essencial: cada subagente começa limpo, sem o histórico dos outros. Isso evita contaminação cruzada e permite escalar.",
      },
    },
    {
      id: "s4",
      title: "Especialização: cada agente tem seu domínio",
      duration: 9000,
      add: ["sa0_t1", "sa0_t2", "sa1_t1", "sa1_t2", "sa2_t1", "sa2_t2"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sa0",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa1",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "sa1",
        placement: "right",
        text: "Cada subagente tem acesso apenas às **ferramentas do seu domínio**: o Pesquisador acessa busca e leitura de URLs; o Coder edita arquivos e roda testes; o Revisor faz lint e scan de segurança.",
        why: "Especialização reduz o espaço de decisão de cada agente, melhora a qualidade e simplifica o controle de permissões: o Revisor não precisa de acesso a edição de arquivos.",
      },
    },
    {
      id: "s5",
      title: "Execução paralela e independente",
      duration: 9000,
      add: ["par_lbl", "par_line", "iso_lbl"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sa0",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "sa1",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "sa2",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "sa0",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa1",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "par_lbl",
        placement: "bottom",
        text: "Os três subagentes **executam em paralelo**: o Pesquisador já busca enquanto o Coder implementa e o Revisor prepara seus critérios. Não há dependência entre eles nessa fase.",
        why: "Paralelismo reduz drasticamente o tempo total de tarefas complexas — de sequencial (n × tempo) para paralelo (≈ max tempo). Em tarefas longas, a diferença pode ser de horas.",
      },
    },
    {
      id: "s6",
      title: "Contexto isolado por subagente",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "sa0",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa1",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa2",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "iso_lbl",
        placement: "bottom",
        text: "Cada subagente tem sua própria janela de contexto **independente**. O Subagente A não vê os pensamentos do B. Isso evita distrações e permite que cada um aprofunde no seu domínio sem interferência.",
        why: "Isolamento também é segurança: um subagente comprometido por injeção de prompt não contamina os outros. O orquestrador valida os resultados antes de usá-los.",
      },
    },
    {
      id: "s7",
      title: "Resultados retornam ao orquestrador",
      duration: 9000,
      add: ["res0_lbl", "res1_lbl", "res2_lbl", "rt0", "rt1", "rt2"],
      remove: [],
      set: {},
      cues: [
        {
          at: 400,
          target: "rt0",
          do: "draw",
        },
        {
          at: 520,
          target: "rt1",
          do: "draw",
        },
        {
          at: 640,
          target: "rt2",
          do: "draw",
        },
        {
          at: 0,
          target: "orch",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "orch",
        placement: "right",
        text: "Cada subagente termina e envia seu **resultado estruturado** ao orquestrador: o Pesquisador devolve links e resumos, o Coder o diff do código, o Revisor a lista de issues.",
        why: "O formato do resultado é combinado no prompt de spawn — resultados estruturados (JSON, markdown) são mais fáceis de processar pelo orquestrador do que texto livre.",
      },
    },
    {
      id: "s8",
      title: "Agregação e síntese",
      duration: 9000,
      add: ["agg_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "agg_box",
          do: "highlight",
        },
        {
          at: 0,
          target: "orch",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "agg_box",
        placement: "top",
        text: "O orquestrador recebe todos os resultados e faz a **síntese final**: usa a pesquisa para contextualizar o código gerado, aplica as correções do revisor e entrega uma resposta coerente e completa.",
        why: "Essa é a vantagem central do padrão: o orquestrador tem visibilidade holística enquanto cada subagente tem profundidade. Separar delegação de execução é o que torna isso escalável.",
      },
    },
    {
      id: "s9",
      title: "Tratamento de falhas e retry",
      duration: 9000,
      add: ["fail_box", "a_fail_r", "retry_box"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "fail_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "fail_box",
        placement: "right",
        text: "Quando um subagente falha (timeout, erro, resposta inválida), o orquestrador pode **tentar novamente** com um prompt mais específico, substituir por outro agente ou usar um fallback — sem impactar os outros subagentes.",
        why: "Resiliência é uma vantagem do multi-agente: a falha de um componente não derruba todo o sistema. O orquestrador mantém o estado e decide como recuperar.",
      },
    },
    {
      id: "s10",
      title: "Quiz rápido",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Teste seu entendimento de SubAgentes 👇",
      },
      quiz: {
        question: "Por que subagentes têm contextos isolados entre si?",
        options: [
          "Para economizar tokens e reduzir o custo de API",
          "Porque o protocolo MCP não permite compartilhar contexto",
          "Para evitar contaminação cruzada, permitir especialização e aumentar a segurança",
          "Porque LLMs não conseguem processar múltiplos contextos ao mesmo tempo",
        ],
        answer: 2,
        explain:
          "Contextos isolados evitam que o estado de um subagente interfira nos outros (contaminação), permitem que cada um aprofunde no seu domínio e isolam o impacto de falhas como injeção de prompt.",
      },
    },
    {
      id: "s11",
      title: "Resumo: o padrão orquestrador-subagente",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "orch",
          do: "pulse",
          times: 2,
        },
        {
          at: 100,
          target: "sa0",
          do: "pulse",
          times: 2,
        },
        {
          at: 200,
          target: "sa1",
          do: "pulse",
          times: 2,
        },
        {
          at: 300,
          target: "sa2",
          do: "pulse",
          times: 2,
        },
        {
          at: 400,
          target: "agg_box",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "orch",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa0",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa1",
          do: "highlight",
        },
        {
          at: 0,
          target: "sa2",
          do: "highlight",
        },
        {
          at: 0,
          target: "agg_box",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "O padrão multi-agente em 5 etapas: **Orquestrador planeja → Spawna subagentes especializados → Execução paralela e isolada → Resultados retornam → Orquestrador sintetiza**. Escalável, resiliente e eficiente.",
        why: "Use multi-agente quando a tarefa é grande demais para uma janela, beneficia de paralelismo ou requer especialização por domínio. Para tarefas simples, um agente único é mais eficiente.",
      },
    },
  ],
};

export const subagents = validateExplainer(data);
