import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/tcp.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "tcp",
  title: "TCP/IP: handshake e transporte confiável",
  subtitle: "Como bytes chegam inteiros e em ordem sobre uma rede que perde pacotes",
  category: "Web & Protocolos",
  tags: ["tcp", "rede"],
  level: "intro",
  glossary: {
    ACK: "Acknowledgement: confirmação de que os bytes até certo número chegaram.",
  },
  elements: [
    {
      id: "cli",
      kind: "box",
      at: {
        x: 325,
        y: 40,
        w: 244,
        h: 50,
      },
      label: "💻 Cliente",
      variant: "outline",
    },
    {
      id: "srv",
      kind: "box",
      at: {
        x: 1071,
        y: 40,
        w: 244,
        h: 50,
      },
      label: "🗄️ Servidor",
      variant: "outline",
    },
    {
      id: "ll_c",
      kind: "connector",
      from: {
        x: 447,
        y: 92,
      },
      to: {
        x: 447,
        y: 867,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_s",
      kind: "connector",
      from: {
        x: 1193,
        y: 92,
      },
      to: {
        x: 1193,
        y: 867,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "lay_app",
      kind: "box",
      at: {
        x: 54,
        y: 165,
        w: 244,
        h: 44,
      },
      label: "Aplicação (HTTP)",
      variant: "outline",
    },
    {
      id: "lay_tcp",
      kind: "box",
      at: {
        x: 54,
        y: 215,
        w: 244,
        h: 44,
      },
      label: "Transporte (TCP)",
      variant: "outline",
    },
    {
      id: "lay_ip",
      kind: "box",
      at: {
        x: 54,
        y: 266,
        w: 244,
        h: 44,
      },
      label: "Rede (IP)",
      variant: "outline",
    },
    {
      id: "lay_cap",
      kind: "label",
      at: {
        x: 6,
        y: 317,
        w: 340,
        h: 36,
      },
      text: "TCP fica entre o app e o IP",
      align: "center",
      muted: true,
    },
    {
      id: "m_syn",
      tone: "accent",
      kind: "connector",
      from: {
        x: 447,
        y: 220,
      },
      to: {
        x: 1193,
        y: 220,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_syn_l",
      kind: "label",
      at: {
        x: 757,
        y: 188,
        w: 126,
        h: 36,
      },
      text: "SYN  seq=x",
      align: "center",
      muted: true,
    },
    {
      id: "m_synack",
      tone: "accent",
      kind: "connector",
      from: {
        x: 1193,
        y: 280,
      },
      to: {
        x: 447,
        y: 280,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_synack_l",
      kind: "label",
      at: {
        x: 675,
        y: 249,
        w: 290,
        h: 36,
      },
      text: "SYN-ACK  seq=y, ack=x+1",
      align: "center",
      muted: true,
    },
    {
      id: "m_ack",
      tone: "accent",
      kind: "connector",
      from: {
        x: 447,
        y: 340,
      },
      to: {
        x: 1193,
        y: 340,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_ack_l",
      kind: "label",
      at: {
        x: 745,
        y: 309,
        w: 151,
        h: 36,
      },
      text: "ACK  ack=y+1",
      align: "center",
      muted: true,
    },
    {
      id: "est",
      kind: "token",
      at: {
        x: 671,
        y: 368,
        w: 298,
        h: 40,
      },
      text: "conexão estabelecida ✓",
    },
    {
      id: "m_d1",
      tone: "good",
      kind: "connector",
      from: {
        x: 447,
        y: 472,
      },
      to: {
        x: 1193,
        y: 472,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_d1_l",
      kind: "label",
      at: {
        x: 701,
        y: 441,
        w: 240,
        h: 36,
      },
      text: "DATA  seq=1 (100 B)",
      align: "center",
      muted: true,
    },
    {
      id: "m_a1",
      tone: "good",
      kind: "connector",
      from: {
        x: 1193,
        y: 527,
      },
      to: {
        x: 447,
        y: 527,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_a1_l",
      kind: "label",
      at: {
        x: 776,
        y: 496,
        w: 88,
        h: 36,
      },
      text: "ACK=101",
      align: "center",
      muted: true,
    },
    {
      id: "win",
      kind: "box",
      at: {
        x: 475,
        y: 571,
        w: 447,
        h: 61,
      },
      label: "Janela deslizante: vários segmentos",
      sub: "em trânsito sem esperar ACK de cada um",
      variant: "outline",
    },
    {
      id: "m_lost",
      tone: "hot",
      kind: "connector",
      from: {
        x: 447,
        y: 691,
      },
      to: {
        x: 875,
        y: 691,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_lost_l",
      kind: "label",
      at: {
        x: 566,
        y: 660,
        w: 189,
        h: 36,
      },
      text: "seq=201 (100 B)",
      align: "center",
      muted: true,
    },
    {
      id: "x_lost",
      kind: "label",
      at: {
        x: 854,
        y: 660,
        w: 81,
        h: 63,
      },
      text: "✗",
      size: 26,
      align: "center",
    },
    {
      id: "lost_cap",
      kind: "label",
      at: {
        x: 744,
        y: 702,
        w: 303,
        h: 36,
      },
      text: "pacote perdido — sem ACK",
      align: "center",
      muted: true,
    },
    {
      id: "m_retx",
      tone: "warn",
      kind: "connector",
      from: {
        x: 447,
        y: 768,
      },
      to: {
        x: 1193,
        y: 768,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_retx_l",
      kind: "label",
      at: {
        x: 637,
        y: 737,
        w: 366,
        h: 36,
      },
      text: "timeout → retransmite seq=201",
      align: "center",
      muted: true,
    },
    {
      id: "m_fin",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 447,
        y: 834,
      },
      to: {
        x: 1193,
        y: 834,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_fin_l",
      kind: "label",
      at: {
        x: 694,
        y: 803,
        w: 252,
        h: 36,
      },
      text: "FIN / ACK  (encerra)",
      align: "center",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Onde o TCP vive",
      duration: 8000,
      add: ["cli", "srv", "ll_c", "ll_s", "lay_app", "lay_tcp", "lay_ip", "lay_cap"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lay_tcp",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "lay_tcp",
        placement: "right",
        text: "O **IP** entrega pacotes entre máquinas, mas pode perdê-los, duplicá-los ou trocá-los de ordem. O **TCP** roda em cima do IP e cria um canal **confiável e ordenado**.",
        why: "Aplicações (como HTTP) querem um “cano” de bytes confiável; o TCP fornece isso usando números de sequência e confirmações (ACK).",
      },
    },
    {
      id: "s2",
      title: "Handshake: SYN",
      duration: 8000,
      add: ["m_syn", "m_syn_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_syn",
          do: "draw",
        },
        {
          at: 0,
          target: "m_syn_l",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_syn_l",
        placement: "bottom",
        text: "O cliente envia um **SYN** com um número de sequência inicial aleatório (seq=x), pedindo para abrir conexão.",
        why: "Escolher um seq inicial sincroniza a contagem de bytes dos dois lados e dificulta falsificação.",
      },
    },
    {
      id: "s3",
      title: "Handshake: SYN-ACK",
      duration: 8000,
      add: ["m_synack", "m_synack_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_synack",
          do: "draw",
        },
      ],
      caption: {
        anchor: "m_synack_l",
        placement: "bottom",
        text: "O servidor responde com **SYN-ACK**: confirma o seq do cliente (ack=x+1) e manda o seu próprio seq=y.",
        why: "Cada lado precisa anunciar e ter confirmado seu número inicial — por isso são **três** mensagens.",
      },
    },
    {
      id: "s4",
      title: "Handshake: ACK",
      duration: 8000,
      add: ["m_ack", "m_ack_l", "est"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_ack",
          do: "draw",
        },
        {
          at: 0,
          target: "est",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "est",
        placement: "bottom",
        text: "O cliente confirma o seq do servidor (ack=y+1). Pronto: o **three-way handshake** terminou e a conexão está aberta nos dois sentidos.",
        why: "Agora ambos sabem por qual número a contagem de bytes começa — podem trocar dados com segurança de ordem.",
      },
    },
    {
      id: "s5",
      title: "Envio de dados + ACK",
      duration: 8000,
      add: ["m_d1", "m_d1_l", "m_a1", "m_a1_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_d1",
          do: "draw",
        },
        {
          at: 350,
          target: "m_a1",
          do: "draw",
        },
      ],
      caption: {
        anchor: "m_a1_l",
        placement: "top",
        text: "Os dados vão em **segmentos numerados** pelo byte (seq=1, 100 bytes). O receptor confirma com **ACK=101** = “já recebi até o byte 100, mande o próximo”.",
        why: "Numerar por byte deixa o receptor remontar tudo na ordem certa, mesmo que os pacotes cheguem embaralhados.",
      },
    },
    {
      id: "s6",
      title: "Janela deslizante",
      duration: 8000,
      add: ["win"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "win",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "win",
        placement: "top",
        text: "O emissor não espera o {{ACK}} de cada segmento: manda vários de uma vez, até o limite da **janela** anunciada pelo receptor.",
        why: "Isso enche o “cano” e dá vazão. A janela também serve de **controle de fluxo**: o receptor freia o emissor se estiver sobrecarregado.",
      },
    },
    {
      id: "s7",
      title: "Perda e retransmissão",
      duration: 8000,
      add: ["m_lost", "m_lost_l", "x_lost", "lost_cap", "m_retx", "m_retx_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_lost",
          do: "draw",
        },
        {
          at: 500,
          target: "m_retx",
          do: "draw",
        },
        {
          at: 0,
          target: "m_retx_l",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "lost_cap",
        placement: "right",
        text: "Se um segmento se perde, o ACK esperado não chega. Ao estourar o **timeout** (ou ver ACKs duplicados), o emissor **retransmite** o segmento.",
        why: "É isso que torna o TCP *confiável* sobre um IP não-confiável: nada é dado como entregue sem ACK.",
      },
    },
    {
      id: "s8",
      title: "Encerramento (FIN)",
      duration: 8000,
      add: ["m_fin", "m_fin_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_fin",
          do: "draw",
        },
      ],
      caption: {
        anchor: "m_fin_l",
        placement: "top",
        text: "Para fechar, cada lado manda um **FIN** e recebe o **ACK** correspondente — encerrando os dois sentidos de forma ordenada.",
        why: "O fechamento também é negociado para garantir que nenhum dado em trânsito seja perdido na hora de desligar.",
      },
    },
    {
      id: "s9",
      title: "Teste rápido",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "est",
        placement: "bottom",
        text: "Fixe a ideia central do TCP 👇",
      },
      quiz: {
        question: "O que o TCP faz quando um segmento se perde (não chega o ACK)?",
        options: [
          "Ignora o segmento e segue em frente",
          "Retransmite o segmento após o timeout",
          "Fecha a conexão imediatamente",
          "Troca automaticamente para UDP",
        ],
        answer: 1,
        explain:
          "Sem ACK dentro do tempo esperado, o emissor reenvia o segmento. É isso que torna o TCP confiável sobre um IP que pode perder pacotes.",
      },
    },
    {
      id: "s10",
      title: "Resumo",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_syn",
          do: "pulse",
          times: 2,
        },
        {
          at: 120,
          target: "m_synack",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "m_ack",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "m_syn",
          do: "highlight",
        },
        {
          at: 0,
          target: "m_synack",
          do: "highlight",
        },
        {
          at: 0,
          target: "m_ack",
          do: "highlight",
        },
        {
          at: 0,
          target: "est",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "est",
        placement: "top",
        text: "Fluxo do TCP: **handshake (SYN/SYN-ACK/ACK) → dados numerados + ACKs → janela para vazão → retransmissão em caso de perda → FIN para fechar**.",
        why: "Números de sequência + ACKs + retransmissão = entrega confiável e em ordem sobre uma rede que, sozinha, não garante nada disso.",
      },
    },
  ],
};

export const tcp = validateExplainer(data);
