import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/tls.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "tls",
  title: "TLS / mTLS — Handshake e Autenticação Mútua",
  category: "Web & Protocolos",
  tags: ["tls", "criptografia", "https"],
  level: "avancado",
  glossary: {},
  elements: [
    {
      id: "col_c",
      tone: "accent",
      kind: "box",
      at: {
        x: 81,
        y: 100,
        w: 163,
        h: 75,
      },
      label: "🌐 Cliente\n(Browser)",
      variant: "outline",
    },
    {
      id: "col_n",
      tone: "hot",
      kind: "box",
      at: {
        x: 619,
        y: 100,
        w: 163,
        h: 75,
      },
      label: "🕵️ Network\n(Eve/MITM)",
      variant: "outline",
    },
    {
      id: "col_s",
      tone: "good",
      kind: "box",
      at: {
        x: 1169,
        y: 100,
        w: 163,
        h: 75,
      },
      label: "🖥️ Servidor\n(TLS)",
      variant: "outline",
    },
    {
      id: "ll_c",
      tone: "accent",
      kind: "connector",
      from: {
        x: 163,
        y: 175,
      },
      to: {
        x: 163,
        y: 863,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_n",
      tone: "hot",
      kind: "connector",
      from: {
        x: 700,
        y: 175,
      },
      to: {
        x: 700,
        y: 863,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "ll_s",
      tone: "good",
      kind: "connector",
      from: {
        x: 1250,
        y: 175,
      },
      to: {
        x: 1250,
        y: 863,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "http_c2s",
      tone: "hot",
      kind: "connector",
      from: {
        x: 163,
        y: 225,
      },
      to: {
        x: 700,
        y: 225,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "http_c2s_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 257,
        y: 189,
        w: 349,
        h: 41,
      },
      text: "GET /api/token  (texto claro!)",
      align: "center",
    },
    {
      id: "http_n2s",
      tone: "hot",
      kind: "connector",
      from: {
        x: 700,
        y: 263,
      },
      to: {
        x: 1250,
        y: 263,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "http_n2s_l",
      tone: "hot",
      kind: "label",
      at: {
        x: 812,
        y: 227,
        w: 326,
        h: 41,
      },
      text: "interceptado → lê + modifica",
      align: "center",
    },
    {
      id: "client_hello",
      tone: "accent",
      kind: "connector",
      from: {
        x: 163,
        y: 338,
      },
      to: {
        x: 1250,
        y: 338,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "client_hello_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 445,
        y: 302,
        w: 523,
        h: 41,
      },
      text: "ClientHello: TLS 1.3, cipher_suites, random_C",
      align: "center",
    },
    {
      id: "server_hello",
      tone: "good",
      kind: "connector",
      from: {
        x: 1250,
        y: 400,
      },
      to: {
        x: 163,
        y: 400,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "server_hello_l",
      tone: "good",
      kind: "label",
      at: {
        x: 480,
        y: 364,
        w: 453,
        h: 41,
      },
      text: "ServerHello: cipher escolhido, random_S",
      align: "center",
    },
    {
      id: "cert_send",
      tone: "good",
      kind: "connector",
      from: {
        x: 1250,
        y: 450,
      },
      to: {
        x: 163,
        y: 450,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "cert_send_l",
      tone: "good",
      kind: "label",
      at: {
        x: 421,
        y: 414,
        w: 570,
        h: 41,
      },
      text: "Certificate: X.509 (Subject, SAN, Issuer, PubKey)",
      align: "center",
    },
    {
      id: "key_ex",
      tone: "accent",
      kind: "connector",
      from: {
        x: 163,
        y: 513,
      },
      to: {
        x: 1250,
        y: 513,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "key_ex_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 491,
        y: 477,
        w: 430,
        h: 41,
      },
      text: "ClientKeyShare: ephemeral EC pubkey_C",
      align: "center",
    },
    {
      id: "client_fin",
      tone: "accent",
      kind: "connector",
      from: {
        x: 163,
        y: 563,
      },
      to: {
        x: 1250,
        y: 563,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "client_fin_l",
      tone: "accent",
      kind: "label",
      at: {
        x: 503,
        y: 527,
        w: 407,
        h: 41,
      },
      text: "Finished (HMAC de todo o handshake)",
      align: "center",
    },
    {
      id: "server_fin",
      tone: "good",
      kind: "connector",
      from: {
        x: 1250,
        y: 600,
      },
      to: {
        x: 163,
        y: 600,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "server_fin_l",
      tone: "good",
      kind: "label",
      at: {
        x: 503,
        y: 564,
        w: 407,
        h: 41,
      },
      text: "Finished (HMAC de todo o handshake)",
      align: "center",
    },
    {
      id: "app_data",
      tone: "good",
      kind: "connector",
      from: {
        x: 163,
        y: 663,
      },
      to: {
        x: 1250,
        y: 663,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "app_data_l",
      tone: "good",
      kind: "label",
      at: {
        x: 474,
        y: 627,
        w: 465,
        h: 41,
      },
      text: "🔒 Application Data (AES-256-GCM + AEAD)",
      align: "center",
    },
    {
      id: "mtls_req",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 1250,
        y: 713,
      },
      to: {
        x: 163,
        y: 713,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "mtls_req_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 561,
        y: 677,
        w: 291,
        h: 41,
      },
      text: "CertificateRequest (mTLS)",
      align: "center",
    },
    {
      id: "mtls_cert",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 163,
        y: 763,
      },
      to: {
        x: 1250,
        y: 763,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "mtls_cert_l",
      tone: "accent2",
      kind: "label",
      at: {
        x: 474,
        y: 727,
        w: 465,
        h: 41,
      },
      text: "ClientCertificate: cert do cliente X.509",
      align: "center",
    },
    {
      id: "mtls_ok",
      tone: "good",
      kind: "connector",
      from: {
        x: 1250,
        y: 813,
      },
      to: {
        x: 163,
        y: 813,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "mtls_ok_l",
      tone: "good",
      kind: "label",
      at: {
        x: 526,
        y: 777,
        w: 360,
        h: 41,
      },
      text: "OK — cliente autenticado (mTLS)",
      align: "center",
    },
    {
      id: "cert_bg",
      kind: "box",
      at: {
        x: 900,
        y: 25,
        w: 663,
        h: 275,
      },
      variant: "outline",
    },
    {
      id: "cert_title",
      kind: "label",
      at: {
        x: 1045,
        y: 27,
        w: 372,
        h: 41,
      },
      text: "📄 Anatomia do Certificado X.509",
      align: "center",
    },
    {
      id: "cx1",
      kind: "label",
      at: {
        x: 663,
        y: 57,
        w: 500,
        h: 41,
      },
      text: "Subject   → CN=api.empresa.com, O=ACME Corp",
      align: "center",
    },
    {
      id: "cx2",
      tone: "good",
      kind: "label",
      at: {
        x: 622,
        y: 82,
        w: 581,
        h: 41,
      },
      text: "SAN       → DNS:api.empresa.com, DNS:*.empresa.com",
      align: "center",
    },
    {
      id: "cx3",
      kind: "label",
      at: {
        x: 732,
        y: 107,
        w: 360,
        h: 41,
      },
      text: "Issuer    → CN=Let's Encrypt R3",
      align: "center",
    },
    {
      id: "cx4",
      tone: "warn",
      kind: "label",
      at: {
        x: 587,
        y: 132,
        w: 651,
        h: 41,
      },
      text: "Validity  → notBefore: 2024-01-01 / notAfter: 2024-04-01",
      align: "center",
    },
    {
      id: "cx5",
      kind: "label",
      at: {
        x: 692,
        y: 157,
        w: 442,
        h: 41,
      },
      text: "PublicKey → EC secp256r1 (ou RSA 2048)",
      align: "center",
    },
    {
      id: "cx6",
      tone: "accent2",
      kind: "label",
      at: {
        x: 634,
        y: 182,
        w: 558,
        h: 41,
      },
      text: "Signature → assinada pela CA com sua private key",
      align: "center",
    },
    {
      id: "cx7",
      kind: "label",
      at: {
        x: 558,
        y: 207,
        w: 709,
        h: 41,
      },
      text: "Extensions→ KeyUsage, BasicConstraints, CRLDistributionPoints",
      align: "center",
    },
    {
      id: "cx8",
      kind: "label",
      at: {
        x: 628,
        y: 232,
        w: 570,
        h: 41,
      },
      text: "SHA-256 fingerprint → identificador único do cert",
      align: "center",
    },
    {
      id: "cx9",
      kind: "label",
      at: {
        x: 599,
        y: 252,
        w: 628,
        h: 41,
      },
      text: "Serial Number → único por CA (para revogação CRL/OCSP)",
      align: "center",
    },
    {
      id: "chain_bg",
      kind: "box",
      at: {
        x: 900,
        y: 325,
        w: 663,
        h: 188,
      },
      variant: "outline",
    },
    {
      id: "chain_title",
      tone: "accent",
      kind: "label",
      at: {
        x: 1132,
        y: 327,
        w: 198,
        h: 41,
      },
      text: "🔗 Chain of Trust",
      align: "center",
    },
    {
      id: "ca_root",
      tone: "good",
      kind: "box",
      at: {
        x: 913,
        y: 370,
        w: 638,
        h: 38,
      },
      label: "🏛️ Root CA  (auto-assinada, confiada pelo OS/browser)",
      variant: "outline",
    },
    {
      id: "ch_arr1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 1231,
        y: 408,
      },
      to: {
        x: 1231,
        y: 425,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ca_int",
      tone: "accent2",
      kind: "box",
      at: {
        x: 913,
        y: 425,
        w: 638,
        h: 38,
      },
      label: "🏢 Intermediate CA  (assinada pela Root CA)",
      variant: "outline",
    },
    {
      id: "ch_arr2",
      tone: "accent",
      kind: "connector",
      from: {
        x: 1231,
        y: 463,
      },
      to: {
        x: 1231,
        y: 480,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ca_leaf",
      tone: "accent",
      kind: "box",
      at: {
        x: 913,
        y: 480,
        w: 638,
        h: 38,
      },
      label: "🌿 Leaf Cert  api.empresa.com  (assinada pela Intermediate)",
      variant: "outline",
    },
    {
      id: "ecdhe_bg",
      kind: "box",
      at: {
        x: 900,
        y: 538,
        w: 663,
        h: 175,
      },
      variant: "outline",
    },
    {
      id: "ecdhe_title",
      tone: "accent2",
      kind: "label",
      at: {
        x: 1039,
        y: 539,
        w: 384,
        h: 41,
      },
      text: "🔀 ECDHE — Ephemeral Key Exchange",
      align: "center",
    },
    {
      id: "ec1",
      kind: "label",
      at: {
        x: 697,
        y: 567,
        w: 430,
        h: 41,
      },
      text: "Cliente: gera (priv_C, pub_C) efêmero",
      align: "center",
    },
    {
      id: "ec2",
      kind: "label",
      at: {
        x: 692,
        y: 592,
        w: 442,
        h: 41,
      },
      text: "Servidor: gera (priv_S, pub_S) efêmero",
      align: "center",
    },
    {
      id: "ec3",
      kind: "label",
      at: {
        x: 599,
        y: 617,
        w: 628,
        h: 41,
      },
      text: "pre_master = ECDH(priv_C, pub_S) = ECDH(priv_S, pub_C)",
      align: "center",
    },
    {
      id: "ec4",
      kind: "label",
      at: {
        x: 610,
        y: 642,
        w: 605,
        h: 41,
      },
      text: "master_secret = PRF(pre_master, random_C + random_S)",
      align: "center",
    },
    {
      id: "ec5",
      tone: "good",
      kind: "label",
      at: {
        x: 674,
        y: 664,
        w: 477,
        h: 41,
      },
      text: "Ephemeral → Perfect Forward Secrecy (PFS)",
      align: "center",
    },
    {
      id: "ec6",
      tone: "good",
      kind: "label",
      at: {
        x: 575,
        y: 684,
        w: 674,
        h: 41,
      },
      text: "→ comprometer private key hoje não decifra tráfego passado",
      align: "center",
    },
    {
      id: "keys_bg",
      kind: "box",
      at: {
        x: 900,
        y: 738,
        w: 663,
        h: 113,
      },
      variant: "outline",
    },
    {
      id: "keys_title",
      tone: "good",
      kind: "label",
      at: {
        x: 1080,
        y: 739,
        w: 302,
        h: 41,
      },
      text: "🗝️ Session Keys derivadas",
      align: "center",
    },
    {
      id: "k1",
      kind: "label",
      at: {
        x: 750,
        y: 767,
        w: 326,
        h: 41,
      },
      text: "HKDF-Expand(master_secret) →",
      align: "center",
    },
    {
      id: "k2",
      kind: "label",
      at: {
        x: 634,
        y: 789,
        w: 558,
        h: 41,
      },
      text: "  client_write_key   server_write_key  (AES-256)",
      align: "center",
    },
    {
      id: "k3",
      kind: "label",
      at: {
        x: 628,
        y: 812,
        w: 570,
        h: 41,
      },
      text: "  client_write_IV    server_write_IV   (12 bytes)",
      align: "center",
    },
    {
      id: "mtls_bg",
      kind: "box",
      at: {
        x: 900,
        y: 863,
        w: 663,
        h: 35,
      },
      variant: "outline",
    },
    {
      id: "mtls_lbl",
      tone: "accent2",
      kind: "label",
      at: {
        x: 865,
        y: 864,
        w: 732,
        h: 41,
      },
      text: "mTLS = TLS + CertificateRequest ao cliente → autenticação mútua",
      align: "center",
    },
    {
      id: "lbl_prob",
      tone: "hot",
      kind: "label",
      at: {
        x: -34,
        y: 192,
        w: 93,
        h: 41,
      },
      text: "Problema",
      align: "center",
    },
    {
      id: "lbl_shake",
      tone: "accent",
      kind: "label",
      at: {
        x: -40,
        y: 304,
        w: 105,
        h: 41,
      },
      text: "Handshake",
      align: "center",
    },
    {
      id: "lbl_data",
      tone: "good",
      kind: "label",
      at: {
        x: -25,
        y: 629,
        w: 75,
        h: 41,
      },
      text: "Dados",
      align: "center",
    },
    {
      id: "lbl_mtls",
      tone: "accent2",
      kind: "label",
      at: {
        x: -25,
        y: 679,
        w: 75,
        h: 41,
      },
      text: "mTLS",
      align: "center",
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: HTTP texto claro",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_n",
        "ll_s",
        "lbl_prob",
        "http_c2s",
        "http_c2s_l",
        "http_n2s",
        "http_n2s_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_n",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "col_n",
        placement: "bottom",
        text: "HTTP sem TLS: qualquer intermediário (roteador, ISP, attacker) pode **ler e modificar** o tráfego. Senha, tokens e dados sensíveis viajam em texto claro.",
        why: "HTTPS = HTTP sobre TLS — o protocolo de aplicação não muda, só o transporte é cifrado.",
      },
    },
    {
      id: "s2",
      title: "TLS: camada de segurança sobre TCP",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_n",
        "ll_s",
        "ecdhe_bg",
        "ecdhe_title",
        "ec5",
        "ec6",
        "keys_bg",
        "keys_title",
        "k1",
        "k2",
        "k3",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "col_s",
        placement: "top",
        text: "TLS (Transport Layer Security) opera entre TCP e a camada de aplicação. Oferece: **confidencialidade** (cifração), **integridade** (AEAD), **autenticação** (certificados X.509) e **Perfect Forward Secrecy**.",
      },
    },
    {
      id: "s3",
      title: "ClientHello: o cliente anuncia suas capacidades",
      duration: 6500,
      add: ["col_c", "col_n", "col_s", "ll_c", "ll_n", "ll_s", "lbl_shake", "client_hello", "client_hello_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_c",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "client_hello_l",
        placement: "bottom",
        text: "`ClientHello` contém: versão máxima suportada (TLS 1.3), lista de **cipher suites** aceitas (`TLS_AES_256_GCM_SHA384`, etc.), `random_C` (32 bytes aleatórios) e extensões como SNI (Server Name Indication).",
        why: "SNI permite ao servidor escolher o certificado correto em hosts com múltiplos domínios.",
      },
    },
    {
      id: "s4",
      title: "ServerHello + Certificate",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_n",
        "ll_s",
        "lbl_shake",
        "client_hello",
        "client_hello_l",
        "server_hello",
        "server_hello_l",
        "cert_send",
        "cert_send_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_s",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cert_send_l",
        placement: "bottom",
        text: "`ServerHello` responde com a cipher suite escolhida, `random_S` e sua chave pública efêmera. Em seguida envia o **Certificate X.509** com informações de identidade e a chave pública para verificação.",
      },
    },
    {
      id: "s5",
      title: "Anatomia do Certificado X.509",
      duration: 6500,
      add: [
        "col_c",
        "col_s",
        "ll_c",
        "ll_s",
        "cert_bg",
        "cert_title",
        "cx1",
        "cx2",
        "cx3",
        "cx4",
        "cx5",
        "cx6",
        "cx7",
        "cx8",
        "cx9",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cert_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "cert_bg",
        placement: "left",
        text: "O campo mais crítico para validação é o **SAN** (Subject Alternative Names) — lista de domínios válidos para o cert. O `CN` está obsoleto; browsers modernos só aceitam SANs.",
        why: "Validity period curto (90 dias, como Let's Encrypt) reduz janela de comprometimento.",
      },
    },
    {
      id: "s6",
      title: "Chain of Trust: Root CA → Intermediate → Leaf",
      duration: 6500,
      add: [
        "col_c",
        "col_s",
        "ll_c",
        "ll_s",
        "chain_bg",
        "chain_title",
        "ca_root",
        "ch_arr1",
        "ca_int",
        "ch_arr2",
        "ca_leaf",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ca_root",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "chain_bg",
        placement: "left",
        text: "O OS/browser tem uma lista de **Root CAs confiáveis** pré-instalada. A Root CA assina a Intermediate CA, que assina o Leaf Certificate do servidor. Cliente verifica cada assinatura na cadeia.",
        why: "Root CAs raramente assinam diretamente — Intermediate CAs ficam online para operação diária, protegendo a Root (offline em air-gapped HSMs).",
      },
    },
    {
      id: "s7",
      title: "Validação do Certificado pelo cliente",
      duration: 6500,
      add: [
        "col_c",
        "col_s",
        "ll_c",
        "ll_s",
        "chain_bg",
        "chain_title",
        "ca_root",
        "ch_arr1",
        "ca_int",
        "ch_arr2",
        "ca_leaf",
        "cert_bg",
        "cert_title",
        "cx2",
        "cx4",
        "cx6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ca_leaf",
          do: "highlight",
        },
        {
          at: 0,
          target: "cert_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "chain_bg",
        placement: "left",
        text: "Validação: 1) Verificar assinatura da CA. 2) Checar `notAfter` (não expirado). 3) Confirmar que o hostname bate com um SAN do cert. 4) Verificar revogação via CRL ou OCSP.",
        why: "Certificate Transparency (CT Logs) permite auditoria pública de todos os certs emitidos — detecta certs mal-emitidos.",
      },
    },
    {
      id: "s8",
      title: "ECDHE: troca de chaves com Perfect Forward Secrecy",
      duration: 6500,
      add: [
        "col_c",
        "col_s",
        "ll_c",
        "ll_s",
        "lbl_shake",
        "server_hello",
        "server_hello_l",
        "key_ex",
        "key_ex_l",
        "ecdhe_bg",
        "ecdhe_title",
        "ec1",
        "ec2",
        "ec3",
        "ec4",
        "ec5",
        "ec6",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ecdhe_bg",
          do: "highlight",
        },
        {
          at: 0,
          target: "key_ex",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ecdhe_bg",
        placement: "left",
        text: "ECDHE: cliente e servidor geram pares de chaves **efêmeros** (descartados após o handshake). O segredo compartilhado é derivado via curva elíptica — sem nunca transmitir a chave secreta.",
        why: "Ephemeral = PFS: se a private key de longo-prazo for comprometida no futuro, o tráfego passado permanece protegido.",
      },
    },
    {
      id: "s9",
      title: "Derivação das session keys",
      duration: 6500,
      add: [
        "col_c",
        "col_s",
        "ll_c",
        "ll_s",
        "lbl_shake",
        "key_ex",
        "key_ex_l",
        "client_fin",
        "client_fin_l",
        "server_fin",
        "server_fin_l",
        "keys_bg",
        "keys_title",
        "k1",
        "k2",
        "k3",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "keys_bg",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "keys_bg",
        placement: "left",
        text: "`HKDF-Expand(master_secret)` deriva chaves simétricas **separadas por direção**: `client_write_key` (cliente cifra) e `server_write_key` (servidor cifra). Cada direção também tem seu próprio IV (nonce).",
        why: "`Finished` é um HMAC de todo o handshake — detecta qualquer adulteração nos passos anteriores.",
      },
    },
    {
      id: "s10",
      title: "Application Data: Record Layer cifrado",
      duration: 6500,
      add: ["col_c", "col_n", "col_s", "ll_c", "ll_n", "ll_s", "lbl_data", "app_data", "app_data_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "app_data",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "app_data_l",
        placement: "top",
        text: "Dados são fragmentados em **TLS Records** (≤16 KB), cifrados com AES-256-GCM (AEAD). O AEAD garante confidencialidade + integridade num único passo. O MITM vê apenas bytes cifrados.",
      },
    },
    {
      id: "s11",
      title: "mTLS: o servidor também valida o cliente",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_n",
        "ll_s",
        "lbl_mtls",
        "mtls_req",
        "mtls_req_l",
        "mtls_cert",
        "mtls_cert_l",
        "mtls_ok",
        "mtls_ok_l",
        "mtls_bg",
        "mtls_lbl",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "col_c",
          do: "highlight",
        },
        {
          at: 0,
          target: "mtls_req",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "mtls_req_l",
        placement: "top",
        text: "Em mTLS, o servidor envia `CertificateRequest`. O cliente responde com seu próprio certificado X.509. O servidor valida a cadeia do cliente — **autenticação mútua** (ambos se provam).",
        why: "Diferente do TLS padrão onde apenas o servidor se identifica. mTLS elimina a necessidade de API keys ou tokens em comunicação serviço-a-serviço.",
      },
    },
    {
      id: "s12",
      title: "mTLS: casos de uso — service mesh e zero-trust",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_s",
        "lbl_mtls",
        "mtls_req",
        "mtls_req_l",
        "mtls_cert",
        "mtls_cert_l",
        "mtls_ok",
        "mtls_ok_l",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "col_s",
        placement: "top",
        text: "**Istio / Envoy** (Kubernetes): injeta sidecar proxy que estabelece mTLS transparente entre pods. **Zero-trust networking**: sem VPN — cada serviço prova identidade com cert. **APIs B2B**: clientes recebem cert para autenticar além de HTTPS.",
      },
    },
    {
      id: "s13",
      title: "Quiz",
      duration: 6500,
      add: ["col_c", "col_n", "col_s", "ll_c", "ll_n", "ll_s", "ecdhe_bg", "ecdhe_title", "ec5", "ec6"],
      remove: [],
      set: {},
      cues: [],
      quiz: {
        question: "Por que ECDHE (Ephemeral Diffie-Hellman) garante Perfect Forward Secrecy (PFS)?",
        options: [
          "Porque usa curvas elípticas que são mais difíceis de quebrar que RSA",
          "Porque as chaves efêmeras são descartadas após o handshake, então comprometer a chave de longo-prazo no futuro não decifra tráfego passado",
          "Porque o servidor gera uma chave diferente para cada cliente conectado",
          "Porque AES-GCM criptografa as chaves efêmeras antes de transmiti-las",
        ],
        answer: 1,
        explain:
          "PFS é garantido pelo caráter **efêmero** das chaves ECDHE: cada sessão usa um par de chaves novo, descartado imediatamente após a derivação do master_secret. Mesmo que um atacante grave o tráfego cifrado hoje e obtenha a private key do servidor no futuro, ele não conseguirá decifrar — pois as chaves efêmeras (que seriam necessárias) já foram destruídas.",
      },
    },
    {
      id: "s14",
      title: "Resumo: TLS / mTLS",
      duration: 6500,
      add: [
        "col_c",
        "col_n",
        "col_s",
        "ll_c",
        "ll_n",
        "ll_s",
        "lbl_shake",
        "lbl_data",
        "lbl_mtls",
        "client_hello",
        "client_hello_l",
        "server_hello",
        "server_hello_l",
        "cert_send",
        "cert_send_l",
        "key_ex",
        "key_ex_l",
        "client_fin",
        "client_fin_l",
        "server_fin",
        "server_fin_l",
        "app_data",
        "app_data_l",
        "mtls_req",
        "mtls_req_l",
        "mtls_cert",
        "mtls_cert_l",
        "chain_bg",
        "chain_title",
        "ca_root",
        "ch_arr1",
        "ca_int",
        "ch_arr2",
        "ca_leaf",
        "ecdhe_bg",
        "ecdhe_title",
        "ec3",
        "ec5",
        "ec6",
        "keys_bg",
        "keys_title",
        "k2",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "col_n",
        placement: "bottom",
        text: "TLS = handshake (ClientHello → cert X.509 → ECDHE → session keys) + dados cifrados com AES-GCM. Chain of trust: Root CA → Intermediate → Leaf. PFS via ECDHE efêmero. mTLS = TLS + autenticação do cliente por certificado.",
      },
    },
  ],
};

export const tls = validateExplainer(data);
