import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/transformer.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "transformer",
  title: "Como funciona uma rede Transformer",
  subtitle: "Do texto cru à próxima palavra — passo a passo",
  category: "IA & Agentes",
  tags: ["llm", "transformer", "atenção"],
  level: "avancado",
  glossary: {
    softmax: "Transforma números quaisquer em probabilidades positivas que somam 1.",
    mascarada: "As posições futuras recebem -infinito antes do softmax, então seu peso vira zero.",
  },
  elements: [
    {
      id: "li_input",
      kind: "box",
      at: {
        x: 88,
        y: 47,
        w: 313,
        h: 54,
      },
      label: "“O gato sentou no tapete”",
      variant: "outline",
    },
    {
      id: "a1",
      kind: "connector",
      from: {
        x: 244,
        y: 104,
      },
      to: {
        x: 244,
        y: 137,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_token",
      kind: "box",
      at: {
        x: 88,
        y: 140,
        w: 313,
        h: 54,
      },
      label: "1 · Tokenização",
      variant: "outline",
    },
    {
      id: "a2",
      kind: "connector",
      from: {
        x: 244,
        y: 197,
      },
      to: {
        x: 244,
        y: 230,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_embed",
      kind: "box",
      at: {
        x: 88,
        y: 232,
        w: 313,
        h: 54,
      },
      label: "2 · Embeddings",
      variant: "outline",
    },
    {
      id: "a3",
      kind: "connector",
      from: {
        x: 244,
        y: 289,
      },
      to: {
        x: 244,
        y: 322,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_pos",
      kind: "box",
      at: {
        x: 88,
        y: 324,
        w: 313,
        h: 54,
      },
      label: "3 · + Positional Encoding",
      variant: "outline",
    },
    {
      id: "a4",
      kind: "connector",
      from: {
        x: 244,
        y: 381,
      },
      to: {
        x: 244,
        y: 414,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_enc",
      kind: "box",
      at: {
        x: 75,
        y: 417,
        w: 338,
        h: 249,
      },
      variant: "outline",
    },
    {
      id: "li_cap",
      kind: "label",
      at: {
        x: 98,
        y: 629,
        w: 291,
        h: 39,
      },
      text: "4 · Bloco do Encoder  × N",
      align: "center",
      muted: true,
    },
    {
      id: "le_mha",
      kind: "box",
      at: {
        x: 100,
        y: 433,
        w: 288,
        h: 47,
      },
      label: "Multi-Head Self-Attention",
      variant: "outline",
    },
    {
      id: "le_an1",
      kind: "box",
      at: {
        x: 100,
        y: 490,
        w: 288,
        h: 33,
      },
      label: "Add & Norm",
      variant: "outline",
    },
    {
      id: "le_ffn",
      kind: "box",
      at: {
        x: 100,
        y: 533,
        w: 288,
        h: 47,
      },
      label: "Feed-Forward",
      variant: "outline",
    },
    {
      id: "le_an2",
      kind: "box",
      at: {
        x: 100,
        y: 590,
        w: 288,
        h: 33,
      },
      label: "Add & Norm",
      variant: "outline",
    },
    {
      id: "a5",
      kind: "connector",
      from: {
        x: 244,
        y: 666,
      },
      to: {
        x: 244,
        y: 699,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_head",
      kind: "box",
      at: {
        x: 75,
        y: 701,
        w: 338,
        h: 59,
      },
      label: "5 · Cabeça de saída",
      sub: "Linear → Softmax",
      variant: "outline",
    },
    {
      id: "a6",
      kind: "connector",
      from: {
        x: 244,
        y: 760,
      },
      to: {
        x: 244,
        y: 793,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "li_out",
      kind: "box",
      at: {
        x: 88,
        y: 796,
        w: 313,
        h: 54,
      },
      label: "→ próxima palavra: “tapete”",
      variant: "outline",
    },
    {
      id: "r1_text",
      kind: "label",
      at: {
        x: 675,
        y: 374,
        w: 775,
        h: 104,
      },
      text: "“O gato sentou no tapete”",
      size: 40,
      align: "center",
    },
    {
      id: "r1_sub",
      kind: "label",
      at: {
        x: 638,
        y: 466,
        w: 849,
        h: 39,
      },
      text: "uma simples string de caracteres — o modelo não entende texto, só números",
      align: "center",
      muted: true,
    },
    {
      id: "tk_0",
      group: "toks",
      kind: "token",
      at: {
        x: 665,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "O",
    },
    {
      id: "tk_1",
      group: "toks",
      kind: "token",
      at: {
        x: 803,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "gato",
    },
    {
      id: "tk_2",
      group: "toks",
      kind: "token",
      at: {
        x: 940,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "sentou",
    },
    {
      id: "tk_3",
      group: "toks",
      kind: "token",
      at: {
        x: 1078,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "no",
    },
    {
      id: "tk_4",
      group: "toks",
      kind: "token",
      at: {
        x: 1215,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "tap",
    },
    {
      id: "tk_5",
      group: "toks",
      kind: "token",
      at: {
        x: 1353,
        y: 296,
        w: 120,
        h: 64,
      },
      text: "ete",
    },
    {
      id: "tk_brace",
      kind: "label",
      at: {
        x: 1210,
        y: 253,
        w: 267,
        h: 39,
      },
      text: "“tapete” → sub-palavras",
      align: "center",
      muted: true,
    },
    {
      id: "id_0",
      kind: "label",
      at: {
        x: 688,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#41",
      align: "center",
    },
    {
      id: "id_1",
      kind: "label",
      at: {
        x: 825,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#920",
      align: "center",
    },
    {
      id: "id_2",
      kind: "label",
      at: {
        x: 963,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#1503",
      align: "center",
    },
    {
      id: "id_3",
      kind: "label",
      at: {
        x: 1100,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#17",
      align: "center",
    },
    {
      id: "id_4",
      kind: "label",
      at: {
        x: 1238,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#2087",
      align: "center",
    },
    {
      id: "id_5",
      kind: "label",
      at: {
        x: 1375,
        y: 376,
        w: 75,
        h: 39,
      },
      text: "#308",
      align: "center",
    },
    {
      id: "ve_0",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 684,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.5932904663923182, 0.6425527263374485, 0.33083247599451304, 0.420784036351166, 0.5602469135802468,
        0.6044680212620027, 0.3049905692729767,
      ],
    },
    {
      id: "ve_1",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 821,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.2561123971193416, 0.5493304183813443, 0.5701461762688614, 0.2775102880658436, 0.7711141117969821,
        0.4802786351165981, 0.9195100308641975,
      ],
    },
    {
      id: "ve_2",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 959,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.6189343278463648, 0.45610811042524, 0.8094598765432098, 0.8342365397805213, 0.2819813100137174,
        0.35608924897119343, 0.8340294924554184,
      ],
    },
    {
      id: "ve_3",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 1096,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.2817562585733882, 0.3628858024691358, 0.3487735768175583, 0.6909627914951988, 0.4928485082304527,
        0.9318998628257886, 0.7485489540466392,
      ],
    },
    {
      id: "ve_4",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 1234,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.6445781893004114, 0.26966349451303157, 0.5880872770919068, 0.5476890432098764, 0.703715706447188,
        0.8077104766803841, 0.6630684156378601,
      ],
    },
    {
      id: "ve_5",
      group: "vecs",
      tone: "good",
      kind: "bars",
      at: {
        x: 1371,
        y: 403,
        w: 83,
        h: 142,
      },
      values: [
        0.30740012002743483, 0.8764411865569273, 0.8274009773662552, 0.4044152949245542, 0.9145829046639231,
        0.6835210905349793, 0.5775878772290809,
      ],
    },
    {
      id: "r5_wave",
      tone: "warn",
      kind: "connector",
      from: {
        x: 675,
        y: 628,
      },
      to: {
        x: 1463,
        y: 652,
      },
      route: "curve",
      arrow: false,
      dashed: true,
    },
    {
      id: "r5_lab",
      kind: "label",
      at: {
        x: 790,
        y: 667,
        w: 558,
        h: 39,
      },
      text: "padrão senoidal somado a cada posição (0,1,2,3…)",
      align: "center",
      muted: true,
    },
    {
      id: "r6_box",
      kind: "box",
      at: {
        x: 588,
        y: 178,
        w: 375,
        h: 557,
      },
      variant: "outline",
    },
    {
      id: "r6_cap",
      kind: "label",
      at: {
        x: 682,
        y: 146,
        w: 186,
        h: 39,
      },
      text: "Bloco do Encoder",
      align: "center",
      muted: true,
    },
    {
      id: "r6_mha",
      kind: "box",
      at: {
        x: 615,
        y: 232,
        w: 320,
        h: 66,
      },
      label: "Multi-Head",
      sub: "Self-Attention",
      variant: "outline",
    },
    {
      id: "r6_an1",
      kind: "box",
      at: {
        x: 615,
        y: 322,
        w: 320,
        h: 40,
      },
      label: "Add & Norm",
      variant: "outline",
    },
    {
      id: "r6_ffn",
      kind: "box",
      at: {
        x: 615,
        y: 403,
        w: 320,
        h: 57,
      },
      label: "Feed-Forward",
      variant: "outline",
    },
    {
      id: "r6_an2",
      kind: "box",
      at: {
        x: 615,
        y: 483,
        w: 320,
        h: 40,
      },
      label: "Add & Norm",
      variant: "outline",
    },
    {
      id: "r6_in",
      kind: "connector",
      from: {
        x: 775,
        y: 711,
      },
      to: {
        x: 775,
        y: 661,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "r6_inlab",
      kind: "label",
      at: {
        x: 577,
        y: 677,
        w: 395,
        h: 39,
      },
      text: "embeddings + posição entram aqui ↑",
      align: "center",
      muted: true,
    },
    {
      id: "r6_res1",
      tone: "warn",
      kind: "connector",
      from: {
        x: 963,
        y: 342,
      },
      to: {
        x: 963,
        y: 265,
      },
      route: "curve",
      arrow: true,
    },
    {
      id: "r6_res2",
      tone: "warn",
      kind: "connector",
      from: {
        x: 963,
        y: 503,
      },
      to: {
        x: 963,
        y: 431,
      },
      route: "curve",
      arrow: true,
    },
    {
      id: "q_src",
      tone: "accent",
      kind: "bars",
      at: {
        x: 1063,
        y: 391,
        w: 70,
        h: 130,
      },
      values: [
        0.3609533607681756, 0.5751333161865568, 0.4628986625514403, 0.2683852023319616, 0.5986917009602195,
        0.4794354423868312, 0.7769744513031549,
      ],
    },
    {
      id: "q_srclab",
      kind: "label",
      at: {
        x: 1051,
        y: 537,
        w: 93,
        h: 39,
      },
      text: "“sentou”",
      align: "center",
      muted: true,
    },
    {
      id: "q_q",
      tone: "accent",
      kind: "bars",
      at: {
        x: 1350,
        y: 213,
        w: 70,
        h: 107,
      },
      values: [
        0.5631155692729767, 0.6858346193415638, 0.3957193072702332, 0.533201731824417, 0.3572325102880658,
        0.2675030006858711, 0.7933341906721536,
      ],
    },
    {
      id: "q_k",
      tone: "warn",
      kind: "bars",
      at: {
        x: 1350,
        y: 379,
        w: 70,
        h: 107,
      },
      values: [
        0.4492125342935528, 0.3737062757201646, 0.8899952846364884, 0.8940672153635116, 0.2670949074074074,
        0.49765860768175585, 0.8706348593964335,
      ],
    },
    {
      id: "q_v",
      tone: "good",
      kind: "bars",
      at: {
        x: 1350,
        y: 545,
        w: 70,
        h: 107,
      },
      values: [
        0.33530949931412896, 0.7615779320987653, 0.6842712620027435, 0.5549326989026063, 0.8769573045267489,
        0.7278142146776405, 0.9479355281207132,
      ],
    },
    {
      id: "q_ql",
      kind: "label",
      at: {
        x: 1286,
        y: 179,
        w: 198,
        h: 39,
      },
      text: "Q · consulta (Wq)",
      align: "center",
      muted: true,
    },
    {
      id: "q_kl",
      kind: "label",
      at: {
        x: 1304,
        y: 345,
        w: 163,
        h: 39,
      },
      text: "K · chave (Wk)",
      align: "center",
      muted: true,
    },
    {
      id: "q_vl",
      kind: "label",
      at: {
        x: 1304,
        y: 511,
        w: 163,
        h: 39,
      },
      text: "V · valor (Wv)",
      align: "center",
      muted: true,
    },
    {
      id: "q_aq",
      kind: "connector",
      from: {
        x: 1140,
        y: 426,
      },
      to: {
        x: 1343,
        y: 266,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "q_ak",
      kind: "connector",
      from: {
        x: 1140,
        y: 456,
      },
      to: {
        x: 1343,
        y: 432,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "q_av",
      kind: "connector",
      from: {
        x: 1140,
        y: 486,
      },
      to: {
        x: 1343,
        y: 598,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_box",
      tone: "accent2",
      kind: "matrix",
      at: {
        x: 1125,
        y: 249,
        w: 360,
        h: 341,
      },
      rows: 6,
      cols: 6,
    },
    {
      id: "m_formula",
      kind: "label",
      at: {
        x: 1175,
        y: 188,
        w: 244,
        h: 39,
      },
      text: "softmax( Q·Kᵀ / √dₖ )",
      align: "center",
    },
    {
      id: "m_qy",
      kind: "label",
      at: {
        x: 1026,
        y: 336,
        w: 93,
        h: 39,
      },
      text: "consulta",
      align: "center",
      muted: true,
    },
    {
      id: "m_kx",
      kind: "label",
      at: {
        x: 1193,
        y: 596,
        w: 209,
        h: 39,
      },
      text: "chave (quem olho?)",
      align: "center",
      muted: true,
    },
    {
      id: "m_note",
      kind: "label",
      at: {
        x: 989,
        y: 644,
        w: 616,
        h: 39,
      },
      text: "linha “sentou” pesa forte em “gato” (sujeito da ação)",
      align: "center",
      muted: true,
    },
    {
      id: "h_0",
      tone: "accent",
      kind: "matrix",
      at: {
        x: 1063,
        y: 237,
        w: 178,
        h: 168,
      },
      rows: 5,
      cols: 5,
    },
    {
      id: "h_1",
      tone: "warn",
      kind: "matrix",
      at: {
        x: 1350,
        y: 237,
        w: 178,
        h: 168,
      },
      rows: 5,
      cols: 5,
    },
    {
      id: "h_2",
      tone: "good",
      kind: "matrix",
      at: {
        x: 1063,
        y: 474,
        w: 178,
        h: 168,
      },
      rows: 5,
      cols: 5,
    },
    {
      id: "h_3",
      tone: "hot",
      kind: "matrix",
      at: {
        x: 1350,
        y: 474,
        w: 178,
        h: 168,
      },
      rows: 5,
      cols: 5,
    },
    {
      id: "h_lab",
      kind: "label",
      at: {
        x: 920,
        y: 691,
        w: 860,
        h: 39,
      },
      text: "cada cabeça aprende um tipo de relação diferente (sintaxe, correferência…)",
      align: "center",
      muted: true,
    },
    {
      id: "f_in",
      tone: "accent",
      kind: "bars",
      at: {
        x: 1075,
        y: 379,
        w: 75,
        h: 154,
      },
      values: [
        0.53747170781893, 0.8722792352537723, 0.6170919067215364, 0.8197492283950617, 0.6354981138545953,
        0.5158817729766804,
      ],
    },
    {
      id: "f_mid",
      tone: "accent2",
      kind: "bars",
      at: {
        x: 1250,
        y: 296,
        w: 163,
        h: 237,
      },
      values: [
        0.7049279835390947, 0.883099708504801, 0.4583136145404664, 0.3228536522633745, 0.4097445130315501,
        0.7816405178326474, 0.3863811728395061, 0.4792133916323731, 0.8116803840877914, 0.48717721193415636,
        0.6831730109739369, 0.8400998799725652, 0.9169084362139918, 0.613290037722908, 0.4585656721536351,
        0.567241512345679,
      ],
    },
    {
      id: "f_out",
      tone: "good",
      kind: "bars",
      at: {
        x: 1475,
        y: 379,
        w: 75,
        h: 154,
      },
      values: [
        0.8723842592592592, 0.8939201817558299, 0.29953532235939645, 0.5259580761316872, 0.8839909122085048,
        0.34739926268861454,
      ],
    },
    {
      id: "f_a1",
      kind: "connector",
      from: {
        x: 1155,
        y: 456,
      },
      to: {
        x: 1245,
        y: 414,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "f_a2",
      kind: "connector",
      from: {
        x: 1418,
        y: 414,
      },
      to: {
        x: 1470,
        y: 456,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "f_l1",
      kind: "label",
      at: {
        x: 1043,
        y: 537,
        w: 140,
        h: 39,
      },
      text: "d (ex.: 512)",
      align: "center",
      muted: true,
    },
    {
      id: "f_l2",
      kind: "label",
      at: {
        x: 1279,
        y: 537,
        w: 105,
        h: 39,
      },
      text: "4d + GELU",
      align: "center",
      muted: true,
    },
    {
      id: "f_l3",
      kind: "label",
      at: {
        x: 1475,
        y: 537,
        w: 75,
        h: 39,
      },
      text: "d",
      align: "center",
      muted: true,
    },
    {
      id: "st_0",
      kind: "box",
      at: {
        x: 950,
        y: 237,
        w: 400,
        h: 142,
      },
      label: "Bloco 1",
      variant: "outline",
    },
    {
      id: "st_1",
      kind: "box",
      at: {
        x: 913,
        y: 320,
        w: 400,
        h: 142,
      },
      label: "Bloco 2",
      variant: "outline",
    },
    {
      id: "st_2",
      kind: "box",
      at: {
        x: 875,
        y: 403,
        w: 400,
        h: 142,
      },
      label: "Bloco N",
      variant: "outline",
    },
    {
      id: "st_arr",
      kind: "connector",
      from: {
        x: 1150,
        y: 557,
      },
      to: {
        x: 1150,
        y: 426,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "st_lab",
      kind: "label",
      at: {
        x: 713,
        y: 644,
        w: 837,
        h: 39,
      },
      text: "12, 24, 96+ blocos idênticos empilhados — cada um refina a representação",
      align: "center",
      muted: true,
    },
    {
      id: "o_0",
      tone: "hot",
      kind: "bars",
      at: {
        x: 900,
        y: 296,
        w: 100,
        h: 308,
      },
      values: [1],
    },
    {
      id: "o_1",
      kind: "bars",
      at: {
        x: 1063,
        y: 296,
        w: 100,
        h: 308,
      },
      values: [0.29032258064516125],
    },
    {
      id: "o_2",
      kind: "bars",
      at: {
        x: 1225,
        y: 296,
        w: 100,
        h: 308,
      },
      values: [0.1935483870967742],
    },
    {
      id: "o_3",
      kind: "bars",
      at: {
        x: 1388,
        y: 296,
        w: 100,
        h: 308,
      },
      values: [0.12903225806451613],
    },
    {
      id: "ol_0",
      kind: "label",
      at: {
        x: 886,
        y: 620,
        w: 128,
        h: 39,
      },
      text: "tapete  62%",
      align: "center",
    },
    {
      id: "ol_1",
      kind: "label",
      at: {
        x: 1060,
        y: 620,
        w: 105,
        h: 39,
      },
      text: "chão  18%",
      align: "center",
    },
    {
      id: "ol_2",
      kind: "label",
      at: {
        x: 1223,
        y: 620,
        w: 105,
        h: 39,
      },
      text: "sofá  12%",
      align: "center",
    },
    {
      id: "ol_3",
      kind: "label",
      at: {
        x: 1374,
        y: 620,
        w: 128,
        h: 39,
      },
      text: "carpete  8%",
      align: "center",
    },
    {
      id: "o_title",
      kind: "label",
      at: {
        x: 1045,
        y: 229,
        w: 360,
        h: 39,
      },
      text: "P( próxima palavra | contexto )",
      align: "center",
    },
    {
      id: "sum_lab",
      kind: "label",
      at: {
        x: 517,
        y: 421,
        w: 1091,
        h: 57,
      },
      text: "texto → números → vetores → atenção → contexto → próxima palavra",
      size: 22,
      align: "center",
    },
    {
      id: "sum_sub",
      kind: "label",
      at: {
        x: 737,
        y: 478,
        w: 651,
        h: 39,
      },
      text: "…e repete, palavra após palavra (geração autoregressiva)",
      align: "center",
      muted: true,
    },
    {
      id: "cm_box",
      tone: "accent2",
      kind: "matrix",
      at: {
        x: 1050,
        y: 261,
        w: 340,
        h: 322,
      },
      rows: 5,
      cols: 5,
    },
    {
      id: "cm_t",
      kind: "label",
      at: {
        x: 1056,
        y: 211,
        w: 314,
        h: 39,
      },
      text: "máscara causal (triangular)",
      align: "center",
    },
    {
      id: "cm_n",
      kind: "label",
      at: {
        x: 899,
        y: 596,
        w: 628,
        h: 39,
      },
      text: "cada token só enxerga os anteriores — nunca o “futuro”",
      align: "center",
      muted: true,
    },
    {
      id: "gen_box",
      kind: "box",
      at: {
        x: 700,
        y: 355,
        w: 675,
        h: 114,
      },
      label: "O gato sentou no  →  “tapete”",
      sub: "↺ “tapete” vira entrada e prevê a próxima palavra",
      variant: "outline",
    },
    {
      id: "gen_loop",
      tone: "hot",
      kind: "connector",
      from: {
        x: 80,
        y: 822,
      },
      to: {
        x: 80,
        y: 73,
      },
      route: "curve",
      arrow: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "Texto de entrada",
      duration: 8000,
      add: ["li_input"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "r1_text",
          do: "show",
        },
        {
          at: 120,
          target: "r1_sub",
          do: "show",
        },
        {
          at: 0,
          target: "li_input",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "r1_text",
        placement: "bottom",
        text: "Tudo começa com texto cru: **“O gato sentou no tapete”**. Para o computador, isso é apenas uma sequência de caracteres.",
        why: "Uma rede neural só faz contas com números. Então o primeiro trabalho é transformar texto em números.",
      },
    },
    {
      id: "s2",
      title: "Tokenização (subword)",
      duration: 8000,
      add: ["a1", "li_token"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "tk_0",
          do: "show",
        },
        {
          at: 90,
          target: "tk_1",
          do: "show",
        },
        {
          at: 180,
          target: "tk_2",
          do: "show",
        },
        {
          at: 270,
          target: "tk_3",
          do: "show",
        },
        {
          at: 420,
          target: "tk_4",
          do: "show",
        },
        {
          at: 530,
          target: "tk_5",
          do: "show",
        },
        {
          at: 640,
          target: "tk_brace",
          do: "show",
        },
        {
          at: 0,
          target: "li_token",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "tk_4",
        placement: "bottom",
        text: "O texto é quebrado em **tokens**. Palavras comuns viram 1 token; palavras raras se dividem em sub-palavras — aqui **“tapete” → “tap” + “ete”**.",
        why: "Um vocabulário fixo (~50 mil pedaços) cobre qualquer texto, inclusive palavras novas ou com erros, sem ficar gigante.",
      },
    },
    {
      id: "s3",
      title: "Token IDs",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "tk_0",
          do: "show",
        },
        {
          at: 40,
          target: "tk_1",
          do: "show",
        },
        {
          at: 80,
          target: "tk_2",
          do: "show",
        },
        {
          at: 120,
          target: "tk_3",
          do: "show",
        },
        {
          at: 160,
          target: "tk_4",
          do: "show",
        },
        {
          at: 200,
          target: "tk_5",
          do: "show",
        },
        {
          at: 250,
          target: "id_0",
          do: "show",
        },
        {
          at: 330,
          target: "id_1",
          do: "show",
        },
        {
          at: 410,
          target: "id_2",
          do: "show",
        },
        {
          at: 490,
          target: "id_3",
          do: "show",
        },
        {
          at: 570,
          target: "id_4",
          do: "show",
        },
        {
          at: 650,
          target: "id_5",
          do: "show",
        },
      ],
      caption: {
        anchor: "id_2",
        placement: "bottom",
        text: "Cada token vira um **número inteiro**: o índice dele na tabela de vocabulário. A frase agora é uma lista de IDs.",
        why: "IDs são apenas endereços — o significado ainda não está aí. É o próximo passo que dá sentido a eles.",
      },
    },
    {
      id: "s4",
      title: "Embeddings",
      duration: 8000,
      add: ["a2", "li_embed"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "tk_0",
          do: "show",
        },
        {
          at: 30,
          target: "tk_1",
          do: "show",
        },
        {
          at: 60,
          target: "tk_2",
          do: "show",
        },
        {
          at: 90,
          target: "tk_3",
          do: "show",
        },
        {
          at: 120,
          target: "tk_4",
          do: "show",
        },
        {
          at: 150,
          target: "tk_5",
          do: "show",
        },
        {
          at: 200,
          target: "ve_0",
          do: "show",
        },
        {
          at: 290,
          target: "ve_1",
          do: "show",
        },
        {
          at: 380,
          target: "ve_2",
          do: "show",
        },
        {
          at: 470,
          target: "ve_3",
          do: "show",
        },
        {
          at: 560,
          target: "ve_4",
          do: "show",
        },
        {
          at: 650,
          target: "ve_5",
          do: "show",
        },
        {
          at: 0,
          target: "li_embed",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "ve_2",
        placement: "bottom",
        text: "Cada ID consulta uma **tabela de embeddings** e vira um vetor denso de números (ex.: 512 ou 768 dimensões), mostrado aqui como barras.",
        why: "No espaço vetorial, palavras de sentido parecido ficam próximas — é assim que o modelo guarda significado, aprendido no treino.",
      },
    },
    {
      id: "s5",
      title: "Positional Encoding",
      duration: 8000,
      add: ["a3", "li_pos"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ve_0",
          do: "show",
        },
        {
          at: 20,
          target: "ve_1",
          do: "show",
        },
        {
          at: 40,
          target: "ve_2",
          do: "show",
        },
        {
          at: 60,
          target: "ve_3",
          do: "show",
        },
        {
          at: 80,
          target: "ve_4",
          do: "show",
        },
        {
          at: 100,
          target: "ve_5",
          do: "show",
        },
        {
          at: 150,
          target: "r5_wave",
          do: "show",
        },
        {
          at: 300,
          target: "r5_lab",
          do: "show",
        },
        {
          at: 0,
          target: "li_pos",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 855,
          y: 530,
        },
        placement: "top",
        text: "Soma-se a cada embedding um **padrão de posição** (ondas de seno/cosseno), codificando se o token é o 1º, 2º, 3º…",
        why: "A atenção olha todos os tokens ao mesmo tempo e não tem noção de ordem. Sem isso, “gato mordeu cão” = “cão mordeu gato”.",
      },
    },
    {
      id: "s6",
      title: "Bloco do Encoder",
      duration: 8000,
      add: [
        "a4",
        "li_enc",
        "li_cap",
        "le_mha",
        "le_an1",
        "le_ffn",
        "le_an2",
        "r6_box",
        "r6_cap",
        "r6_mha",
        "r6_an1",
        "r6_ffn",
        "r6_an2",
        "r6_in",
        "r6_inlab",
        "r6_res1",
        "r6_res2",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "li_enc",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "r6_box",
        placement: "left",
        text: "Os vetores entram no **bloco do encoder**. Ele tem duas sub-camadas: **Self-Attention** e **Feed-Forward**, cada uma embrulhada por **Add & Norm** (setas amarelas = atalhos residuais).",
        why: "Esse mesmo bloco é repetido N vezes. Vamos abrir cada parte dele a seguir.",
      },
    },
    {
      id: "s7",
      title: "Self-Attention: Q, K, V",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 350,
          target: "q_aq",
          do: "draw",
        },
        {
          at: 350,
          target: "q_ak",
          do: "draw",
        },
        {
          at: 350,
          target: "q_av",
          do: "draw",
        },
        {
          at: 0,
          target: "q_src",
          do: "show",
        },
        {
          at: 60,
          target: "q_srclab",
          do: "show",
        },
        {
          at: 350,
          target: "q_aq",
          do: "show",
        },
        {
          at: 350,
          target: "q_ak",
          do: "show",
        },
        {
          at: 350,
          target: "q_av",
          do: "show",
        },
        {
          at: 350,
          target: "q_q",
          do: "show",
        },
        {
          at: 440,
          target: "q_k",
          do: "show",
        },
        {
          at: 530,
          target: "q_v",
          do: "show",
        },
        {
          at: 620,
          target: "q_ql",
          do: "show",
        },
        {
          at: 710,
          target: "q_kl",
          do: "show",
        },
        {
          at: 800,
          target: "q_vl",
          do: "show",
        },
        {
          at: 0,
          target: "le_mha",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_mha",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "q_v",
        placement: "right",
        text: "Dentro da atenção, cada token gera 3 vetores via matrizes aprendidas: **Q** (o que eu procuro), **K** (o que eu ofereço) e **V** (a informação que entrego).",
        why: "Separar “procura” (Q), “rótulo” (K) e “conteúdo” (V) permite que cada palavra busque dinamicamente as outras relevantes.",
      },
    },
    {
      id: "s8",
      title: "Scores de atenção",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 500,
          target: "m_box",
          do: "lightCells",
          cells: [
            [0, 0],
            [1, 1],
            [2, 1],
            [2, 2],
            [2, 0],
            [3, 3],
            [4, 4],
            [5, 5],
            [1, 0],
            [4, 1],
          ],
          stagger: 90,
        },
        {
          at: 0,
          target: "m_box",
          do: "show",
        },
        {
          at: 80,
          target: "m_formula",
          do: "show",
        },
        {
          at: 160,
          target: "m_qy",
          do: "show",
        },
        {
          at: 240,
          target: "m_kx",
          do: "show",
        },
        {
          at: 320,
          target: "m_note",
          do: "show",
        },
        {
          at: 0,
          target: "le_mha",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_mha",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "m_box",
        placement: "left",
        text: "Multiplica-se cada **Q** por todos os **K** (Q·Kᵀ), escala por √dₖ e aplica {{softmax}}. Resulta numa matriz de **pesos**: quanto cada token atende aos demais (cada linha soma 1).",
        why: "Assim “sentou” pode pesar forte em “gato” (o sujeito) e fraco em “no”. O resultado é a soma dos V ponderada por esses pesos.",
      },
    },
    {
      id: "s9",
      title: "Multi-Head Attention",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 300,
          target: "h_0",
          do: "lightCells",
          cells: [
            [0, 1],
            [1, 3],
            [2, 2],
            [3, 0],
            [4, 4],
          ],
          stagger: 90,
        },
        {
          at: 450,
          target: "h_1",
          do: "lightCells",
          cells: [
            [0, 1],
            [1, 3],
            [2, 2],
            [3, 0],
            [4, 4],
          ],
          stagger: 90,
        },
        {
          at: 600,
          target: "h_2",
          do: "lightCells",
          cells: [
            [0, 1],
            [1, 3],
            [2, 2],
            [3, 0],
            [4, 4],
          ],
          stagger: 90,
        },
        {
          at: 750,
          target: "h_3",
          do: "lightCells",
          cells: [
            [0, 1],
            [1, 3],
            [2, 2],
            [3, 0],
            [4, 4],
          ],
          stagger: 90,
        },
        {
          at: 0,
          target: "h_0",
          do: "show",
        },
        {
          at: 110,
          target: "h_1",
          do: "show",
        },
        {
          at: 220,
          target: "h_2",
          do: "show",
        },
        {
          at: 330,
          target: "h_3",
          do: "show",
        },
        {
          at: 440,
          target: "h_lab",
          do: "show",
        },
        {
          at: 0,
          target: "le_mha",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_mha",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 1080,
          y: 400,
        },
        placement: "left",
        text: "Não há uma atenção só, mas **várias cabeças em paralelo**. Cada uma tem seus próprios Q/K/V e olha um aspecto diferente das relações.",
        why: "Uma cabeça pode seguir sintaxe; outra, correferência; outra, proximidade. As saídas são concatenadas e projetadas de volta.",
      },
    },
    {
      id: "s10",
      title: "Add & Norm (residual)",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "le_an1",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_an1",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_res1",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "r6_res1",
        placement: "left",
        text: "A saída da atenção é **somada à própria entrada** (conexão residual, seta amarela) e passa por **LayerNorm**.",
        why: "O atalho residual deixa o gradiente fluir e preserva a informação original; o LayerNorm estabiliza os valores. Sem eles, redes profundas não treinam bem.",
      },
    },
    {
      id: "s11",
      title: "Feed-Forward (MLP)",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 350,
          target: "f_a1",
          do: "draw",
        },
        {
          at: 750,
          target: "f_a2",
          do: "draw",
        },
        {
          at: 0,
          target: "f_in",
          do: "show",
        },
        {
          at: 60,
          target: "f_l1",
          do: "show",
        },
        {
          at: 350,
          target: "f_a1",
          do: "show",
        },
        {
          at: 350,
          target: "f_mid",
          do: "show",
        },
        {
          at: 410,
          target: "f_l2",
          do: "show",
        },
        {
          at: 750,
          target: "f_a2",
          do: "show",
        },
        {
          at: 750,
          target: "f_out",
          do: "show",
        },
        {
          at: 810,
          target: "f_l3",
          do: "show",
        },
        {
          at: 0,
          target: "le_ffn",
          do: "highlight",
        },
        {
          at: 0,
          target: "r6_ffn",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "f_mid",
        placement: "bottom",
        text: "Cada posição passa, de forma independente, por um **MLP**: expande para ~4× a dimensão, aplica uma não-linearidade (GELU) e volta ao tamanho original.",
        why: "A atenção mistura informação entre tokens; o feed-forward transforma cada token em profundidade, dando capacidade de representação não-linear.",
      },
    },
    {
      id: "s12",
      title: "Empilhar N camadas",
      duration: 8000,
      add: [],
      remove: [
        "r6_box",
        "r6_cap",
        "r6_mha",
        "r6_an1",
        "r6_ffn",
        "r6_an2",
        "r6_in",
        "r6_inlab",
        "r6_res1",
        "r6_res2",
      ],
      set: {},
      cues: [
        {
          at: 500,
          target: "st_arr",
          do: "draw",
        },
        {
          at: 0,
          target: "st_2",
          do: "show",
        },
        {
          at: 130,
          target: "st_1",
          do: "show",
        },
        {
          at: 260,
          target: "st_0",
          do: "show",
        },
        {
          at: 390,
          target: "st_lab",
          do: "show",
        },
        {
          at: 500,
          target: "st_arr",
          do: "show",
        },
        {
          at: 0,
          target: "li_enc",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "st_1",
        placement: "left",
        text: "O bloco inteiro é **repetido N vezes** (12, 24, 96+ camadas). A saída de um vira a entrada do próximo.",
        why: "Camadas iniciais captam padrões locais (sintaxe); as profundas, sentido abstrato e contexto global. Empilhar é o que dá ‘profundidade de raciocínio’.",
      },
    },
    {
      id: "s13",
      title: "Cabeça de saída",
      duration: 8000,
      add: ["a5", "li_head", "a6", "li_out"],
      remove: [],
      set: {},
      cues: [
        {
          at: 700,
          target: "o_0",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "o_title",
          do: "show",
        },
        {
          at: 80,
          target: "o_0",
          do: "show",
        },
        {
          at: 160,
          target: "o_1",
          do: "show",
        },
        {
          at: 240,
          target: "o_2",
          do: "show",
        },
        {
          at: 320,
          target: "o_3",
          do: "show",
        },
        {
          at: 250,
          target: "ol_0",
          do: "show",
        },
        {
          at: 320,
          target: "ol_1",
          do: "show",
        },
        {
          at: 390,
          target: "ol_2",
          do: "show",
        },
        {
          at: 460,
          target: "ol_3",
          do: "show",
        },
        {
          at: 0,
          target: "li_head",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_out",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "o_0",
        placement: "left",
        text: "O vetor final passa por uma **camada Linear** até o tamanho do vocabulário e por **softmax**, virando uma **probabilidade para cada próxima palavra**. Aqui vence **“tapete”**.",
        why: "Para gerar texto, escolhe-se uma palavra, ela é acrescentada à entrada e tudo recomeça — token a token. É a geração autoregressiva.",
      },
    },
    {
      id: "s14",
      title: "Atenção causal (no decoder)",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 350,
          target: "cm_box",
          do: "lightCells",
          cells: [
            [0, 0],
            [1, 0],
            [1, 1],
            [2, 0],
            [2, 1],
            [2, 2],
            [3, 0],
            [3, 1],
            [3, 2],
            [3, 3],
            [4, 0],
            [4, 1],
            [4, 2],
            [4, 3],
            [4, 4],
          ],
          stagger: 90,
        },
        {
          at: 0,
          target: "cm_box",
          do: "show",
        },
        {
          at: 90,
          target: "cm_t",
          do: "show",
        },
        {
          at: 180,
          target: "cm_n",
          do: "show",
        },
      ],
      caption: {
        anchor: "cm_box",
        placement: "left",
        text: "Em modelos geradores (decoder, estilo GPT), a self-attention é {{mascarada}}: cada posição só atende às **anteriores** e a si mesma (triângulo inferior).",
        why: "Durante a geração, o modelo não pode “espiar” a palavra que ainda vai prever. A máscara triangular garante isso.",
      },
    },
    {
      id: "s15",
      title: "Geração autoregressiva",
      duration: 8000,
      add: ["gen_loop"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "gen_loop",
          do: "draw",
        },
        {
          at: 0,
          target: "gen_loop",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "gen_box",
          do: "show",
        },
        {
          at: 0,
          target: "li_input",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_out",
          do: "highlight",
        },
      ],
      caption: {
        anchor: "gen_box",
        placement: "bottom",
        text: "A palavra escolhida é **anexada à entrada** e todo o fluxo recomeça para prever a próxima — e assim sucessivamente.",
        why: "Por isso o texto sai palavra a palavra. O mesmo passo se repete até sair um token de parada (fim de texto).",
      },
    },
    {
      id: "s16",
      title: "Teste rápido",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 380,
          y: 360,
        },
        placement: "right",
        text: "Antes do resumo, fixe o conceito mais importante 👇",
      },
      quiz: {
        question: "Por que o Transformer precisa do positional encoding?",
        options: [
          "Para comprimir os embeddings e economizar memória",
          "Porque a self-attention, sozinha, não tem noção da ordem das palavras",
          "Para acelerar o cálculo do softmax",
          "Para evitar overfitting durante o treino",
        ],
        answer: 1,
        explain:
          "A atenção processa todos os tokens em paralelo; sem um sinal de posição, “gato mordeu cão” e “cão mordeu gato” ficariam idênticos.",
      },
    },
    {
      id: "s17",
      title: "Resumo do fluxo",
      duration: 8000,
      add: [],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "a1",
          do: "pulse",
          times: 2,
        },
        {
          at: 120,
          target: "a2",
          do: "pulse",
          times: 2,
        },
        {
          at: 240,
          target: "a3",
          do: "pulse",
          times: 2,
        },
        {
          at: 360,
          target: "a4",
          do: "pulse",
          times: 2,
        },
        {
          at: 480,
          target: "a5",
          do: "pulse",
          times: 2,
        },
        {
          at: 600,
          target: "a6",
          do: "pulse",
          times: 2,
        },
        {
          at: 0,
          target: "sum_lab",
          do: "show",
        },
        {
          at: 150,
          target: "sum_sub",
          do: "show",
        },
        {
          at: 0,
          target: "li_input",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_token",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_embed",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_pos",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_enc",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_head",
          do: "highlight",
        },
        {
          at: 0,
          target: "li_out",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 850,
          y: 400,
        },
        placement: "top",
        text: "Esse é o caminho completo: **texto → tokens → embeddings (+posição) → blocos de atenção → cabeça de saída → próxima palavra**.",
        why: "A peça-chave é a self-attention: deixa cada palavra ‘olhar’ todas as outras e construir contexto. Empilhada muitas vezes, é o que torna os Transformers tão poderosos.",
      },
    },
  ],
};

export const transformer = validateExplainer(data);
