import { validateExplainer, type ExplainerInput } from "@/schema/explainer";

// Gerado por v2/scripts/convert-v1.ts a partir de explainers/websocket.data.js (v1).
// Câmera usa o default do schema (fit:"all") — sem ajuste fino de enquadramento
// por cena. Revise o relatório do conversor para avisos específicos deste arquivo.
const data: ExplainerInput = {
  slug: "websocket",
  title: "WebSockets",
  subtitle: "Full-duplex · Frames · Opcodes · Heartbeat · RFC 6455",
  category: "Web & Protocolos",
  tags: ["websocket", "tempo-real"],
  level: "medio",
  glossary: {},
  elements: [
    {
      id: "lbl_c",
      kind: "box",
      at: {
        x: 175,
        y: 75,
        w: 150,
        h: 55,
      },
      label: "🖥️  Client",
      variant: "outline",
    },
    {
      id: "lbl_s",
      kind: "box",
      at: {
        x: 775,
        y: 75,
        w: 150,
        h: 55,
      },
      label: "☁️  Server",
      variant: "outline",
    },
    {
      id: "life_c",
      tone: "accent",
      kind: "connector",
      from: {
        x: 250,
        y: 130,
      },
      to: {
        x: 250,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "life_s",
      tone: "good",
      kind: "connector",
      from: {
        x: 850,
        y: 130,
      },
      to: {
        x: 850,
        y: 850,
      },
      route: "line",
      arrow: false,
      dashed: true,
    },
    {
      id: "poll1",
      kind: "label",
      at: {
        x: 11,
        y: 204,
        w: 140,
        h: 41,
      },
      text: "GET /updates",
      align: "end",
      muted: true,
    },
    {
      id: "poll1a",
      kind: "connector",
      from: {
        x: 270,
        y: 219,
      },
      to: {
        x: 830,
        y: 219,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "poll1b",
      kind: "label",
      at: {
        x: 393,
        y: 182,
        w: 314,
        h: 41,
      },
      text: "GET /updates (long-polling)",
      align: "center",
      muted: true,
    },
    {
      id: "poll2",
      kind: "connector",
      from: {
        x: 830,
        y: 288,
      },
      to: {
        x: 270,
        y: 288,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "poll2b",
      kind: "label",
      at: {
        x: 387,
        y: 251,
        w: 326,
        h: 41,
      },
      text: "⏱  wait 30s → 200 OK (maybe)",
      align: "center",
      muted: true,
    },
    {
      id: "poll3",
      kind: "connector",
      from: {
        x: 270,
        y: 350,
      },
      to: {
        x: 830,
        y: 350,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "poll3b",
      kind: "label",
      at: {
        x: 440,
        y: 313,
        w: 221,
        h: 41,
      },
      text: "GET /updates again…",
      align: "center",
      muted: true,
    },
    {
      id: "poll_lbl",
      kind: "token",
      at: {
        x: 150,
        y: 369,
        w: 225,
        h: 45,
      },
      text: "🔁  Polling loop — overhead!",
    },
    {
      id: "hs1",
      tone: "warn",
      kind: "connector",
      from: {
        x: 270,
        y: 219,
      },
      to: {
        x: 830,
        y: 219,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "hs1_l",
      kind: "label",
      at: {
        x: 254,
        y: 182,
        w: 593,
        h: 41,
      },
      text: "GET /chat HTTP/1.1↵Upgrade: websocket↵Sec-WS-Key: …",
      align: "center",
      muted: true,
    },
    {
      id: "hs2",
      tone: "good",
      kind: "connector",
      from: {
        x: 870,
        y: 313,
      },
      to: {
        x: 230,
        y: 313,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "hs2_l",
      kind: "label",
      at: {
        x: 318,
        y: 276,
        w: 465,
        h: 41,
      },
      text: "101 Switching Protocols↵Sec-WS-Accept: …",
      align: "center",
      muted: true,
    },
    {
      id: "hs_badge",
      kind: "token",
      at: {
        x: 425,
        y: 335,
        w: 250,
        h: 40,
      },
      text: "✓ Upgraded — TCP reused",
    },
    {
      id: "m_cs1",
      tone: "accent",
      kind: "connector",
      from: {
        x: 270,
        y: 413,
      },
      to: {
        x: 830,
        y: 413,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_cs1_l",
      kind: "label",
      at: {
        x: 358,
        y: 376,
        w: 384,
        h: 41,
      },
      text: '"Hello from client"  [text frame]',
      align: "center",
      muted: true,
    },
    {
      id: "m_sc1",
      tone: "good",
      kind: "connector",
      from: {
        x: 870,
        y: 488,
      },
      to: {
        x: 230,
        y: 488,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_sc1_l",
      kind: "label",
      at: {
        x: 358,
        y: 451,
        w: 384,
        h: 41,
      },
      text: '"Hello from server"  [text frame]',
      align: "center",
      muted: true,
    },
    {
      id: "m_cs2",
      tone: "accent2",
      kind: "connector",
      from: {
        x: 270,
        y: 563,
      },
      to: {
        x: 830,
        y: 563,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "m_cs2_l",
      kind: "label",
      at: {
        x: 376,
        y: 526,
        w: 349,
        h: 41,
      },
      text: '"binary data…"  [binary frame]',
      align: "center",
      muted: true,
    },
    {
      id: "bc1",
      tone: "good",
      kind: "connector",
      from: {
        x: 870,
        y: 563,
      },
      to: {
        x: 963,
        y: 563,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "bc1l",
      kind: "label",
      at: {
        x: 878,
        y: 526,
        w: 81,
        h: 41,
      },
      text: "client2",
      align: "center",
      muted: true,
    },
    {
      id: "bc2",
      tone: "good",
      kind: "connector",
      from: {
        x: 870,
        y: 594,
      },
      to: {
        x: 963,
        y: 594,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "bc2l",
      kind: "label",
      at: {
        x: 878,
        y: 557,
        w: 81,
        h: 41,
      },
      text: "client3",
      align: "center",
      muted: true,
    },
    {
      id: "ping1",
      tone: "warn",
      kind: "connector",
      from: {
        x: 270,
        y: 638,
      },
      to: {
        x: 830,
        y: 638,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "ping1_l",
      kind: "label",
      at: {
        x: 492,
        y: 601,
        w: 116,
        h: 41,
      },
      text: "PING (0x9)",
      align: "center",
      muted: true,
    },
    {
      id: "pong1",
      tone: "warn",
      kind: "connector",
      from: {
        x: 870,
        y: 694,
      },
      to: {
        x: 230,
        y: 694,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "pong1_l",
      kind: "label",
      at: {
        x: 492,
        y: 657,
        w: 116,
        h: 41,
      },
      text: "PONG (0xA)",
      align: "center",
      muted: true,
    },
    {
      id: "cls1",
      tone: "hot",
      kind: "connector",
      from: {
        x: 270,
        y: 738,
      },
      to: {
        x: 830,
        y: 738,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "cls1_l",
      kind: "label",
      at: {
        x: 387,
        y: 701,
        w: 326,
        h: 41,
      },
      text: "CLOSE (0x8) code=1000 Normal",
      align: "center",
      muted: true,
    },
    {
      id: "cls2",
      tone: "hot",
      kind: "connector",
      from: {
        x: 870,
        y: 788,
      },
      to: {
        x: 230,
        y: 788,
      },
      route: "line",
      arrow: true,
    },
    {
      id: "cls2_l",
      kind: "label",
      at: {
        x: 457,
        y: 751,
        w: 186,
        h: 41,
      },
      text: "CLOSE (0x8) echo",
      align: "center",
      muted: true,
    },
    {
      id: "fr_bg",
      kind: "box",
      at: {
        x: 1013,
        y: 100,
        w: 550,
        h: 625,
      },
      variant: "outline",
    },
    {
      id: "fr_ttl",
      kind: "label",
      at: {
        x: 1154,
        y: 107,
        w: 267,
        h: 41,
      },
      text: "WebSocket Frame Anatomy",
      align: "center",
    },
    {
      id: "fr_r1",
      kind: "box",
      at: {
        x: 1025,
        y: 163,
        w: 63,
        h: 50,
      },
      label: "FIN",
      variant: "outline",
    },
    {
      id: "fr_r2",
      kind: "box",
      at: {
        x: 1094,
        y: 163,
        w: 113,
        h: 50,
      },
      label: "RSV 1-3",
      variant: "outline",
    },
    {
      id: "fr_r3",
      kind: "box",
      at: {
        x: 1213,
        y: 163,
        w: 175,
        h: 50,
      },
      label: "Opcode (4b)",
      variant: "outline",
    },
    {
      id: "fr_r3l",
      kind: "label",
      at: {
        x: 1009,
        y: 214,
        w: 407,
        h: 41,
      },
      text: "0x1=text 0x2=bin 0x8=close 0x9=ping",
      align: "center",
      muted: true,
    },
    {
      id: "fr_r4",
      kind: "box",
      at: {
        x: 1400,
        y: 163,
        w: 138,
        h: 50,
      },
      label: "MASK bit",
      variant: "outline",
    },
    {
      id: "fr_r4l",
      kind: "label",
      at: {
        x: 1301,
        y: 214,
        w: 198,
        h: 41,
      },
      text: "1 = client→server",
      align: "center",
      muted: true,
    },
    {
      id: "fr_r5",
      kind: "box",
      at: {
        x: 1025,
        y: 263,
        w: 250,
        h: 50,
      },
      label: "Payload Len (7b)",
      variant: "outline",
    },
    {
      id: "fr_r5l",
      kind: "label",
      at: {
        x: 775,
        y: 314,
        w: 500,
        h: 41,
      },
      text: "≤125 → inline  126 → next 2B  127 → next 8B",
      align: "center",
      muted: true,
    },
    {
      id: "fr_r6",
      kind: "box",
      at: {
        x: 1288,
        y: 263,
        w: 250,
        h: 50,
      },
      label: "Masking Key (32b)",
      variant: "outline",
    },
    {
      id: "fr_r6l",
      kind: "label",
      at: {
        x: 1154,
        y: 314,
        w: 267,
        h: 41,
      },
      text: "XOR applied when MASK=1",
      align: "center",
      muted: true,
    },
    {
      id: "fr_r7",
      kind: "box",
      at: {
        x: 1025,
        y: 363,
        w: 525,
        h: 75,
      },
      label: "Payload Data",
      sub: "(0 to 2⁶³ bytes)",
      variant: "outline",
    },
    {
      id: "cmp_bg",
      kind: "box",
      at: {
        x: 1013,
        y: 463,
        w: 550,
        h: 244,
      },
      variant: "outline",
    },
    {
      id: "cmp_ttl",
      kind: "label",
      at: {
        x: 1148,
        y: 469,
        w: 279,
        h: 41,
      },
      text: "WS vs SSE vs HTTP/2 Push",
      align: "center",
    },
    {
      id: "cmp_0k",
      kind: "label",
      at: {
        x: 979,
        y: 504,
        w: 93,
        h: 41,
      },
      text: "Protocol",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_0a",
      kind: "label",
      at: {
        x: 1160,
        y: 504,
        w: 105,
        h: 41,
      },
      text: "WebSocket",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_0b",
      kind: "label",
      at: {
        x: 1325,
        y: 504,
        w: 75,
        h: 41,
      },
      text: "SSE",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_0c",
      kind: "label",
      at: {
        x: 1424,
        y: 504,
        w: 128,
        h: 41,
      },
      text: "HTTP/2 Push",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_1k",
      kind: "label",
      at: {
        x: 973,
        y: 537,
        w: 105,
        h: 41,
      },
      text: "Direction",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_1a",
      kind: "label",
      at: {
        x: 1149,
        y: 537,
        w: 128,
        h: 41,
      },
      text: "Full-duplex",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_1b",
      kind: "label",
      at: {
        x: 1316,
        y: 537,
        w: 93,
        h: 41,
      },
      text: "S→C only",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_1c",
      kind: "label",
      at: {
        x: 1441,
        y: 537,
        w: 93,
        h: 41,
      },
      text: "S→C only",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_2k",
      kind: "label",
      at: {
        x: 979,
        y: 569,
        w: 93,
        h: 41,
      },
      text: "Protocol",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_2a",
      kind: "label",
      at: {
        x: 1143,
        y: 569,
        w: 140,
        h: 41,
      },
      text: "ws:// wss://",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_2b",
      kind: "label",
      at: {
        x: 1310,
        y: 569,
        w: 105,
        h: 41,
      },
      text: "HTTP/1.1+",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_2c",
      kind: "label",
      at: {
        x: 1450,
        y: 569,
        w: 75,
        h: 41,
      },
      text: "HTTP/2",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_3k",
      kind: "label",
      at: {
        x: 988,
        y: 602,
        w: 75,
        h: 41,
      },
      text: "Binary",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_3a",
      kind: "label",
      at: {
        x: 1166,
        y: 602,
        w: 93,
        h: 41,
      },
      text: "✓ native",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_3b",
      kind: "label",
      at: {
        x: 1310,
        y: 602,
        w: 105,
        h: 41,
      },
      text: "text only",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_3c",
      kind: "label",
      at: {
        x: 1441,
        y: 602,
        w: 93,
        h: 41,
      },
      text: "✓ frames",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_4k",
      kind: "label",
      at: {
        x: 979,
        y: 634,
        w: 93,
        h: 41,
      },
      text: "Best for",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_4a",
      kind: "label",
      at: {
        x: 1149,
        y: 634,
        w: 128,
        h: 41,
      },
      text: "chat, games",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_4b",
      kind: "label",
      at: {
        x: 1310,
        y: 634,
        w: 105,
        h: 41,
      },
      text: "live feed",
      align: "center",
      muted: true,
    },
    {
      id: "cmp_4c",
      kind: "label",
      at: {
        x: 1424,
        y: 634,
        w: 128,
        h: 41,
      },
      text: "page assets",
      align: "center",
      muted: true,
    },
  ],
  scenes: [
    {
      id: "s1",
      title: "O Problema: HTTP não serve para Real-time",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 440,
          y: 200,
        },
        placement: "right",
        text: "HTTP é **request-response**: o servidor só responde quando o cliente pergunta. Para chat, jogos ou dashboards ao vivo, precisamos que o servidor envie dados *a qualquer momento*.",
        why: "Cada requisição HTTP cria nova conexão TCP (ou reutiliza via keep-alive), mas o servidor nunca inicia a comunicação — o cliente sempre puxa.",
      },
    },
    {
      id: "s2",
      title: "Long-Polling: A Gambiarra",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "poll1",
        "poll1a",
        "poll1b",
        "poll2",
        "poll2b",
        "poll3",
        "poll3b",
        "poll_lbl",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 440,
          y: 230,
        },
        placement: "right",
        text: "Long-polling: o cliente faz GET e o servidor **segura a conexão aberta** até ter algo para responder. Quando responde, o cliente abre outra conexão imediatamente.",
        why: "Funciona, mas desperdiça threads no servidor, tem latência de reconexão e explode em escala. Não é uma solução, é uma adaptação.",
      },
    },
    {
      id: "s3",
      title: "WebSocket: Full-Duplex Persistente",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lbl_c",
          do: "highlight",
        },
        {
          at: 0,
          target: "lbl_s",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 200,
        },
        placement: "right",
        text: "WebSocket estabelece um **canal TCP persistente e bidirecional**. Depois do handshake inicial, tanto cliente quanto servidor podem enviar mensagens a qualquer momento, sem overhead de headers HTTP.",
        why: "TCP já é bidirecional — WebSocket apenas expõe isso na camada de aplicação com um protocolo de framing leve.",
      },
    },
    {
      id: "s4",
      title: "HTTP Upgrade Handshake (101)",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s", "hs1", "hs1_l", "hs2", "hs2_l", "hs_badge"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "hs1",
          do: "draw",
        },
        {
          at: 0,
          target: "hs2",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 210,
        },
        placement: "right",
        text: "**O handshake começa como HTTP/1.1 GET** com headers especiais:<br>`Upgrade: websocket`<br>`Connection: Upgrade`<br>`Sec-WebSocket-Key: <base64 random>`<br>Servidor responde **101 Switching Protocols**.",
        why: "Usar HTTP para negociar o upgrade permite atravessar proxies e firewalls que já entendem HTTP. A partir daí o protocolo muda para WebSocket frames.",
      },
    },
    {
      id: "s5",
      title: "Conexão Estabelecida — Canal Reutilizado",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s", "hs1", "hs1_l", "hs2", "hs2_l", "hs_badge"],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: "hs_badge",
        placement: "right",
        text: "Após o 101, a **mesma conexão TCP** é reutilizada para o protocolo WebSocket. Não há mais overhead de cabeçalhos HTTP nem nova conexão a cada mensagem.",
        why: "O TCP three-way handshake (e TLS se wss://) foi feito uma única vez. Economiza ~100ms por mensagem em redes típicas.",
      },
    },
    {
      id: "s6",
      title: "Anatomia do Frame WebSocket",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "hs_badge",
        "fr_bg",
        "fr_ttl",
        "fr_r1",
        "fr_r2",
        "fr_r3",
        "fr_r3l",
        "fr_r4",
        "fr_r4l",
        "fr_r5",
        "fr_r5l",
        "fr_r6",
        "fr_r6l",
        "fr_r7",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 1030,
          y: 130,
        },
        placement: "bottom",
        text: "**FIN**: último fragmento do msg. **Opcode**: tipo (text/binary/close/ping/pong). **MASK**: clientes mascariam payload (segurança contra proxies). **Payload Len**: tamanho variável.",
        why: "Frames são leves: header mínimo de 2 bytes (vs ~400 bytes em headers HTTP típicos). Ideal para mensagens frequentes e pequenas.",
      },
    },
    {
      id: "s7",
      title: "Cliente → Servidor: Mensagem de Texto",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "hs_badge",
        "fr_bg",
        "fr_ttl",
        "fr_r1",
        "fr_r2",
        "fr_r3",
        "fr_r3l",
        "fr_r4",
        "fr_r4l",
        "fr_r5",
        "fr_r5l",
        "fr_r6",
        "fr_r6l",
        "fr_r7",
        "m_cs1",
        "m_cs1_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_cs1",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 330,
        },
        placement: "bottom",
        text: "**Opcode 0x1** (text frame). Payload é UTF-8. O bit MASK está ativado — cliente *deve* mascarar todos os frames enviados ao servidor (RFC 6455).",
        why: "A máscara (XOR com 32-bit key aleatória) evita que proxies transparentes cacheiem ou modifiquem dados WebSocket incorretamente.",
      },
    },
    {
      id: "s8",
      title: "Servidor → Múltiplos Clientes (Broadcast)",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "hs_badge",
        "m_cs1",
        "m_cs1_l",
        "m_sc1",
        "m_sc1_l",
        "bc1",
        "bc1l",
        "bc2",
        "bc2l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "m_sc1",
          do: "draw",
        },
        {
          at: 300,
          target: "bc1",
          do: "draw",
        },
        {
          at: 300,
          target: "bc2",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 680,
          y: 450,
        },
        placement: "right",
        text: "O servidor pode fazer **broadcast**: enviar a mesma mensagem para múltiplas conexões WebSocket simultâneas. Frames do servidor para o cliente *não* são mascarados.",
        why: "Típico em chat: quando um usuário envia, o servidor redistribui para todos na mesma sala. O servidor mantém um registry de conexões ativas.",
      },
    },
    {
      id: "s9",
      title: "Opcodes: Tipos de Frame",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s", "fr_bg", "fr_ttl", "fr_r3", "fr_r3l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "fr_r3",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 1040,
          y: 150,
        },
        placement: "bottom",
        text: "**0x1** Text (UTF-8) · **0x2** Binary (bytes livres) · **0x8** Close · **0x9** Ping · **0xA** Pong<br>Opcodes 0x3–0x7 e 0xB–0xF reservados para extensões futuras.",
        why: "Separar text de binary permite que implementações validem UTF-8 só quando necessário. Ping/pong são controle de conexão em nível de protocolo, não de aplicação.",
      },
    },
    {
      id: "s10",
      title: "Heartbeat: Ping / Pong",
      duration: 9000,
      add: ["lbl_c", "lbl_s", "life_c", "life_s", "ping1", "ping1_l", "pong1", "pong1_l"],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "ping1",
          do: "draw",
        },
        {
          at: 400,
          target: "pong1",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 530,
        },
        placement: "bottom",
        text: "Cliente (ou servidor) envia **PING** periodicamente. O receptor *deve* responder com **PONG** imediatamente. Ausência de pong → conexão morta → fechar e reconectar.",
        why: "Conexões TCP podem ficar 'silenciosamente quebradas' por NATs e firewalls que expiram entradas idle. O heartbeat mantém o estado ativo.",
      },
    },
    {
      id: "s11",
      title: "Close Handshake (Encerramento Gracioso)",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "ping1",
        "ping1_l",
        "pong1",
        "pong1_l",
        "cls1",
        "cls1_l",
        "cls2",
        "cls2_l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "cls1",
          do: "draw",
        },
        {
          at: 400,
          target: "cls2",
          do: "draw",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 610,
        },
        placement: "top",
        text: "Quem quer fechar envia **close frame** (opcode 0x8) com código de status. O receptor ecoa o close frame e então o TCP é finalizado. Códigos: 1000=normal, 1001=going away, 1002=protocol error.",
        why: "Diferente de TCP RST, o close handshake garante que ambos lados concordaram em encerrar e que todos os frames anteriores foram processados.",
      },
    },
    {
      id: "s12",
      title: "WS vs SSE vs HTTP/2 Push",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "fr_bg",
        "fr_ttl",
        "cmp_bg",
        "cmp_ttl",
        "cmp_0k",
        "cmp_0a",
        "cmp_0b",
        "cmp_0c",
        "cmp_1k",
        "cmp_1a",
        "cmp_1b",
        "cmp_1c",
        "cmp_2k",
        "cmp_2a",
        "cmp_2b",
        "cmp_2c",
        "cmp_3k",
        "cmp_3a",
        "cmp_3b",
        "cmp_3c",
        "cmp_4k",
        "cmp_4a",
        "cmp_4b",
        "cmp_4c",
      ],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 1030,
          y: 390,
        },
        placement: "top",
        text: "Use **WebSocket** para comunicação bidirecional (chat, games, colaboração). Use **SSE** para push simples server→client (dashboards, notificações). **HTTP/2 Push** é para recursos de página.",
        why: "SSE é mais simples de implementar e atravessa proxies HTTP com mais facilidade. WebSocket exige suporte explícito em load balancers e reverse proxies.",
      },
    },
    {
      id: "s13",
      title: "Quiz",
      duration: 9000,
      add: [],
      remove: [],
      set: {},
      cues: [],
      caption: {
        anchor: {
          x: 640,
          y: 360,
        },
        placement: "bottom",
        text: "Teste seu conhecimento sobre WebSockets:",
      },
      quiz: {
        question: "Por que o cliente WebSocket DEVE mascarar todos os frames enviados ao servidor?",
        options: [
          "Para criptografar o conteúdo e garantir confidencialidade",
          "Para evitar que proxies transparentes cacheiem ou modifiquem dados WebSocket",
          "Porque o servidor não consegue processar frames não mascarados",
          "Para reduzir o tamanho do payload com uma forma de compressão",
        ],
        answer: 1,
        explain:
          "A máscara XOR (RFC 6455) protege contra proxies que, ao não reconhecer WebSocket, podem interpretar frames como requests HTTP e causar cache poisoning. Não provê confidencialidade — use wss:// (TLS) para isso.",
      },
    },
    {
      id: "s14",
      title: "Resumo",
      duration: 9000,
      add: [
        "lbl_c",
        "lbl_s",
        "life_c",
        "life_s",
        "hs1",
        "hs1_l",
        "hs2",
        "hs2_l",
        "hs_badge",
        "m_cs1",
        "m_cs1_l",
        "m_sc1",
        "m_sc1_l",
        "ping1",
        "ping1_l",
        "pong1",
        "pong1_l",
        "fr_bg",
        "fr_ttl",
        "fr_r3",
        "fr_r3l",
      ],
      remove: [],
      set: {},
      cues: [
        {
          at: 0,
          target: "lbl_c",
          do: "highlight",
        },
        {
          at: 0,
          target: "lbl_s",
          do: "highlight",
        },
      ],
      caption: {
        anchor: {
          x: 440,
          y: 400,
        },
        placement: "right",
        text: "**WebSocket** = HTTP Upgrade 101 → canal TCP full-duplex. Frames leves com opcode, mask e payload. Heartbeat via ping/pong. Close gracioso com código de status.",
        why: "Escolha WebSocket quando o servidor precisa iniciar mensagens ao cliente com baixa latência. Caso contrário, SSE é mais simples e suficiente.",
      },
    },
  ],
};

export const websocket = validateExplainer(data);
